### ISSUE TITLE
stack/ustack per-event printing

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#10]
This works, which frequency counts stack traces:

```
# ./src/bpftrace -e 'kprobe:decay_load { @[stack] = count(); }'
Attaching 1 probe...
```

But neither of these work, which should just print out each stack trace as it happens:

```
# ./src/bpftrace -e 'kprobe:do_nanosleep { printf("%s", stack); }'
printf: %s specifier expects a value of type string (stack supplied)

# ./src/bpftrace -e 'kprobe:do_nanosleep { stack; }'
Attaching 1 probe...
^C
```

Maybe they should both work? Maybe just the printf() one? Maybe printf() needs a different format code, like %S for stack trace? See printf_format_types.h.

This ticket is to make at least one of these work.

It might involve adding a %S, then having printf.cpp call BPFtrace::get_stack from bpftrace.cpp.

If the printf() method is insane, then the standalone "stack" may be fine, similar to how join() currently works. I think I prefer the printf() method.

Perhaps this should use the new BPF_FUNC_get_stack() support in 4.18? https://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git/commit/?id=de2ff05f48afcde816ff4edb217417f62f624ab5

**Comment by psanford** [comment]
I'm going to try to tackle this. Making printf("%s", stack) work doesn't look too bad.
