### ISSUE TITLE
error: 'BPF_FUNC_send_signal' was not declared

### ISSUE THREAD

**Issue by mwuertinger** [iovisor/bpftrace#1014]
Building master (`d95a2d1`) on Ubuntu 19.10 currently fails with:
```
/home/mw/bpftrace/src/ast/irbuilderbpf.cpp: In member function 'void bpftrace::ast::IRBuilderBPF::CreateSignal(llvm::Value*)':
/home/mw/bpftrace/src/ast/irbuilderbpf.cpp:669:16: error: 'BPF_FUNC_send_signal' was not declared in this scope
  669 |       getInt64(BPF_FUNC_send_signal),
      |                ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/ast/CMakeFiles/ast.dir/build.make:89: src/ast/CMakeFiles/ast.dir/irbuilderbpf.cpp.o] Error 1
```

**Comment by fbs** [comment]
Weird, cmake should detect whether that feature is available. I'll try to reproduce it

**Comment by mwuertinger** [comment]
It can be reproduced in a `ubuntu:19.10` docker container by following the official build steps from https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#ubuntu

Please let me know if you need any more info from me.

**Comment by fbs** [comment]
Hmm what happens here is that your kernel supports send_signal but bcc does not:

```
$ grep -ri 'FN(send_signal' /usr/include/
/usr/include/linux/bpf.h:	FN(send_signal),
```

Compared to `cgroupid`
```
$ grep -ri 'FN(get_current_cgroup' /usr/include/
/usr/include/linux/bpf.h:	FN(get_current_cgroup_id),	\
/usr/include/bcc/compa1t/linux/bpf.h:	FN(get_current_cgroup_id),	\
/usr/include/bcc/compat/linux/virtual_bpf.h:	FN(get_current_cgroup_id),	\
```

We're using the kernel headers to verify whether the option is present but use the bpf.h shipped with bcc in the code generation.

I guess we could first check whether the kernel has the feature. If it does we check bcc. If bcc has it we set the flag. If bcc doesn't we emit a warning advising the user to upgrade to a bcc that has been synced with their kernel to enable more features.

Or maybe we can use the bpf.h shipped with the kernel.

**Comment by zedware** [comment]
Found the same problem in my Ubuntu 19.10 QEMU env.

**Comment by fbs** [comment]
I tried switching `irbuilderbpf.h` to the systems `<linux/bpf.h>` and it seems to work fine, except for the static build. The build can be found [here](https://travis-ci.org/fbs/bpftrace/builds/630481659)

@ajor / @danobi  any objections to switching to the system bpf.h for irbuilder ?

**Comment by ajor** [comment]
Sounds good to me as long as the static build can be fixed

**Comment by dalehamel** [comment]
once #1063 lands the static build issue can probably be revisited to see if it is still an issue.

**Comment by fbs** [comment]
So we ended up switching to our own bpf.h in #1088, I think this can be closed
