### ISSUE TITLE
build problem on ubuntu 1804

### ISSUE THREAD

**Issue by supersojo** [iovisor/bpftrace#1028]
hello
i want to build bpftrace on  ubuntu 1804.
i have already installed the bcc manually.
when i run 'cmake -DCMAKE_BUILD_TYPE=Release ..'', it returns error as below:
root@vm_compiler-s8:~/bpftrace/build# cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibBcc: /usr/local/lib/libbcc.so
-- Found LibElf: /usr/lib/x86_64-linux-gnu/libelf.so
-- Performing Test ELF_GETSHDRSTRNDX
-- Performing Test ELF_GETSHDRSTRNDX - Success
-- Found BISON: /usr/bin/bison (found version "3.0.4")
-- Found FLEX: /usr/bin/flex (found version "2.6.4")
-- Looking for name_to_handle_at
-- Looking for name_to_handle_at - found
-- Looking for bcc_prog_load
-- Looking for bcc_prog_load - not found
-- Looking for bcc_create_map
-- Looking for bcc_create_map - not found
-- Looking for bcc_elf_foreach_sym
-- Looking for bcc_elf_foreach_sym - not found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of BPF_FUNC_get_current_cgroup_id
-- Check size of BPF_FUNC_get_current_cgroup_id - failed
-- Check size of BPF_FUNC_send_signal
-- Check size of BPF_FUNC_send_signal - failed
-- Please install the libbpf development package (missing: LIBBPF_LIBRARIES LIBBPF_INCLUDE_DIRS)
-- Please install the libbfd development package (missing: LIBBFD_LIBRARIES LIBBFD_INCLUDE_DIRS)
-- Please install the libopcodes development package (missing: LIBOPCODES_LIBRARIES LIBOPCODES_INCLUDE_DIRS)
-- Looking for sys/sdt.h
-- Looking for sys/sdt.h - found
CMake Error at CMakeLists.txt:110 (find_package):
  By not providing "FindClang.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Clang", but
  CMake did not find one.

  Could not find a package configuration file provided by "Clang" with any of
  the following names:

    ClangConfig.cmake
    clang-config.cmake

  Add the installation prefix of "Clang" to CMAKE_PREFIX_PATH or set
  "Clang_DIR" to a directory containing one of the above files.  If "Clang"
  provides a separate development package or SDK, be sure it has been
  installed.

So what's the problem?

Thanks in advance.

**Comment by ajor** [comment]
Older Ubuntus have a bug in their LLVM CMake files - you might be hitting that here.
We don't run builds on those old versions any more, but you can take a look at our old Docker files which contain some workarounds we needed in the past:
https://github.com/iovisor/bpftrace/blob/1dbbbf03c2698c943c3a0a9efed00ba804ffa926/docker/Dockerfile.ubuntu
https://github.com/iovisor/bpftrace/blob/aa05dca06e33da0004705c96452a51f1551e58f9/docker/Dockerfile.ubuntu

**Comment by supersojo** [comment]
i will try it later today.
thanks ajor!

**Comment by supersojo** [comment]
i installed clang-7 and modify cmake/FindLibBpf.cmake cmake/FindLibBcc.cmake  to point to bcc directory where i build bcc.

bpftrace build ok. but i meet new problem,once run any probe then SIGSEGV.

bpftrace -e 'BEGIN { printf("hello world\n"); }'Segmentation fault (core dumped)

i use strace it shows something like as below:

prlimit64(0, RLIMIT_RSS, {rlim_cur=1048576*1024, rlim_max=1048576*1024}, NULL) = 0
uname({sysname="Linux", nodename="vm_compiler-s8", ...}) = 0
stat("/lib/modules/4.15.0-72-generic/source", 0x7ffd8f75aeb0) = -1 ENOENT (No such file or directory)
stat("/lib/modules/4.15.0-72-generic/build", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/sys/devices/system/cpu/online", O_RDONLY) = 3
read(3, "0-15\n", 8191)                 = 5
read(3, "", 8191)                       = 0
close(3)                                = 0
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_PERF_EVENT_ARRAY, key_size=4, value_size=4, max_entries=16, map_flags=0, inner_map_fd=0, ...}, 120) = 3
getpid()                                = 37230
futex(0x7f9b4cd58ac4, FUTEX_WAKE_PRIVATE, 2147483647) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x100000004} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

does it means i miss kernel dbgsym? 

Thanks.

**Comment by supersojo** [comment]
i use gdb to trace bpftrace it shows error in libllvm-7
Starting program: /usr/local/bin/bpftrace -e kprobe:do_nanosleep\ \{\ printf\(\"PID\ %d\ sleeping...\\n\",\ pid\)\;\ \}
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff1e27ea3 in llvm::RegisterTargetMachine<llvm::BPFTargetMachine>::Allocator(llvm::Target const&, llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::TargetOptions const&, llvm::Optional<llvm::Reloc::Model>, llvm::Optional<llvm::CodeModel::Model>, llvm::CodeGenOpt::Level, bool) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
(gdb) bt
#0  0x00007ffff1e27ea3 in llvm::RegisterTargetMachine<llvm::BPFTargetMachine>::Allocator(llvm::Target const&, llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::TargetOptions const&, llvm::Optional<llvm::Reloc::Model>, llvm::Optional<llvm::CodeModel::Model>, llvm::CodeGenOpt::Level, bool) ()
   from /usr/lib/x86_64-linux-gnu/libLLVM-7.so.1
#1  0x00000000004ca968 in bpftrace::ast::CodegenLLVM::compile(bpftrace::DebugLevel, std::ostream&) ()
#2  0x00000000004a6c5a in main ()

Dump of assembler code for function _ZN4llvm21RegisterTargetMachineINS_16BPFTargetMachineEE9AllocatorERKNS_6TargetERKNS_6TripleENS_9StringRefES9_RKNS_13TargetOptionsENS_8OptionalINS_5Reloc5ModelEEENSD_INS_9CodeModel5ModelEEENS_10CodeGenOpt5LevelEb:
   0x00007ffff1e27e60 <+0>:     push   %r15
   0x00007ffff1e27e62 <+2>:     push   %r14
   0x00007ffff1e27e64 <+4>:     mov    %r9,%r15
   0x00007ffff1e27e67 <+7>:     push   %r13
   0x00007ffff1e27e69 <+9>:     push   %r12
   0x00007ffff1e27e6b <+11>:    mov    %rdx,%r13
   0x00007ffff1e27e6e <+14>:    push   %rbp
   0x00007ffff1e27e6f <+15>:    push   %rbx
   0x00007ffff1e27e70 <+16>:    mov    %rcx,%rbx
   0x00007ffff1e27e73 <+19>:    mov    %rsi,%r12
   0x00007ffff1e27e76 <+22>:    mov    %r8,%r14
   0x00007ffff1e27e79 <+25>:    sub    $0x38,%rsp
   0x00007ffff1e27e7d <+29>:    mov    0x78(%rsp),%rcx
   0x00007ffff1e27e82 <+34>:    mov    %rdi,(%rsp)
   0x00007ffff1e27e86 <+38>:    mov    %fs:0x28,%rax
   0x00007ffff1e27e8f <+47>:    mov    %rax,0x28(%rsp)
   0x00007ffff1e27e94 <+52>:    xor    %eax,%eax
   0x00007ffff1e27e96 <+54>:    mov    0x70(%rsp),%r9
   0x00007ffff1e27e9b <+59>:    mov    0x80(%rsp),%rdx
---Type <return> to continue, or q <return> to quit---
   **0x00007ffff1e27ea3 <+67>:    movzbl 0x4(%rcx),%eax**
   0x00007ffff1e27ea7 <+71>:    mov    0x90(%rsp),%ebp
   0x00007ffff1e27eae <+78>:    test   %al,%al
   0x00007ffff1e27eb0 <+80>:    mov    %al,0x1c(%rsp)
it looks like %rcx has wrong memory address.

**Comment by supersojo** [comment]
After i use clang-8, everything is ok now.
Maybe i meet the prolem in llvm, https://groups.google.com/forum/#!topic/llvm-dev/8Tcz49kTNCw
