### ISSUE TITLE
ustack can't solve symbol after first run

### ISSUE THREAD

**Issue by tty5** [iovisor/bpftrace#1031]
bpftrace -V
bpftrace v0.9.2-1-g9bf8

bpftrace -e 'uprobe:/tmp/a.out:"github.com/sirupsen/logrus.(*Logger).SetFormatter" { printf("%s\n", ustack())}'
Attaching 1 probe...
```
        github.com/sirupsen/logrus.(*Logger).SetFormatter+0
        main.main+369
        runtime.main+524
        0xc000016060
        0x89481febc0313574


        github.com/sirupsen/logrus.(*Logger).SetFormatter+0
        runtime.main+524
        0xc000016060
        0x89481febc0313574
```
second run app
```
        0x4db6c0
        0x4ecf81
        0x42cbac
        0xc000016060
        0x89481febc0313574


        0x4db6c0
        0x42cbac
        0xc000016060
        0x89481febc0313574
```

**Comment by mmisono** [comment]
This is reported in https://github.com/iovisor/bpftrace/issues/75#issuecomment-535727598.

> As of ustack() and usym(), bpftrace caches bcc's SymbolCache object using the executable name as a key. To fix this issue, bpftrace needs to stop caching when the target file is PIE ASLR. 
https://github.com/iovisor/bpftrace/issues/75#issuecomment-555386648

**Comment by tty5** [comment]
> This is reported in [#75 (comment)](https://github.com/iovisor/bpftrace/issues/75#issuecomment-535727598).
> 
> > As of ustack() and usym(), bpftrace caches bcc's SymbolCache object using the executable name as a key. To fix this issue, bpftrace needs to stop caching when the target file is PIE ASLR.
> > [#75 (comment)](https://github.com/iovisor/bpftrace/issues/75#issuecomment-555386648)

how to stop caching when the target file is PIE ASLR

the help manual is not show

**Comment by mmisono** [comment]
The functionality is not implemented yet. I wrote a prototype before, so I'll make a PR later.

**Comment by tty5** [comment]
> The functionality is not implemented yet. I wrote a prototype before, so I'll make a PR later.

will be release to snap after solved this problem?

**Comment by mmisono** [comment]
I don't know anything about snap releases, but I guess It'll take some time.
First of all, the PR needs to be merged. There are several issues around symbol resolutions, so it may take some time. However fast it is, the next bpftrace release (0.9.4) will be around February. Then it'll also take some time for a snap maintainer to publish a new bpftrace version (Note that bpftrace 0.9.3, which is released last month, is not available on snap yet.)
