### ISSUE TITLE
profiling app get different key in the map even if it is in same function

### ISSUE THREAD

**Issue by tty5** [iovisor/bpftrace#1037]
```
bpftrace -e 'profile:hz:1999 /comm=="a.out"/{ @[ustack] = count(); }'

cat 3.c
void moo(){}
void foo(){}
int main(){
    while(1){
    foo();
    moo();
    }
}
```
get this map
```
@[
    moo+5
    main+24
    generic_start_main+484
    __strcpy_sse2_unaligned+0
    0x202860f20f983
]: 3
@[
    moo+4
    main+24
    generic_start_main+484
    __strcpy_sse2_unaligned+0
    0x202860f20f983
]: 5
```
is there a method can merge the same function name.

i think the ustack should add param to remove the offset of function

**Comment by fbs** [comment]
(when you open a issue/feature, could you wrap the code snippets in \```\<here>``` )

> i think the ustack should add param to remove the offset of function

What is the use case for this?

**Comment by tty5** [comment]
> (when you open a issue/feature, could you wrap the code snippets in ```<here>``` )
> 
> > i think the ustack should add param to remove the offset of function
> 
> What is the use case for this?

i want to profile which function cost the most cpu time, but now, the different offset of same function are not merged

**Comment by fbs** [comment]
> i want to profile which function cost the most cpu time, but now, the different offset of same function are not merged

In that case, why don't you just print the top stack frame, `@[ustack(1)] = count()`? If you remove the function offset the stack frame becomes useless anyway. 

Or you could do this in userspace, remove everything after the `+` and aggregate using some awk.

**Comment by tty5** [comment]
thanks for your reply. this tool is very useful for developer
