### ISSUE TITLE
Duplicates in string keyed map

### ISSUE THREAD

**Issue by terrelln** [iovisor/bpftrace#1067]
```
> bpftrace --version
bpftrace v0.9.3
> sudo bpftrace -e 'tracepoint:block:block_rq_issue { @bytes[args->rwbs] = sum(args->bytes); }'
Attaching 1 probe...
^C

@bytes[WS]: 2
@bytes[R]: 4
@bytes[R]: 5
@bytes[RA]: 6
@bytes[RA]: 9
@bytes[R]: 16
@bytes[RA]: 30
@bytes[R]: 32
```

There are duplicates in the string keyed map. It seems like maybe the end of the string isn't being zeroed, and then the whole buffer gets strcmped, but that is just a guess. I'm running a patched version of Linux 4.16.

**Comment by mmisono** [comment]
I guess your guess is right. Maybe the following (terrible) workaround will work.

```
#include <linux/types.h>

struct arg_1 { long pad; dev_t dev; sector_t sector; unsigned int nr_sector; unsigned int bytes; char rwbs[1]; }
struct arg_2 { long pad; dev_t dev; sector_t sector; unsigned int nr_sector; unsigned int bytes; char rwbs[2]; }
struct arg_3 { long pad; dev_t dev; sector_t sector; unsigned int nr_sector; unsigned int bytes; char rwbs[3]; }
struct arg_4 { long pad; dev_t dev; sector_t sector; unsigned int nr_sector; unsigned int bytes; char rwbs[4]; }
struct arg_5 { long pad; dev_t dev; sector_t sector; unsigned int nr_sector; unsigned int bytes; char rwbs[5]; }
struct arg_6 { long pad; dev_t dev; sector_t sector; unsigned int nr_sector; unsigned int bytes; char rwbs[6]; }
struct arg_7 { long pad; dev_t dev; sector_t sector; unsigned int nr_sector; unsigned int bytes; char rwbs[7]; }
struct arg_8 { long pad; dev_t dev; sector_t sector; unsigned int nr_sector; unsigned int bytes; char rwbs[8]; }
struct arg   { long pad; dev_t dev; sector_t sector; unsigned int nr_sector; unsigned int bytes;  int rwbs[8]; }

tracepoint:block:block_rq_issue
{
  $i = 0;
  $a = (struct arg*)args;
  if($a->rwbs[0] != 0) { $i = 1; }
  if($i == 1 && $a->rwbs[1] != 0) { $i = 2; }
  if($i == 2 && $a->rwbs[2] != 0) { $i = 3; }
  if($i == 3 && $a->rwbs[3] != 0) { $i = 4; }
  if($i == 4 && $a->rwbs[4] != 0) { $i = 5; }
  if($i == 5 && $a->rwbs[5] != 0) { $i = 6; }
  if($i == 6 && $a->rwbs[6] != 0) { $i = 7; }
  if($i == 7 && $a->rwbs[7] != 0) { $i = 8; }

  $key = "?";
  if ($i == 1) { $key = ((struct arg_1*)args)->rwbs }
  if ($i == 2) { $key = ((struct arg_2*)args)->rwbs }
  if ($i == 3) { $key = ((struct arg_3*)args)->rwbs }
  if ($i == 4) { $key = ((struct arg_4*)args)->rwbs }
  if ($i == 5) { $key = ((struct arg_5*)args)->rwbs }
  if ($i == 6) { $key = ((struct arg_6*)args)->rwbs }
  if ($i == 7) { $key = ((struct arg_7*)args)->rwbs }
  if ($i == 8) { $key = ((struct arg_8*)args)->rwbs }
  @bytes[$key] = sum(args->bytes);
}
```

---------

Should this part use `CreateProbeReadStr()` instead of `CreateProbeRead()`?

https://github.com/iovisor/bpftrace/blob/13556f949d46984132f75120ac5166f412d52726/src/ast/codegen_llvm.cpp#L1168-L1173

**Comment by fbs** [comment]
@terrelln  can you add a `bpftool map dump` of the map?

E.g.:
```
$  sudo bpftool map dump id 5525
key:
57 4d 00 00 00 00 00 00
value (CPU 00): 00 80 00 00 00 00 00 00
value (CPU 01): 00 00 00 00 00 00 00 00
key:
57 00 00 00 00 00 00 00
value (CPU 00): 00 c0 03 00 00 00 00 00
value (CPU 01): 00 d0 01 00 00 00 00 00
key:
57 53 00 00 00 00 00 00
value (CPU 00): 00 10 00 00 00 00 00 00
value (CPU 01): 00 80 01 00 00 00 00 00
Found 3 elements
```
( you can find the map id with something like `bpftool prog | grep -E 'tracepoint +name block_rq_issue' -A2 |grep -oP 'map_ids \K[0-9]+'`)

I want to know whether the keys actually differ or that it is a bug in our printer, e.g. printing a value for each cpu in some cases

**Comment by javierhonduco** [comment]
I'm running the same `bpftrace` version as @terrelln and kernel `4.16.18`. 

Searching for one of the keys, such as`57 53 4d` (`WSM` in ascii hex) [in the maps content](https://gist.github.com/javierhonduco/0f7ca5c410f57315dc7a14514fc19d7a) we can see some trailing bytes behind that seem like they could be an out of bounds read? Notice the `0xface` at the end 🤔

**Comment by fbs** [comment]
Can you post the generated bpf too (bpftool prog dump xlated id x) and the tracepoint signature too, just to be sure.

Converting your maps to ascii i see this:

```
R  / s c r i b
R  / w a t c h
R  =
R  a l
R  e l e m _ l
```

There is always a null byte seperating the valid and invalid input.

As the first chars are as expected we must be reading from the correct offset. And the map key is 8 bytes so the amount of data we read is ok too, not outside of the array boundary.

I guess that means that the kernel doesn't zero the array first and just `strcpy`s the data over, stopping at the first null byte.

In this case switching to `prob_read_str` should indeed fix it, I'm not sure it is a good long term fix though as not every char array is a string. being able to write `str(args->file, 8)` might be better?

**Comment by javierhonduco** [comment]
> Can you post the generated bpf too (bpftool prog dump xlated id x) and the tracepoint signature too, just to be sure.

<details>

```
   0: (bf) r6 = r1
   1: (bf) r3 = r6
   2: (07) r3 += 32
   3: (bf) r7 = r10
   4: (07) r7 += -16
   5: (bf) r1 = r7
   6: (b7) r2 = 8
   7: (85) call bpf_probe_read#-41568
   8: (18) r1 = map[id:329]
  10: (bf) r2 = r7
  11: (85) call htab_percpu_map_lookup_elem#90432
  12: (b7) r7 = 0
  13: (15) if r0 == 0x0 goto pc+1
  14: (79) r7 = *(u64 *)(r0 +0)
  15: (07) r6 += 28
  16: (bf) r1 = r10
  17: (07) r1 += -8
  18: (b7) r2 = 4
  19: (bf) r3 = r6
  20: (85) call bpf_probe_read#-41568
  21: (61) r1 = *(u32 *)(r10 -8)
  22: (0f) r7 += r1
  23: (7b) *(u64 *)(r10 -8) = r7
  24: (18) r1 = map[id:329]
  26: (bf) r2 = r10
  27: (07) r2 += -16
  28: (bf) r3 = r10
  29: (07) r3 += -8
  30: (b7) r4 = 0
  31: (85) call htab_percpu_map_update_elem#93184
  32: (b7) r0 = 0
  33: (95) exit
```
</details>

> Converting your maps to ascii i see this:

Yep! All these match some of the process names of the binaries we run. Not sure if it might be the `COMM` or something else, though, but what you said makes sense to me 😄

**Comment by jordalgo** [comment]
This seems resolved. Not seeing any repeated strings with `sudo bpftrace -e 'tracepoint:block:block_rq_issue { @bytes[args->rwbs] = sum(args->bytes); }'`

**Comment by danobi** [comment]
Ah yeah I fixed this a few years ago: https://dxuuu.xyz/string-overcopy.html
