### ISSUE TITLE
Break up `class BPFtrace` into smaller classes

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#1080]
The class has gotten too big and does way too many things now. We should break it up into smaller components.

### Work items:
- [x] child process management
  * `cmd_` and `pid_` are used and abused too often b/c they are public
- [x] logging

**Comment by fbs** [comment]
Child process management might   be one to move. 

logging can be moved out of it too

**Comment by jordalgo** [comment]
The two work items were completed. Going to close
