### ISSUE TITLE
Unknown error -1; Couldn't set RLIMIT_MEMLOCK for bpftrace.

### ISSUE THREAD

**Issue by nagmat1** [iovisor/bpftrace#1100]
while trying :
sudo bpftrace -v -e 'tracepoint:syscalls:sys_enter_nanosleep { printf(%s is sleeping.\n",comm); }'
got :
Unknown error -1 : Couldn't set RLIMIT_MEMLOCK for bpftrace. If your program is not loading, you can try "ulimit -l 8192" to fix the problem
fatal error : '/lib/modules/5.3.0-26-generic/build/include/linux/kconfig.h' file not found.

Have tried "ulimit -l 8102" but did not help.

What may be the problem?

**Comment by mmisono** [comment]
Related? #1034

**Comment by nagmat1** [comment]
Yeah it helped. 

I found a workaround here: #1034 
Reinstalling bpftrace with --devmode seems work.

If removed package : 

root@VM-250-12-ubuntu:~# sudo snap remove bpftrace 

then 

root@VM-250-12-ubuntu:~# sudo snap install --devmode bpftrace
bpftrace 0.9.2 from Colin King (cking-kernel-tools) installed

Then it was working normally.
