### ISSUE TITLE
Is BPFTRACE_NO_CPP_DEMANGLE  invalid?

### ISSUE THREAD

**Issue by bbccaaac** [iovisor/bpftrace#1101]
I traced mysql_parse .

> root@payne:/tracing/bpftrace# bpftrace -e 'uprobe:/usr/local/mysql/bin/mysqld:mysql_parse {printf("ok\n");}'
> Attaching 1 probe...
> Could not resolve symbol: /usr/local/mysql/bin/mysqld:mysql_parse

I tried to set BPFTRACE_NO_CPP_DEMANGLE to 0 or 1. The result was same.

And using nm:

> root@payne:/tracing/bpftrace# nm -C /usr/local/mysql/bin/mysqld | grep mysql_parse
> 0000000000cac9f0 T mysql_parser_current_session
> 0000000000cad1b0 T mysql_parser_extract_prepared_params
> 0000000000cad390 T mysql_parser_free_string
> 0000000000cad3d0 T mysql_parser_get_normalized_query
> 0000000000cad190 T mysql_parser_get_number_params
> 0000000000cad3b0 T mysql_parser_get_query
> 0000000000cad160 T mysql_parser_get_statement_digest
> 0000000000cad140 T mysql_parser_get_statement_type
> 0000000000cad2a0 T mysql_parser_item_string
> 0000000000cacbd0 T mysql_parser_join_thread
> 0000000000caca10 T mysql_parser_open_session
> 0000000000cace60 T mysql_parser_parse
> 0000000000cacbe0 T mysql_parser_set_current_database
> 0000000000cacb30 T mysql_parser_start_thread
> 0000000000cad200 T mysql_parser_visit_tree
> 0000000000b4a600 T mysql_parse(THD*, Parser_state*)
> 000000000144f870 r mysql_parse(THD*, Parser_state*)::__func__

I'm a newbie for bpftrace. I'm confusing for this environment. Why bpftrace does not DEMANGLE?Anyone can help me? Thanks in adance.

**Comment by caringi** [comment]
In my system (Fedora):

```
$ nm -D /usr/libexec/mysqld|grep mysql_parse
00000000005b8920 T _Z11mysql_parseP3THDPcjP12Parser_statebb

```

```
# bpftrace -e 'uprobe:/usr/libexec/mysqld:_Z11mysql_parseP3THDPcjP12Parser_statebb {printf("ok\n");}'
Attaching 1 probe...
```

The BPFTRACE_NO_CPP_DEMANGLE environment variable only works for the output...

```
bpftrace -e 'uprobe:/usr/libexec/mysqld:_Z11mysql_parseP3THDPcjP12Parser_statebb {printf("%s\n", usym(reg("ip"))); }'
Attaching 1 probe...
mysql_parse(THD*, char*, unsigned int, Parser_state*, bool, bool)
^C
```

```
BPFTRACE_NO_CPP_DEMANGLE=1 bpftrace -e 'uprobe:/usr/libexec/mysqld:_Z11mysql_parseP3THDPcjP12Parser_statebb {printf("%s\n", usym(reg("ip"))); }'
Attaching 1 probe...
_Z11mysql_parseP3THDPcjP12Parser_statebb
^C
```

So AFAIK, for the command line you have to specify the mangled symbol name.

**Comment by bbccaaac** [comment]
I see.Thank your reply.
 Can we implement like the feature of stap, which just inputs source function name?

**Comment by ajor** [comment]
Yeah this is something we'll hopefully do some point, see #687

Closing so discussions can continue that ticket
