### ISSUE TITLE
`file not found` for existing header

### ISSUE THREAD

**Issue by Hi-Angel** [iovisor/bpftrace#1142]
Initially I stumbled upon this problem while trying to include the base directory for linux headers with `-I` option. Later then I reduced the testcase to just using the `--include` for the file.

# Steps to reproduce *(in terms of terminal commands)*

```
$ cat hello.bt
BEGIN { printf("Hello\n"); }
$ file /usr/include/x86_64-linux-gnu/sys/types.h
/usr/include/x86_64-linux-gnu/sys/types.h: C source, ASCII text
$ bpftrace hello.bt --include /usr/include/x86_64-linux-gnu/sys/types.h
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
fatal error: '/usr/include/x86_64-linux-gnu/sys/types.h' file not found
```

## Expected

No error "file not found"

## Actual

There's the error "file not found"

# Additional information

bpftrace version: `0.9.3`, installed as a snap package
distro: Ubuntu 18.04

**Comment by Hi-Angel** [comment]
Okay, so, it turns out this bug was fixed in newer `bpftrace` version. I built one at commit `2667b8a2e1c22613e731c7b68d66e742a58f2249`, and it doesn't have this problem.

Worth noting that this is irrelevant to snap `devmode`: I have it enabled. Replacing binary at `/snap/bin` with newly built one makes the problem go away, so it's something fixed upstream.

**Comment by pjgoodall** [comment]
pardon my ignorance. Is there a way I can get notified when this is fixed in the snap?
I'm learning this stuff, and am trying to keep my system configuration manageable. Keep getting bitten by feral binaries.
