### ISSUE TITLE
add a new command option in llvm-mc

### ISSUE THREAD

**Issue by WilliamWangPeng** [iovisor/bpftrace#1143]
hi guys (-)
I have done some tests about llvm-mc now.
and I have another problem:
How to add a option command in llvm-mc，like ---assemble , -disassemble ,-mattr=<a1,+a2,-a3,...>
and I have seen many options in llvm-mc --help, I want to add a new one

**Comment by fbs** [comment]
We  only make use of LLVM, we don't maintain it. You might want to take a look at https://llvm.org/docs/Contributing.html :)
