### ISSUE TITLE
Running opensnoop.bt failing

### ISSUE THREAD

**Issue by Kundeshi** [iovisor/bpftrace#1144]
trying out the simple one liner after bpftrace install (via package install on fedora) returns with the message below:
malloc(): invalid size (unsorted)

**Comment by fbs** [comment]
Hi @Kundeshi . Would it be possible for you to create a stacktrace with gdb? This might require installing the debug-info packages. Something along the lines of:

```
$ sudo gdb --args bpftrace /usr/share/bpftrace/tools/opensnoop.bt
> run
> bt
```

Which fedora, kernel and bpftrace version are you running?

**Comment by caringi** [comment]
I suppose you are using Fedora 31 (package `bpftrace-0.9.2-1.fc31.x86_64`), right?

Please, upgrade to the latest version (`bpftrace-0.9.4-1.fc31.x86_64` - still in testing) using the following command:

`sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-bc9ba06a58`

And try it again...

**Comment by Kundeshi** [comment]
I did the update but still got the same response:
===Fedora Update===
Fedora 31 - x86_64 - Test Updates                                                            298 kB/s | 7.9 MB     00:27    
Last metadata expiration check: 0:00:09 ago on Fri 28 Feb 2020 08:11:32 AM GMT.
No security updates needed, but 150 updates available
Dependencies resolved.
Nothing to do.
Complete!
===Response when running bpftrace on tracepoint===
The bpftrace still fails as; as shown below:
# bpftrace -e 'tracepoint:syscalls:sys_enter_execve{printf("%s -> %s\n", comm, str(args->filename));}'
malloc(): invalid size (unsorted)
==
Secondly a test of the bpftrace shows it works as expected. I suspect the issue could be with "tracepoint"
e.g helloworld
==bpftrace hello world==
# bpftrace -e 'BEGIN{ printf("hello world\n");}'
Attaching 1 probe...
hello world
^C
==

**Comment by Kundeshi** [comment]
This issue was resolved by simply updating the bpftrace to version "bpftrace v0.9.4"
