### ISSUE TITLE
bpftrace doesn't support cast to unsigned

### ISSUE THREAD

**Issue by Hi-Angel** [iovisor/bpftrace#1146]
While working with command line arguments, I stumbled upon the following warning:

```
$ cat test.bt
BEGIN {
    $x = $1 / 5;
}
$ bpftrace test.bt 10
test.bt:2:13-14: WARNING: signed operands for '/' can lead to undefined behavior (cast to unsigned to silence warning)
    $x = $1 / 5;
```

So, it asks me to cast to `unsigned`, but here's the problem: `bpftrace` doesn't know `unsigned` nor `unsigned int`.

## Steps to reproduce *(in terms of terminal commands)*

```
$ cat test.bt
BEGIN {
    $x = (unsigned)$1 / 5;
}
$ bpftrace test.bt 10
test.bt:2:10-20: ERROR: Unknown struct/union: 'unsigned'
    $x = (unsigned)$1 / 5;
         ~~~~~~~~~~
```

### Expected

No error

### Actual

There's the error about unknown struct/union

## Version

OS: Ubuntu 18.04
bpftrace: v0.9.4-5-g2667

**Comment by fbs** [comment]
Bpftrace has a few built-in types:

https://github.com/iovisor/bpftrace/blob/4638b968cc234ef1a9bd543a372b58c662e9b541/src/ast/semantic_analyser.cpp#L21-L32

`((uint64) $1)/5` should work in this case. 

Looks like we don't have them in the reference guide / man page yet.

**Comment by danobi** [comment]
Added in https://github.com/iovisor/bpftrace/commit/f087abbdd2e610818
