### ISSUE TITLE
Error loading program: kprobe:udp_recvmsg (Associative Array)

### ISSUE THREAD

**Issue by anmathew** [iovisor/bpftrace#1172]
Apologies if this is not the right place to ask this question. 

I am newly learning `bpftrace`.  I am using `bpftrace v0.9.2-1-g9bf8` on an Ubuntu 18.04 running `4.15.0-76-generic`. 

Can someone please shed some light to why is this below trace attempt failing with `Error loading program: kprobe:udp_recvmsg` ?

```

#!/usr/local/bin/bpftrace
#include <net/sock.h>

kprobe:udp_recvmsg{
        @udp_recv_sk[tid] = (struct sock *)arg0;
        @rx[@udp_recv_sk[tid]] = 0; // <-- works if this line is commented out
        printf("%s tid: %d\n", probe, tid);
}
```
Thanks in advance!

**Comment by fbs** [comment]
Can you try again with a build from master? 

```
$ sudo bpftrace t.bt
Attaching 1 probe...
kprobe:udp_recvmsg tid: 17329
kprobe:udp_recvmsg tid: 17329
kprobe:udp_recvmsg tid: 622
kprobe:udp_recvmsg tid: 622
kprobe:udp_recvmsg tid: 622
kprobe:udp_recvmsg tid: 622
kprobe:udp_recvmsg tid: 17329
```

**Comment by anmathew** [comment]
> Can you try again with a build from master?

Thank you for the reply. Updated to `bpftrace v0.9.4-42-g9a9d1`, also switched to Ubuntu 19.04 running `5.0.0-13-generic` - it works OK now. 

Closing this issue.
