### ISSUE TITLE
Missing Headers Issue with recommended `docker run` in INSTALL.md

### ISSUE THREAD

**Issue by ConnorNelson** [iovisor/bpftrace#1182]
INSTALL.md recommends that the docker container be run as follows:
```
$ docker run -ti -v /usr/src/linux:/usr/src/linux:ro \
       -v /lib/modules/:/lib/modules:ro \
       -v /sys/kernel/debug/:/sys/kernel/debug:rw \
       --net=host --pid=host --privileged \
       quay.io/iovisor/bpftrace:latest \
       tcplife.bt
Attaching 3 probes...
PID   COMM       LADDR           LPORT RADDR           RPORT TX_KB RX_KB MS
```

However, running my bpftrace script results in missing linux header errors. 
Replacing `-v /usr/src/linux:/usr/src/linux:ro` with `-v /usr/src:/usr/src:ro`resolves this.

On my system, `/usr/src/linux` is empty, but `/usr/src/linux-headers-$(uname -r)` contains the correct headers/symlinks to them. I am not familiar with how these headers are expected to appear in the filesystem (perhaps I mistakenly overwrote `/usr/src/linux`), but I figured I would document this incase someone else has issues.

**Comment by fbs** [comment]
Yes `/usr/src` is better here as each distro has their own location in `/usr/src`. Can you submit a PR? :)
