### ISSUE TITLE
cmake errors: Target "bpftrace" requires the language dialect "CXX17" , but CMake does not know the compile flags to use to enable it.

### ISSUE THREAD

**Issue by gfx** [iovisor/bpftrace#1193]
probably caused by https://github.com/iovisor/bpftrace/pull/1184

My environment:

* Ubuntu 16.04
* cmake 3.5.1

**Comment by fbs** [comment]
We've reverted the change in #1204. 

However, the upcoming release will likely be the last one to support  stock 16.04 as we want to use C++17 features.

**Comment by gfx** [comment]
Thanks!
