### ISSUE TITLE
0.9.5 / 0.10.0 release

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#1214]
I've originally set the release date for the next release to April 1. As we're approaching 100 commits again (60 in the `src` dir) we should probably stick to that.

Is there anything that has to land before we do our next release? The milestone itself is empty (just removed `while` as that is blocked on the type fixes). 

We also still have the version number "issue". IIRC the main argument against a 0.10.0 release is that it looks a lot like an 0.1.0. My preference would be to do a 0.10.0 as sticking to 0.9.x feels like we're doing minor patch releases. But if there is good reason to stick to 0.9.0 thats fine too (or do we skip to 0.11.0?)

@ajor @brendangregg  @danobi  @mmarchini @mmisono

**Comment by danobi** [comment]
I was seeing BTF support failing on some prod machines. Lemme debug it tomorrow. Maybe it regressed.

**Comment by danobi** [comment]
I think I have the fix: https://github.com/iovisor/bpftrace/pull/1220

**Comment by Cogitri** [comment]
A new release would certainly be very welcome for LLVM10 support, we're using the latest git to test against LLVM10 right now in Alpine Linux Edge.

**Comment by fbs** [comment]
With #1186 almost done I think we should merge that and do the 0.10 release. highlights of the release would be:

- kfuncs
- c++ demangle
- the fixes around `type:;ctx`
- llvm10

internally we have the new parser, type fixes etc. Total of 90+ commits in the src/ dir.

@danobi  @mmisono

**Comment by mmisono** [comment]
Looks good to me!
As of the next version, I don't have strong opinion but 0.10.0 is straightforward to me.

**Comment by danobi** [comment]
0.10.0 sounds good to me. It might be a bit confusing mathematically but it's pretty consistent with how software releases go.
