### ISSUE TITLE
Drop LLVM 5 codegen tests

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#1215]
We currently have codegen tests for LLVM 5 - 9 (10 in a PR).  The code we generate is basically the same for each LLVM version (the only LLVM_VERSION ifdefs are the `mem*` calls) so there is not much to test between versions there. That we're able to automatically rewrite most of the tests confirms that.
The main advantage of having codegen tests for each version is probably that it makes development easy, you can use the LLVM your OS has instead of having everyone use the same version.

Especially the LLVM5 tests mainly feel like a maintenance burden. The automatic rewriting fails in a lot of places (17) and the CI job has a massive test filter too.
Are there objections to dropping LLVM 5 from the codegen tests?  We still have the runtime and other tests to verify that everything is working. This might cause some issues for people that still use LLVM5 as their codegen tests will fail (unless we code the exception into the test runner) but I don't think there are many (any) LLVM5 users left. Even ubunt 16.04 has LLVM8 

Or we could drop LLVM5 support completely, removing it completely (and use the glibc static(ish) builds instead).

**Comment by danobi** [comment]
+1 on dropping

**Comment by mmisono** [comment]
LLVM 10 test is merged: #1190
+1 on dropping

**Comment by acj** [comment]
Another +1 for dropping

> Or we could drop LLVM5 support completely, removing it completely (and use the glibc static(ish) builds instead).

fwiw, #1063 removes the static LLVM 5 builds in favor of LLVM 9, still on Alpine as before.
