### ISSUE TITLE
Installing bpftrace on a Broadcom SmartNIC

### ISSUE THREAD

**Issue by hesam4g** [iovisor/bpftrace#1228]
I tried to install bpftrace on a CCX SmartNIC using its modified Kernel. I have installed Ubuntu 19.04 on the SmartNIC as well. Having built and made bpftrace from the source code, I faced 22 errors when I ran the test script. The output of the test is provided below:
```
[----------] Global test environment tear-down
[==========] 369 tests from 9 test cases ran. (1303 ms total)
[  PASSED  ] 347 tests.
[  FAILED  ] 22 tests, listed below:
[  FAILED  ] semantic_analyser.builtin_functions
[  FAILED  ] semantic_analyser.call_reg
[  FAILED  ] semantic_analyser.type_ctx
[  FAILED  ] codegen.builtin_arg
[  FAILED  ] codegen.builtin_ctx_field
[  FAILED  ] codegen.builtin_func
[  FAILED  ] codegen.builtin_func_uprobe
[  FAILED  ] codegen.builtin_func_wild
[  FAILED  ] codegen.builtin_retval
[  FAILED  ] codegen.builtin_sarg
[  FAILED  ] codegen.call_override
[  FAILED  ] codegen.call_reg
[  FAILED  ] codegen.call_signal
[  FAILED  ] codegen.call_str
[  FAILED  ] codegen.call_str_2_expr
[  FAILED  ] codegen.call_str_2_lit
[  FAILED  ] codegen.comparison_extend
[  FAILED  ] codegen.intcast_retval
[  FAILED  ] codegen.intcast_call
[  FAILED  ] codegen.intptrcast_assign_var
[  FAILED  ] codegen.intptrcast_call
[  FAILED  ] codegen.struct_char

```
Using `bpftrace -l` shows there is no kprobe* event available:
```
software:alignment-faults:
software:bpf-output:
software:context-switches:
software:cpu-clock:
software:cpu-migrations:
software:dummy:
software:emulation-faults:
software:major-faults:
software:minor-faults:
software:page-faults:
software:task-clock:
hardware:backend-stalls:
hardware:branch-instructions:
hardware:branch-misses:
hardware:bus-cycles:
hardware:cache-misses:
hardware:cache-references:
hardware:cpu-cycles:
hardware:frontend-stalls:
hardware:instructions:
hardware:ref-cycles:
No such file or directory: /sys/kernel/debug/tracing/available_filter_functions
```
Has anybody faced with the same problem?!

**Comment by fbs** [comment]
Can you some more details about the platform itself and provide `bpftrace --info` output?

Are tracefs and debugfs available and mounted?

**Comment by hesam4g** [comment]
The output of `bpftrace --info` :
```
System
  OS: Linux 4.14.65+g5514c83 #1 SMP Fri Oct 5 05:02:35 UTC 2018
  Arch: aarch64

Build
  version: v0.9.4-101-g6323
  LLVM: 7
  foreach_sym: yes
  unsafe uprobe: no
  btf: no
  bfd: yes

Kernel helpers
  probe_read: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes

Kernel features
  Instruction limit: -1
  Loop support: no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: no
  tracepoint: no
  perf_event: no
```
debugfs is avilable, but tracefs is not.
`debugfs on /sys/kernel/debug type debugfs (rw,relatime)`

**Comment by fbs** [comment]
The test failures are due to some x86 assumptions currently in the code. Also see #1137. 

As for the lack of tracefs, I don't think it is possible to attach kprobes without. You might be out of luck here.

**Comment by hesam4g** [comment]
Is there anyway to create/build tracefs?

**Comment by fbs** [comment]
If it is possible to recompile the kernel you should be able to enable it. But I'm not familiar with the platform and do not know why /sys/kernel/debug/tracing is empty on the broadcom kernel so I cannot help you with it.

**Comment by danobi** [comment]
Yeah it seems like the smart nic kernel was compiled without some features bpftrace needs. I don't see why it wouldn't be possible to compile a kernel with all the necessary options. But I don't have any hardware to tinker with so you might be on your own for this.

**Comment by fbs** [comment]
I'm closing this one as we cannot help with it.
