### ISSUE TITLE
Improve changelog / release process

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#1255]
Our changelog is currently a list of commits grouped into a few sections. To end users this isn't useful as it is hard to make sense of what individual commits do. It would be a lot more useful if we describe what each PR does and how it impacts the end user. But doing this once every two months is a lot of work.

We've discussed this on IRC a bit, the best we came up with is to make this part of every PR. Each PR that add/changes/fixes something that impacts the user must also create a change log entry. Internal changes (refactoring etc) don't need a changelog entry.

To make sure we don't forget this we can add a PR template or even hook it into the CI.

Are there any objections to this?

**Comment by danobi** [comment]
+1

**Comment by danobi** [comment]
So github actions can't comment on a pull request coming from a forked repository: https://github.community/t5/GitHub-Actions/Github-Workflow-not-running-from-pull-request-from-forked/td-p/32979/highlight/true

Quite unfortunate. I think the next best thing is a pull request template

**Comment by danobi** [comment]
PR template: #1299

**Comment by fbs** [comment]
I think the current flow is good enough for now
