### ISSUE TITLE
How to disable semantic analyser warnings?

### ISSUE THREAD

**Issue by ex3me0** [iovisor/bpftrace#1267]
**version:** `bpftrace  v0.9.4-97-20200317-1417-gef39ed0` installed via snap

Hey
Is it possible to disable such kind of warnings, or what u can advice?
I have updated from bpftrace 0.9.1 to 0.9.4 and these messages are slightly annoying 
```
script.bt:7:7-9: WARNING: comparison of integers of different signs: 'unsigned int64' and 'int64' can lead to undefined behavior
/ pid == $1 /
```

`script.bt` example
```
tracepoint:syscalls:sys_enter_read,
tracepoint:syscalls:sys_enter_write
/ pid == $1 /
{
  @fd = args->fd;
  @buf_raw = args->buf;
  @size = args->count;
}
```

**Comment by fbs** [comment]
There currently is none, but it would be nice to have :)

This particular warning should be fixed in the 0.10 release btw

**Comment by mmisono** [comment]
To fix the warning, you can cast a value.

```
tracepoint:syscalls:sys_enter_read,
tracepoint:syscalls:sys_enter_write
/ pid == (uint64)$1 /
{
  @fd = args->fd;
  @buf_raw = args->buf;
  @size = args->count;
}
```

(in this case, upgrading bpftrace would be better though)

**Comment by ex3me0** [comment]
Got it, thanks for your support!
