### ISSUE TITLE
No kprobe for kobject_uevent_env available?

### ISSUE THREAD

**Issue by stapelberg** [iovisor/bpftrace#1281]
Thanks for bpftrace, it’s a very useful tool!

Today, I wanted to learn about the kernel call stack of a particular uevent I’m trying to understand.

To do that, I wanted to attach a kprobe to `kobject_uevent_env`: https://elixir.bootlin.com/linux/v5.5.8/source/lib/kobject_uevent.c#L456

Unfortunately, `sudo bpftrace -l |& grep kobject_uevent_env` comes back empty!

Why is it not possible to attach a kprobe to `kobject_uevent_env`, and can I do something about it? More generally, what are the criteria for a kernel function to be available as kprobe?

I’m running this on Arch Linux with kernel Linux 5.5.8.

Thanks in advance,

**Comment by danobi** [comment]
I'm no expert on the kernel build system but I took a look anyways. My educated guess is that symbols from kernel libs do not end up in the vmlinux binary.

The comment here seems to indicate this: https://github.com/torvalds/linux/blob/master/scripts/link-vmlinux.sh#L9-L10

`kobject_uevent.o` is added to library goal here: https://github.com/torvalds/linux/blob/master/lib/Makefile#L32

Library goals pulled out into top level makefile here: https://github.com/torvalds/linux/blob/master/Makefile#L643

Top level libraries pulled out here: https://github.com/torvalds/linux/blob/master/Makefile#L1056

KBUILD_VMLINUX_LIBS set here: https://github.com/torvalds/linux/blob/master/Makefile#L1066

**Comment by stapelberg** [comment]
> I'm no expert on the kernel build system but I took a look anyways. My educated guess is that symbols from kernel libs do not end up in the vmlinux binary.

If you’re correct, is that behavior required? It looks to be determinate (not an oversight), but obviously it’d be better for the symbols to be present for my particular use-case :)

**Comment by danobi** [comment]
Perhaps the behavior could be changed. But you would have to ask the kernel folks. Unfortunately not bpftrace related so closing this issue out.

If you do convince the kernels folks do let me know :)
