### ISSUE TITLE
Question: uprobe on arbitrary address (without defined symbol)

### ISSUE THREAD

**Issue by mzr** [iovisor/bpftrace#1282]
Can I place uprobe on an address that doesn't relate to any symbol?

[Here](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#3-uprobeuretprobe-dynamic-tracing-user-level) is a suggestion that it is possible:

>Syntax:
>```
>uprobe:library_name:function_name[+offset]
>uprobe:library_name:address
>uretprobe:library_name:function_name
>```

But when I run: `sudo bpftrace -e 'uprobe:/full/path/to/binary:0x40076a { printf("called"); }` I get:
```
Attaching 1 probe...
Could not resolve address: /full/path/to/binary:0x40076a
```

This error message corresponds to [this code](https://github.com/iovisor/bpftrace/blob/8cd398b9bc5021557db40da5a3b057f7eb92c15b/src/attached_probe.cpp#L413):
```
  if (symbol.empty())
  {
    sym.address = probe_.address;
    bcc_elf_foreach_sym(probe_.path.c_str(), sym_address_cb, &option, &sym);

    symbol = sym.name;
    func_offset = probe_.address - sym.start;

    if (!sym.start) {
      std::stringstream ss;
      ss << "0x" << std::hex << probe_.address;
      throw std::runtime_error("Could not resolve address: " + probe_.path + ":" + ss.str());
    }
  }
```

And there if I understand correctly `bcc_elf_foreach_sym` is looking for a symbol defined at `sym_address_cb`.

The binary `/full/path/to/binary` is being ptraced by gdb.

So, is it possible to define uprobe on arbitrary address without any symbol defined on it?

**Comment by danobi** [comment]
I guess it could be done but what is the use case? Why can you not reference the address by function+offset?

**Comment by mzr** [comment]
TBH my use case is CTF right now, but what if one tries to set uprobes inside stripped binaries?

**Comment by danobi** [comment]
Oh interesting. I suppose we could allow it since we're checking instruction boundaries already. What do you think @fbs , @tyroguru ?

>  but what if one tries to set uprobes inside stripped binaries (eg. running on prod)?

Generally stripping binaries is a pretty bad idea b/c it breaks a lot of tooling. Like stack traces.

**Comment by mzr** [comment]
> Generally stripping binaries is a pretty bad idea b/c it breaks a lot of tooling. Like stack traces.
Sure, but isn't being production-safe one of strengths of bpftrace (like dtrace) and dynamic tracing in general? Binaries running in production environments often are stripped.

**Comment by danobi** [comment]
> being production-safe one of the strengths of bpftrace 

So one other thing I'm concerned about by allowing attaching to arbitrary addresses is attaching to stuff in .data and clobbering values. Not sure if our current checks prevent this.

**Comment by mzr** [comment]
How about enabling it only on pages with R-X (.text/code) permissions?

**Comment by fbs** [comment]
> > Generally stripping binaries is a pretty bad idea b/c it breaks a lot of tooling. Like stack traces.
> 
> Sure, but isn't being production-safe one of the strengths of bpftrace (like dtrace) and dynamic tracing in general?

If you misalign your uprobe it tends to crash your program. Which is why we currently check for instruction and why you need UNSAFE_UPROBE if alignment checking fails.

But then again we also allow uretprobes on go binaries even though that breaks(SEGV) with goroutines so it is not unsafe will always protect you.

> Oh interesting. I suppose we could allow it since we're checking instruction boundaries already. What do you think @fbs , @tyroguru ?

Without symbols I think we have to start scanning from the start of the .text sections, which sounds heavy on big binaries. But I don't see why we shouldn't allow a "random" address if the user adds the `--unsafe` flag. Instead of exiting we can just emit the warning and continue.
