### ISSUE TITLE
Cache intermediate objects in CI

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#1285]
Should be possible to speed up CI by caching docker images. We can key the cache object based on the hash of the image.

See https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows

**Comment by filbert14** [comment]
Hi! Is this issue still active? I'd like to contribute, could I claim this issue/get some pointers on where to start?

**Comment by danobi** [comment]
Hi @filbert14 , thanks for the interest!

My memory is a little hazy, but it looks like I ended up implementing this a while ago: https://github.com/iovisor/bpftrace/blob/720bbd086a2da5c8a2915a4cdb8687c666378d31/.github/workflows/ci.yml#L154-L167
