### ISSUE TITLE
Set up CI + code coverage

### ISSUE THREAD

**Issue by ajor** [iovisor/bpftrace#130]

**Comment by mmarchini** [comment]
CI is working, but we still need to figure out a way to execute runtime tests on it (Travis kernel is too old to execute them).

**Comment by mmlb** [comment]
https://cloud.drone.io/ may be an option. I think the underlying host os is ub18.04 and likely that same kernel.

**Comment by zlim** [comment]
Drone Cloud doesn't support docker build yet.

**Comment by mmlb** [comment]
Not even with `plugins/docker`?

**Comment by mmlb** [comment]
Hmm but `/sys/kernel/debug:/sys/kernel/debug` and `--privileged` may be problematic

**Comment by zlim** [comment]
> Not even with `plugins/docker`?
https://github.com/drone/drone/issues/2462 looks relevant. cc @bradrydzewski

**Comment by zlim** [comment]
> Hmm but `/sys/kernel/debug:/sys/kernel/debug` and `--privileged` may be problematic

For testing, you'll need a VM and mounting debugfs on the host kernel.

Running drone + qemu (system) + etc. could be an option.

Or a collection of VM + drone runtime? :)

**Comment by zlim** [comment]
CI-related issues: https://github.com/iovisor/bpftrace/issues/365 https://github.com/iovisor/bpftrace/issues/312

**Comment by zlim** [comment]
A GitLab project is setup at https://gitlab.com/zlim1/bpftrace-ci.

The CI/CI>Pipelines dashboard is available at https://gitlab.com/zlim1/bpftrace-ci/pipelines.
Currently included:
- alpine/arm64
- alpine/amd64 (as comparison against arm64)
- fedora29/amd64 (as comparison against Travis)

Additional reference: https://github.com/WorksOnArm/cluster/issues/150
