### ISSUE TITLE
No output from sys_enter_open ?

### ISSUE THREAD

**Issue by wiperpaul** [iovisor/bpftrace#1306]
## No output from sys_enter_open

sys_enter_open or exit never gives me **any** output compared to openat, below is the static trace I am making.
`tracepoint:syscalls:sys_enter_open` 

In Brendans book he has an example in which he uses
 `tracepoint:syscalls:sys_enter_open { printf("%s %s\n", comm, str(args->filename)); }`
  it results in some `open` calls made by slack for example. For me even when opening various files through services and scripts I can't get a result.

I have been trying to force an `open` call rather than `openat` which I recognise is used more often these days. To do this from my native shell for example I have been trying `exec 4>outfile`.

### debug/tracing/events/syscalls/sys_enter_open/format file
>syscalls/sys_enter_open/format
name: sys_enter_open
ID: 624
format:
	field:unsigned short common_type;	offset:0;	size:2;	signed:0;
	field:unsigned char common_flags;	offset:2;	size:1;	signed:0;
	field:unsigned char common_preempt_count;	offset:3;	size:1;	signed:0;
	field:int common_pid;	offset:4;	size:4;	signed:1;
        field:int __syscall_nr;	offset:8;	size:4;	signed:1;
	field:const char * filename;	offset:16;	size:8;	signed:0;
	field:int flags;	offset:24;	size:8;	signed:0;
	field:umode_t mode;	offset:32;	size:8;	signed:0;

>print fmt: "filename: 0x%08lx, flags: 0x%08lx, mode: 0x%08lx", ((unsigned long)(REC->filename)), ((unsigned long)(REC->flags)), ((unsigned long)(REC->mode))
 
### Sys info
bpftrace 0.9.2-1
Ubuntu 19.10 (Eoan Ermine)
Linux  5.3.0-46-generic

**Comment by brendangregg** [comment]
Did you read Chapter 1? The bit after "The output generated was slower
than I was expecting: I think I’m missing some
open(2) syscall events..."

I might update later tracing examples of open(2), but I hoped
Chapter 1 had it covered.

Brendan

**Comment by wiperpaul** [comment]
You explained it well in the book, I obviously rushed this section in excitement.

**Comment by desolatorxxl** [comment]
For those stumbling about this issues like me, the problem is that most processes don't use the open syscall, but the openat syscall instead.

You can list the different "open" syscalls like this:

```sh
$ bpftrace -l 'tracepoint:syscalls:sys_enter_open*'
tracepoint:syscalls:sys_enter_open
tracepoint:syscalls:sys_enter_open_by_handle_at
tracepoint:syscalls:sys_enter_open_tree
tracepoint:syscalls:sys_enter_openat
tracepoint:syscalls:sys_enter_openat2
```

Most likely openat is what you are looking for:
```sh
bpftrace -e 'tracepoint:syscalls:sys_enter_openat { printf("%s %s\n", comm, str(args->filename)); }'
```

On my rather minimal system I could finally see tmux spamming some calls:

```
tmux /etc/ld.so.cache
tmux /lib64/libutil.so.1
tmux /lib64/libtinfo.so.6
tmux /usr/lib64/libevent-2.1.so.7
tmux /lib64/libresolv.so.2
tmux /lib64/libc.so.6
tmux /lib64/libpthread.so.0
tmux /usr/lib/locale/locale-archive
tmux /etc/localtime
tmux /etc/ld.so.cache
tmux /lib64/libutil.so.1
tmux /lib64/libtinfo.so.6
tmux /usr/lib64/libevent-2.1.so.7
tmux /lib64/libresolv.so.2
tmux /lib64/libc.so.6
tmux /lib64/libpthread.so.0
tmux /usr/lib/locale/locale-archive
tmux /etc/localtime
```

**Comment by Rtoax** [comment]
Hi, everyone, I got a problem. Why my ENV don't have `tracepoint:syscalls:sys_enter_open`?

```
$ sudo bpftrace -l 'tracepoint:syscalls:sys_enter_open*'
tracepoint:syscalls:sys_enter_open_by_handle_at
tracepoint:syscalls:sys_enter_open_tree
tracepoint:syscalls:sys_enter_openat
tracepoint:syscalls:sys_enter_openat2
```

**Comment by fbs** [comment]
probably just the configuration of your kernel but please open a discussion if you need help. This issue is about something else completely and has long since been solved
