### ISSUE TITLE
Expose eBPF bit shift op codes

### ISSUE THREAD

**Issue by jfischoff** [iovisor/bpftrace#1322]
### Is your feature request related to a problem? Please describe.
I am tracing out the ports of sockets and the port is a 16 big endian number. I would like to convert it little endian before displaying. There is no builtin to convert between endianness so I want to write my own with bit shift operations. 

### Describe the solution you'd like

The eBNF assembly has left and right bit shift operations as opcodes AFAIKT (`lsh` and `rsh`). I'd like to expose these arithmetic instructions.

### Describe alternative solutions or features you've considered

A builtin to convert big endian to little endian.

**Comment by danobi** [comment]
It's not documented (should fix that...) but we do have support already:

```
$ sudo ./build/src/bpftrace -e 'BEGIN { printf("%d\n", 1 << 2); }'
[sudo] password for daniel:
Attaching 1 probe...
4
^C
```

Does this work for you?

Also, cc @sumanthkorikkar who was interested in ading hton*/ntoh* builtins a while ago.

**Comment by jfischoff** [comment]
Yes! Thank you!

**Comment by jfischoff** [comment]
Hmm I see there is support for bitwise "not" but is there support for bitwise "or" and "and"? I think I can shift and add in my case which work ... just curious.

**Comment by fbs** [comment]
We support most of the operators C has, bitwise would be &, | and ^. You can find the full list in lexer.l (until we fix documentation), e.g.. `"|" { return Parser::make_BOR(loc); }` being  the bitwise or
`

**Comment by jfischoff** [comment]
I'm going to close the issue since I'm unblocked.
