### ISSUE TITLE
printf() only supports 7 arguments

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#1336]
### Is your feature request related to a problem? Please describe.
It would be useful to have support for more arguments. I don't think there's a technical limit.

### Describe the solution you'd like
More args

### Describe alternative solutions or features you've considered
n/a

**Comment by danobi** [comment]
One way I thought of to support arbitrary number of arguments is to:
* use a format string regex (see `bpftrace::verify_format_string`) to capture and pull out all format string tokens
* format each token one by one in scratch buffer
* add formatted string to accumulator, being careful to truncate if accumulated length goes past max size
* add interposed text (ie not format string token) as appropriate, still being careful to truncate

The reason we can't do it all in one shot is b/c `*printf` family of functions need a fixed # of args known at compile time (b/c of the va_args) stuff. Same thing w/ c++ parameter packs and if we wanted to use `fmt` (https://fmt.dev/latest/api.html#printf-formatting) + parameter packs

**Comment by Birch-san** [comment]
> `*printf` family of functions need a fixed # of args known at compile time

Can we use [`*vprintf`](https://en.cppreference.com/w/cpp/io/c/vfprintf) instead?

**Comment by danobi** [comment]
> Can we use *vprintf instead?

I looked into this but there's no way to safely construct a `va_list` struct (according to the internet)
