### ISSUE TITLE
bpftrace looking for /sys/kernel/debug/tracing instead of /sys/kernel/tracing

### ISSUE THREAD

**Issue by avdi** [iovisor/bpftrace#1338]
Today I ran into an issue where bpftrace reported that it couldn't find the `available_filter_functions`:

```
root@b40be1747ab9:/workspaces/idw# bpftrace -l
...a very short list, followed by...
No such file or directory: /sys/kernel/debug/tracing/available_filter_functions
```

It turned out that `debugfs` had come unmounted for some reason. But I went down a rabbit hole because I found [this documentation ](https://www.kernel.org/doc/Documentation/trace/ftrace.txt)saying that tracing lives at `/sys/kernel/tracing` not `/sys/kernel/debug/tracing` in recent kernels. And indeed, `/sys/kernel/tracing` WAS available.

Anyway like I said, re-mounting `debugfs` fixed the issue. But it might be nice to have an error message that suggests mounting `debugfs`.

**Comment by javierhonduco** [comment]
Good idea! Wonder if it would make sense to have some subcommand like `bpftrace doctor` to check for various things to be in the "right" place.

Maybe also do some Kernel checks like [this script](https://github.com/iovisor/bpftrace/blob/master/scripts/check_kernel_features.sh)?

**Comment by fbs** [comment]
> Good idea! Wonder if it would make sense to have some subcommand like `bpftrace doctor` to check for various things to be in the "right" place.

I think we can do that in the `--info` flag, displaying either the path to tracefs or `no`.

For detection we could extend (and possibly rename to kernelfeature) bpffeature.

**Comment by brendangregg** [comment]
G'Day @avdi! Glad you're trying bpftrace!

**Comment by avdi** [comment]
Hi @brendangregg! Since diving into the world of BPF I've been having some "oh it was THAT Brenden Gregg that I hung out with in Australia" moments 😅

**Comment by Davis-A** [comment]
I've just run into this issue.  We don't mount debugfs which makes this somewhat awkward

**Comment by danobi** [comment]
We really should just parse mount table and not hard code these paths

**Comment by neomafo88** [comment]
if it helps anyone, what worked for me wanting to build https://github.com/facebookexperimental/ExtendedAndroidTools, which uses `bpftrace`, was:

from root `/ExtendedAndroidTools/projects`,

```
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/docs/reference_guide.md
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/docs/tutorial_bcc_python_developer.md
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/examples/cpp/CGroupTest.cc
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/examples/cpp/HelloWorld.cc
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/examples/tracing/urandomread-explicit.py
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/examples/tracing/urandomread.py
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/examples/usdt_sample/usdt_sample.md
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/libbpf-tools/trace_helpers.c
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/libbpf-tools/trace_helpers.h
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/src/cc/compat/linux/virtual_bpf.h
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/src/cc/frontends/clang/tp_frontend_action.cc
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/src/cc/libbpf.c
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/src/cc/libbpf/include/uapi/linux/bpf.h
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/src/cc/libbpf/src/bpf_helper_defs.h
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/src/cc/libbpf/src/libbpf.c
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/src/lua/bpf/bpf.lua
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/src/lua/bpf/cdef.lua
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/src/lua/README.md
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/src/python/bcc/__init__.py
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/tools/bpflist.py
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/tools/opensnoop_example.txt
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bcc/sources/tools/reset-trace_example.txt
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bpftrace/sources/docs/reference_guide.md
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bpftrace/sources/scripts/tracepoint_variable_sized_types.py
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bpftrace/sources/src/probe_matcher.h
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bpftrace/sources/src/tracepoint_format_parser.cpp
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bpftrace/sources/tests/bpftrace.cpp
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bpftrace/sources/tests/mocks.cpp
sed -E -i 's|/sys/kernel/debug/tracing/|/sys/kernel/tracing/|g' bpftrace/sources/tools/writeback.bt

```

**Comment by tiann** [comment]
https://github.com/iovisor/bcc/issues/4043

**Comment by michalgr** [comment]
Hi all.

Thanks to @anakryiko [libbpf already has some logic to determine whether to use debugfs or not](https://github.com/libbpf/libbpf/blob/master/src/libbpf.c#L9908) and I opened pull requests to mirror it in [bpftrace](https://github.com/iovisor/bpftrace/pull/2351) and [bcc](https://github.com/iovisor/bcc/pull/4216).

**Comment by sanmai-NL** [comment]
@avdi Can this be closed, given the previous post?

**Comment by avdi** [comment]
Heh, it's been long enough I don't remember anything about this issue. Close it! 

—
Avdi Grimm

--- original message ---
On April 9, 2023 at 3:05 AM EDT ***@***.*** wrote:



@avdi Can this be closed, given the previous post?

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by sanmai-NL** [comment]
You can yourself 😃
