### ISSUE TITLE
bpftrace uprobe pthread_create on android adeb env

### ISSUE THREAD

**Issue by b-ripper** [iovisor/bpftrace#1348]
On Android adeb env, if use bpftrace trace uprobe pthread_create, the path should be uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_create,
not uprobe:/system/lib/bootstrap/libc.so:pthread_create, uprobe:/system/lib64/bootstrap/libc.so:pthread_create.
Is that right?
All these three paths could find the uprobe pthread* list. On my device, there is no any event traced out on these paths.

**Comment by danobi** [comment]
To restate: is the issue that there are no uprobe events available on any of those 3 paths?

If so, can you share the output of `bpftrace --info`? Wondering if your android kernel has uprobe config turned off.

**Comment by b-ripper** [comment]
> To restate: is the issue that there are no uprobe events available on any of those 3 paths?
> 
> If so, can you share the output of `bpftrace --info`? Wondering if your android kernel has uprobe config turned off.

**Comment by b-ripper** [comment]
> To restate: is the issue that there are no uprobe events available on any of those 3 paths?
> 
> If so, can you share the output of `bpftrace --info`? Wondering if your android kernel has uprobe config turned off.

@danobi  
**hi danobi, the following is the output if bpftrace --info**:
root@localhost:/# bpftrace --info
bpftrace: unrecognized option '--info'
USAGE:
    bpftrace [options] filename
    bpftrace [options] -e 'program'

OPTIONS:
    -B MODE        output buffering mode ('line', 'full', or 'none')
    -d             debug info dry run
    -o file        redirect program output to file
    -dd            verbose debug info dry run
    -e 'program'   execute this program
    -h, --help     show this help message
    -I DIR         add the directory to the include search path
    --include FILE add an #include file before preprocessing
    -l [search]    list probes
    -p PID         enable USDT probes on PID
    -c 'CMD'       run CMD and enable USDT probes on resulting process
    --unsafe       allow unsafe builtin functions
    -v             verbose messages
    -V, --version  bpftrace version

ENVIRONMENT:
    BPFTRACE_STRLEN           [default: 64] bytes on BPF stack per str()
    BPFTRACE_NO_CPP_DEMANGLE  [default: 0] disable C++ symbol demangling
    BPFTRACE_MAP_KEYS_MAX     [default: 4096] max keys in a map
    BPFTRACE_CAT_BYTES_MAX    [default: 10k] maximum bytes read by cat builtin
    BPFTRACE_MAX_PROBES       [default: 512] max number of probes

EXAMPLES:
bpftrace -l '*sleep*'
    list probes containing "sleep"
bpftrace -e 'kprobe:do_nanosleep { printf("PID %d sleeping...\n", pid); }'
    trace processes calling sleep
bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'
    count syscalls by process name

**All these paths could list the function path**:
root@localhost:/# bpftrace -l 'uprobe:/system/lib/bootstrap/libc.so:pthread*'
uprobe:/system/lib/bootstrap/libc.so:pthread_setspecific
uprobe:/system/lib/bootstrap/libc.so:pthread_barrierattr_getpshared
uprobe:/system/lib/bootstrap/libc.so:pthread_exit
uprobe:/system/lib/bootstrap/libc.so:pthread_mutexattr_gettype
uprobe:/system/lib/bootstrap/libc.so:pthread_attr_getscope
uprobe:/system/lib/bootstrap/libc.so:pthread_cond_timedwait_monotonic_np
uprobe:/system/lib/bootstrap/libc.so:pthread_attr_setguardsize
uprobe:/system/lib/bootstrap/libc.so:pthread_attr_setschedpolicy
uprobe:/system/lib/bootstrap/libc.so:pthread_getschedparam
uprobe:/system/lib/bootstrap/libc.so:pthread_rwlock_timedwrlock
uprobe:/system/lib/bootstrap/libc.so:pthread_mutexattr_getpshared
uprobe:/system/lib/bootstrap/libc.so:pthread_attr_setinheritsched
...

root@localhost:/# bpftrace -l 'uprobe:/system/lib64/bootstrap/libc.so:pthread*'
uprobe:/system/lib64/bootstrap/libc.so:pthread_mutex_lock
uprobe:/system/lib64/bootstrap/libc.so:pthread_mutexattr_destroy
uprobe:/system/lib64/bootstrap/libc.so:pthread_cond_signal
uprobe:/system/lib64/bootstrap/libc.so:pthread_cond_timedwait
uprobe:/system/lib64/bootstrap/libc.so:pthread_rwlockattr_setpshared
uprobe:/system/lib64/bootstrap/libc.so:pthread_create
uprobe:/system/lib64/bootstrap/libc.so:pthread_attr_setstacksize
uprobe:/system/lib64/bootstrap/libc.so:pthread_mutexattr_gettype
uprobe:/system/lib64/bootstrap/libc.so:pthread_attr_destroy
uprobe:/system/lib64/bootstrap/libc.so:pthread_gettid_np
...

root@localhost:/# bpftrace -l 'uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread*'
uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_getattr_np
uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_condattr_getpshared
uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_attr_setaffinity_np
uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_rwlockattr_init
uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_timedjoin_np
uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_attr_setguardsize
uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_attr_getstackaddr
uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_condattr_setclock
uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_sigqueue
uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_attr_setscope
uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_barrierattr_setpshared
uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_condattr_setpshared
...


**but there is no trace event happen**:
root@localhost:/# bpftrace -e 'BEGIN { printf("%-10s %-6s %-16s %s\n", "TIME(ms)", "PID", "COMM", "FUNC");} uprobe:/system/lib/bootstrap/libc.so:pthread_create{ printf("%-6d %-16s\n", pid, comm);}'
Attaching 2 probes...
TIME(ms) PID COMM FUNC
^C

root@localhost:/# bpftrace -e 'BEGIN { printf("%-10s %-6s %-16s %s\n", "TIME(ms)", "PID", "COMM", "FUNC");} uprobe:/system/lib64/bootstrap/libc.so:pthread_create{ printf("%-10u %-6d %-16s %s\n", elapsed /1000000, pid, comm, usym(arg2));}'
Attaching 2 probes...
TIME(ms) PID COMM FUNC
^C

root@localhost:/# bpftrace -e 'BEGIN { printf("%-10s %-6s %-16s %s\n", "TIME(ms)", "PID", "COMM", "FUNC");} uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_create{ printf("%-10u %-6d %-16s %s\n", elapsed /1000000, pid, comm, usym(arg2));}'
Attaching 2 probes...
TIME(ms) PID COMM FUNC
^C

**I don't know which path is the right one, or any dependency needed.**

**Comment by danobi** [comment]
Seems you're on a pretty old version of bpftrace. First thing I would try is to get a newer version and see if issue is still around.

Not really sure what could be wrong. Maybe you could try writing a test program that calls `pthread_create` and check via `ldd` that it's linked to one of the `libc.so`'s you're trying to attach to.

**Comment by b-ripper** [comment]
@danobi 
Hi danobi,

the version of bpftrace on my device is 0.9.1;

**I write a test program that calls pthread_create, built under adeb env, could trace the output result:**
root@localhost:/# bpftrace -e 'BEGIN { printf("%-10s %-6s %-16s %s\n", "TIME(ms)", "PID", "COMM", "FUNC");} uprobe:/lib/aarch64-linux-gnu/libpthread.so.0:pthread_create{ printf("%-10u %-6d %-16s %s\n", elapsed /1000000, pid, comm, usym(arg2));}'
Attaching 2 probes...
TIME(ms) PID COMM FUNC
181 4669 pthread_test ChildThreadFunction
457 4669 pthread_test ChildThreadFunction
764 4669 pthread_test ChildThreadFunction
1065 4669 pthread_test ChildThreadFunction
1366 4669 pthread_test ChildThreadFunction
1666 4669 pthread_test ChildThreadFunction
1966 4669 pthread_test ChildThreadFunction
2266 4669 pthread_test ChildThreadFunction
2566 4669 pthread_test ChildThreadFunction
2866 4669 pthread_test ChildThreadFunction
3165 4669 pthread_test ChildThreadFunction
3466 4669 pthread_test ChildThreadFunction
3765 4669 pthread_test ChildThreadFunction
^C

**but for test program built for android which execute under adb env, there is no trace result output:**
root@localhost:/# bpftrace -e 'BEGIN { printf("%-10s %-6s %-16s %s\n", "TIME(ms)", "PID", "COMM", "FUNC");} uprobe:/system/lib/bootstrap/libc.so:pthread_create{ printf("%-6d %-16s\n", pid, comm);}'
Attaching 2 probes...
TIME(ms) PID COMM FUNC
^C

root@localhost:/# bpftrace -e 'BEGIN { printf("%-10s %-6s %-16s %s\n", "TIME(ms)", "PID", "COMM", "FUNC");} uprobe:/system/lib64/bootstrap/libc.so:pthread_create{ printf("%-10u %-6d %-16s %s\n", elapsed /1000000, pid, comm, usym(arg2));}'
Attaching 2 probes...
TIME(ms) PID COMM FUNC
^C

**So, my problem is that under adeb env, no ability to trace the function caller to bionic library?**

**Comment by danobi** [comment]
> So, my problem is that under adeb env, no ability to trace the function caller to bionic library?

Can you run `ldd <your application>` and see which libc it links to? Maybe it's statically linked in. In that case the uprobe won't fire.

**Comment by b-ripper** [comment]
On Android Q, bionic shared library is now symlink:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
root@localhost:/# ls system/lib64/libc.so -l
lrw-r--r--. 1 root root 46 Jan  1  2009 system/lib64/libc.so -> /apex/com.android.runtime/lib64/bionic/libc.so
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

this will work fine:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
root@localhost:/# bpftrace -e 'BEGIN { printf("%-10s %-6s %-16s %s\n", "TIME(ms)", "PID", "COMM", "FUNC");} uprobe:/system/apex/com.android.runtime.release/lib64/bionic/libc.so:pthread_create{ printf("%-10u %-6d %-16s %s\n", elapsed /1000000, pid, comm, usym(arg2));}'
Attaching 2 probes...
TIME(ms)   PID    COMM             FUNC
4307       732    perf@2.0-servic  __timer_thread_start(void*)
4354       11363  .android.camera  art::Thread::CreateCallback(void*)
4364       11363  RxCachedThreadS  art::Thread::CreateCallback(void*)
4390       11363  .android.camera  art::Thread::CreateCallback(void*)
4406       732    perf@2.0-servic  __timer_thread_start(void*)
4578       5250   pool-15-thread-  art::Thread::CreateCallback(void*)
4777       1237   backlight-notif  0x75090b29a8
4811       701    HwBinder:701_5   0x7d510079c0
4842       701    HwBinder:701_5   0x7d5102c228
4856       602    netd             0x7644cd39a0
4859       701    HwBinder:701_5   0x7d5102c228
4897       701    HwBinder:701_5   0x7d510a0628
4996       701    HwBinder:701_5   0x7d773a89a8
5003       701    HwBinder:701_5   0x7d779554c0
5088       11363  RxSingleSchedul  art::Thread::CreateCallback(void*)
5170       1237   backlight-notif  0x75090b29a8
5477       1237   backlight-notif  0x75090b29a8
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
