### ISSUE TITLE
clear() on count()-based map fails with a key error

### ISSUE THREAD

**Issue by lorddoskias** [iovisor/bpftrace#1350]
### bpftrace --info

```
root@ubuntu18:~# bpftrace --info
System
  OS: Linux 5.7.0-rc5-default #361 SMP Tue May 26 12:34:40 EEST 2020
  Arch: x86_64

Build
  version: v0.10.0-124-g147a
  LLVM: 6
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
```

### What reproduces the bug?
Following bpftrace program exits with an error: 

`bpftrace -e 'kprobe:btrfs_commit_transaction { @exec = count() } interval:s:3 { print(@exec); clear(@exec); } '`  

I get: 

```
terminate called after throwing an instance of 'std::runtime_error'
what():  Could not clear map with ident "@exec", err=-1
```

My expectation is to print the number of times this kprobe has fired and clear it up for the next interval. I've literally coded this after an example in the reference guide.

**Comment by fbs** [comment]
Thanks for the report.

Looks like this is due to the change in 439a6bc57ef9daf5d4b8789e918133d62da90d50. As the type now depends on whether the map "has keys" the way it has to be cleared has to change too.

as a quick work around you can do `@exec[1]=count()`. Ill work on a fix

**Comment by fbs** [comment]
Hmm looking at this again I wonder if it makes sense to `clear` a `count` map like happens here.   Maybe it makes more sense to only allow `zero()` in this case and inform the user.

So  `@=count(); zero(@)` will be valid. `@=count(); clear(@)` will generate a warning `cannot clear() a count map, use zero() instead`. 

However with an associative array both are valid. So `@[1,2]=count(); clear(@);` and `@[1,2]=count(); zero(@)` will both be valid but they will do different things. Clear will delete all keys while zero will set the value to 0 for each.

The alternative is to do something like this

```diff
diff --git a/src/bpftrace.cpp b/src/bpftrace.cpp
index 965d7188..14404de7 100644
--- a/src/bpftrace.cpp
+++ b/src/bpftrace.cpp
@@ -1099,6 +1099,10 @@ int BPFtrace::print_maps()
 // clear a map
 int BPFtrace::clear_map(IMap &map)
 {
+  if (map.is_array_type())
+  {
+    return zero_map(map);
+  }
```

**Comment by mmisono** [comment]
I found that `delete()` also does not work with count()-map since an element of BPF_MAP_TYPE_(PERCPU_)ARRAY cannot be deleted.

```
% sudo ./src/bpftrace -e 'BEGIN { @ = count(); delete(@); print(@) }' -k
Attaching 1 probe...
stdin:1:22-31: WARNING: Failed to map_delete_elem: Invalid argument (-22)
BEGIN { @ = count(); delete(@); print(@) }
                     ~~~~~~~~~
@: 1
```

**Comment by lorddoskias** [comment]
> I found that `delete()` also does not work with count()-map since an element of BPF_MAP_TYPE_(PERCPU_)ARRAY cannot be deleted.
> 
> ```
> % sudo ./src/bpftrace -e 'BEGIN { @ = count(); delete(@); print(@) }' -k
> Attaching 1 probe...
> stdin:1:22-31: WARNING: Failed to map_delete_elem: Invalid argument (-22)
> BEGIN { @ = count(); delete(@); print(@) }
>                      ~~~~~~~~~
> @: 1
> ```

That's to be expected due to the way percup maps are implemented. Excerpt from bcc reference guide on PERCPU_ARRAYS: 

> Note that all array elements are pre-allocated with zero values and can not be deleted.

I think bpf filter should provide consistent interface when working with counts() or alternatively explicitly document changed behavior. As it stands now some of the examples in  the reference guide as broken as well.

**Comment by jeromemarchand** [comment]
Any progress on that issue?
The pidpersec tool is affected by the issue:

```$ pidpersec.bt 
Attaching 4 probes...
Tracing new processes... Hit Ctrl-C to end.
10:32:46 PIDs/sec: @: 0

Error looking up elem: -1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not clear map with ident "@", err=-1
Aborted
```

Replacing clear() with zero() as suggested above fixes the issue.

**Comment by mmisono** [comment]
I hit the issue and made the fix. I'll create a PR over the weekend.

**Comment by mmisono** [comment]
I was going to make a PR after processing my fuzzing-related PRs, but suddenly I heard a noise from the machine, so I made a PR anyway.
