### ISSUE TITLE
bpftrace fails on arm64 with many CPUs

### ISSUE THREAD

**Issue by jeromemarchand** [iovisor/bpftrace#1355]
### bpftrace --info
System
  OS: Linux 4.18.0-206.el8.aarch64 #1 SMP Tue May 26 18:40:29 UTC 2020
  Arch: aarch64

Build
  version: v0.10.0-143-g1033
  LLVM: 10
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no

### What reproduces the bug?
Running any bpftrace tool on a arm64 machine with enough CPUs.

$ /usr/local/share/bpftrace/tools/biolatency.bt
Attaching 4 probes...
mmap: Cannot allocate memory
Failed to open perf buffer

What's happening is that we hit the 1 GB address space limit set in cap_memory_limits(). There are 2 factors at play here: first, there are many cpus on this machine (256) and second, the page size is 64k. So in setup_perf_events() we're trying to open 256 perf buffer of  64 pages (that is 4 MB per cpu).

The memory limits in cap_memory_limits() should probably be dependant on the memory available in the machine. Also, do we need address space limit at all? The RSS limit should be enough to prevent OOM and it's quite common that the address space is significantly bigger than RSS. Just removing the RLIMIT_AS line allows bpftrace to work on that machine and the RSS stays well below the 1 GB limit.

**Comment by danobi** [comment]
Thanks for the report. I suspect we can remove the RLIMIT_AS. AS limits are kinda stupid in principle anyways. I believe it was added to mitigate some llvm issue we had a long time ago. As a temporary workaround, newer versions of bpftrace have https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#98-bpftrace_perf_rb_pages which you can use to lower the memory allocation.
