### ISSUE TITLE
config bpftrace 0.10.0 version has problem

### ISSUE THREAD

**Issue by b-ripper** [iovisor/bpftrace#1359]
I built under  adeb debian env on Android device:

root@localhost:/bpftrace/build# cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-7 -DCMAKE_CXX_COMPILER=clang++-7  -DBUILD_TESTING=OFF 
-- The C compiler identification is Clang 7.0.1
-- The CXX compiler identification is Clang 7.0.1
-- Check for working C compiler: /usr/bin/clang-7
-- Check for working C compiler: /usr/bin/clang-7 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-7
-- Check for working CXX compiler: /usr/bin/clang++-7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibBcc: /usr/lib/aarch64-linux-gnu/libbcc.so  
-- Found LibElf: /usr/lib/aarch64-linux-gnu/libelf.so  
-- Performing Test ELF_GETSHDRSTRNDX
-- Performing Test ELF_GETSHDRSTRNDX - Success
-- Found BISON: /usr/bin/bison (found version "3.3.2") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Looking for name_to_handle_at
-- Looking for name_to_handle_at - found
-- Looking for bcc_prog_load
-- Looking for bcc_prog_load - found
-- Looking for bcc_create_map
-- Looking for bcc_create_map - found
-- Looking for bcc_elf_foreach_sym
-- Looking for bcc_elf_foreach_sym - found
-- Looking for bpf_attach_kfunc
-- Looking for **bpf_attach_kfunc - not found**
-- Performing Test HAVE_BPF_PROG_TYPE_TRACING
**-- Performing Test HAVE_BPF_PROG_TYPE_TRACING - Failed**
-- **Please install the libbpf development package (missing: LIBBPF_LIBRARIES LIBBPF_INCLUDE_DIRS)** 
-- Found LibBfd: /usr/lib/aarch64-linux-gnu/libbfd.so  
-- Found LibOpcodes: /usr/lib/aarch64-linux-gnu/libopcodes.so  
-- Performing Test LIBBFD_DISASM_FOUR_ARGS_SIGNATURE
-- Performing Test LIBBFD_DISASM_FOUR_ARGS_SIGNATURE - Success
-- Looking for sys/sdt.h
-- Looking for sys/sdt.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /bpftrace/build

**Comment by b-ripper** [comment]
build has no error, but `bpftrace --info` has abnormal message:
root@localhost:/bpftrace/build# bpftrace --info
System
  OS: Linux 4.14.117-perf-gb69f97f #1 SMP PREEMPT Thu May 28 16:27:40 CST 2020
  Arch: aarch64

Build
  version: v0.10.0
  LLVM: 7
  foreach_sym: yes
  unsafe uprobe: no
  btf: no
  bfd: yes

Segmentation fault

**Comment by danobi** [comment]
Can you post a stack trace of the segfault? Never seen this before.

**Comment by b-ripper** [comment]
sorry the segfault error is my local error.
