### ISSUE TITLE
test codegen before opt

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#1368]
Currently we test codegen _after_ optimization. this has 2 issues: 

- We have to rewrite generated code to deal with LLVM versions which adds a lot of noise
- We don't actually test the code we generate, we test what LLVM does to it. This makes harder to relate a change in the codegen to a change in the LLVM output.

Are there any objections to switching the tests to the code we generate? It will be a bit more verbose but we wont have to deal with llvm version specific optimizations anymore, only with version specific function call differences.

**Comment by mmisono** [comment]
codegen before optimization generally contains several unused functions (log2, hist.is_less_than_zero, etc.). So if we use all codegen results before optimization for tests, we need to change all tests when changing these functions. I wonder if we can only optimize out unused functions (and do other fewer side-effects optimization if any) for tests.

**Comment by danobi** [comment]
I think this is a good idea.

> codegen before optimization generally contains several unused functions (log2, hist.is_less_than_zero, etc.). So if we use all codegen results before optimization for tests, we need to change all tests when changing these functions.

I'm hitting this issue right now (log2 changes). I don't see why we can't generate global function code on demand -- it's straightforward enough.

**Comment by fbs** [comment]
I'm  wondering whether there are any downsides to limiting codegen tests to LLVM7. The rewriting turned out more complex than I originally hoped for and now we have to deal with evaluation order (between gcc and clang) too.
