### ISSUE TITLE
0.10.0 bpftrace dependency

### ISSUE THREAD

**Issue by b-ripper** [iovisor/bpftrace#1369]
### How to resolve the following dependency problems?

-- Looking for bpf_attach_kfunc - not found
-- Performing Test HAVE_BPF_PROG_TYPE_TRACING
-- Performing Test HAVE_BPF_PROG_TYPE_TRACING - Failed
-- Please install the libbpf development package (missing: LIBBPF_LIBRARIES LIBBPF_INCLUDE_DIRS)

  unsafe uprobe: no
  bpf_attach_kfunc: no
  libbpf: no
  libbpf btf dump: no
  libbpf btf dump type decl: no

Kernel features
  Instruction limit: -1
  Loop support: no
  btf: no

Probe types
  kprobe: no
  kfunc: no

### bpftrace --info

System
  OS: Linux 4.14.117-perf-gcb2425c #1 SMP PREEMPT Wed Jun 3 13:09:15 CST 2020
  Arch: aarch64

Build
  version: v0.10.0-155-ga34c
  LLVM: 7
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: no
  libbpf: no
  libbpf btf dump: no
  libbpf btf dump type decl: no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes

Kernel features
  Instruction limit: -1
  Loop support: no
  btf: no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: no
  tracepoint: yes
  perf_event: yes
  kfunc: no

**Comment by b-ripper** [comment]
[Kconfig.txt](https://github.com/iovisor/bpftrace/files/4727085/Kconfig.txt)

@danobi  please help to check the Kconfig, very thanks!

**Comment by danobi** [comment]
kconfig looks reasonable. Not sure what it could be. Maybe selinux or lockdown?

Can you strace `bpftrace --info` execution and send results? Curious what the error codes are when bpftrace feature tests.

**Comment by b-ripper** [comment]
[output.txt](https://github.com/iovisor/bpftrace/files/4743611/output.txt)
@danobi  please help to check the strace output of `bpftrace --info`, very thanks!

**Comment by danobi** [comment]
It's showing EINVAL on trying to load progs that should be ok. My best guess is it has to do with your custom kernel.

I don't think there's much I can do to help you debug this without access to your system.
