### ISSUE TITLE
perf_event_output needn't call CreateGetCpuId()

### ISSUE THREAD

**Issue by Birch-san** [iovisor/bpftrace#1375]
According to the [BPF helpers man page](https://man7.org/linux/man-pages/man7/bpf-helpers.7.html), there's an easier way to "send perf event to current CPU".

> ```c
> int bpf_perf_event_output(struct pt_regs *ctx, struct bpf_map *map,
>        u64 flags, void *data, u64 size)
> ```
>
> The _flags_ are used to indicate the index in map for
> which the value must be put, masked with
> `BPF_F_INDEX_MASK`.  Alternatively, _flags_ can be set to
> `BPF_F_CURRENT_CPU` to indicate that the index of the
> current CPU core should be used.

In our `IRBuilderBPF::CreatePerfEventOutput`, we go to the trouble of emitting a call to `bpf_raw_smp_processor_id()`:

https://github.com/iovisor/bpftrace/blob/1d8a3a7/src/ast/irbuilderbpf.cpp#L868

but we can ask Linus to do that for us by setting our flag to `BPF_F_CURRENT_CPU`:

```diff
-   Value *flags_val = CreateGetCpuId();
+   Value *flags_val = getInt64(BPF_F_CURRENT_CPU);
```

Sure enough, it looks like the kernel would give us `smp_processor_id()` if we set the flag like that:

https://github.com/torvalds/linux/blob/cb8e59c/kernel/trace/bpf_trace.c#L783

Any reason not to prefer the `BPF_F_CURRENT_CPU` approach? It'd reduce the amount of instructions in our BPF program, and it worked in the branch I tried it in.

**Comment by Birch-san** [comment]
Also, whilst we're in the area: should we respell `CreateGetCpuId()` to return a 32-bit int?

https://github.com/iovisor/bpftrace/blob/1d8a3a7/src/ast/irbuilderbpf.cpp#L767

```diff
    // u64 bpf_get_current_task(void)
    // Return: current task_struct
-   FunctionType *getcurtask_func_type = FunctionType::get(getInt64Ty(), false);
+   FunctionType *getcurtask_func_type = FunctionType::get(getInt32Ty(), false);
```

**Comment by mmisono** [comment]
As for return values, yes, the function (as well as other helper functions) should return a 32-bit int (cf. https://github.com/iovisor/bpftrace/blob/1d8a3a7/src/ast/irbuilderbpf.cpp#L1011-L1013). The fix is not quite simple since it'll cause a lot of codegen test changes.

**Comment by danobi** [comment]
> Any reason not to prefer the BPF_F_CURRENT_CPU approach? It'd reduce the amount of instructions in our BPF program, and it worked in the branch I tried it in.

Can't think of any reasons. Seems like an oversight in the current implementation.

**Comment by fbs** [comment]
> Also, whilst we're in the area: should we respell `CreateGetCpuId()` to return a 32-bit int?
> 
> https://github.com/iovisor/bpftrace/blob/1d8a3a7/src/ast/irbuilderbpf.cpp#L767
> 
> ```diff
>     // u32 bpf_raw_smp_processor_id(void)
>     // Return: SMP processor ID
> -   FunctionType *getcurtask_func_type = FunctionType::get(getInt64Ty(), false);
> +   FunctionType *getcurtask_func_type = FunctionType::get(getInt32Ty(), false);
> ```

> As for return values, yes, the function (as well as other helper functions) should return a 32-bit int (cf. https://github.com/iovisor/bpftrace/blob/1d8a3a7/src/ast/irbuilderbpf.cpp#L1011-L1013). The fix is not quite simple since it'll cause a lot of codegen test changes.

I think all this still stems from the "all ints are 64 bits", e.g. we still upgrade printf arguments to 8bytes too. We should fix this, but we might have to fix a few more cases to get it to work properly. I started on it, but then got blocked on the lack of a proper pointer type (which im fixing fix, slowly). IIRC we also have a ticket for it somewhere

> Any reason not to prefer the BPF_F_CURRENT_CPU approach? It'd reduce the amount of instructions in our BPF program, and it worked in the branch I tried it in.

+1 for fixing this
