### ISSUE TITLE
could bpftrace trace uprobe for c++ library support c++filt transfer func name?

### ISSUE THREAD

**Issue by b-ripper** [iovisor/bpftrace#1408]
### Is your feature request related to a problem? Please describe.

Trace uprobe func in c++ library, need like this:
`root@localhost:/# bpftrace -e 'uprobe:/vendor/lib64/hw/com.qti.chi.override.so:_ZN16CHIBufferManager6CreateEPKcP26CHIBufferManagerCreateData {  printf("comm: %s pid: %d func: %s\n", comm, pid, func);}'
Attaching 1 probe...
comm: HwBinder:851_3 pid: 851 func: CHIBufferManager::Create(char const*, CHIBufferManagerCreateData*)`

`root@localhost:/# c++filt _ZN16CHIBufferManager6CreateEPKcP26CHIBufferManagerCreateData
CHIBufferManager::Create(char const*, CHIBufferManagerCreateData*)`

### Describe the solution you'd like

could bpftrace support c++filt internally，then it will be like this：
`uprobe:/vendor/lib64/hw/com.qti.chi.override.so:CHIBufferManager::Create(char const*, CHIBufferManagerCreateData*) {  printf("comm: %s pid: %d func: %s\n", comm, pid, func);}'
Attaching 1 probe...
comm: HwBinder:851_3 pid: 851 func: CHIBufferManager::Create(char const*, CHIBufferManagerCreateData*)`

**Comment by caringi** [comment]
Which bpftrace are you using?

Support for C++ Symbol demangling has been added in version 0.10.0:

https://github.com/iovisor/bpftrace/releases/tag/v0.10.0

https://github.com/iovisor/bpftrace/issues/687
https://github.com/iovisor/bpftrace/pull/1116

Or is it not working as expected?

**Comment by b-ripper** [comment]
@caringi I used bpftrace version: v0.10.0-193-g68b4 
It not worked on my Android device.
@michalgr could you help to have a look that check on your Android device about uprobe func list from C++ library? very thanks!

**Comment by caringi** [comment]
Please, could you try this way (adding double quotes around the function name):

bpftrace -e 'uprobe:/vendor/lib64/hw/com.qti.chi.override.so:"CHIBufferManager::Create(char const*, CHIBufferManagerCreateData*)" { printf("comm: %s pid: %d func: %s\n", comm, pid, func);}'

**Comment by b-ripper** [comment]
root@localhost:/# bpftrace -e 'uprobe:/vendor/lib64/hw/com.qti.chi.override.so:"CHIBufferManager::Create(char const*, CHIBufferManagerCreateData*)" { printf("comm: %s pid: %d func: %s\n", comm, pid, func);}'
Attaching 1 probe...
comm: HwBinder:809_1 pid: 809 func: CHIBufferManager::Create(char const*, CHIBufferManagerCreateData*)


It worked! very thanks! @caringi

**Comment by b-ripper** [comment]
@caringi  I have another problem:
how to list the right func name by bpftrace -l? 
like:
`root@localhost:/# bpftrace -l 'uprobe:/vendor/lib64/hw/com.qti.chi.override.so:*CHIBufferManager*'
uprobe:/vendor/lib64/hw/com.qti.chi.override.so:_ZN16CHIBufferManager10BindBufferEPK13ChiBufferInfo
uprobe:/vendor/lib64/hw/com.qti.chi.override.so:_ZN16CHIBufferManager10CopyBufferEPK13ChiBufferInfoPS0_
uprobe:/vendor/lib64/hw/com.qti.chi.override.so:_ZN16CHIBufferManager10DeactivateEi
uprobe:/vendor/lib64/hw/com.qti.chi.override.so:_ZN16CHIBufferManager10InitializeEPKcP26CHIBufferManagerCreateData
uprobe:/vendor/lib64/hw/com.qti.chi.override.so:_ZN16CHIBufferManager11FreeBuffersEi
`

**Comment by b-ripper** [comment]
It not worked like this:
`root@localhost:/# bpftrace -l 'uprobe:/vendor/lib64/hw/com.qti.chi.override.so:"*CHIBufferManager*"'
`

**Comment by b-ripper** [comment]
It will work like this:
`root@localhost:/# bpftrace -l 'uprobe:/vendor/lib64/hw/com.qti.chi.override.so:*CHIBufferManager*' | stdbuf -oL c++filt
uprobe:/vendor/lib64/hw/com.qti.chi.override.so:CHIBufferManager::BindBuffer(ChiBufferInfo const*)
uprobe:/vendor/lib64/hw/com.qti.chi.override.so:CHIBufferManager::CopyBuffer(ChiBufferInfo const*, ChiBufferInfo*)
uprobe:/vendor/lib64/hw/com.qti.chi.override.so:CHIBufferManager::Deactivate(int)
uprobe:/vendor/lib64/hw/com.qti.chi.override.so:CHIBufferManager::Initialize(char const*, CHIBufferManagerCreateData*)
uprobe:/vendor/lib64/hw/com.qti.chi.override.so:CHIBufferManager::FreeBuffers(int)
uprobe:/vendor/lib64/hw/com.qti.chi.override.so:CHIBufferManager::SetPerfMode(ChiBufferInfo*)
`
