### ISSUE TITLE
undefined symbol: bpf_detach_kfunc @ Fedora32

### ISSUE THREAD

**Issue by hermithuang** [iovisor/bpftrace#1409]
bpftrace can't execute @ Fedora32

$ bpftrace 
bpftrace: symbol lookup error: bpftrace: undefined symbol: bpf_detach_kfunc
$ uname -a
Linux home 5.6.19-300.fc32.x86_64 #1 SMP Wed Jun 17 16:10:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ rpm -qi bpftrace
Name        : bpftrace
Version     : 0.10.0
Release     : 2.fc32
Architecture: x86_64
Install Date: 2020/05/30 Sat 11:28:56
Group       : Unspecified
Size        : 4074406
License     : ASL 2.0
Signature   : RSA/SHA256, 2020/05/20 Wed 06:23:36, Key ID 6c13026d12c944d0
Source RPM  : bpftrace-0.10.0-2.fc32.src.rpm
Build Date  : 2020/05/20 Wed 06:14:20
Build Host  : buildvm-06.phx2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/iovisor/bpftrace
Bug URL     : https://bugz.fedoraproject.org/bpftrace
Summary     : High-level tracing language for Linux eBPF
Description :
BPFtrace is a high-level tracing language for Linux enhanced Berkeley Packet
Filter (eBPF) available in recent Linux kernels (4.x). BPFtrace uses LLVM as a
backend to compile scripts to BPF-bytecode and makes use of BCC for
interacting with the Linux BPF system, as well as existing Linux tracing
capabilities: kernel dynamic tracing (kprobes), user-level dynamic tracing
(uprobes), and tracepoints. The BPFtrace language is inspired by awk and C,
and predecessor tracers such as DTrace and SystemTap

**Comment by caringi** [comment]
This problem has been caused by an update in the bcc package (bcc-0.15.0-1.fc32.x86_64).

The latest update (bcc-0.15.0-2.fc32.x86_64), which is still in "testing", fixes it:

https://bodhi.fedoraproject.org/updates/FEDORA-2020-2406f3a6c5

You can force the installation of this update with the following command:

`
sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-2406f3a6c5`

**Comment by hermithuang** [comment]
thank you @caringi . it works !
