### ISSUE TITLE
Does printf not support %f for float in bpftrace?

### ISSUE THREAD

**Issue by b-ripper** [iovisor/bpftrace#1412]
### bpftrace --info

System
  OS: Linux 4.19.81-perf-gf0e9895 #1 SMP PREEMPT Fri Jul 3 14:03:59 CST 2020
  Arch: aarch64

Build
  version: v0.10.0-194-g07989
  LLVM: 7
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: no
  bcc_usdt_addsem: no
  libbpf: yes
  libbpf btf dump: no
  libbpf btf dump type decl: no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes

Kernel features
  Instruction limit: -1
  Loop support: no
  btf: no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: no
  tracepoint: yes
  perf_event: yes
  kfunc: no

### What reproduces the bug?

`
#include <linux/types.h>
struct XXINFO
{
	float fGainMax;
};

uretprobe:/vendor/lib64/libxx.so:"Session::GetXXInfo(XXINFO*)"
/$1 == 0 || pid == $1/
{
	$Info = (struct XXINFO*)@Info[tid];
        printf(" return Info:MaxGain: %.2f\n", $Info->fMaxGain);
}
`

test will has error:

`ERROR: printf: Unknown format string token: %f
       printf(" return Info:MaxGain: %.2f\n", $Info->fMaxGain);`

**Comment by danobi** [comment]
Seems like it was an explicit choice. Full list here: https://github.com/iovisor/bpftrace/blob/master/src/printf_format_types.h

Possibly b/c kernel doesn't really use floating point b/c FPU is expensive (I think)

**Comment by mmisono** [comment]
%f might be useful for user programs. another example:  https://github.com/iovisor/bpftrace/issues/1343#issuecomment-631977279

By the way, since ClangParser does not support floating values for now, `$info->fMaxGain` is Type::none and not usable even if bpftrace supports %f.

**Comment by barathrm** [comment]
Could we not reopen this as a feature request? Imo printing floating point values for user space probes is more than legitimate.

**Comment by fbs** [comment]
If bpf support floats we can add it in but until they do its not something we can add. Unless we derive from using bpf as a tool for user space tracing and use something else instead, but that seems unlikely
