### ISSUE TITLE
Latest bpftrace doesn't appear to have BTF support

### ISSUE THREAD

**Issue by echiu64** [iovisor/bpftrace#1422]
Using the latest bpftrace via `docker run -v $(pwd):/output quay.io/iovisor/bpftrace:master-vanilla_llvm_clang_glibc2.27 /bin/bash -c "cp /usr/bin/bpftrace /output"` 

Does not appear to have BTF support:
```
# ./bpftrace --info
System
  OS: Linux 5.4.49+ #1 SMP Wed Jul 8 01:55:59 PDT 2020
  Arch: x86_64

Build
  version: v0.10.0
  LLVM: 8
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  libbpf: no
  libbpf btf dump: no
  libbpf btf dump type decl: no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: no
```

Kernel has BTF: 
```
# ls -l /sys/kernel/btf/
total 0
-r--r--r-- 1 root root 1550982 Jul 14 19:55 vmlinux
```

**Comment by dalehamel** [comment]
had a quick chat with @echiu64 on slack, I think the builds are just missing (or not detecting) the BFD deps 

I had support for embedding this in my android branch:

https://github.com/iovisor/bpftrace/pull/1095/files#diff-af3b638bc2a3e6c650974192a53c7291R176-R179

just need to pull that over i think, but need to dig in further.

**Comment by mmisono** [comment]
I believe the build misses libbpf as well.

**Comment by danobi** [comment]
Yeah, the

> libbpf: no

is a dependency. I'll put up a PR to make that more obvious

**Comment by echiu64** [comment]
I hacked together a working build in https://github.com/echiu64/bpftrace/tree/btfhack, its ugly and definitely not something to be merged

**Comment by echiu64** [comment]
Just realized the commits in my btfhack branch were wrong, fixed it now, should build "cleanly"
