### ISSUE TITLE
-I for includes on command line

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#143]
This should be doable as a one-liner:

```
#include <linux/path.h>
#include <linux/dcache.h>

kprobe:vfs_open
{
	printf("open path: %s\n", str(((path *)arg0)->dentry->d_name.name));
}
```

But we need a way to specify those includes at the command line. Eg, these should work

```
bpftrace -I linux/path.h,linux/dcache.h -e 'kprobe:vfs_open { printf("open path: %s\n", str(((path *)arg0)->dentry->d_name.name)); }'
bpftrace -I linux/path.h -I linux/dcache.h -e 'kprobe:vfs_open { printf("open path: %s\n", str(((path *)arg0)->dentry->d_name.name)); }'
```

**Comment by mmarchini** [comment]
I'll work on this, but I think we should follow `gcc` and `clang` conventions and use `-I` to add extra include paths and `-include` to include files from the command line.

**Comment by brendangregg** [comment]
I'm ok with -I for paths, but -include doesn't fit with the other options, which are -[single-char] or --[word]. Can it be -i?

**Comment by mmarchini** [comment]
It can, if we don't mind diverging from clang and gcc. I don't think diverging is a big deal, but users who are already familiar with clang and gcc flags might get confused.

**Comment by mmarchini** [comment]
(in clang and gcc, `-i` is also used to indicate path instead of file)

**Comment by brendangregg** [comment]
I'm familiar with -I for paths, but -i for the same thing doesn't ring a bell, so I would not be confused if we used -i for the include file. Maybe other people feel differently!

Although, before we spend -i for anything, we'd want to consider if there's any reason to have a -i input option for bpftrace, since I usually use -i for inputs.

If we make it --include instead of -i, then we can add -i later or not.

**Comment by mmarchini** [comment]
Ok, i think I've mistaken `-I`/`-i` with `-L`/`-l`:

![image](https://user-images.githubusercontent.com/4048656/56610859-59bc8300-65c5-11e9-85e1-46529302c04f.png)

I'll open a PR and we can iterate on the flag there (changing the character used in the flag is).
