### ISSUE TITLE
encounter ERROR：「sh: 1: objdump: not found」

### ISSUE THREAD

**Issue by miaogen123** [iovisor/bpftrace#1430]
### bpftrace --info
bpftrace is installed with snap.
(command: snap info  bpftrace )
```

name:      bpftrace
summary:   high-level tracing language for Linux eBPF
publisher: Colin King (cking-kernel-tools)
store-url: https://snapcraft.io/bpftrace
license:   unset
description: |
  BPFtrace is a high-level tracing language for Linux enhanced Berkeley Packet Filter
  available in recent Linux kernels. BPFtrace uses LLVM as a backend to compile
  scripts to BPF-bytecode and makes use of BCC for interacting with the Linux BPF
  system, as well as existing Linux tracing capabilities like kernel dynamic tracing,
  user-level dynamic tracing and tracepoints.
commands:
  - bpftrace
snap-id:      1UFcXKXSBtFK4i91LmQTaAbx7x4nszOn
refresh-date: today at 16:34 CST
channels:
  latest/stable:    v0.10.0-193-20200705-1691-g24205 2020-07-07 (63) 52MB -
  latest/candidate: 0.9.2                            2019-08-02 (27) 65MB -
  latest/beta:      0-20181118-0024                  2019-02-23 (13) 81MB -
  latest/edge:      v0.11.0-12-20200719-1712-g646fff 2020-07-19 (66) 52MB -
installed:          v0.10.0-193-20200705-1691-g24205            (63) 52MB -
```
### system info
debian 9
( command : uname -a）
```
Linux n18-081-095 4.14.81.bm.23-amd64 #1 SMP Debian 4.14.81.bm.23 Wed Jul 1 13:23:33 UTC 2020 x86_64 GNU/Linux
```
### What reproduces the bug?
here comes the error when run
```
sudo /snap/bin/bpftrace -e 'uretprobe:/bin/bash:readline { printf("readline: \"%s\"\n", str(retval)); }'
sh: 1: objdump: not found
Failed to compile: stoull
```

I ensured objdump command is availiable with sudo or not
I am blocking by this problem, need  your help

**Comment by fbs** [comment]
Can you attach the `bpftrace --info` output. objdump should only be used when HAVE_BCC_ELF_FOREACH_SYM is missing. Sounds like this is compiled with an old bcc.


Would it be possible for you to try https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#copying-bpftrace-binary-from-docker ?

**Comment by fbs** [comment]
Ah that seems like an issue with the snap build. `  foreach_sym: no` indicates that the used bcc is old. IIRC that happens when build on ubunt18.04 with the shipped bcc.

Snap is still something we need to fix and integrate with the ci, but for now I'd recommend the docker image.

**Comment by miaogen123** [comment]
> Ah that seems like an issue with the snap build. ` foreach_sym: no` indicates that the used bcc is old. IIRC that happens when build on ubunt18.04 with the shipped bcc.
> 
> Snap is still something we need to fix and integrate with the ci, but for now I'd recommend the docker image.

Great thanks, it works by copying file from docker image.
Another question : Is that possible to  trace args of any user-space function by bpftrace?
Here I find a post [Attach bpftrace probe to C++ function](https://stackoverflow.com/questions/58207204/attach-bpftrace-probe-to-c-function#), which doesn't work for me when i try on my host with command 
```
sudo ./bpftrace  -e 'uprobe:/home/miaogen.123/tmp/main:_ZN6BigApp10methodNameEi { printf("1"); }' 
```
just nothing happened when i run ```main```  in another terminal.
(BTW, is there any group such as reddit to discuss）
Append ouput of additional -d option
```
AST
-------------------
Program
 uprobe:/home/miaogen.123/tmp/main:_ZN6BigApp10methodNameEv
  call: printf
   string: 1


AST after semantic analysis
-------------------
Program
 uprobe:/home/miaogen.123/tmp/main:_ZN6BigApp10methodNameEv
  call: printf :: type[none]
   string: 1 :: type[string[64]]

; ModuleID = 'bpftrace'
source_filename = "bpftrace"
target datalayout = "e-m:e-p:64:64-i64:64-n32:64-S128"
target triple = "bpf-pc-linux"

%printf_t = type { i64 }

; Function Attrs: nounwind
declare i64 @llvm.bpf.pseudo(i64, i64) #0

define i64 @"uprobe:/home/miaogen.123/tmp/main:_ZN6BigApp10methodNameEv"(i8*) local_unnamed_addr section "s_uprobe:/home/miaogen.123/tmp/main:_ZN6BigApp10methodNameEv_1" {
entry:
  %printf_args = alloca %printf_t, align 8
  %1 = bitcast %printf_t* %printf_args to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* nonnull %1)
  %2 = getelementptr inbounds %printf_t, %printf_t* %printf_args, i64 0, i32 0
  store i64 0, i64* %2, align 8
  %pseudo = tail call i64 @llvm.bpf.pseudo(i64 1, i64 1)
  %get_cpu_id = tail call i64 inttoptr (i64 8 to i64 ()*)()
  %perf_event_output = call i64 inttoptr (i64 25 to i64 (i8*, i64, i64, %printf_t*, i64)*)(i8* %0, i64 %pseudo, i64 %get_cpu_id, %printf_t* nonnull %printf_args, i64 8)
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* nonnull %1)
  ret i64 0
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64, i8* nocapture) #1

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64, i8* nocapture) #1

attributes #0 = { nounwind }
attributes #1 = { argmemonly nounwind }
```

**Comment by danobi** [comment]
Hi @miaogen123,

Do you mind filing a separate issue? We can help debug there.

Also, there's https://bpftrace.discourse.group/ for community discussion. It's pretty new so not much activity yet, but we're hoping to nudge people towards that from now on.

**Comment by miaogen123** [comment]
Of course, i will move to the community.

**Comment by goodwzboy** [comment]
> > Ah that seems like an issue with the snap build. ` foreach_sym: no` indicates that the used bcc is old. IIRC that happens when build on ubunt18.04 with the shipped bcc.
> > Snap is still something we need to fix and integrate with the ci, but for now I'd recommend the docker image.
> 
> Great thanks, it works by copying file from docker image.
> Another question : Is that possible to trace args of any user-space function by bpftrace?
> Here I find a post [Attach bpftrace probe to C++ function](https://stackoverflow.com/questions/58207204/attach-bpftrace-probe-to-c-function#), which doesn't work for me when i try on my host with command
> 
> ```
> sudo ./bpftrace  -e 'uprobe:/home/miaogen.123/tmp/main:_ZN6BigApp10methodNameEi { printf("1"); }' 
> ```
> 
> just nothing happened when i run `main` in another terminal.
> (BTW, is there any group such as reddit to discuss）
> Append ouput of additional -d option
> 
> ```
> AST
> -------------------
> Program
>  uprobe:/home/miaogen.123/tmp/main:_ZN6BigApp10methodNameEv
>   call: printf
>    string: 1
> 
> 
> AST after semantic analysis
> -------------------
> Program
>  uprobe:/home/miaogen.123/tmp/main:_ZN6BigApp10methodNameEv
>   call: printf :: type[none]
>    string: 1 :: type[string[64]]
> 
> ; ModuleID = 'bpftrace'
> source_filename = "bpftrace"
> target datalayout = "e-m:e-p:64:64-i64:64-n32:64-S128"
> target triple = "bpf-pc-linux"
> 
> %printf_t = type { i64 }
> 
> ; Function Attrs: nounwind
> declare i64 @llvm.bpf.pseudo(i64, i64) #0
> 
> define i64 @"uprobe:/home/miaogen.123/tmp/main:_ZN6BigApp10methodNameEv"(i8*) local_unnamed_addr section "s_uprobe:/home/miaogen.123/tmp/main:_ZN6BigApp10methodNameEv_1" {
> entry:
>   %printf_args = alloca %printf_t, align 8
>   %1 = bitcast %printf_t* %printf_args to i8*
>   call void @llvm.lifetime.start.p0i8(i64 -1, i8* nonnull %1)
>   %2 = getelementptr inbounds %printf_t, %printf_t* %printf_args, i64 0, i32 0
>   store i64 0, i64* %2, align 8
>   %pseudo = tail call i64 @llvm.bpf.pseudo(i64 1, i64 1)
>   %get_cpu_id = tail call i64 inttoptr (i64 8 to i64 ()*)()
>   %perf_event_output = call i64 inttoptr (i64 25 to i64 (i8*, i64, i64, %printf_t*, i64)*)(i8* %0, i64 %pseudo, i64 %get_cpu_id, %printf_t* nonnull %printf_args, i64 8)
>   call void @llvm.lifetime.end.p0i8(i64 -1, i8* nonnull %1)
>   ret i64 0
> }
> 
> ; Function Attrs: argmemonly nounwind
> declare void @llvm.lifetime.start.p0i8(i64, i8* nocapture) #1
> 
> ; Function Attrs: argmemonly nounwind
> declare void @llvm.lifetime.end.p0i8(i64, i8* nocapture) #1
> 
> attributes #0 = { nounwind }
> attributes #1 = { argmemonly nounwind }
> ```

Would you tell me that which  file did you copy from docker?

**Comment by miaogen123** [comment]
just the file：./bpftrace

**Comment by wangjinnana** [comment]
sudo ./bpftrace  -e 'uprobe:/home/miaogen.123/tmp/main:_ZN6BigApp10methodNameEi { printf("1**\n**"); }' 

have you tried add new line at end, may be is it the cause of output buffer, or ctr + c at end will out put 111
