### ISSUE TITLE
usdt: what the default namespace should be?

### ISSUE THREAD

**Issue by viktormalik** [iovisor/bpftrace#1469]
This is a question that follows #1466.

According to the documentation, it is possible to omit namespace when specifying usdt probe:
>Syntax:
>
>```
>usdt:binary_path:probe_name
>usdt:binary_path:[probe_namespace]:probe_name
>usdt:library_path:probe_name
>usdt:library_path:[probe_namespace]:probe_name
>```
>
>Where the `probe_namespace` is optional, and will default to the basename of the binary or library path.

This suggests that in such case, namespace is set to the basename of the binary. 

On the other hand, the code in [bpftrace.cpp#L366-L367](https://github.com/iovisor/bpftrace/blob/722c5c73ebdc3b87ea525dcf3f8573179bf1d7c8/src/bpftrace.cpp#L366-L367) indicates that the empty namespace should be expanded as if `*` was provided. This behaviour is also supported by a test in [tests/bpftrace.cpp#L541](https://github.com/iovisor/bpftrace/blob/722c5c73ebdc3b87ea525dcf3f8573179bf1d7c8/tests/bpftrace.cpp#L541).

My question is, what do you think the correct behaviour should be? I'd suggest the expansion, but that currently doesn't work since it is not handled correctly in all places in the code, causing the mentioned bug.

Any thoughts?

**Comment by danobi** [comment]
The wildcard makes sense to me. Should help with writing terser bpftrace scripts. And it'd be a compatible change with the documented behavior (to say nothing of the actual behavior).

**Comment by viktormalik** [comment]
There is also a third option - find the namespace automatically but assume that just a single probe with the given name exists. This is also how bcc does it. After some thinking, I start to prefer this solution - it would shorten simple scripts where the namespace is obvious and it would also notify the user when there are multiple probes with the same name. If the user wants to attach to all of them, he must use a wildcard.

**Comment by danobi** [comment]
Sure, that makes sense too.
