### ISSUE TITLE
RFE: bpftrace exporter

### ISSUE THREAD

**Issue by myllynen** [iovisor/bpftrace#147]
Consider adding bpftrace exporter in the spirit of stap-exporter (see https://www.mankier.com/8/stap-exporter) that would allow providing bpftrace results to Prometheus and other such tools capable consuming the exported data.

From the `stap-exporter` man page:

```
stap-exporter runs a set of systemtap scripts and relays their procfs outputs to remote
HTTP clients on demand.  This makes systemtap scripts directly usable as individual
prometheus exporters.
```

Thanks.

**Comment by brendangregg** [comment]
Something simple, sure. I think for daemons/agents many may end up done in bcc, if they need many customizations beyond bpftrace. bpftrace would be a good version one of deamons, and then they move to bcc when needed.

**Comment by yadutaf** [comment]
A partial solution (2021) is to combine:

1. The json output ``bpftrace -f json``
2. Periodic dumping of variables/maps/histograms/... of interest:
```
    interval:s:1
    {
        print(@some_maps);
    }
```
3. Consumption of the json output by a custom exporter

**Comment by richardelling** [comment]
Check out https://github.com/cloudflare/ebpf_exporter  it is quite good.
I'll recommend closing this issue with the above xref.

**Comment by mmarchini** [comment]
I'm closing this issue, if anyone believes there's more to discuss we can reopen it
