### ISSUE TITLE
Document quoted attach points

### ISSUE THREAD

**Issue by yshui** [iovisor/bpftrace#1487]
`++` can't be used as part of library name. I can't set uprobe in `libstdc++` because of this.

**Comment by fbs** [comment]
Quoting it seems to work:

```
$ bpftrace  -e 'uprobe:"/usr/lib/x86_64-linux-gnu/libstdc++.so.6":_ZSt18uncaught_exceptionv { printf("HIT\n"); }'
Attaching 1 probe...
^C
```

Although it is inconsistent with the listing, we should probably fix that:

```
$ bpftrace -l 'u:"/usr/lib/x86_64-linux-gnu/libstdc++.so.6":*'
ERROR: uprobe target '"/usr/lib/x86_64-linux-gnu/libstdc++.so.6"' does not exist or is not executable
```

**Comment by yshui** [comment]
Thanks for the tip about quoting, is this documented somewhere? I didn't find it in the reference guide.

**Comment by fbs** [comment]
Appearently not. I've updated the issues to fix that
