### ISSUE TITLE
filter make '/' optional

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#15]
Filters (aka predicates) are wrapped in "/"s, like awk. But awk was using them to identify string comparisons, and they weren't needed for int comparisons. I'm wondering if we can make them completely optional, since we already have a type system.

Eg:

```
./src/bpftrace -e 'kretprobe:vfs_read /pid > 1000/ { @[pid] = count(); }'
./src/bpftrace -e 'kretprobe:vfs_read pid > 1000 { @[pid] = count(); }'
```

The first works, the second doesn't. Could the second work? This is a nice-to-have if it's easy, but not that important.

I imagine it'd involve editing lexer.l and parser.yy Also see ast/codegen_llvm.cpp and start with:

```
      case bpftrace::Parser::token::BAND:  expr_ = b_.CreateAnd    (lhs, rhs); break;
```

**Comment by tyroguru** [comment]
@brendangregg - I personally don't like this as the second invocation (with the slash '/' removed) is much harder for me to parse. Is there a language that you're thinking of that does this?

**Comment by brendangregg** [comment]
awk.

```
awk -F: '$3 > 100 { print $1 }' /etc/passwd
```

So we could support:

```
bpftrace -e 't:syscalls:sys_exit_read args->ret > 100 { @[comm] = count(); }'
```

awk only used '/' for regexp comparisons. I still write a lot of awk, and when I'm in bpftrace I keep wondering why do I need to type in the slashes for non-regexps.

I don't feel strongly about losing the '/'s. They could be made optional: we alias t to tracepoint to save typing. I do think we want to think about a few things before 1.0. In another ticket I'm going to investigate count() and sum() vs ++ and +=.
