### ISSUE TITLE
Implement filter for cgroups

### ISSUE THREAD

**Issue by alban** [iovisor/bpftrace#150]
According to the [documentation](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#2--filtering), filters can be on arguments (`/arg2 < 16/`) or on comm (`/comm == "bash"/`) but there is no filtering on cgroup. I would like to have a filter like `/cgroup == cgroupid("/sys/fs/cgroup/mycgroup")`.

I'm new to bpftrace, I am not sure where to start looking. Are the filters implemented here?
https://github.com/iovisor/bpftrace/blob/e5f633f/src/ast/codegen_llvm.cpp#L32

Other implementation details:
- "cgroup" would generate BPF code for `bpf_get_current_cgroup_id()` ([bpf helpers](https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md)) available in Linux 4.18 (https://github.com/torvalds/linux/commit/bf6fa2c893c5237b48569a13fa3c673041430b6c).
- "cgroupid()" would call `name_to_handle_at()` in userspace, see example in https://github.com/torvalds/linux/commit/f269099a7e7a0c6732c4a817d0e99e92216414d9

**Comment by brendangregg** [comment]
see #152 (I added it just for you!) -- I'd try following the "2. Codegen: curtask" section for adding the cgroup builtin. You can do that as a first PR to get the hang of bpftrace, then follow up with cgroupid().

As for cgroupid(), look at the implementation of uaddr or kaddr (and I wrote some initial docs on kaddr here https://github.com/iovisor/bpftrace/issues/3). So codegen would call a bpftrace function that returned a uint64 for the cgroup.

As for the comparison: if they end up both uint64s, I think the existing code will just work. If you made them a special type (like Type::cgroup) then it'd need more work, but I'm not sure why that's necessary here.

We need this functionality, so it'd be great if you could add it. :)

**Comment by brendangregg** [comment]
Don't forget to add docs: README.md, and docs/reference_guide.md.

**Comment by alban** [comment]
@brendangregg thanks for the detailed documentation! I started with the first part: https://github.com/iovisor/bpftrace/pull/158

**Comment by chrahunt** [comment]
This was completed in #170.
