### ISSUE TITLE
ustack(perf) segv on bpftrace

### ISSUE THREAD

**Issue by grooverdan** [iovisor/bpftrace#1523]
removing 'perf' and using default `ustack` type in script works without fault.

### bpftrace --info

 /home/dan/repos/bpftrace/build-release/src/bpftrace --info
System
  OS: Linux 5.8.4-200.fc32.x86_64 #1 SMP Wed Aug 26 22:28:08 UTC 2020
  Arch: x86_64

Build
  version: v0.11.0-136-gd6c4-dirty
  LLVM: 10
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  libbpf: no
  libbpf btf dump: no
  libbpf btf dump type decl: no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): no
  map batch (depends on Build:libbpf): no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes

("dirty" in git verison is I've replaced docker with podman in scripts)

### What reproduces the bug?

<pre>
build-mariadb-server-10.3]# /home/dan/repos/bpftrace/build-release/./src/bpftrace -e 'uprobe:/lib64/libpthread.so:pthread_mutex_lock /comm == "mysqld" / { @start[arg0] = nsecs; @s[arg0] = ustack(perf) }  uprobe:/lib64/libpthread.so:pthread_mutex_unlock  /comm == "mysqld" / { @ns[ustack(perf), @s[arg0], arg0] = hist(nsecs - @start[arg0]); } END { clear(@start); clear(@s); print(@ns, 5); clear(@ns); }' -p $(pidof mysqld)
</pre>

After ^C the bpftrace segfaults

### stack trace ( short )

<pre>
bt#0  0x000000000046475a in bpftrace::BPFtrace::get_stack[abi:cxx11](unsigned long, bool, bpftrace::StackType, int) (this=0x7ffda894cc50, stackidpid=2700881594158432, ustack=true, stack_type=..., indent=4)
    at /home/dan/repos/bpftrace/src/bpftrace.cpp:1680
1680	  int err = bpf_lookup_elem(maps[stack_type].value()->mapfd_,

(gdb) bt
#0  0x000000000046475a in bpftrace::BPFtrace::get_stack[abi:cxx11](unsigned long, bool, bpftrace::StackType, int) (this=0x7ffda894cc50, stackidpid=2700881594158432, ustack=true, stack_type=..., indent=4)
    at /home/dan/repos/bpftrace/src/bpftrace.cpp:1680
#1  0x00000000004cb949 in bpftrace::MapKey::argument_value[abi:cxx11](bpftrace::BPFtrace&, bpftrace::SizedType const&, void const*) (bpftrace=..., arg=..., data=0xaadd58) at /home/dan/repos/bpftrace/src/mapkey.cpp:87
#2  0x00000000004cb51b in bpftrace::MapKey::argument_value_list[abi:cxx11](bpftrace::BPFtrace&, std::vector<unsigned char, std::allocator<unsigned char> > const&) const (this=0xba6f68, bpftrace=..., 
    data=std::vector of length 24, capacity 24 = {...}) at /home/dan/repos/bpftrace/src/mapkey.cpp:45
#3  0x00000000004cb650 in bpftrace::MapKey::argument_value_list_str[abi:cxx11](bpftrace::BPFtrace&, std::vector<unsigned char, std::allocator<unsigned char> > const&) const (this=0xba6f68, bpftrace=..., 
    data=std::vector of length 24, capacity 24 = {...}) at /home/dan/repos/bpftrace/src/mapkey.cpp:56
#4  0x00000000004ced6d in bpftrace::TextOutput::map_hist (this=0xa93c10, bpftrace=..., map=..., top=5, div=1, values_by_key=std::map with 265 elements = {...}, total_counts_by_key=std::vector of length 265, capacity 512 = {...})
    at /home/dan/repos/bpftrace/src/output.cpp:264
#5  0x0000000000463591 in bpftrace::BPFtrace::print_map_hist (this=0x7ffda894cc50, map=..., top=5, div=1) at /home/dan/repos/bpftrace/src/bpftrace.cpp:1519
#6  0x0000000000462684 in bpftrace::BPFtrace::print_map (this=0x7ffda894cc50, map=..., top=5, div=0) at /home/dan/repos/bpftrace/src/bpftrace.cpp:1364
#7  0x000000000045ca7f in bpftrace::perf_event_printer (cb_cookie=0x7ffda894cc50, data=0x7fd50807d03c, size=20) at /home/dan/repos/bpftrace/src/bpftrace.cpp:570
#8  0x00007fd514d71f56 in parse_sw (size=<optimized out>, data=<optimized out>, reader=0xbeeb30) at /usr/src/debug/bcc-0.15.0-2.fc32.x86_64/src/cc/perf_reader.c:146
#9  perf_reader_event_read (reader=0xbeeb30) at /usr/src/debug/bcc-0.15.0-2.fc32.x86_64/src/cc/perf_reader.c:210
#10 0x00000000004613dc in bpftrace::BPFtrace::poll_perf_events (this=0x7ffda894cc50, epollfd=9, drain=true) at /home/dan/repos/bpftrace/src/bpftrace.cpp:1194
#11 0x0000000000460aff in bpftrace::BPFtrace::run (this=0x7ffda894cc50, bpforc=std::unique_ptr<bpftrace::BpfOrc> = {...}) at /home/dan/repos/bpftrace/src/bpftrace.cpp:1123
#12 0x00000000004b7531 in main (argc=5, argv=0x7ffda894ffc8) at /home/dan/repos/bpftrace/src/main.cpp:802
</pre>

### gdb --args bpftrace ....

<pre>
Thread 1 "bpftrace" received signal SIGTERM, Terminated.
0x00007fffee21ac5e in epoll_wait (epfd=9, events=0xadc010, maxevents=8, timeout=100) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
30	  return SYSCALL_CANCEL (epoll_wait, epfd, events, maxevents, timeout);
(gdb) c
Continuing.

Thread 1 "bpftrace" received signal SIGSEGV, Segmentation fault.
0x000000000046475a in bpftrace::BPFtrace::get_stack[abi:cxx11](unsigned long, bool, bpftrace::StackType, int) (this=0x7fffffffab30, stackidpid=2700396262851369, ustack=true, stack_type=..., indent=4)
    at /home/dan/repos/bpftrace/src/bpftrace.cpp:1680
1680	  int err = bpf_lookup_elem(maps[stack_type].value()->mapfd_,
(gdb) p stack_type
$1 = {limit = 127, mode = bpftrace::StackMode::bpftrace}
(gdb) p maps[stack_type]

Thread 1 "bpftrace" received signal SIGSEGV, Segmentation fault.
std::_Hashtable<bpftrace::StackType, std::pair<bpftrace::StackType const, std::unique_ptr<bpftrace::IMap, std::default_delete<bpftrace::IMap> > >, std::allocator<std::pair<bpftrace::StackType const, std::unique_ptr<bpftrace::IMap, std::default_delete<bpftrace::IMap> > > >, std::__detail::_Select1st, std::equal_to<bpftrace::StackType>, std::hash<bpftrace::StackType>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_insert_bucket_begin (this=0x7fffffff6fd8, __bkt=0, __node=0xf31400) at /usr/include/c++/10/bits/hashtable.h:1616
1616		    _M_buckets[_M_bucket_index(__node->_M_next())] = __node;
</pre>

**Comment by fbs** [comment]
Thanks for reporting! Looks like we've had this issue for a while.

#1524 should fix this, can you try it?
