### ISSUE TITLE
offset kprobe always gets "ERROR: Could not resolve symbol XXX "

### ISSUE THREAD

**Issue by lostjeffle** [iovisor/bpftrace#1531]
If we set BPFTRACE_VMLINUX env ahead, then we will always get an error message when attaching a kprobe with offset.

```
$./src/bpftrace -e 'kprobe:pagecache_get_page+0x11{printf("hit\n");}'

ERROR: Could not resolve symbol pagecache_get_page. Use BPFTRACE_VMLINUX env variable to specify vmlinux path. Compile bpftrace with ALLOW_UNSAFE_PROBE option to force skip the check.
```

#1530 could fix this issue.

### bpftrace --info
System
  OS: Linux 4.19.57-15.1.al7.x86_64 #1 SMP Thu Aug 29 13:46:41 CST 2019
  Arch: x86_64

Build
  version: v0.11.0-132-g9df5-dirty
  LLVM: 7
  foreach_sym: yes
  unsafe uprobe: no
  bfd: no
  bpf_attach_kfunc: no
  bcc_usdt_addsem: no
  libbpf: no
  libbpf btf dump: no
  libbpf btf dump type decl: no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: yes
  send_signal: no
  override_return: no
  get_boot_ns: no

Kernel features
  Instruction limit: 131072
  Loop support: no
  btf (depends on Build:libbpf): no
  map batch (depends on Build:libbpf): no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no

### What reproduces the bug?
- set BPFTRACE_VMLINUX env
- and then run kprobe with offset

**Comment by mmisono** [comment]
@lostjeffle Can we close this now?

**Comment by lostjeffle** [comment]
> @lostjeffle Can we close this now?

Certainly.
