### ISSUE TITLE
Cannot read struct into variable

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#1535]
The semantic analyser allows reading  structs onto the stack but it leads to invalid code:

```
$ bpftrace -e 'struct A{int a; int b;}; u:./a.out:foo { $foo = *(struct A*)arg0; printf("%d %d\n", $foo.a, 1); }'  -c ./a.out
ERROR: Error loading program: uprobe:./a.out:foo (try -v)

$ bpftrace -e 'struct A{int a; int b;}; u:./a.out:foo { $foo = *(struct A*)arg0; printf("%d %d\n", $foo.a, $foo.b); }'  -c ./a.out
LLVM ERROR: out of memory
```

The pointer variant works:

```
$ bpftrace  -e 'struct A{int a; int b;}; u:./a.out:foo { $foo = (struct A*)arg0; printf("%d %d\n", $foo->a, $foo->b); }'  -c ./a.out
0 0
1 2
```

I think that being able to read structs into vars/maps makes sense. Being able to `print($struct_a)` would be quite useful. We'd be limited by stack size of course, but it is still useful to have.

Fixing this might need a bit of work. The parser currently does this:

```
     | MUL  expr %prec DEREF                    { $$ = new ast::Unop(token::MUL,  $2, @1); }
     | expr DOT INT                             { $$ = new ast::FieldAccess($1, $3, @3); }
     | expr PTR ident                           { $$ = new ast::FieldAccess(new ast::Unop(token::MUL, $1, @2), $3, @$); }
```

In the case of `$foo = *(struct X*)arg0` we'd want to read the whole thing into the stack. But `$foo = $bar->x` gets translated into `$foo = (*$bar).x;`, reading the whole thing would be a waste in this case.

This is also the source of the invalid addrspace casts which we need to fix for #1091.

**Comment by viktormalik** [comment]
This issue is similar to what I solved in #1656, so I'll look into this.
