### ISSUE TITLE
Handle printf literal arguments at compile time

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#1539]
For a simple program like:

```
sudo bpftrace -e 'BEGIN { printf("%s %s\n", "abc", "def"); }'
```

We currently emit 140 instructions. 90% of that is just useless string handling (strings are 64 bytes) and moving data to the stack for a perf_event.

The whole thing can be reduced to `BEGIN{ printf("abc def\n") }`, which emits a single 64bit perf event in a total of 14 instructions.

Applies to integer literal and other format strings calls (system) as well

**Comment by fbs** [comment]
Once this lands we can address https://github.com/iovisor/bpftrace/pull/1538/files#r495452630

**Comment by fbs** [comment]
working on this right now, the amount of runtime code some scripts generates get in my way

**Comment by ajor** [comment]
Reopening as this doesn't appear to have been implemented
