### ISSUE TITLE
-v does not print BPF bytecodes on the recent kernel

### ISSUE THREAD

**Issue by mmisono** [iovisor/bpftrace#1551]
The commit https://github.com/torvalds/linux/commit/6f8a57ccf8511724e6f48d732cb2940889789ab2 (from 5.8 rc1) changed the way to log the verifier and now it removes parts of the log that are successfully verified. Therefore we cannot check the BPF bytecodes if the program is loaded successfully. For example:

```
% sudo ./src/bpftrace -e 'BEGIN { @=1 }' -v
BTF: using data from /sys/kernel/btf/vmlinux
Attaching 1 probe...

Program ID: 720

Bytecode:
processed 13 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
```

We can use [log_level = 2](https://github.com/iovisor/bpftrace/blob/d7934ede74edc8fee0755eecaa1959ab2fa089ed/src/attached_probe.cpp#L624) to get the full log, but it's verbose for checking bytecodes.

```
% sudo ./src/bpftrace -e 'BEGIN { @=1 }' -v
BTF: using data from /sys/kernel/btf/vmlinux
Attaching 1 probe...

Program ID: 721

Bytecode:
func#0 @0
0: R1=ctx(id=0,off=0,imm=0) R10=fp0
0: (b7) r1 = 0
1: R1_w=inv0 R10=fp0
1: (7b) *(u64 *)(r10 -16) = r1
last_idx 1 first_idx 0
regs=2 stack=0 before 0: (b7) r1 = 0
2: R1_w=invP0 R10=fp0 fp-16_w=00000000
2: (b7) r1 = 1
3: R1_w=inv1 R10=fp0 fp-16_w=00000000
3: (7b) *(u64 *)(r10 -8) = r1
4: R1_w=inv1 R10=fp0 fp-8_w=inv1 fp-16_w=00000000
4: (18) r1 = 0xffff897957a54800
6: R1_w=map_ptr(id=0,off=0,ks=8,vs=8,imm=0) R10=fp0 fp-8_w=inv1 fp-16_w=00000000
6: (bf) r2 = r10
7: R1_w=map_ptr(id=0,off=0,ks=8,vs=8,imm=0) R2_w=fp0 R10=fp0 fp-8_w=inv1 fp-16_w=00000000
7: (07) r2 += -16
8: R1_w=map_ptr(id=0,off=0,ks=8,vs=8,imm=0) R2_w=fp-16 R10=fp0 fp-8_w=inv1 fp-16_w=00000000
8: (bf) r3 = r10
9: R1_w=map_ptr(id=0,off=0,ks=8,vs=8,imm=0) R2_w=fp-16 R3_w=fp0 R10=fp0 fp-8_w=inv1 fp-16_w=00000000
9: (07) r3 += -8
10: R1_w=map_ptr(id=0,off=0,ks=8,vs=8,imm=0) R2_w=fp-16 R3_w=fp-8 R10=fp0 fp-8_w=inv1 fp-16_w=00000000
10: (b7) r4 = 0
11: R1_w=map_ptr(id=0,off=0,ks=8,vs=8,imm=0) R2_w=fp-16 R3_w=fp-8 R4_w=inv0 R10=fp0 fp-8_w=inv1 fp-16_w=00000000
11: (85) call bpf_map_update_elem#2
12: R0_w=inv(id=0) R10=fp0 fp-8_w=mmmmmmmm fp-16_w=mmmmmmmm
12: (b7) r0 = 0
13: R0_w=inv0 R10=fp0 fp-8_w=mmmmmmmm fp-16_w=mmmmmmmm
13: (95) exit
processed 13 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
```

Printing bytecodes is useful for debugging in some cases. I wonder if bpftrace should print bytecode itself.

**Comment by fbs** [comment]
Seems like a good improvement. I've seen log output of 30MB (iirc) with a big loop which is not at all useful when trying to find an issue with it. 

If you're really interested in the bytecode generated we have the `--emit-elf` flag, and `bpftool prog dump`. I don't think we have to add more options.

**Comment by mmisono** [comment]
That makes sense. `--emit-elf` and `bpftool prog dump` seems enough. I created #1553 to change the message.
