### ISSUE TITLE
Add support for assigning one tuple element value

### ISSUE THREAD

**Issue by rdmello** [iovisor/bpftrace#1560]
### Is your feature request related to a problem? Please describe.
I'm using a `tuple` to store some data after looking at the syntax [here](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#14----tuples).

This allows me to access the data in the tuple using a convenient `@tuple.1` syntax. However, I get an error message when I try to assign to it using `@tuple.1 = 1;`.

I'm running bpftrace v0.11.1 on Gentoo. Here's a one-liner that reproduces this:

```bash
root# bpftrace -e 'interval:s:1 { @x = (3, 3); @x.1 = 1; printf("%d\n", @x.1); }'
stdin:1:34-35: ERROR: syntax error, unexpected =, expecting }
interval:s:1 { @x = (3, 3); @x.1 = 1; printf("%d\n", @x.1); }
                                 ~
```

### Describe the solution you'd like

It would be convenient if assigning to a `tuple` element just worked:

```bash
root# bpftrace -e 'interval:s:1 { @x = (3, 3); @x.1 = 1; printf("%d\n", @x.1); }'
Attaching 1 probe...
1
1
^C
```

### Describe alternative solutions or features you've considered

* The current solution of updating a tuple by assigning all the tuple values to it does work fine:

```bash
root# bpftrace -e 'interval:s:1 { @x = (3, 3); @x = (@x.0, 1); printf("%d\n", @x.1); }'
Attaching 1 probe...
1
1
^C
```

but allowing direct assignment would be a little more convenient.

* If this is not possible due to syntax limitations, it would be good to document this in the reference guide.

**Comment by danobi** [comment]
Right, tuples are currently immutable once created. Just like python. Seems like python can get away with doing that so I'd like to see how long we can get away from it as well.

**Comment by fbs** [comment]
Agree on keeping immutable (atleast until we have a valid real world usecase)

But we should improve error message, so reopening this. 

```
stdin:1:34-35: ERROR: syntax error, unexpected =, expecting }
interval:s:1 { @x = (3, 3); @x.1 = 1; printf("%d\n", @x.1); }
```
