### ISSUE TITLE
bpftrace SEGV (double free detected)

### ISSUE THREAD

**Issue by mmisono** [iovisor/bpftrace#1585]
In my environment (Ubuntu 20.04, kernel 5.10-rc1), bpftrace report double-free after program termination.

```
% sudo ./src/bpftrace -V
bpftrace v0.11.0-216-ge6bb-dirty
free(): double free detected in tcache 2
zsh: abort      sudo ./src/bpftrace -V
```

and AddressSanitizer said

```
% sudo ./src/bpftrace -V
bpftrace v0.11.0-216-ge6bb-dirty
AddressSanitizer:DEADLYSIGNAL
=================================================================
==450650==ERROR: AddressSanitizer: SEGV on unknown address 0x000079800007 (pc 0x7fa42e494f2f bp 0x7fa4305c5aa0 sp 0x7ffccf227d10 T0)
==450650==The signal is caused by a READ memory access.
    #0 0x7fa42e494f2f  (/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x2e01f2f)
    #1 0x7fa42b16a15d in __cxa_finalize /build/glibc-ZN95T4/glibc-2.31/stdlib/cxa_finalize.c:83:6
    #2 0x7fa42c00c856  (/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x979856)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x2e01f2f)
==450650==ABORTING
```

This happens also with LLVM10. A curious thing is that I don't have this error on another Ubuntu machine that has the exact same version of llvm and bpftrace.

@bobrik also reported this.

> It builds just fine, but I'm getting the following at runtime:
> 
> ```
> $ sudo /tmp/bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'
> Two passes with the same argument (-tti) attempted to be registered!
> Segmentation fault
> ```
> 
> ```
> $ sudo /tmp/bpftrace -V
> bpftrace v0.11.1-4-g774b
> free(): double free detected in tcache 2
> Aborted
> ```
> 
> This is with LLVM 11.0.0 on Linux 5.10-rc1.
> 
> _Originally posted by @bobrik in https://github.com/iovisor/bpftrace/pull/1578#issuecomment-718084228_

**Comment by mmisono** [comment]
One of the solution is

> If anyone stumbles on that same error I did here: https://github.com/iovisor/bpftrace/pull/1578#issuecomment-718084228
> 
> I solved it by making libbcc link to libllvm dynamically via `-DENABLE_LLVM_SHARED=ON`, which seems to avoid initializing two identical LLVM versions (one static in libbcc and one dynamic from bpftrace).
> 
> _Originally posted by @bobrik in https://github.com/iovisor/bpftrace/issues/1578#issuecomment-729380270_

I still hit the issue though..

**Comment by viktormalik** [comment]
It looks like there's not much to be done here, closing.
