### ISSUE TITLE
BTF and user types

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#1588]
Split from a thread in an old PR

----

So, after some experiments, I discovered a problem with this approach  - when asking BTF to dump a type definition, it also dumps definitions of all other types needed for successful compilation. If one of those types is overridden by the user, a re-definition error occurs (and it's quite difficult to discover which types were dumped).

This leads me to another thought - do we really want to allow user to do this? I'd say that allowing overriding a part of kernel types while taking the rest from BTF will always eventually blow up somewhere. I'd suggest enabling only the following scenarios:
- there are no user-defined types -> use BTF
- there are user-defined types but they do not override kernel types -> use BTF
- there are user-defined types conflicting with kernel types -> don't use BTF

This should allow user to define his own types that use existing kernel types without any problems, but if he wants to use types with conflicting names (e.g. for userspace tracing), he must define/include all the necessary types manually (or use them from `linux/types.h`, which is included in such case). This approach should be also backwards compatible for scripts that include kernel headers (such as the above `tcplife.bt`) as those must have already specified all the necessary types.

Any thoughs before I start implementing this?

_Originally posted by @viktormalik in https://github.com/iovisor/bpftrace/pull/1506#discussion_r516575033_

**Comment by fbs** [comment]
#1511

**Comment by mmisono** [comment]
This seems good to me. In the third case, bpftrace could emit a warning, and a user can rename the struct if they want to use BTF.

**Comment by viktormalik** [comment]
> Seems like we already have #1511 , this disucssion happens in too many places :p

The problem in #1511 is not related to BTF - the redefinition occurs because `sys/types.h` conflicts with `linux/types.h`, so it's a slightly different (although related) thing.

**Comment by fbs** [comment]
Hmm, I think both will probably end up being the same thing. But we can keep the discussion here :)

**Comment by fbs** [comment]
Fully disabling BTF for one user type conflict seems a bit harsh. 

Maybe we need something like a "type stack"/scope? When resolving a type you start at  the top and work down. So the stack can look like:

1. in script defined types (struct X {...}) & user includes
2. dwarf (in case we ever add it)
3. BTF
4. bpftrace built in types

So if both my script and the kernel define a `struct foo` we will use the user type.

**Comment by viktormalik** [comment]
There are 2 problems with this:
1. This will allow situations like this:
```
struct foo { struct bar *x; }; // user-defined
struct bar { struct baz *y; }; // taken from BTF
struct baz { ... }; // user-defined
```
Do we really want to allow this? We might end up with half of the types taken from user-specified headers (which may come, e.g., from a different kernel version) and half of the types taken from BTF.

2. This will be quite hard to implement as BTF by default returns not only the requested type definition, but also definitions of all types needed for compilation. If those are at the same time user-defined, conflicts will occur.
Example:
```
// BTF:
struct foo { struct bar b; };
struct bar { int x; };

// User-defined:
struct bar { int x; int y;};
```
What to do now? We can't just take `struct bar` from user, that might lead to invalid memory access. 
And even if we wanted to do that, we'd probably have to parse the string returned by BTF and remove the `struct bar` definition from there, which may be quite time-consuming for a large number of such types.
