### ISSUE TITLE
Improve AST / allow mutation

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#1603]
I think we can simplify our big AST passes (esp semantic) a bit if we make it easier to build new passes for analysis or mutation. E.g. we could have a pass that replaces all positional parameters with their actual value (and cases like `str($1+1)`) with their constant value. This should not only improve the semantic pass, but also make codegen better as we currently emit such cases onto the stack and probe read them. There are more passes like these we could add.

Adding new passes is currently a bit tricky. You have to copy a lot of boilerplate to visit the tree add the pass into main and to debug the pass you might want to add the printer before/after. This also means we have to extend every pass if we ever add an AST node.

What I want to add:

- A Visitor base class that handles the tree iteration. Allowing us to write a pass like:

```
class MyThing : public ASTVisitor {
   MyThing(Node * root, args..) :  ASTVisitor(root);

   void visit(Integer &n) { dosomthing(); ASTVistor::visit(n); }
}
```
- A mutator base class which makes it easy to return a modified copy of the tree, similar to the ASTVisitor
- A pass manager to make it easier to add/disable passes and collect info(runtime, new tree etc).

And related:

- Tree destructor to clean up the old copy of the ast.
- Disable the copy constructors to avoid accidental shallow copies of pointers

**Comment by fbs** [comment]
Got a working thing [here](https://github.com/fbs/bpftrace/commits/ast_walker) but I'm not that happy with how the double dispatch makes it hard to customize the return value (would need copies of accept() in the node classes), which is now handled by helpers in the astmutator class (Return, Value). I'm currentl looking at dropping double dispatch and implementing our own vtable dispatch based on type id. The added benefit is that we can have a pattern like:

```
visit(call c)
{
    for (arg in c.args)
        visitor(arg)
}

visitor(node c)
{
    return vtable(c)
}
```

As visitor is visited for every node we can also override visitor to run a single function on each node, similar to what #1601 does now.

**Comment by brendangregg** [comment]
Maybe this will fix ttysnoop.bt, and another tool I'm writing that is supposed to accept an optional filename argument; e.g.:

```if ($2 == 0 || str($2) == str($filename)) {```

**Comment by fbs** [comment]
iirc we did some fixes to allow `str($1 + 3)` again but i see it now fails on the ==0 check.

We should be able to make it work with the pos param removing pass and maybe another. That way we can write it as  `if($1)` and keep `if($1 == 0)` supported for legacy purposes
