### ISSUE TITLE
CMake builds download from github by default

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#161]
It seems like gtest and bcc are updated from github every build. It can be turned off with the right environment variables, but it seems like using git submodules would be a better idea. Does this seem reasonable?

**Comment by danobi** [comment]
Yes, as far as I'm aware, the only option is to pin a submodule to a specific commit.

**Comment by ajor** [comment]
I’m not familiar with all the options, but we should also look into allowing people to point bpftrace to an already cloned repository they’ve got on their computer

**Comment by caringi** [comment]
Hi folks,

I am starting to think about the creation of a bpftrace package for Fedora, but there are these constraints in the Fedora Packaging Guidelines:

"Packages in the Fedora buildsystem are built in a mock chroot with no access to the internet. Packages must not depend or or use any network resources that they don't themselves create (ie, for tests). In no cases should source code be downloaded from any external sources, only from the lookaside cache and/or the Fedora git repository." (https://fedoraproject.org/wiki/Packaging:Guidelines#Build_time_network_access)

Additionally, "Fedora packages SHOULD make every effort to avoid having multiple, separate, upstream projects bundled together in a single package. All packages whose upstreams allow them to be built against system libraries MUST be built against system libraries. All packages whose upstreams have no mechanism to build against system libraries MAY opt to carry bundled libraries, but if they do, they MUST include an indication of what they bundle. This provides a mechanism for locating libraries with bundled code which can, for example, assist in locating packages which may have particular security vulnerabilities." (https://fedoraproject.org/wiki/Packaging:Guidelines#Bundling_and_Duplication_of_system_libraries)

So, what I'm wondering now is if would be possible to build bpftrace following these guidelines... What do you think?

The best option would be to use the bcc and gtest libraries (shared) already shipped with Fedora... But I am not sure if this is possible... Opinions?

**Comment by mskarbek** [comment]
@caringi I have created a package that uses default cmake behavior with only `man` path fixed with `sed` on the fly during the build: https://copr.fedorainfracloud.org/coprs/mskarbek/bpftrace/

Right now it would be good to be able to build against `bcc-devel` package without internet access. Without that there is no chance to go further than personal repo on COPR.

**Comment by ajor** [comment]
Feel free to switch bpftrace over to using Git submodules if anyone wants to btw.

I'll keep this ticket open for enabling building bpftrace against packages as well though.

**Comment by caringi** [comment]
@ajor, @brendangregg I'm analyzing the possibility of building bpftrace using bcc-devel rpm package provided by Fedora (or libbcc rpm package provided by iovisor project), but as far as I can see there is one problem: 

bpftrace is using header files (private?) from bcc which are not part of these rpm packages nor installed through bcc "make install", for example: common.h, syms.h

So, my question is: Do you think that bcc "make install" should installl these "missing" header files?

**Comment by cyphar** [comment]
Yeah, that looks nice -- though of course the changes to `bpftrace`'s CMakeLists.txt are probably a bit more drastic.

**Comment by caringi** [comment]
@cyphar the changes aren't so drastic... :)

https://github.com/iovisor/bpftrace/pull/227

For that to work my previously mentioned bcc tools modification is needed (just the installation of some extra bcc headers files)...

**Comment by mmarchini** [comment]
Sounds reasonable to me, but as @cyphar pointed out in #227, right now bpftrace depends on several internal bcc symbols, so it might take some time to get to this state.

**Comment by danobi** [comment]
I've implemented both (1) and (2) in #327.

**Comment by danobi** [comment]
Patch has landed. Closing out now.

Regarding gtest downloading, I actually think that's ok. In past projects, I've experienced nothing but pain from trying to make tests compile with every distro's outdated gtest package. For packagers, simply skip building tests. For devs, building tests will take a bit longer but it'll be well worth the sanity saved.
