### ISSUE TITLE
Can't check if kprobe is in proper place

### ISSUE THREAD

**Issue by saeedm92** [iovisor/bpftrace#1632]
Hi,

If I download and install the bpftrace rpm v0.10.0, I still don't get the 'kprobe offset' support. This support should be available from v0.9.4 above. 

bpftrace --version
bpftrace v0.10.0

bpftrace  -e 'kprobe:do_sys_open+9 { printf("in here\n"); }'
Attaching 1 probe...
Can't check if kprobe is in proper place (compiled without (k|u)probe offset support): /usr/lib/debug/lib/modules/5.4.0-1947.01.tst30549968.el8uek.rc1.x86_64/vmlinux:do_sys_open+9

However, if I build this manually and install the packages, I would get such support.

Thanks,

System
  OS: Linux 5.4.0-1947.01.tst30549968.el8uek.rc1.x86_64 #2 SMP Wed Nov 20 15:45:15 PST 2019
  Arch: x86_64

Build
  version: v0.10.0
  LLVM: 10
  foreach_sym: yes
  unsafe uprobe: no
  btf: no
  bfd: no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes

**Comment by mmisono** [comment]
I guess to use this functionality,  bpftrace built with bfd. From your `bpftrace --info`:

> bfd: no

So rpm version does not build with bfd. `bpftrace --unsafe -e 'kprobe:do_sys_open+9 { printf("in here\n"); }'` might work, though function boundary check is not performed in this case (IIRC kernel checks whether attach point is middle of instruction or not, but it does not check function boundary, so bpftrace have this feature).
