### ISSUE TITLE
Only tracing processes spawned by -c `command`

### ISSUE THREAD

**Issue by dvc94ch** [iovisor/bpftrace#1666]
### Is your feature request related to a problem? Please describe.
I'd like to use it for benchmarking. So I don't really care about seeing the webbrowser and other stuff that is running. I didn't find a way to accomplish this. To filter on pid I'd have to know the pid of the started command.

### Describe the solution you'd like
bpftrace -c './binary' -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }' would only show stuff that was caused by `./binary`.

**Comment by fbs** [comment]
When using `-c` you can use the `cpid` builtin to get the pid of the child process spawned.

However if the child forks that cpid builtin becomes useless, so we need a way to determine whether a pid is the child of something too. IIRC work has been done on that. Just not sure whether it ever got merged into linux. #397 is related to that.

**Comment by dvc94ch** [comment]
It is indeed documented under the `builtins` section. Sorry I missed it. Closing in favor of #397.
