### ISSUE TITLE
"str" not work for some scene

### ISSUE THREAD

**Issue by jim3ma** [iovisor/bpftrace#1675]
Original issue:
https://stackoverflow.com/questions/65413266/how-to-use-a-struct-for-golang-fuction-args-in-bpftrace

bpftrace code:
printf("array: %s\n", str(*($array), $length)); // work
printf("array: %s\n", str($s->array, $s->length)); // not work

```
struct args
{
    uint64_t array;
    uint64_t length;
    uint64_t somevalue;
};

uprobe:/tmp/main:0x49aa00 {

  $s = (struct args *)(reg("sp") + 16);

  $length = *(reg("sp") + 24);
  $array  = reg("sp") + 16;

  printf("length: %d\n", $s->length);
  printf("array: %s\n", str(*($array), $length));
  printf("somevalue: %d\n", $s->somevalue);
  // this one will be empty
  printf("array: %s\n", str($s->array, $s->length));
}
```

Can some one help?

**Comment by mmisono** [comment]
I guess this is related to #1305. Can you try to run bpftrace with `-kk` option? The problem might be solved.

**Comment by jim3ma** [comment]
@mmisono Thanks, the bpftrace in ubuntu is 0.9.4, after build from source, all is ok with out `-kk` option.
