### ISSUE TITLE
bpftrace's kprobes not triggering

### ISSUE THREAD

**Issue by lorddoskias** [iovisor/bpftrace#1682]
### What reproduces the bug?
The following test case does't trigger any input from bpftrace:

```
#!/bin/bash

mkfs.btrfs -f /dev/vdc &> /dev/null
mount /dev/vdc /media/scratch/

bpftrace -e 'kprobe:btrfs_sync_file {printf("kprobe: %s\n", kstack());}' &>bpf-output &
bpf_trace_pid=$!

# force btrfs_sync_file to be called 
sleep 2
xfs_io -f -c "pwrite 0 4m" -c "fsync" /media/scratch/file5

kill $bpf_trace_pid
sleep 1

grep -q kprobe bpf-output
retval=$?
#rm -f bpf-output
umount /media/scratch

exit $retval
```
However if I replace the bpftrace script with the following program only the tracepoint produces an output: 
`bpftrace -e 'tracepoint:btrfs:btrfs_sync_file {printf("tracepoint: %s\n", kstack());} kprobe:btrfs_sync_file {printf("kprobe: %s\n", kstack());}'`

Yet on the same kernel the following test does produce the expected call trace in ftrace's buffer: 

```
#!/bin/bash

mkfs.btrfs -f /dev/vdc &> /dev/null
mount /dev/vdc /media/scratch/

echo "p:myevent btrfs_sync_file" >> /sys/kernel/debug/tracing/kprobe_events
echo stacktrace > /sys/kernel/debug/tracing/events/kprobes/myevent/trigger
echo 1 > /sys/kernel/debug/tracing/events/kprobes/myevent/enable

# force btrfs_sync_file to be called 
xfs_io -f -c "pwrite 0 4m" -c "fsync" /media/scratch/file5

cat /sys/kernel/debug/tracing/trace
echo 0 > /sys/kernel/debug/tracing/events/kprobes/myevent/enable
umount /media/scratch
```

Initially I thought this is a kernel issue as this problem appears following upstream kernel commit `0d00449c7a28 ("x86: Replace ist_enter() with nmi_enter()")` . However, ftrace's tracepoint always work. Additionally bcc's funccount utility also doesn't produce outputs. And the issue is not specific to btrfs_sync_file function but to other, independent functions as well. 

### bpftrace --info
```
System
  OS: Linux 5.11.0-rc5-default #85 SMP Wed Jan 27 15:41:48 EET 2021
  Arch: x86_64

Build
  version: v0.11.0-336-g79d3
  LLVM: 6.0.0
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  libbpf: no
  libbpf btf dump: no
  libbpf btf dump type decl: no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): no
  map batch (depends on Build:libbpf): no
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
```

**Comment by lorddoskias** [comment]
So the problems seems to be purely kernel related... Following email thread explains why: 
https://lore.kernel.org/bpf/20210128123842.c9e33949e62f504b84bfadf5@gmail.com/T/#u

I'm surprised that bpf's core kprobe support went broken undetected for almost a year!

**Comment by danobi** [comment]
Looks like it was some CET compiler thing. Complicated..

**Comment by lorddoskias** [comment]
This was actually a kernel issue so closing it.
