### ISSUE TITLE
arm 32 support

### ISSUE THREAD

**Issue by RobertBerger** [iovisor/bpftrace#1688]
### Is your feature request related to a problem? Please describe.

If you have a look here [https://github.com/iovisor/bpftrace/tree/master/src/arch](https://github.com/iovisor/bpftrace/tree/master/src/arch) you see that only 64-bit architectures seem to be supported. Are there any plans to support arm 32?

### Describe the solution you'd like

Is there any reason why arm 32 is not supported?

### Describe alternative solutions or features you've considered

At the moment the only solution I found which works on arm 32 is [https://github.com/iovisor/ply](https://github.com/iovisor/ply) but bpftrace and various other frameworks are much more popular and there is much more info/are more examples out there.

**Comment by fbs** [comment]
I don't have a proper arm setup to test with but I assume some of it might just work. There might be some issues around 64 bit assumptions but I don't think too many are left. 

You could start with copying aarch64.cpp to aarch(32?).cpp and update src/arch/CMakeLists.txt to support it and see what happens. If it works we can merge it here. Only issue is that we dont have proper ci support for anything but x86 yet, so it will probably break unnoticed from time to time

**Comment by waby38b** [comment]
hello, 
I've just try our proposal (to copy aarch64.cpp into arm32.cpp then update src/arch/CMakeLists.txt
And here the status (here you have major dependencies versions,feel free to ask more !)
gcc-c++-11.0.1-0.3.fc34.armv7hl
llvm-devel-12.0.0-0.1.rc1.fc34.armv7hl
clang-devel-12.0.0-0.3.rc1.fc34.armv7hl
bcc-devel-0.19.0-2.fc34.armv7hl
libbpf-devel-0.3.0-2.fc34.armv7hl
libbpf-static-0.3.0-2.fc34.armv7hl
binutils-devel-2.35.1-41.fc34.armv7hl
bpftrace-0.12.0-1.fc34.armv7hl

My board (4kopen / 4 x A9 + 2go RAM) is running a pre-release of Fedora 34 + recompiled bcc-0.19.0
and also bpftrace 0.12 + small arm.patch (your proposal)
[root@fedora ~]# uname -a
Linux fedora 5.11.14-200.4kopen.fc33.armv7hl #1 SMP Wed Apr 14 20:54:39 UTC 2021 armv7l armv7l armv7l GNU/Linux

First test seem to work as expected!
```
[root@fedora ~]# bpftrace -e 'BEGIN { printf("hello world\n"); }'
Attaching 1 probe...
hello world
```

now, let switch to another example
```
[root@fedora ~]# /usr/share/bpftrace/tools/bashreadline.bt
Attaching 2 probes...
Tracing bash commands... Hit Ctrl-C to end.
TIME      PID    COMMAND
22:15:24  -1096367948 
22:15:28  -1096367948 ls
22:15:38  -1096367948 echo It seem to work

```
It seem to work, but as you can see, PID number is just broken....

now, let try "loads.bt"
```
[root@fedora ~]# /usr/share/bpftrace/tools/loads.bt
Attaching 2 probes...
Reading load averages... Hit Ctrl-C to end.
22:18:03 load averages: 24382384.-1090941020 -1090941020.-1090941020 -1090941020.-1090941020
22:18:04 load averages: 24382384.-1090941020 -1090941020.-1090941020 -1090941020.-1090941020
22:18:05 load averages: 24382384.-1090941020 -1090941020.-1090941020 -1090941020.-1090941020
22:18:06 load averages: 24382384.-1090941020 -1090941020.-1090941020 -1090941020.-1090941020
22:18:07 load averages: 24382384.-1090941020 -1090941020.-1090941020 -1090941020.-1090941020
22:18:08 load averages: 24382384.-1090941020 -1090941020.-1090941020 -1090941020.-1090941020
^C

```
Again, numbers returned seem broken... (64 bits => 32 bits issues ?)

```
[root@fedora ~]# /usr/share/bpftrace/tools/bitesize.bt
Attaching 3 probes...
Tracing block device I/O... Hit Ctrl-C to end.
^C
I/O size (bytes) histograms by process name:

@[kworker/1:1H]: 
[64K, 128K)            1 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
[128K, 256K)           0 |                                                    |
[256K, 512K)           1 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|

@[kworker/2:1H]: 
[4K, 8K)               2 |@@@@@@@@@@@@@@@@@@@@                                |
[8K, 16K)              0 |                                                    |
[16K, 32K)             0 |                                                    |
[32K, 64K)             0 |                                                    |
[64K, 128K)            5 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|

@[kworker/3:1H]: 
[4K, 8K)              31 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
[8K, 16K)              0 |                                                    |
[16K, 32K)             0 |                                                    |
[32K, 64K)             1 |@                                                   |
[64K, 128K)            1 |@                                                   |

@[kworker/0:1H]: 
[4K, 8K)              45 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
[8K, 16K)              4 |@@@@                                                |

```
Seem to work as expected (I was just make "ls -R /boot/" in another term)

cpuwalk
```
[root@fedora ~]# /usr/share/bpftrace/tools/cpuwalk.bt
Attaching 2 probes...
Sampling CPU at 99hz... Hit Ctrl-C to end.
^C

@cpu: 
[0, 1)                 4 |@@@@@@                                              |
[1, 2)                32 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
[2, 3)                19 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                      |
[3, 4)                 6 |@@@@@@@@@                                           |

```
Now, let's try capable.bt
```
[root@fedora ~]# /usr/share/bpftrace/tools/capable.bt
Attaching 3 probes...
Tracing cap_capable syscalls... Hit Ctrl-C to end.
TIME      UID    PID    COMM             CAP  NAME                 AUDIT
22:26:01  15702136 -1091379292 NetworkManager   -1091379292                      -1091379292
22:26:01  15702136 -1091379292 NetworkManager   -1091379292                      -1091379292
22:26:01  15702136 -1091379292 NetworkManager   -1091379292                      -1091379292
22:26:01  15702136 -1091379292 NetworkManager   -1091379292                      -1091379292
22:26:01  15702136 -1091379292 NetworkManager   -1091379292                      -1091379292
22:26:01  15702136 -1091379292 NetworkManager   -1091379292                      -1091379292
22:26:01  15702136 -1091379292 NetworkManager   -1091379292                      -1091379292
22:26:01  15702136 -1091379292 NetworkManager   -1091379292                      -1091379292
22:26:01  15702136 -1091379292 NetworkManager   -1091379292                      -1091379292
22:26:01  15702136 -1091379292 NetworkManager   -1091379292                      -1091379292
^C

```
again, same issue with "numbers"...

Now, let try syscount
```
[root@fedora ~]# /usr/share/bpftrace/tools/syscount.bt
Attaching 3 probes...
Counting syscalls... Hit Ctrl-C to end.
^C
Top 10 syscalls IDs:
@syscall[175]: 220
@syscall[20]: 238
@syscall[54]: 309
@syscall[217]: 1018
@syscall[403]: 1034
@syscall[397]: 1236
@syscall[221]: 1343
@syscall[3]: 1825
@syscall[6]: 2135
@syscall[322]: 2211

Top 10 processes:
@process[sssd]: 56
@process[watchdog]: 108
@process[ls]: 166
@process[gdbus]: 222
@process[bash]: 251
@process[NetworkManager]: 345
@process[sssd_nss]: 530
@process[sshd]: 636
@process[systemd-oomd]: 1832
@process[htop]: 8558

```
sounds good !

And the last one for now
```
[root@fedora ~]# /usr/share/bpftrace/tools/execsnoop.bt
Attaching 3 probes...
ERROR: Error loading program: tracepoint:syscalls:sys_enter_execve (try -v)
[root@fedora ~]# /usr/share/bpftrace/tools/execsnoop.bt -v
INFO: node count: 23
Attaching 3 probes...

Program ID: 82

The verifier log: 
processed 101 insns (limit 1000000) max_states_per_insn 0 total_states 1 peak_states 1 mark_read 0

Attaching BEGIN

Error log: 
processed 218 insns (limit 1000000) max_states_per_insn 0 total_states 20 peak_states 20 mark_read 17

ERROR: Error loading program: tracepoint:syscalls:sys_enter_execve
```
Not really clear for me....


So to conclude, it's not in bad shape, but we probably need to identify why number are broken!
Feel free to ask me everything which can help to fix ARM32 bpftrace !!!

**Comment by HA-sala** [comment]
Hi,   @waby38b :
  I'm a newcomer of bpftrace.  I want to run bpftrace on arm 32, but i don't  know  how to set the cmake command to cross compile for arm 32.  Any step-by-step tutorial about sinstalling this tool on arm 32?

My board: 
`root@lubancat:~# uname -a
Linux lubancat 4.19.35-imx6 #1.2108stable SMP PREEMPT Tue Aug 17 00:52:28 EDT 2021 armv7l GNU/Linux
`

**Comment by waby38b** [comment]
Hi , @HA-sala 

Bpftrace require many dependencies to build (BCC, llvm,clang,...) And not vers easy to build by yourself( without a distro)

I use to build it on fedora for arm32 which already provide many dependencies

Now, I have also a prototype of build using buildroot
Which build système are using with your board ?

**Comment by RobertBerger** [comment]
Hi, @waby38b 

I use the Yocto project. So the magic you did for buildroot might help.

**Comment by HA-sala** [comment]
> Hi , @HA-sala
> 
> Bpftrace require many dependencies to build (BCC, llvm,clang,...) And not vers easy to build by yourself( without a distro)
> 
> I use to build it on fedora for arm32 which already provide many dependencies
> 
> Now, I have also a prototype of build using buildroot
> Which build système are using with your board ?

thank you! 
this is my board. 
```
root@lubancat:~# uname -a
Linux lubancat 4.19.35-imx6 #1.2108stable SMP PREEMPT Tue Aug 17 00:52:28 EDT 2021 armv7l GNU/Linux
```

Now,  I‘m trying to cross-compile using the method provided in the project[https://github.com/iovisor/bpftrace/blob/master/docs/embedded_builds.md](url), but it's bumpy for me. :(

If i use buildroot, how to do it？

**Comment by RobertBerger** [comment]
@waby38b  Are your arm32 patches somewhere to give them a try? Do you plan to upstream them?

**Comment by waby38b** [comment]
Here almost "broken" patch I've used for my experiment.
[0001-preliminary-arm32-support.txt](https://github.com/iovisor/bpftrace/files/7231507/0001-preliminary-arm32-support.txt)

`src/arch/arm32.cpp` is a direct copy of `aarch64.cpp` which is probably broken....
=> looking @https://github.com/iovisor/ply/tree/master/src/libply/arch just show something different for aarch64 & arm32

2nd point related to bcc which is a dependency of bpftrace:
=> seem also broken on arm32... tried both on fedora & buildroot ( armv7hl ) 
   => example (in python) alway failed to excute.... 

Anyway, I've put a simple copr repos for fedora32 / armv7hl here if you just want to try without any compilation
https://copr.fedorainfracloud.org/coprs/waby38/arm32-bpftrace/
to enable repo; `dnf copr enable waby38/arm32-bpftrace`
to try: `dnf install bpftrace`

I will back with patchs for buildroot (bcc, bpftrace support), but don't expect too much....

As a proposal, you may have a look to ply project https://github.com/iovisor/ply
which has arm32 support & sweeter for embedded platform / easy to compile

**Comment by waby38b** [comment]
Here preliminary arm32 patches for buildroot 2021.08.x

Again, don't expect magic full working version !!!!!
This add "bcc" and "bpftrace" support, and upgrade a bit libbpf (see patches for credit !)

[buildroot-2021-08.x-patches.tar.gz](https://github.com/iovisor/bpftrace/files/7237686/buildroot-2021-08.x-patches.tar.gz)

With this, you can have a ~bpftrace / arm32 under buildroot

```
$ bpftrace --info
System
  OS: Linux 5.14.8 #47 SMP Mon Sep 27 17:25:40 CEST 2021
  Arch: armv7l

Build
  version: v0.13.0
  LLVM: 9.0.1
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: no
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): no
  map batch (depends on Build:libbpf): yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
  iter:task: no
  iter:task_file: no
```
and somes basic stuff are working
```
$  bpftrace -e 'BEGIN { printf("hello world\n"); }'
Attaching 1 probe...
hello world
^C
```

```
$ /usr/share/bpftrace/tools/cpuwalk.bt
Attaching 2 probes...
Sampling CPU at 99hz... Hit Ctrl-C to end.
^C

@cpu: 
[0, 1)                 9 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@      |
[1, 2)                 4 |@@@@@@@@@@@@@@@@@@@@                                |
[2, 3)                 0 |                                                    |
[3, 4)                10 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
```
```
$ /usr/share/bpftrace/tools/syscount.bt
Attaching 3 probes...
Counting syscalls... Hit Ctrl-C to end.

^C
Top 10 syscalls IDs:
@syscall[54]: 24
@syscall[172]: 25
@syscall[91]: 27
@syscall[3]: 46
@syscall[4]: 51
@syscall[6]: 84
@syscall[322]: 86
@syscall[403]: 134
@syscall[217]: 138
@syscall[397]: 875

Top 10 processes:
@process[ntpd]: 8
@process[motion]: 20
@process[bpftrace]: 23
@process[watchdog]: 26
@process[syslogd]: 75
@process[ml1]: 217
@process[python3]: 1260
```

but still wrong return values....
```
$ /usr/share/bpftrace/tools/loads.bt
Attaching 2 probes...
Reading load averages... Hit Ctrl-C to end.
18:06:07 load averages: -1091830948.-1091830948 -1091830948.-1091830948 -1091830948.-1091830948
18:06:08 load averages: -1091830948.-1091830948 -1091830948.-1091830948 -1091830948.-1091830948
^C
```

Now, you can play with the thing !

**Comment by waby38b** [comment]
An updated version of buildroot patches (just replace previous one)
[buildroot-2021-08.x-patches-v2.tar.gz](https://github.com/iovisor/bpftrace/files/7250445/buildroot-2021-08.x-patches-v2.tar.gz)

This introduce new package "[libdwarves](https://github.com/acmel/dwarves)" which provide pahole to compile 
kernel with [BTF](https://www.brendangregg.com/blog/2020-11-04/bpf-co-re-btf-libbpf.html) support (CONFIG_DEBUG_INFO_BTF)

after that, bpftrace support (for buildroot) seem a bit better (check previous `bpftrace --info`)

```
$ bpftrace --info
System
  OS: Linux 5.14.8 #29 SMP Wed Sep 29 09:43:59 CEST 2021
  Arch: armv7l

Build
  version: v0.13.0
  LLVM: 9.0.1
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: no
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): yes
  map batch (depends on Build:libbpf): yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes

```

**Comment by HA-sala** [comment]
@waby38b Thank you very much for your buildroot patches. I successfully deployed bpftrace on my ARM32, that's cool!!!
