### ISSUE TITLE
Distorted output when tracing opened files

### ISSUE THREAD

**Issue by arsinclair** [iovisor/bpftrace#1699]
Following a [guide from the Reference](https://github.com/iovisor/bpftrace/blob/master/docs/tutorial_one_liners.md#lesson-3-file-opens) I get a distorted output for filename param. I've tried playing with my Konsole encoding settings (set to Unicode by default), but no effect.

Example output:

> Chrome_IOThread         !�!��t(�V:
> Chrome_IOThread         !�!��t(�V:
> Chrome_IOThread         !�!��h
>                               �V:
> Chrome_IOThread         !�!�����V:
> Chrome_IOThread         !�!�PI �V:
> Chrome_IOThread         !�!�@�}�V:
> Chrome_IOThread         !�!�@�}�V:
> Chrome_IOThread         !�!�@�}�V:
> Chrome_IOThread         !�!��u��V:
> Chrome_IOThread         !�!��u��V:
> brave ���
> konsole ��_
> konsole ��_
> konsole `�_
> konsole ��_
> konsole ��_
> krusader  qE��U

### What reproduces the bug?
```bash
# bpftrace -e 'tracepoint:syscalls:sys_enter_openat { printf("%s %s\n", comm, str(args->filename)); }'
```
I expect to see the actual file names.

### 

# bpftrace --info
```bash
root@jrmpc:~# bpftrace --info
bpftrace: invalid option -- '-'
USAGE:
    bpftrace [options] filename
    bpftrace [options] -e 'program'

OPTIONS:
    -d             debug info dry run
    -dd            verbose debug info dry run
    -e 'program'   execute this program
    -h             show this help message
    -l [search]    list probes
    -p PID         enable USDT probes on PID
    -c 'CMD'       run CMD and enable USDT probes on resulting process
    -v             verbose messages

ENVIRONMENT:
    BPFTRACE_STRLEN    [default: 64] bytes on BPF stack per str()

EXAMPLES:
bpftrace -l '*sleep*'
    list probes containing "sleep"
bpftrace -e 'kprobe:do_nanosleep { printf("PID %d sleeping...\n", pid); }'
    trace processes calling sleep
bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'
    count syscalls by process name
```

**Comment by danobi** [comment]
Can you try on a newer version of bpftrace? Yours is so old it doesn't even have the `--info` flag!

**Comment by arsinclair** [comment]
Looks like the version I'm using is 0.8. Someone with Debian knowledge should push newer version to Buster branch, really. Unfortunately, I don't know how.

I've tried downloading newest version from sid branch of Debian, but I can't run it since it depends on packages that are not available in my branch

>The following packages have unmet dependencies:
 bpftrace : Depends: libbpf0 (>= 1:0.0.8) but it is not installable
            Depends: libbpfcc (>= 0.18.0+ds) but 0.8.0-4 is to be installed
            Depends: libclang1-11 (>= 1:9~svn359771-1~) but it is not installable
            Depends: libgcc-s1 (>= 3.0) but it is not installable
            Depends: libllvm11 (>= 1:9~svn298832-1~) but it is not installable
            Depends: libstdc++6 (>= 9) but 8.3.0-6 is to be installed

I've also tried downloading the bundled version from Releases page here on Github, but it doesn't attach the probe. It outputs a few warning and quits. These are the errors:

> root@jrmpc:/home/jrm/Downloads# ./bpftrace -e 'tracepoint:syscalls:sys_enter_openat { printf("%s %s\n", comm, str(args->filename)); }'
definitions.h:13:3: error: unknown type name 's64'
definitions.h:15:3: error: unknown type name 's64'
definitions.h:16:3: error: unknown type name 'umode_t'
root@jrmpc:/home/jrm/Downloads# 

What are my next steps?

**Comment by fbs** [comment]
Is `/usr/src/kernels/$(uname -r)/include/linux/types.h` available on your system?

**Comment by arsinclair** [comment]
Sorry for late response, I'm finally back here.

No, it is missing. In fact `/usr/src/` folder appears to be empty.

**Comment by fbs** [comment]
Can you install the headers and make sure `/usr/lib/modules/$(uname -r)/build`  links to them and try again?

**Comment by arsinclair** [comment]
With headers installed bundled version works like a charm. Why does it need headers? In my understanding, the headers are only needed for the development purposes.

**Comment by fbs** [comment]
```
$ sudo bpftrace -lv tracepoint:syscalls:sys_enter_openat
tracepoint:syscalls:sys_enter_openat
    int nr;
    int dfd;
    const char * filename;
    int flags;
    umode_t mode;
    ```

Additionally we do:

```
std::string TracepointFormatParser::adjust_integer_types(const std::string &field_type, int size)
{
  std::string new_type = field_type;
  // Adjust integer fields to correctly sized types
  if (size == 8)
  {
    if (field_type == "int")
      new_type = "s64";
    if (field_type == "unsigned int" || field_type == "unsigned" ||
        field_type == "u32" || field_type == "pid_t" ||
        field_type == "uid_t" || field_type == "gid_t")
      new_type = "u64";
  }
```

So we need to have atleast those two types (u64, umode_t) defined for it to work.

**Comment by arsinclair** [comment]
Great, thank you for your explanation. I'm upgrading to Debian 11 at the moment which has newer version in the store, and the issue is not affecting me anymore.

Feel free to close the ticket, if there's no plan on updating the _bpftrace_ version in the Debian 10 package repository.

Thank you!

**Comment by scilla0531** [comment]
What is the problem with this error?
```
definitions.h:14:3: error: unknown type name 's64'
definitions.h:16:3: error: unknown type name 's64'
definitions.h:17:3: error: unknown type name 'umode_t'
```

**Comment by arsinclair** [comment]
> What is the problem with this error?
> 
> ```
> definitions.h:14:3: error: unknown type name 's64'
> definitions.h:16:3: error: unknown type name 's64'
> definitions.h:17:3: error: unknown type name 'umode_t'
> ```

The problem was solved by installed additional headers (see above). BPFTrace requires:

> at least those two types (u64, umode_t) defined for it to work.
