### ISSUE TITLE
Not able to attach kprobe in bpftrace one-liner

### ISSUE THREAD

**Issue by rahul-kr4604** [iovisor/bpftrace#1707]
I am executing a one-liner with kprobe 'tnet_csk_accept', but getting below error:

```
cannot attach kprobe, probe entry may not exist
ERROR: Error attaching probe: 'kprobe:tnet_csk_accept' 
```

Is this a bug?
or 
Only those kprobes could be attached which are listed in 'bpftrace -l' command, 'tnet_csk_accept' is not available in 'bpftrace -l' command.
or 
I could use it after registering it with bpftrace if possible.

**Comment by fbs** [comment]
If the function doesn't exist in the kernel it cannot be traced. If it doesn't show up in `bpftrace -l` but you're sure it should please add the details required.

Maybe try **i**net, not **t**net

**Comment by rahul-kr4604** [comment]
Thanks fbs for your reply!

>> Maybe try inet, not tnet

Yes, this is inet.

I have a query in this:

If any kernel function is not available in **bpftrace -l** then as a user, could I add this function to bpftrace? If yes then what is the procedure to do so. Or bpftrace authors are responsible to add missing kernel function in **bpftrace -l**.

Thanks!

**Comment by fbs** [comment]
bpftrace is a kernel api consumer, we don't extend the kernel with any apis/interfaces/function (excluding ofc bpf programs). If the function doesn't show up in `bpftrace -l` it's either not tracable(some functions are blocked iirc) or it's a bug.

What function do you want to trace and does it actually exist? Are you able to trace it with ftrace or bcc?

**Comment by viktormalik** [comment]
Not related to bpftrace, closing.
