### ISSUE TITLE
Support array indexing on pointers

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#1717]
### Is your feature request related to a problem? Please describe.
Array indexing is only supported on constant length arrays. I can't think of any reasons why we can't let users index through a pointer as long as the pointer isn't `void *`.

### Describe the solution you'd like
Support array index through pointers.

eg.
```
$p = (uint32 *)arg0;
$val = $p[5];
```

### Describe alternative solutions or features you've considered
You can currently workaround it by doing pointer math and printing individual elements.

Or you can declare a dummy struct with a constant length array, eg:
```
struct Foo {
  uint32_t arr[16];
}

... {
  $p = (struct Foo *)arg0;
  $val = $p->arr[5];
}
```

**Comment by fbs** [comment]
+1 but this links to #1507 as there was some discussion there on what pointer arithmetic means, this is just syntactic sugar for it.

**Comment by viktormalik** [comment]
This should be quite straightforward to do, the only drawback is that we won't be able to do array bounds checks on pointers.

I can do this, as I recently did some work on array indexing, but as @fbs points out, we should maybe wait until the discussion on pointer arithmetics is finished.

**Comment by danobi** [comment]
> the only drawback is that we won't be able to do array bounds checks on pointers

Yes, unfortunate, but also unavoidable sometimes (eg if a function takes `u32 * array_of_ints` as an argument.

> I can do this, as I recently did some work on array indexing, but as @fbs points out, we should maybe wait until the discussion on pointer arithmetics is finished.

Awesome, thanks :). I left a comment on the pointer arith thread to try and move things along.
