### ISSUE TITLE
Strange values probing tracepoint:syscalls:sys_exit_read using sum(args->ret)

### ISSUE THREAD

**Issue by caringi** [iovisor/bpftrace#172]
Running the following one-liner in my system for a few seconds:

bpftrace -e 'tracepoint:syscalls:sys_exit_read /args->ret/ { @[comm] = sum(args->ret); }

I get:

@[TaskSchedulerSe]: 1
@[systemd-logind]: 8
@[rtkit-daemon]: 8
@[QThread]: 8
@[systemd-machine]: 8
@[goldendict]: 16
@[nm-applet]: 16
@[firewall-applet]: 24
@[atom]: 31
@[Media]: 32
@[mate-sensors-ap]: 33
@[abrt-dump-journ]: 63
@[gdbus]: 64
@[gmain]: 77
@[hexchat]: 101
@[InputThread]: 208
@[mate-cpufreq-ap]: 225
@[docker-containe]: 392
@[dockerd-current]: 405
@[openvpn]: 452
@[sedispatch]: 535
@[gvfsd-fuse]: 600
@[AudioOutputDevi]: 1256
@[Chrome_ChildIOT]: 1306
@[systemd-journal]: 1605
@[systemd]: 2182
@[alsa-sink-CX207]: 2544
@[Chrome_IOThread]: 3367
@[marco]: 3424
@[chrome]: 3866
@[irqbalance]: 4697
@[sa1]: 7608
@[mate-netspeed-a]: 9513
@[Xorg]: 24071
@[sadc]: 55436
@[mate-multiload-]: 522663
@[pulseaudio]: 18446744073709549508
@[threaded-ml]: 18446744073709551400
@[in:imjournal]: 18446744073709551560
@[mate-terminal]: 18446744073709551606

The value of these last 4 entries seem strange for me... Or am I missing something?

**Comment by brendangregg** [comment]
args->ret can be negative with errors (-ERRNO). To start with, I'd change the predicate to be /args->ret > 0/

**Comment by caringi** [comment]
@brendangregg understood, thanks!
