### ISSUE TITLE
Support argument access by name, show arguments in probe list

### ISSUE THREAD

**Issue by ema** [iovisor/bpftrace#1742]
### Is your feature request related to a problem? Please describe.
While in the case of static kernel tracepoints arguments [can be accessed by name](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#6-tracepoint-static-tracing-kernel-level-arguments), when it comes to dynamic kernel and userspace tracing (kprobe, uprobe) arguments can only be accessed with the arg0, ... argN positionals. Argument names are more user friendly, make tracing scripts slightly less implemetation-dependant, and improve readability.
 
### Describe the solution you'd like
SystemTap supports accessing arguments by name for all type of probes, and shows which arguments are in scope  together with the data type:

```
$ sudo stap -L 'process("/bin/ls").function("print_name_with_quoting")' 
process("/bin/ls").function("print_name_with_quoting@src/ls.c:4727") $f:struct fileinfo const* $symlink_target:_Bool $stack:struct obstack* $start_col:size_t
```
It would be great if bpftrace could do the same too.

**Comment by danobi** [comment]
We have support for kernel arguments: https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#16-kfunckretfunc-kernel-functions-tracing-arguments

User arguments would require some cost/benefit analysis. Seems like it'd require deep language support (for anything other than C).

**Comment by ema** [comment]
> We have support for kernel arguments: https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#16-kfunckretfunc-kernel-functions-tracing-arguments

Oh, I did not know that, thanks for pointing it out. The distinction between kprobe and kfunc confused me. It seems that kfunc support isn't available on my system?

```
$ sudo bpftrace -e 'kfunc:fget { printf("fd %d\n", args->fd);  }'
stdin:1:1-11: ERROR: kfunc/kretfunc not available for your kernel version.
kfunc:fget { printf("fd %d\n", args->fd);  }
~~~~~~~~~~
stdin:1:32-40: ERROR: Can't find a field
kfunc:fget { printf("fd %d\n", args->fd);  }
```
```
$ sudo bpftrace --info
System
  OS: Linux 5.10.0-5-amd64 #1 SMP Debian 5.10.24-1 (2021-03-19)
  Arch: x86_64

Build
  version: v0.11.3
  LLVM: 11
  foreach_sym: yes
  unsafe uprobe: no
  bfd: no
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
```

**Comment by danobi** [comment]
> > We have support for kernel arguments: https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#16-kfunckretfunc-kernel-functions-tracing-arguments
> 
> Oh, I did not know that, thanks for pointing it out. The distinction between kprobe and kfunc confused me. It seems that kfunc support isn't available on my system?
> 
> <...>
>   kfunc: no
> ```

Yeah, --info is telling you it isn't available on your system as well.

It's a relatively new feature (~5.6): https://lore.kernel.org/bpf/20191114185720.1641606-1-ast@kernel.org/ .

kfunc/kretfunc is almost completely superior to kprobe/kretprobes.

k[ret]func's:
* nearly 0 overhead to call
* can access function arguments in return probe
* bpftrace can infer argument names (less error prone)

The only thing kprobes can do that k[ret]func's can't is attach to arbitrary offsets/instructions in a function.

**Comment by ema** [comment]
> Yeah, --info is telling you it isn't available on your system as well.
> 
> It's a relatively new feature (~5.6): https://lore.kernel.org/bpf/20191114185720.1641606-1-ast@kernel.org/ .

I'm running a 5.10 kernel though, so I should be able to use the feature? Does it depend on any specific kernel config? The following are not set on a Debian kernel:

```
$ grep BPF /boot/config-5.10.0-5-amd64 | grep not
# CONFIG_BPF_JIT_ALWAYS_ON is not set
# CONFIG_BPF_PRELOAD is not set
# CONFIG_BPFILTER is not set
# CONFIG_BPF_KPROBE_OVERRIDE is not set
```

**Comment by danobi** [comment]
> > Yeah, --info is telling you it isn't available on your system as well.
> > It's a relatively new feature (~5.6): https://lore.kernel.org/bpf/20191114185720.1641606-1-ast@kernel.org/ .
> 
> I'm running a 5.10 kernel though, so I should be able to use the feature? Does it depend on any specific kernel config? The following are not set on a Debian kernel:
> 
> ```
> $ grep BPF /boot/config-5.10.0-5-amd64 | grep not
> # CONFIG_BPF_JIT_ALWAYS_ON is not set
> # CONFIG_BPF_PRELOAD is not set
> # CONFIG_BPFILTER is not set
> # CONFIG_BPF_KPROBE_OVERRIDE is not set
> ```

I think you need a relatively new bcc as well. kfunc support depends on the bcc support. But I believe kernel + bcc are the only dependencies.
