### ISSUE TITLE
Not able to build on Ubuntu 18.04 

### ISSUE THREAD

**Issue by abhinav-upadhyay** [iovisor/bpftrace#179]
I am trying to build on Ubuntu 18.04 following the instructions provided in install.md. But I am getting configure errors from cmake. I already had most of the dependencies installed (including llvm-5.0, clang-5.0). Initially it was complaining about not able to find `ClangConfig.cmake`, I provided its location by setting `CLANG_DIR` but afterwards it failed at not being able to load `ClangTargets.cmake` which is included at line 18 in `ClangConfig.cmak`. Any hints about how to resolve would be appreciated.

```
abhinav@abhinav-asus2 ~/d/b/build> env Clang_DIR=/usr/share/llvm-5.0/cmake CLANG_CMAKE_DIR=/usr/share/llvm-5.0/cmake cmake -DCMAKE_BUILD_TYPE=DEBUG ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibElf: /usr/lib/x86_64-linux-gnu/libelf.so
-- Performing Test ELF_GETSHDRSTRNDX
-- Performing Test ELF_GETSHDRSTRNDX - Success
-- Found BISON: /usr/bin/bison (found version "3.0.4")
-- Found FLEX: /usr/bin/flex (found version "2.6.4")
CMake Error at /usr/share/llvm-5.0/cmake/ClangConfig.cmake:18 (include):
  include could not find load file:

    /usr/lib/cmake/clang/ClangTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:67 (find_package)


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring incomplete, errors occurred!
See also "/home/abhinav/dev/bpftrace/build/CMakeFiles/CMakeOutput.log".
See also "/home/abhinav/dev/bpftrace/build/CMakeFiles/CMakeError.log".
```

**Comment by brendangregg** [comment]
This looks like #76, and the install.md has the workaround: it installs llvm/clang from llvm.org repos, rather than the default ones. If you miss a step, like `sudo apt-key add -`, then it will install from the default and not llvm.org, and you'll hit this issue. Can you try again and make sure it's installing llvm/clang from llvm.org?

**Comment by brendangregg** [comment]
Was this still an issue? We can close the ticket if it isn't.

**Comment by abhinav-upadhyay** [comment]
I didn't get around to try it. Will do today and let you know. Thanks

**Comment by abhinav-upadhyay** [comment]
Installing clang and llvm from llvm apt repo fixed it.

In the past I remember installing llvm from the llvm apt repo but it seems during dist upgrades at some point those repos were disabled in my apt sources list and I ended up installing llvm from Ubuntu's repos.

Thanks for the pointers.
