### ISSUE TITLE
Failed to link bpftrace against libLLVM12

### ISSUE THREAD

**Issue by Birch-san** [iovisor/bpftrace#1791]
compile succeeded, but link failed:

```
[100%] Building CXX object src/CMakeFiles/bpftrace.dir/main.cpp.o
[100%] Linking CXX executable bpftrace
/usr/bin/ld: libbpftrace.a(clang_parser.cpp.o): in function `bpftrace::is_anonymous(CXCursor)':
/home/alex/git/bpftrace/src/clang_parser.cpp:108: undefined reference to `clang_Cursor_isAnonymousRecordDecl'
collect2: error: ld returned 1 exit status
make[3]: *** [src/CMakeFiles/bpftrace.dir/build.make:95: src/bpftrace] Error 1
make[2]: *** [CMakeFiles/Makefile2:1287: src/CMakeFiles/bpftrace.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1294: src/CMakeFiles/bpftrace.dir/rule] Error 2
make: *** [Makefile:630: bpftrace] Error 2
```

The linker `/usr/bin/ld` seems to be… the system linker?

```
ls -l `which ld`
lrwxrwxrwx 1 root root 19 Jan 21 15:23 /usr/bin/ld -> x86_64-linux-gnu-ld

ld --version
GNU ld (GNU Binutils for Ubuntu) 2.34
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public Licence version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

I build like so:

```bash
mkdir build-llvm12
cd build-llvm12
# forgive the ugly use of CXX/CC env vars; this was the only way I could find to affect the environment of the child process which compiles gtest
export CXX=g++-10 && export CC=gcc-10 && cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_REQUESTED_VERSION=12 ..
make -j5
```

those same cmake flags work fine if I set `LLVM_REQUESTED_VERSION=7` or `LLVM_REQUESTED_VERSION=8`. so my environment is otherwise known-good (i.e. GCC 10 has worked for me).

I'm on Ubuntu 20.04.2 LTS.

I installed llvm 12 [like so](https://askubuntu.com/a/1065402/718719):

```bash
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
sudo apt-get update
sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main"
sudo apt-get install llvm-12-dev llvm-12-runtime libclang-12-dev clang-12
```

I get the same result when using `export CXX=clang++-12 && export CC=clang-12`

**Comment by fbs** [comment]
What I've seen happen is that it links against the requested LLVM version but fails to link the correct clang, as you have 7 and 8 and 

```
src/clang_parser.cpp
105-#if LLVM_VERSION_MAJOR <= 7
106-  return clang_Cursor_isAnonymous(c);
107-#elif LLVM_VERSION_MAJOR >= 9
108:  return clang_Cursor_isAnonymousRecordDecl(c);
109-#else // LLVM 8
110-  if (!clang_Cursor_isAnonymous(c))
111-    return false;
```

But I've never tried to fix it, docker solves the issue for me.

There's probably a flag  like the current one we can use

```
  find_package(Clang REQUIRED)
  include_directories(SYSTEM ${CLANG_INCLUDE_DIRS})

  if(${LLVM_REQUESTED_VERSION})
    find_package(LLVM ${LLVM_REQUESTED_VERSION} REQUIRED)
  else()
    find_package(LLVM REQUIRED)
```


The guard in clang_parser is probably wrong. We should test on the clang version if possible. Or somehow force that both versions are the same.

**Comment by fbs** [comment]
`-DCMAKE_VERBOSE_MAKEFILE` might show you which libs it links against

**Comment by Birch-san** [comment]
`-DCMAKE_VERBOSE_MAKEFILE=1` creates the following makefile at: `build-llvm12/src/CMakeFiles/bpftrace.dir/build.make`

```
CMAKE_COMMAND = /usr/bin/cmake

src/bpftrace: src/CMakeFiles/bpftrace.dir/link.txt
  @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/alex/git/bpftrace/build-llvm12/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX executable bpftrace"
  cd /home/alex/git/bpftrace/build-llvm12/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/bpftrace.dir/link.txt --verbose=$(VERBOSE)
```

not very enlightening… looks like the interesting part would be `cmake_link_script`, but I dunno where that is.

===

I'm also trying to tell it to use LLVM's linker, `lld`:

```bash
# creates executable /usr/bin/ld.lld-12
sudo apt-get install lld-12
# creates symlink lld just in case that's what gcc expects to see
sudo ln -sf /usr/bin/ld.lld-12 /usr/bin/lld

export CXX=g++-10 && export CC=gcc-10 && cmake -DCMAKE_CXX_FLAGS="-fuse-ld=lld" -DCMAKE_BUILD_TYPE=Debug -DLLVM_REQUESTED_VERSION=12 ..
```

but during "Check for working CXX compiler", g++ complains:

```
collect2: fatal error: cannot find ‘ld’
```

I've also tried with Clang, and have also tried supplying full path to executable `-DCMAKE_CXX_FLAGS="-fuse-ld=/usr/bin/ld.lld-12"` (which Clang claims to support). but it proceeds to compilation and warns:

```
clang: warning: argument unused during compilation: '-fuse-ld=lld' [-Wunused-command-line-argument]
```

so, I've not succeeded in telling it which linker to use.

maybe I'm being ignored, and I have to modify this line in CMakeCache.txt:

```
CMAKE_LINKER:FILEPATH=/usr/bin/ld
```

not sure what's the idiomatic way to configure that (i.e. by command-line)…

**Comment by fbs** [comment]
> `-DCMAKE_VERBOSE_MAKEFILE=1` creates the following makefile at: `build-llvm12/src/CMakeFiles/bpftrace.dir/build.make`
> 

You're not supposed to look at the makefile, just run make

```
[ 51%] Linking CXX executable bpftrace_test
cd /home/vagrant/build/tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/bpftrace_test.dir/link.txt --verbose=1
/usr/bin/c++  -g   CMakeFiles/bpftrace_test.dir/ast.cpp.o CMakeFiles/bpftrace_test.dir/bpftrace.cpp.o CMakeFiles/bpftrace_test.dir/child.cpp.o CMakeFiles/bpftrace_test.dir/clang_parser.cpp.o CMakeFiles/bpftrace_test.dir/log.cpp.o CMakeFiles/bpftrace_test.dir/main.cpp.o CMakeFiles/bpftrace_test.dir/mocks.cpp.o CMakeFiles/bpftrace_test.dir/parser.cpp.o CMakeFiles/bpftrace_test.dir/procmon.cpp.o CMakeFiles/bpftrace_test.dir/probe.cpp.o CMakeFiles/bpftrace_test.dir/semantic_analyser.cpp.o CMakeFiles/bpftrace_test.dir/tracepoint_format_parser.cpp.o CMakeFiles/bpftrace_test.dir/utils.cpp.o CMakeFiles/bpftrace_test.dir/codegen_includes.cpp.o  -o bpftrace_test  -Wl,-rpath,/usr/lib/llvm-12/lib:/usr/lib/llvm-10/lib ../src/libbpftrace.a gtest-git-prefix/src/gtest-git-build/googlemock/gtest/libgtest.a gtest-git-prefix/src/gtest-git-build/googlemock/gtest/libgtest_main.a gtest-git-prefix/src/gtest-git-build/googlemock/libgmock.a -lpthread /usr/lib/x86_64-linux-gnu/libbfd.so /usr/lib/x86_64-linux-gnu/libopcodes.so ../src/ast/libast.a ../src/arch/libarch.a /usr/lib/llvm-12/lib/libclang-12.so.1 /usr/lib/llvm-10/lib/libLLVM-10.so.1 ../libparser.a ../resources/libresources.a /usr/lib/x86_64-linux-gnu/libbcc.so /usr/lib/x86_64-linux-gnu/libelf.so
```

I'm not sure why you're messing with the linker, the issue seems to be what you link agianst not the linker itself.

Pretty sure that everything works fine if you remove all other llvm&clang verions

**Comment by Birch-san** [comment]
ah, is this what you were looking for? the contents of `CMakeFiles/bpftrace.dir/link.txt`, as mentioned in that Makefile:

```bash
/usr/bin/g++-10  -g   CMakeFiles/bpftrace.dir/main.cpp.o  -o bpftrace  -Wl,-rpath,/usr/lib/llvm-8/lib:/usr/lib/llvm-12/lib: libbpftrace.a /usr/lib/x86_64-linux-gnu/libbfd.so /usr/lib/x86_64-linux-gnu/libopcodes.so ast/libast.a arch/libarch.a /usr/lib/llvm-8/lib/libclang-8.so.1 /usr/lib/llvm-12/lib/libLLVM-12.so.1 ../libparser.a ../resources/libresources.a /usr/lib/x86_64-linux-gnu/libbcc.so /usr/lib/x86_64-linux-gnu/libelf.so 
```

okay yeah, there's some mistakes there. mixture of LLVM 8 and 12… so yeah, changing the linker itself won't help.

====

are there any other options than removing all other LLVM & clang versions? I need LLVM 7 around in order to regenerate codegen test fixtures. but I need LLVM 12 in order to run nested struct tests. and when I tried uninstalling "unused" llvm versions, my Ubuntu lost its GUI…

**Comment by fbs** [comment]
If its a one time thing you can probably get away with editing `./src/CMakeFiles/bpftrace.dir/link.txt` to suite your needs. Just dont rerun cmake (chattr +i the file maybe).

Long term we have to investigate what I said in the first comment. See whether we can specify the clang version somehow and make sure the versions match

**Comment by Birch-san** [comment]
okay lol yeah, I was trying that as you typed it. yeah, it works! 😄 `./tests/CMakeFiles/bpftrace_test.dir/link.txt` too.

cool; definitely agree that a solution like the one in your initial comment is needed eventually.

**Comment by jordalgo** [comment]
This seems to work `nix build .#bpftrace-llvm12` so closing this issue. feel free to re-open if needed
