### ISSUE TITLE
Include manpages in the tools.tar.gz archive when released

### ISSUE THREAD

**Issue by NoSuchCommand** [iovisor/bpftrace#1793]
I see that the latest release of bpftrace on GitHub provides a `tools.tar.gz` asset, which includes the tools themselves, their `_examples.txt` (basically, the `tools` subdir and its contents) but not the `man` subdir of the project. 

### Is your feature request related to a problem? Please describe.

When installing bpftrace from the GitHub release assets on a system for which a proper official package does not exist (e.g. Ubuntu Bionic), downloading the `tools.tar.gz` is not sufficient to benefit from the (very well written) manpages. Further actions must be taken to get them from the repository, but this can be cumbersome to automate.

### Describe the solution you'd like

Include the `man` subdirectory of the project in the `tools.tar.gz` asset when released, or provide a separate `man.tar.gz` asset.

**Comment by fbs** [comment]
Yes good idea, let's fix that :)

**Comment by jordalgo** [comment]
Seems like man.tar.gz is now included: https://github.com/iovisor/bpftrace/releases/tag/v0.19.1
