### ISSUE TITLE
Example given to list probes given containing "sleep" no longer works unless provider is accounted for

### ISSUE THREAD

**Issue by sevan** [iovisor/bpftrace#1794]
https://github.com/iovisor/bpftrace/blob/e2fb442afa2cad12f6138976c3a26370e48b9123/src/main.cpp#L98

`-su-5.1# bpftrace -l '*sleep*'`  
`stdin:1:1-8: ERROR: No probe type matched for *sleep*`
`*sleep*`
`~~~~~~~`

If a wildcard for the provider is specified, it works as expected
`-su-5.1# bpftrace -l '*:*sleep*'|wc -l`
`86`

`bpftrace -l '*sleep*'` works ok on v0.11.4 but not v0.12.0 or .1, I don't know if that's expected and the examples should be updated or a regression, hence raising an issue and not a pull request.

**Comment by sevan** [comment]
I've confirmed the issue is present on a stock Ubuntu 20.04 install. In both cases I was using the prebuilt bpftrace binary offered here.

**Comment by danobi** [comment]
Hi @sevan, thanks for the report. This issue was fixed in https://github.com/iovisor/bpftrace/commit/b7fd0900b18c4b640926e0bb830464565a527ca1 (not yet released)
