### ISSUE TITLE
missing kretprobe on nfsd_dispatch

### ISSUE THREAD

**Issue by vishnuitta** [iovisor/bpftrace#1811]
### What reproduces the bug?
Below is the code snippet to track the number of entries and exits of nfsd_dispatch function.
```
kprobe:nfsd_dispatch {
        @enters[0] = count();
}

kretprobe:nfsd_dispatch {
        @enters[1] = count();
}

interval:s:1 {
        print(@enters);
}
```

When I copy data to the nfs mountpoint, below is the output:
```
@enters[0]: 3
@enters[1]: 3

@enters[0]: 3
@enters[1]: 3

@enters[1]: 62
@enters[0]: 212

@enters[1]: 73
@enters[0]: 346

@enters[1]: 89
@enters[0]: 408

@enters[1]: 91
@enters[0]: 410

@enters[1]: 91
@enters[0]: 410

@enters[1]: 91
@enters[0]: 410

@enters[1]: 91
@enters[0]: 410
```
It clearly shows that return probes are missed.

### bpftrace --info
Kernel version is 4.15.0-137 on x86_64
```
Build
  version: v0.10.0
  LLVM: 8
  foreach_sym: yes
  unsafe uprobe: no
  btf: no
  bfd: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes

Kernel features
  Instruction limit: -1
  Loop support: no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: no
  tracepoint: yes
  perf_event: yes
```

Please help if anything is missing in the code snippet.

**Comment by fbs** [comment]
I think #835 is related to this

**Comment by vishnuitta** [comment]
> I think #835 is related to this

thanks for info @fbs
One question I have: (sorry if being naive here). Will there be same issue with 'bcc' tool as well? Trying to understand whether issue is in the libraries/modules related to bpftrace.

**Comment by vishnuitta** [comment]
> > I think #835 is related to this
> 
> thanks for info @fbs
> One question I have: (sorry if being naive here). Will there be same issue with 'bcc' tool as well? Trying to understand whether issue is in the libraries/modules related to bpftrace.

I tried quickly with 'bcc', and found the same issue with that tool as well. So, root cause seems to be at kernel as pointed out in that issue.

**Comment by vishnuitta** [comment]
closing this as it is duplicate of #835
