### ISSUE TITLE
Access kernel global variables

### ISSUE THREAD

**Issue by vishnuitta** [iovisor/bpftrace#1813]
### Is your feature request related to a problem? Please describe.
Accessing OS variables would be useful for observability/monitoring of applications. It would be great if bpftrace can provide this feature.
For example, accessing 'nfsdstats' can be useful for monitoring.

### Describe the solution you'd like
'dtrace' provides similar functionality with backquote '`' (https://illumos.org/books/dtrace/chp-variables.html#chp-variables-6).

**Comment by danobi** [comment]
Yes, this sounds useful. I wonder if this will require kernel support or if we can the symbol location from debuginfo or symbol table.

**Comment by fbs** [comment]
We already support something similar through `kaddr`, see tools/loads.bt.  might just work here too

```
# grep nfsdstat /proc/kallsyms
ffffffffc076e5c0 b nfsdstats	[nfsd]
```

**Comment by danobi** [comment]
Ah right, forgot about that.

**Comment by vishnuitta** [comment]
Thanks @fbs . This is really helpful. Also, got to learn that I need to set /proc/sys/kernel/kptr_restrict to 1.
