### ISSUE TITLE
Create a clang-format config

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#182]
Is there any interest in commititng a [clang-format config][0]? Most big projects have one to enforce a consistent coding style.

[0]: https://clang.llvm.org/docs/ClangFormat.html

**Comment by brendangregg** [comment]
I haven't used that, but yes, it would be nice to have a tool to check for consistent style (can it be used to verify and throw warnings?). It would be ideal if it could be based on something close to @ajor 's style (eg, 2 character space indent) to minimize the amount of change we need to do to the existing codebase.

**Comment by danobi** [comment]
Yeah, I think we can play around with it and see which settings cause the least churn. It not only checks style, but can do in-place modifications of source files to match the configured style. Most projects add a automatic build job that errors out if there's a delta between the submitted patch and the clang-formatted patch.

**Comment by mmarchini** [comment]
Sounds good to me. We use clang-format on llnode (V8 also uses it) and it decreases the number of nit comments on PRs about coding style as well as enforces one style on the entire code base :)
