### ISSUE TITLE
Some tools don't work without kernel-devel package when the kernel is build with ikheaders and BTF

### ISSUE THREAD

**Issue by jeromemarchand** [iovisor/bpftrace#1820]
### What reproduces the bug?

biosnoop.bt, dcsnoop.bt, mdflush.bt, runqlat.bt, tcpaccept.bt, tcpconnect.bt, rcpdrop.bt and tcpretrans.bt won't work when no kernel-devel package is installed, even though the kernel is build with CONFIG_IKHEADERS=m.
Ever since commit 17bbcd2b0773 ("kheader: Do not unpack kheaders if system has BTF"), we skip unpacking kheaders when BTF is available, but it seems those tools rely on data present in kheaders and not BTF. Reverting commit 17bbcd2b0773 fixes the issue.

Note that for some tools like biosnoop.bt, it just a matter of not finding the header file and removing the  #include line fixes the issue.
```
# /usr/share/bpftrace/tools/biosnoop.bt
definitions.h:2:10: fatal error: 'linux/blkdev.h' file not found
```

For other like dcsnoop.bt, it's complaining about incomplete type:
```
# /usr/share/bpftrace/tools/dcsnoop.bt 
definitions.h:5:25: error: field has incomplete type 'struct path'
definitions.h:5:16: note: forward declaration of 'struct path'
definitions.h:6:25: error: field has incomplete type 'struct qstr'
definitions.h:6:16: note: forward declaration of 'struct qstr'
```

### bpftrace --info
System
  OS: Linux 4.18.0-304.3.el8.bz1928463.x86_64 #1 SMP Wed Apr 14 11:46:12 EDT 2021
  Arch: x86_64

Build
  version: v0.12.1
  LLVM: 11.0.0
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: no
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): yes
  map batch (depends on Build:libbpf): yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes

**Comment by danobi** [comment]
Thanks for the report.

I think the best move is to fix the tools to rely on BTF instead of header files. Many distros already ship kernels with BTF (see https://github.com/libbpf/libbpf#bpf-co-re-compile-once--run-everywhere ). Parsing and dealing with header files is nasty business and not even guaranteed to work correctly (how to handle ifdefs?).

**Comment by jeromemarchand** [comment]
> Thanks for the report.
> 
> I think the best move is to fix the tools to rely on BTF instead of header files. Many distros already ship kernels with BTF (see https://github.com/libbpf/libbpf#bpf-co-re-compile-once--run-everywhere ). Parsing and dealing with header files is nasty business and not even guaranteed to work correctly (how to handle ifdefs?).

I've tried that, but that breaks some CI checks. I don't see how to make those tool work both on kernel with and without BTF support.
