### ISSUE TITLE
opensnoop.bt: no open syscall on aarch64

### ISSUE THREAD

**Issue by martinetd** [iovisor/bpftrace#1838]
### What reproduces the bug?

On aarch64, opensnoop fails to run:
```
# uname -m
aarch64
# opensnoop.bt -b
/tmp/opensnoop.bt:22-24: ERROR: tracepoint not found: syscalls:sys_enter_ope
```

That is because aarch64 has no open syscall, as a new arch they only implement the openat* variants, so there will obviously be no associated tracepoint. See iovisor/bcc#3344 for discussions around the libbpf-tools variant of opensnoop, where probe loading will likely be disabled based on arch.

Removing sys_enter/exit_open tracepoints from opensnoop.bt obviously works but I'm curious if bpftrace has a way to handle that kind of things gracefully, or if we'd have to fall back to things like cmake generating an appropriate opensnoop.bt based on target arch? which isn't exactly pretty...

(Bonus question, I didn't take the time to try yet but if someone knows -- arm32 has an open syscall and aarch64 has 32bit emulation, so it should be possible to run a 32bit program that actually uses open there. How will it show up in tracepoints? Looking at the code it should go through `COMPAT_SYSCALL_DEFINE3(open...` which just calls `do_sys_open` which doesn't seem to go through any tracepoint unlike the SYSCALL_DEFINEx, so there will just not be caught?)

### bpftrace --info
```
System
  OS: Linux 5.4.47-1-at #2-Alpine SMP PREEMPT Fri May 7 00:27:04 UTC 2021
  Arch: aarch64

Build
  version: v0.11.3
  LLVM: 11
  foreach_sym: yes
  unsafe uprobe: no
  bfd: no
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
```

**Comment by fbs** [comment]
We don't really have a solution for it. As script go through the C pre processor you might be able to do some #ifdef magic although thats a bit hacky.

I guess having an easy way to do arch dependent things could be useful, although I don't see a lot of usecases yet.

Or maybe we can expand the probe name matching. If you could write something like `tracepoint:syscalls:sys_enter_open(at)? {}` . The current wildcard matching only runs on probes that it finds, so thats what you want. The only issue is that `sys_enter_open*` matches too much, so basic regex support might be good

**Comment by martinetd** [comment]
pattern matching is elegant, I like it! But there's also the problem of not having any match, or if e.g. sys_enter_open's probe and sys_enter_openat probe contents would become different you'd need to split it in two sections and in that case the sys_enter_open probe would have code but no associated entry point, which currently errors out.

What I had suggested early in the libbpf case was to just make a probe optional, for bpftrace that would be some syntax like `tracepoint:syscalls:sys_enter_open? { ... }` that hint that if the probe isn't found it's ok to just continue - since we list available probes for pattern matching we can check if the name exists and act on it so that should be possible. (would need a syntax different from `?` if we ever have basic regex support)

**Comment by jordalgo** [comment]
Closing for now. Feel free to re-open a new issue/RFC to discuss the possible new syntax or create a PR.
