### ISSUE TITLE
CMake option for not using ExternalProject

### ISSUE THREAD

**Issue by rvl** [iovisor/bpftrace#184]
Would it be possible to add an option to the CMake build so that gtest and bcc can be integrated in the "normal" way, rather than downloaded through ExternalProject? By the "normal" way I mean `find_library(LIBGTEST "gtest")` and `pkg_check_modules(BCC libbcc)`. Cheers.

**Comment by ajor** [comment]
See #161 for discussion on how we want to do this

**Comment by brendangregg** [comment]
#161 is for git submodules (right?)

I'm not an expert in packaging, but I'd guess there was value in also supporting a way to use bcc from a previously installed and packaged bcc (just like the bpftrace build uses a bunch of other things, like cmake, flex, bison, llvm, etc, which it's using via packages).

**Comment by ajor** [comment]
The first comment was suggesting submodules, but there is also talk about using installed packages later on. I do think that'd be a good idea
