### ISSUE TITLE
Create builder images on quay

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#1851]
Right now we're still building CI images from scratch every time. We take the base image (either llvm or plain ubuntu), install stuff and then build and test bpftrace. Build failures due to ubuntu mirrors happen quite often and building the same versions of bcc/libbpf every time is a resource waste as well. Creating a weekly updating image should speedup the CI quite a bit.

**Comment by fbs** [comment]
https://quay.io/repository/iovisor/bpftrace-ci?tab=tags repo

**Comment by fbs** [comment]
https://github.com/iovisor/bpftrace/tree/cache_ci

**Comment by jordalgo** [comment]
Are we still planning on doing this?

**Comment by viktormalik** [comment]
We're not using builder images anymore, instead we use Nix. The Dockerfiles in `docker/` now only serve as "instructions" on how to build bpftrace on various repos.
