### ISSUE TITLE
bpftrace Docker container: Permission denied

### ISSUE THREAD

**Issue by g0194776** [iovisor/bpftrace#1859]
Hi guys,

bpftrace Docker image `CAN NOT` run as well properly. 

I just followed the official guideline [here](https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#docker-images) to run a Docker container in my VM, error output:

```bash
[root@worker1 vagrant]# docker run -ti -v /usr/src:/usr/src:ro \
>        -v /lib/modules/:/lib/modules:ro \
>        -v /sys/kernel/debug/:/sys/kernel/debug:rw \
>        --net=host --pid=host --privileged \
>        quay.io/iovisor/bpftrace:latest \
>        tcplife.bt
ERROR: failed to create map: '@birth': Permission denied
ERROR: failed to create map: '@skcomm': Permission denied
ERROR: failed to create map: '@skpid': Permission denied
ERROR: failed to create printf map: Permission denied
Creation of the required BPF maps has failed.
Make sure you have all the required permissions and are not confined (e.g. like
snapcraft does). `dmesg` will likely have useful output for further troubleshooting
```
- System Information

```bash
[root@worker1 vagrant]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

[root@worker1 vagrant]# uname -r
4.19.12-1.el7.elrepo.x86_64
```

And, **I've installed kernel headers.**

Is there anyone can help me debug it?

Thanks.

**Comment by danobi** [comment]
This looks like a permission issue. Do you have anything SELinux policies enabled? Without access to your system I can only guess.

**Comment by g0194776** [comment]
> This looks like a permission issue. Do you have any SELinux policies enabled? Without access to your system I can only guess.

@danobi Thanks, You are right. It works after I executed `setenforce 0` command.
