### ISSUE TITLE
bpftrace type casting problem

### ISSUE THREAD

**Issue by marywangran** [iovisor/bpftrace#1869]
I wrote a bpftrace script as below:

```
#!/usr/local/bin/bpftrace

#include <net/neighbour.h>

k:___neigh_create
{
	$tbl = (struct neigh_table *)arg0;
	$va1 = (uint64)$tbl->gc_thresh1;
	$va2 = (uint64)$tbl->gc_entries;
	printf("aaa: %lx  %lx \n", $va1, $va2);
}
```

I want to take the values of gc_thresh1 and gc_entries of arp_tbl, where gc_entries1 is correct, but when I print gc_entries, I get the address of gc_entries instead of the value.

Looking at the bytecode, the results are as follows:

```
\# bpftool prog dump xlated id 53
0: (bf) r6 = r1
1: (79) r7 = *(u64 *)(r6 +112)
2: (bf) r3 = r7
3: (07) r3 += 244
4: (bf) r1 = r10
5: (07) r1 += -24
6: (b7) r2 = 4
7: (85) call bpf_probe_read#-52880
8: (61) r1 = *(u32 *)(r10 -24)
9: (67) r1 <<= 32
10: (c7) r1 s>>= 32
11: (7b) *(u64 *)(r10 -16) = r1
12: (07) r7 += 420          # Locate offset to gc_entries here
13: (7b) *(u64 *)(r10-8) = r7 # Assignment of the result
14: (b7) r1 = 0
15: (7b) *(u64 *)(r10 -24) = r1
```

In my opinion, C does not allow casts between compound types and primitive types, so it is better to report an error when this is done:
error: aggregate value used where an integer was expected
Instead of giving an address out of nowhere.

```
bpftrace --info

System
  OS: Linux 5.4.56.XXX
  Arch: x86_64

Build
  version: XXX-v0.11.3
  LLVM: 7
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: no
  libbpf: no
  libbpf btf dump: no
  libbpf btf dump type decl: no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
```

**Comment by fbs** [comment]
Looks like we're failing to emit a probe_read here for some reason which causes the address to be printed instead of the value. Thats quite bad.

**Comment by fbs** [comment]
Oh I see what you mean, my bad. I thought atomic_t was an int but it's a struct:

```
typedef struct {
	int counter;
} atomic_t;
```

So we skip the deref to avoid reading a lot of data onto the stack. `$va2` is actually a `atomic_t *`

I think a warning would be appropriate here.

**Comment by viktormalik** [comment]
Yeah, exactly, since `gc_entries` is a struct, we just store its pointer in `$va2` to avoid copying large structs to the stack. The actual reading is done later when accessing a field or printing the entire struct. The problem here is that the cast to `uint64` makes us loose the type information.

I think that we should forbid casting structs to ints (AFAIK, C doesn't allow this either) and emit en error here. I'll post a fix for this.

**Comment by danobi** [comment]
> I think that we should forbid casting structs to ints (AFAIK, C doesn't allow this either) and emit en error here. I'll post a fix for this.

+1
