### ISSUE TITLE
[RFC]  Support to compile the BPF-bytecode in one host and load it on other hosts

### ISSUE THREAD

**Issue by liuhangbin** [iovisor/bpftrace#1902]
Some user/customer refuse/can't install compilers on production environment.
Sometimes bpftrace may also broke with incompatible llvm version, e.g. [issue #1305](https://github.com/iovisor/bpftrace/issues/1305)

While systemtap worked around by allowing the build to happen on a different system.

So how about add bpftrace support to compile the  BPF-bytecode in one host and load it on other hosts?

Thanks
Hangbin

**Comment by viktormalik** [comment]
If I understand you correctly, this is exactly what Ahead-Of-Time compiled bpftrace programs should allow. It's currently work in progress, more details [here](https://dxuuu.xyz/aot-bpftrace.html).

**Comment by liuhangbin** [comment]
Yes, it is. Thanks a lot for your works.

**Comment by danobi** [comment]
Yep, I'm currently working on it. I expect AOT will work for simple scripts soon (~1 month of work left). But for full feature support I expect it'll take 1-2 years. There's a long tail of tricky problems to deal with.
