### ISSUE TITLE
guide instructions for listing available uprobes miss "ifuncs"

### ISSUE THREAD

**Issue by scottlamb** [iovisor/bpftrace#1904]
### What reproduces the bug?

The guide [says](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#3-uprobeuretprobe-dynamic-tracing-user-level):
> To list available uprobes, you can use any program to list the text segment symbols from a binary, such as `objdump` and `nm`. For example:
> ```
> # objdump -tT /bin/bash | grep readline
> ```

but this doesn't actually list all the valid probe points. In particular I found via `perf` that a bunch of my CPU was going into `__memmove_avx_unaligned_erms`. `objtool -tT` doesn't show this function:

```
$ objdump -tT /lib/x86_64-linux-gnu/libc-2.32.so | fgrep memmove
00000000001275d0 g   iD  .text	00000000000000c1  GLIBC_2.3.4 __memmove_chk
00000000001288d0 g    DF .text	0000000000000021  GLIBC_2.4   __wmemmove_chk
000000000009d1f0 g   iD  .text	00000000000000c1  GLIBC_2.2.5 memmove
00000000000b9210  w   DF .text	000000000000000d  GLIBC_2.2.5 wmemmove
```

but it apparently is a valid trace point, eg I can do this and get a bunch of results:

```
sudo bpftrace -e 'uprobe:/lib/x86_64-linux-gnu/libc-2.32.so:__memmove_avx_unaligned_erms { @bytes = hist(arg2); }'
```

If I switch that out to plain `memmove`, I see (almost?) nothing.

From a quick skim of glibc source code, I see that this is an ["IFUNC"](https://sourceware.org/glibc/wiki/GNU_IFUNC): an indirect function selected at runtime (during dynamic loading, I think? presumably based on my CPU supporting AVX).

I'd like the guide to say how to list *all* valid probe points.

(It'd also be really nice if I could just add a probe for "memmove" and have it run on all the possible ifuncs for that function, but I imagine that's much harder than coming up with a correct description of how it works today.)

### bpftrace --info
```
System
  OS: Linux 5.8.0-53-generic #60-Ubuntu SMP Thu May 6 07:46:32 UTC 2021
  Arch: x86_64

Build
  version: v0.11.0
  LLVM: 9
  foreach_sym: yes
  unsafe uprobe: no
  bfd: no
  bpf_attach_kfunc: no
  bcc_usdt_addsem: no
  libbpf: no
  libbpf btf dump: no
  libbpf btf dump type decl: no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
```

**Comment by fbs** [comment]
do they show up in `bpftrace -l uprobe:/lib/x86_64-linux-gnu/libc-2.32.so:*`?

**Comment by scottlamb** [comment]
Yes, they do! Thanks!

(Sorry, I missed the notification you'd replied.)

**Comment by fbs** [comment]
@scottlamb so this can be closed? :)
