### ISSUE TITLE
bpftrace can't open script file

### ISSUE THREAD

**Issue by wangjinnana** [iovisor/bpftrace#1907]
### What reproduces the bug?
#cat sleepers
tracepoint:syscalls:sys_enter_nanosleep
{
  printf("%s is sleeping.\n", comm);
}

#bpftrace sleepers
got
**ERROR: failed to open file 'sleepers': No such file or directory**

#bpftrace ./sleepers
got
**ERROR: failed to open file 'sleepers': No such file or directory**

#bpftrace - <sleepers
got
Attaching 1 probe...
qemu-ga is sleeping.
qemu-ga is sleeping.
^C

expect **bpftrace sleepers act as bpftrace - <sleepers**

### bpftrace --info

System
  OS: Linux 4.15.0-42-generic #46~16.04.1+4 SMP Fri Mar 22 11:56:34 +08 2019
  Arch: x86_64

Build
  version: v0.12.0-22-g2c7a7
  LLVM: 7.0.0
  foreach_sym: no
  unsafe uprobe: no
  bfd: no
  bpf_attach_kfunc: no
  bcc_usdt_addsem: no
  bcc bpf_attach_uprobe refcount: no
  libbpf: no
  libbpf btf dump: no
  libbpf btf dump type decl: no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: no
  send_signal: no
  override_return: no
  get_boot_ns: no
  dpath: no

Kernel features
  Instruction limit: -1
  Loop support: no
  btf (depends on Build:libbpf): no
  map batch (depends on Build:libbpf): no
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
  iter:task: no
  iter:task_file: no

**Comment by danobi** [comment]
How did you install bpftrace? Snapcraft?

**Comment by wangjinnana** [comment]
> How did you install bpftrace? Snapcraft?

I installed bpftrace by 
sudo snap install --devmode bpftrace
sudo snap connect bpftrace:system-trace

**Comment by wangjinnana** [comment]
from https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#ubuntu-packages

**Comment by danobi** [comment]
That's interesting. If I had to guess, it'd be a permission issue. Maybe the snap cannot access your files. I would say it's rather unlikely it's a bpftrace issue b/c we have a lot of tests that exercise reading from a file.

**Comment by fbs** [comment]
I can recommend using the static binary over snapcraft. Snap just has too many restrictions that keep on blocking us in one way or another. You can find the latest release build here: https://github.com/iovisor/bpftrace/releases/tag/v0.13.0 .

Removed the bug label as we don't control the snapcraft package.

We should probably just remove it from the docs

**Comment by danobi** [comment]
> We should probably just remove it from the docs
 +1

**Comment by wangjinnana** [comment]
when i install bpftrace by apt-get install bpftrace, run bpftrace sleepers success
