### ISSUE TITLE
Ubuntu 18.04 Kernel 4.14 does not output bpftrace one-liner commands

### ISSUE THREAD

**Issue by divija95** [iovisor/bpftrace#1934]
I am trying to run biolatency (tried with 2016 version as well). Here's the output I get:
````
root@node1:/home/ngd/bcc# python biolatency.py -mT 10
Tracing block device I/O... Hit Ctrl-C to end.

10:56:10

10:56:20

10:56:30

10:56:40

10:56:50

10:57:00
^C
````
While, ext4dist works fine:
````
root@node1:/home/ngd/bcc# ./bcc/tools/ext4dist.py
Tracing ext4 operation latency... Hit Ctrl-C to end.
^C

operation = write
     usecs               : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 0        |                                        |
         8 -> 15         : 0        |                                        |
        16 -> 31         : 0        |                                        |
        32 -> 63         : 6        |****************************************|
````

**Comment by fbs** [comment]
you're using a bcc tool, not a bpftrace oneliner, or did you paste the wrong snippet?

Are you actually doing blockio?

**Comment by divija95** [comment]
My bad. Yes, I am running bcc tools.
What do you mean by if I am actually doing blockio?

**Comment by fbs** [comment]
is the kernel actually doing blockio when you measure?

Do you have the same issue with the bpftrace version of biolatency?

**Comment by divija95** [comment]
Actually, bpftrace version's biolatency is working. Is it fair to compare bio latency of a host with Linux kernel 5.4 to a machine with Linux kernel 4.14?

**Comment by viktormalik** [comment]
The kernel version may be an issue, but more important is whether the kernel is actually doing the operation that you're tracing (blockio).

Anyway, closing this as stale.
