### ISSUE TITLE
Ubuntu 18.04 (bionic) & minimum cmake version

### ISSUE THREAD

**Issue by hadret** [iovisor/bpftrace#1939]
Hi 👋🏻

I'm building bcc and bpftrace basing it off of official Ubuntu/Debian packages. I'm also trying not to depend on external repositories so that I can ensure no additional dependencies on different PPAs are necessary. That's the reason why I'm building bpftrace against LLVM 9 (version 10 is available but not patched and has this "Polly issue") with cmake version 3.10.2-1ubuntu2.18.04.2 -- cause these are working and are available in the official repositories. Today on my first attempt of building bpftrace 0.13.0 for Ubuntu 18.04 I got this message:

```
CMake 3.13.0 or higher is required.  You are running version 3.10.2
```

The only way to have 3.13 on 18.04 would be to use external PPA -- which I'd rather not do. I would still like to support bionic, as it's still officially supported and widely used LTS release. For now I patched the CMakeLists.txt like so:

```
--- bpftrace-0.13.0.orig/CMakeLists.txt
+++ bpftrace-0.13.0/CMakeLists.txt
@@ -1,4 +1,4 @@
-cmake_minimum_required(VERSION 3.13.0)
+cmake_minimum_required(VERSION 3.10.2)
 project(bpftrace)
```

I'm still before testing it, but it did build just fine -- is there anything really required for the build to succeed that is available in 3.13+ but isn't in 3.10? Or this should be fine when building it with LLVM 9?

Having this opportunity -- many thanks for awesome software! 🙌🏻

**Comment by fbs** [comment]
We bumped it in e053e43138943ebfcbc863046f340feb6d23af12 but going back to 10 is not an issue for your use case.

Due to #1305 using LLVM9 is not recommended. Maybe you can use the static build we provide and package that instead. Its based on ubuntu-18.04 but it comes with LLVM12 and a new libbpf and bcc. You can download it from the releases or extract the master builds from quay.io/iovisor/bpftrace, see the INSTALL.md doc

**Comment by hadret** [comment]
@fbs many thanks for fast reply. I now better understand why building against LLVM12 is the best option here. I think what I'll do is to backport LLVM12 for bionic to Launchpad and then build packages against it this way. I'd still prefer to have reproducible builds that are roughly the same as for the newer OS versions.
