### ISSUE TITLE
formated the key value of Associative Arrays

### ISSUE THREAD

**Issue by b-ripper** [iovisor/bpftrace#1944]
<!--
ex. I want to trace the mem leak like this:
```
xxxxxx:create
{
    @alloc_buf[mem_addr, mem_type, mem_size] = (pid, mem_addr, mem_type, mem_size);
}

xxxxxx:destroy
{
    delete(@alloc_buf[mem_addr, mem_type, mem_size]);
}

-->

### Is your feature request related to a problem? Please describe.
<!--
Place description here
-->

I want to trace the mem leak like this:
```
xxxxxx:create
{
    @alloc_buf[mem_addr, mem_type, mem_size] = (pid, mem_addr, mem_type, mem_size);
}

xxxxxx:destroy
{
    delete(@alloc_buf[mem_addr, mem_type, mem_size]);
}
```
The map was printed after the Ctrl-C to end the program, like this:
```
@alloc_buf[274887397376, 6, 6316032] = (934, 274887397376, 6, 6316032);
... ...
```

### Describe the solution you'd like
<!--
Place description here
-->
I want the address in the map output like 0xXXXXX:
```
@alloc_buf[0x400090D000, 6, 6316032] = (934, 0x400090D000, 6, 6316032);
```


### Describe alternative solutions or features you've considered
<!--
Place description here
-->

**Comment by fbs** [comment]
+1, our output options are still limited and often require ugly shell pipelines

I was looking at implementing type hints for variables / maps so we can pre-define them and document them in the pre-amble

```
// @bananas holds yellow things
let @bananas : [uint64, str] -> Count

BEGIN {
   $bread : uint32 = 0;
}
```

Which is a different issue but I'd be nice if we can extend that to define metadata for a map.

Python has the __str__ and __repr__ magic methods, but that feels clunky and not in the way.

While rust itself has a Display trait to handle it it also has a nice attribute syntax which we might be able to steal: https://doc.rust-lang.org/rust-by-example/attribute.html

So we could write something like (which only works if we can pre-define types)

```
#[format("%x %s", "%lu")]
let @bananas : [uint64, str] -> Count
```

A more trait/python like solution might be

```
metadata:@bananas {
  keyformat = "%x %s";
  valueformat = "%lu";
}
```

Or we could overload print, but then you'd always need a END probe.

@danobi @viktormalik

**Comment by viktormalik** [comment]
AFAIK, we should be properly formatting pointers if used in map keys. @b-ripper which bpftrace you're using? Could you perhaps post a complete minimal example?

@fbs I like the idea of letting the user define the intended variable type. It'd make bpftrace programs more readable and their debugging much easier.

**Comment by b-ripper** [comment]
@viktormalik  @fbs  thanks for your response！

I use the bpftrace v0.11.0-324-g691c5 on android platform.

I think an minimal example could be like this:
```
uretprobe:/apex/com.android.runtime/lib64/bionic/libc.so:malloc
{
    printf("malloc C %p\n", retval);
    @tobefreedbuf[retval] = (comm, uid);
}

uprobe:/apex/com.android.runtime/lib64/bionic/libc.so:free
{
    printf("free D %p\n", arg0);
    delete(@tobefreedbuf[arg0]);
}
```
I wonder if this way is better, add the redefined format type when saved:
```
@tobefreedbuf[(formated type)retval] = (comm, uid);
```

**Comment by fbs** [comment]
> @fbs I like the idea of letting the user define the intended variable type. It'd make bpftrace programs more readable and their debugging much easier.

Ill write up a little rfc with my idea. Working on fixing the last R/R conflicts in the parser and this would be a good test to see if it is still extendable.




> @viktormalik @fbs thanks for your response！
> 
> 
> I wonder if this way is better, add the redefined format type when saved:
> 
> ```
> @tobefreedbuf[(formated type)retval] = (comm, uid);
> ```

Not sure how this works we already have typecasts in the lang. Or do you want to specify a format string this way?

**Comment by b-ripper** [comment]
@fbs  I just think it's good for use, please ignore my idea.

**Comment by viktormalik** [comment]
> I wonder if this way is better, add the redefined format type when saved:
> 
> ```
> @tobefreedbuf[(formated type)retval] = (comm, uid);
> ```

Yes, this should help, if you typecast `retval` to a pointer. For your case:

```
@tobefreedbuf[(uint64 *)retval] = (comm, uid);
```

Then, the map key should be properly formatted.

**Comment by b-ripper** [comment]
@viktormalik  very thanks!

**Comment by viktormalik** [comment]
I believe that we can close this. We have other issues for tracking type hints extensions.
