### ISSUE TITLE
strncmp length parameter uses positional parameter's index instead of its value

### ISSUE THREAD

**Issue by j0057** [iovisor/bpftrace#1980]
When using a positional parameter as the length argument to the strncmp function, the positional parameter's index is used instead of its value.

### What reproduces the bug?

This should detect a difference between $1 and $2, but compares only the first 3 characters, so returns 0 when it should return 1:

    # bpftrace -e 'BEGIN {printf("%d\n", strncmp(str($1), str($2), $3)); exit() }' -- aaaa aaab 4
    Attaching 1 probe...
    0

This should detect no difference between the first three characters in $1 and $2, but returns 1 when it should return 0:

    # bpftrace -e 'BEGIN {printf("%d\n", strncmp(str($1), str($2), $4)); exit() }' -- aaaa aaab x 3
    Attaching 1 probe...
    1

### bpftrace --info

```
System
  OS: Linux 5.13.12-arch1-1 #1 SMP PREEMPT Wed, 18 Aug 2021 20:49:03 +0000
  Arch: x86_64

Build
  version: v0.13.0
  LLVM: 12.0.1
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  libbpf: yes
  libbpf btf dump: no
  libbpf btf dump type decl: no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): no
  map batch (depends on Build:libbpf): yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes```

**Comment by viktormalik** [comment]
Hi @j0057, thanks for reporting this!

The problem is due to missing support for usage of positional parameters in function calls. I'm working on a fix, should be ready soon.
