### ISSUE TITLE
Tools examples does not start some tools correctly

### ISSUE THREAD

**Issue by JorgenRask** [iovisor/bpftrace#200]
The example text for some of the tools does not have "bpftrace " in front of the tool bt-file, so it looks like the bt-file is directly executable. This is the case for these tools:
  biolatency.bt
  capable.bt
  cpuwalk.bt
  dcsnoop.bt
  ./mdflush.bt
  pidpersec.bt
  runqlen.bt 
  xfsdist.bt

The tools should be run like this:
  bpftrace biolatency.bt
  bpftrace capable.bt
  bpftrace cpuwalk.bt
  bpftrace dcsnoop.bt
  bpftrace mdflush.bt
  bpftrace pidpersec.bt
  bpftrace runqlen.bt 
  bpftrace xfsdist.bt

**Comment by brendangregg** [comment]
We'll fix #17 first, and then update all the examples to ensure they don't have bpftrace (although it doesn't matter if they do).

**Comment by brendangregg** [comment]
I took a quick look at #17 and added a starting point diff. Maybe you or someone would like to finish it? :-)

**Comment by JorgenRask** [comment]
I'm afraid that's a little too daunting for me :-)
I just struggled a little trying to understand how to use the examples...

**Comment by ajor** [comment]
All tools are directly executable now - closing
