### ISSUE TITLE
The printed representation of a buf() contains non-hexadecimal characters/values

### ISSUE THREAD

**Issue by barathrm** [iovisor/bpftrace#2009]
This may be a daft question or a misunderstanding on my point, but the `buf()` function's printed representation seems to behave in an unexpected way. Please correct me if I'm missing something and I apologize if I've overlooked something.

Printing the `buf()` of a uuid gets me `\x14\xfd\xc8\x16\xb4\xe5K!\xaa\x11\x85\xc2\x09\x99\x87\x0d` where I would've expected to get `\x14\xfd\xc8\x16\xb4\xe5\x4b\x21\xaa\x11\x85\xc2\x09\x99\x87\x0d`.

Ie. the documentation says that buf `Returns a hex-formatted string of the data pointed to by d that is safe to print.`. is `\xe5K!` a hex-value? It's safe to print, but... am I misunderstanding something?

### What reproduces the bug?
The following bpftrace snippet with the following c++ code, where the bpftrace snippet is attempting to print a uuid using the bpftrace `buf()` function as well as printing it manually as a comparison.

```
usdt:./uuid:category:name {
    @uuid_buf = buf((uint8*)arg0, 16);
    printf("uuid as buf: %r \n", @uuid_buf);

    // Manually printing the uuid
    printf("Manually-printed uuid: ");
    $i = 0;
    while ($i < 16)
    {
        $num = (uint8)(*(arg0 + (uint64)$i));
        if($num < 10)
        {
            printf("0%x", $num);

        }
        else
        {
            printf("%x", $num);
        }
        if($i > 0 && ($i == 3 || $i == 5 || $i == 7 || $i == 9))
        {
            printf("-");
        }
        $i++;
    }
    printf("\n");
}
```

Compiled with `clang++  uuid.cpp -o uuid`. 

```cpp
#include <unistd.h>
#include <sys/sdt.h>

int main()
{
  // 14fdc816-b4e5-4b21-aa11-85c20999870d
  const unsigned char uuid[] = {0x14, 0xfd, 0xc8, 0x16, 0xb4, 0xe5, 0x4b, 0x21, 0xaa, 0x11, 0x85, 0xc2, 0x09, 0x99, 0x87, 0x0d};
  while(true)
  {
    sleep(1);
    DTRACE_PROBE1(category, name, uuid);
  }
}
```

And the bpftrace output with uuid running in the background:

```
$ sudo bpftrace -v trace.bt
INFO: node count: 72
Attaching 1 probe...

Program ID: 92

The verifier log:
processed 1342 insns (limit 1000000) max_states_per_insn 7 total_states 36 peak_states 27 mark_read
10

Running...
uuid as buf: \x14\xfd\xc8\x16\xb4\xe5K!\xaa\x11\x85\xc2\x09\x99\x87\x0d
Manually-printed uuid: 14fdc816-b4e5-4b21-aa11-85c2099987d
```

The printed `buf()` return value stats divering from the actual bytes after `0xb4`, with the next value being `0xe5K!`. What's going on here?

### bpftrace --info
```
System
  OS: Linux 5.14.2-3.g3b944fc-default #1 SMP Sun Sep 12 00:31:31 UTC 2021 (3b944fc)
  Arch: x86_64

Build
  version: v0.13.0
  LLVM: 12.0.1
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  libbpf: no
  libbpf btf dump: no
  libbpf btf dump type decl: no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): no
  map batch (depends on Build:libbpf): no
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint:
```

**Comment by barathrm** [comment]
Seems to be caused by this special-case handling of buffer "elements" (bytes) being in the range of `buf[i] >= 32 && buf[i] <= 126`, which is the case for amongst others is the case for hex value `0x4b`, which would be decimal `75` or ascii `K`. 

Ditching the special-case makes the string-representation of `buf()` behave as expected for me.

```diff
diff --git a/src/utils.cpp b/src/utils.cpp
index decc785d..61ec2fd1 100644
--- a/src/utils.cpp
+++ b/src/utils.cpp
@@ -747,9 +747,6 @@ std::string hex_format_buffer(const char *buf, size_t size)
 
   size_t offset = 0;
   for (size_t i = 0; i < size; i++)
-    if (buf[i] >= 32 && buf[i] <= 126)
-      offset += sprintf(s + offset, "%c", ((const uint8_t *)buf)[i]);
-    else
       offset += sprintf(s + offset, "\\x%02x", ((const uint8_t *)buf)[i]);
 
   s[offset] = '\0';

```

**Comment by viktormalik** [comment]
Ah, this is unfortunate, it should be at least documented. I updated the docs (see the linked PR), although I'm wondering if this is the behaviour that we really want.

**Comment by fbs** [comment]
The 'advantage' of doing this is that ascii data is still readable which makes it easier to ascii And at least python is still able to decode it just fine. Although it might break if the actual data is '\' 'x' 'e' 'e'?

I wouldn't mind if we change it to fully hex strings

**Comment by mmisono** [comment]
The representation is the same as the python (and I think `%r` is named after it). e.g.,
```
>>> "%r" % b'\x01\x02\x41\x42\x43'
"b'\\x01\\x02ABC'"
```
(%r means calling `repr()`.)

I think there is no format specifier for printing hex values in python, but we can use `hex()`.
```
"%s" % b'\x01\x02\x41\x42\x43'.hex()
'0102414243'
```

I think it would be nice to have another format specifier for printing all values as hex.

**Comment by barathrm** [comment]
In case someone were to be willing to submit a PR for this, what would be the preferred usage? A new build-in function `hex(void*, size)` which returns a printf'able string?
