### ISSUE TITLE
How to access pointer to pointer from uprobe/uretprobe?

### ISSUE THREAD

**Issue by b-ripper** [iovisor/bpftrace#2011]
### Is your feature request related to a problem? Please describe.

I want to trace memory by function posix_memalign:
```
extern "C" int posix_memalign(void** memptr, size_t alignment, size_t size) {
  auto dispatch_table = GetDispatchTable();
  int result;
  if (__predict_false(dispatch_table != nullptr)) {
    result = dispatch_table->posix_memalign(memptr, alignment, size);
  } else {
    result = Malloc(posix_memalign)(memptr, alignment, size);
  }
  if (result == 0) {
    *memptr = MaybeTagPointer(*memptr);
  }
  return result;
}
```
```
u:/apex/com.android.runtime/lib64/bionic/libc.so:posix_memalign
{
    //save the memptr
    printf(">>> %s posix_memalign C size %d addr %p pid %d tid %d uid %d gid %d\n",
        strftime("%H:%M:%S:%f", nsecs),
        arg2,
        arg0,
        pid, tid, uid, gid);

    @posix_memalign_info[pid, tid, uid, gid] = (arg2, nsecs, @PID[pid], tid, uid, gid, arg0);
    //@posix_memalign_info[pid, tid, uid, gid] = (arg2, nsecs, @PID[pid], tid, uid, gid, uptr(arg0));
}
ur:/apex/com.android.runtime/lib64/bionic/libc.so:posix_memalign
/retval == 0/
{
    $posix_memalign_ptr = @posix_memalign_info[pid, tid, uid, gid].6;

    printf("<<< %s posix_memalign C %p %p %p\n",
        strftime("%H:%M:%S:%f", nsecs),
        $posix_memalign_ptr,
        uptr($posix_memalign_ptr),
        uptr(uptr($posix_memalign_ptr)));

    $posix_memalign_size = @posix_memalign_info[pid, tid, uid, gid].0;
    $posix_memalign_latency = (nsecs - @posix_memalign_info[pid, tid, uid, gid].1) / 1000000;

    @tobefreedbuf[(uint64 *)$posix_memalign_ptr] = ($posix_memalign_size, comm, uid);

    delete(@posix_memalign_info[pid, tid, uid, gid]);
}
```
#### But I can't save and access the *memptr correctly. How to do that?

**Comment by fbs** [comment]
What is the error exactly? Does it not compile or return the wrong result?

```
        uptr($posix_memalign_ptr),
        uptr(uptr($posix_memalign_ptr)));
```

`uptr` only marks a pointer as user space pointer, it doesn't derefence it. Calling uptr twice is (or should be) useless.

`@posix_memalign_info[pid, tid, uid, gid]` isnt the tid itself enough to get a unique map key btw?

**Comment by b-ripper** [comment]
@fbs  thanks for your response!
> What is the error exactly? Does it not compile or return the wrong result?

In my case, uptr($posix_memalign_ptr) is the same as the $posix_memalign_ptr, but different from the log print out.

> @posix_memalign_info[pid, tid, uid, gid] isnt the tid itself enough to get a unique map key btw?

Is there a better way to get the unique map key? very thanks.

**Comment by fbs** [comment]
> @fbs thanks for your response!
> 
> > What is the error exactly? Does it not compile or return the wrong result?
> 
> In my case, uptr($posix_memalign_ptr) is the same as the $posix_memalign_ptr, but different from the log print out.
> 
Different in what way? Can you show some output?

> > @posix_memalign_info[pid, tid, uid, gid] isnt the tid itself enough to get a unique map key btw?
> 
> Is there a better way to get the unique map key? very thanks.

Just use `tid`?  The others are not more specific (pid can have multiple threads, users are per pid)

**Comment by b-ripper** [comment]
@fbs  very thanks!
I changed the script as below:
```
u:/apex/com.android.runtime/lib64/bionic/libc.so:posix_memalign
/(@size_min ? (arg2 >= @size_min) : 1) && (@size_max ? (arg2 <= @size_max) : 1)
&& (pid == @provider)/
{
    @posix_memalign_info[tid] = (arg2, arg0);
}

ur:/apex/com.android.runtime/lib64/bionic/libc.so:posix_memalign
/(pid == @provider)/
{
    if ((retval == 0) &&
        (@size_min ? (@posix_memalign_info[tid].0 <= @size_max) : 1) &&
        (@size_max ? (@posix_memalign_info[tid].0 >= @size_min) : 1))
    {
        $posix_memalign_size = @posix_memalign_info[tid].0;
        $posix_memalign_ptr = @posix_memalign_info[tid].1;

        printf("## posix_memalign C size %d %p %p pid %d tid %d comm %s\n",
            $posix_memalign_size,
            $posix_memalign_ptr,
            uptr($posix_memalign_ptr),
            pid, tid, comm);

        delete(@posix_memalign_info[tid]);
    }
    else
    {
        delete(@posix_memalign_info[tid]);
    }
}

```
only trace the size 152 and the output:
```
## posix_memalign C size 152 0x6ea2d101c8 0x6ea2d101c8 pid 968 tid 5965 comm provider@2.4-se
## posix_memalign C size 152 0x6e6f1ca018 0x6e6f1ca018 pid 968 tid 15243 comm HwBinder:968_1
## posix_memalign C size 152 0x6e6f2c8018 0x6e6f2c8018 pid 968 tid 15242 comm HwBinder:968_1
## posix_memalign C size 152 0x6e6f0cc018 0x6e6f0cc018 pid 968 tid 15244 comm HwBinder:968_1
## posix_memalign C size 152 0x6e6f3dbad0 0x6e6f3dbad0 pid 968 tid 15241 comm HwBinder:968_1
## posix_memalign C size 152 0x6e6f3c6238 0x6e6f3c6238 pid 968 tid 15241 comm HwBinder:968_1
## posix_memalign C size 152 0x6e6f3c6228 0x6e6f3c6228 pid 968 tid 15241 comm HwBinder:968_1
## posix_memalign C size 152 0x6e6f2c8018 0x6e6f2c8018 pid 968 tid 15253 comm HwBinder:968_1
## posix_memalign C size 152 0x6ee00f13b8 0x6ee00f13b8 pid 968 tid 3228 comm Preview_3
## posix_memalign C size 152 0x6ee03eb3b8 0x6ee03eb3b8 pid 968 tid 3225 comm Preview_0
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6edfef53b8 0x6edfef53b8 pid 968 tid 3230 comm Preview_5
## posix_memalign C size 152 0x6ee00f13b8 0x6ee00f13b8 pid 968 tid 3228 comm Preview_3
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6ee03eb3b8 0x6ee03eb3b8 pid 968 tid 3225 comm Preview_0
## posix_memalign C size 152 0x6ee01ef3b8 0x6ee01ef3b8 pid 968 tid 3227 comm Preview_2
## posix_memalign C size 152 0x6edfef53b8 0x6edfef53b8 pid 968 tid 3230 comm Preview_5
## posix_memalign C size 152 0x6ee00f13b8 0x6ee00f13b8 pid 968 tid 3228 comm Preview_3
## posix_memalign C size 152 0x6edfff33b8 0x6edfff33b8 pid 968 tid 3229 comm Preview_4
## posix_memalign C size 152 0x6ee01ef3b8 0x6ee01ef3b8 pid 968 tid 3227 comm Preview_2
## posix_memalign C size 152 0x6ee01ef3b8 0x6ee01ef3b8 pid 968 tid 3227 comm Preview_2
## posix_memalign C size 152 0x6ee01ef3b8 0x6ee01ef3b8 pid 968 tid 3227 comm Preview_2
## posix_memalign C size 152 0x6ee03eb3b8 0x6ee03eb3b8 pid 968 tid 3225 comm Preview_0
## posix_memalign C size 152 0x6edfff33b8 0x6edfff33b8 pid 968 tid 3229 comm Preview_4
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6ee01ef3b8 0x6ee01ef3b8 pid 968 tid 3227 comm Preview_2
## posix_memalign C size 152 0x6ee01ef3b8 0x6ee01ef3b8 pid 968 tid 3227 comm Preview_2
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6ee01ef3b8 0x6ee01ef3b8 pid 968 tid 3227 comm Preview_2
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6edfff33b8 0x6edfff33b8 pid 968 tid 3229 comm Preview_4
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6ee01ef3b8 0x6ee01ef3b8 pid 968 tid 3227 comm Preview_2
## posix_memalign C size 152 0x6edfef53b8 0x6edfef53b8 pid 968 tid 3230 comm Preview_5
## posix_memalign C size 152 0x6ee00f13b8 0x6ee00f13b8 pid 968 tid 3228 comm Preview_3
## posix_memalign C size 152 0x6ee03eb3b8 0x6ee03eb3b8 pid 968 tid 3225 comm Preview_0
## posix_memalign C size 152 0x6ee01ef3b8 0x6ee01ef3b8 pid 968 tid 3227 comm Preview_2
## posix_memalign C size 152 0x6edfef53b8 0x6edfef53b8 pid 968 tid 3230 comm Preview_5
## posix_memalign C size 152 0x6edfff33b8 0x6edfff33b8 pid 968 tid 3229 comm Preview_4
## posix_memalign C size 152 0x6ea2d101c8 0x6ea2d101c8 pid 968 tid 5965 comm provider@2.4-se
``` 
the log print out:
09-18 04:40:16.831   968  5965   posix_memalign size 152   0xb400006f2fa0aa40
09-18 04:40:17.116   968 15242  posix_memalign size 152    0xb400006e4ddaf620
09-18 04:40:17.589   968  3226  posix_memalign size 152    0xb400006e05e2d8a0
09-18 04:40:17.690   968  3228  posix_memalign size 152    0xb400006e18934440
09-18 04:40:17.789   968  3227  posix_memalign size 152    0xb400006e18935ca0
09-18 04:40:17.854   968  3228  posix_memalign size 152    0xb400006e18934580
09-18 04:40:22.020   968  3229  posix_memalign size 152   0xb400006eb52fd760
09-18 04:40:23.052   968  3226  posix_memalign size 152   0xb400006e18b85860
09-18 04:40:23.885   968  3227  posix_memalign size 152   0xb400006eb52fc720
09-18 04:40:25.416   968  3230  posix_memalign size 152   0xb400006e3ee6d9a0
09-18 04:40:26.814   968  3225  posix_memalign size 152   0xb400006e18b88ce0
09-18 04:40:32.576   968  3230  posix_memalign size 152   0xb400006e09ea9000
09-18 04:40:40.342   968  5965  posix_memalign size 152   0xb400006e9a4ec0a0
```
Take the first line as example:
## posix_memalign C size 152 0x6ea2d101c8 0x6ea2d101c8 pid 968 tid 5965 comm provider@2.4-se
log output is:
09-18 04:40:16.831   968  5965   posix_memalign size 152   0xb400006f2fa0aa40

Another problem:
the bpftrace output is more than the log output, has multi the same results, like:
```
## posix_memalign C size 152 0x6ee00f13b8 0x6ee00f13b8 pid 968 tid 3228 comm Preview_3
## posix_memalign C size 152 0x6ee00f13b8 0x6ee00f13b8 pid 968 tid 3228 comm Preview_3
## posix_memalign C size 152 0x6ee00f13b8 0x6ee00f13b8 pid 968 tid 3228 comm Preview_3
## posix_memalign C size 152 0x6ee00f13b8 0x6ee00f13b8 pid 968 tid 3228 comm Preview_3

## posix_memalign C size 152 0x6ee03eb3b8 0x6ee03eb3b8 pid 968 tid 3225 comm Preview_0
## posix_memalign C size 152 0x6ee03eb3b8 0x6ee03eb3b8 pid 968 tid 3225 comm Preview_0
## posix_memalign C size 152 0x6ee03eb3b8 0x6ee03eb3b8 pid 968 tid 3225 comm Preview_0
## posix_memalign C size 152 0x6ee03eb3b8 0x6ee03eb3b8 pid 968 tid 3225 comm Preview_0

## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1
## posix_memalign C size 152 0x6ee02ed3b8 0x6ee02ed3b8 pid 968 tid 3226 comm Preview_1

## posix_memalign C size 152 0x6edfef53b8 0x6edfef53b8 pid 968 tid 3230 comm Preview_5
## posix_memalign C size 152 0x6edfef53b8 0x6edfef53b8 pid 968 tid 3230 comm Preview_5
## posix_memalign C size 152 0x6edfef53b8 0x6edfef53b8 pid 968 tid 3230 comm Preview_5
## posix_memalign C size 152 0x6edfef53b8 0x6edfef53b8 pid 968 tid 3230 comm Preview_5

## posix_memalign C size 152 0x6edfff33b8 0x6edfff33b8 pid 968 tid 3229 comm Preview_4
## posix_memalign C size 152 0x6edfff33b8 0x6edfff33b8 pid 968 tid 3229 comm Preview_4
## posix_memalign C size 152 0x6edfff33b8 0x6edfff33b8 pid 968 tid 3229 comm Preview_4
## posix_memalign C size 152 0x6edfff33b8 0x6edfff33b8 pid 968 tid 3229 comm Preview_4
```

**Comment by fbs** [comment]
Dont you need to deref the pointer once as its a  `**`?

**Comment by b-ripper** [comment]
@fbs  yes, my problem is just that how to deref the pointer by the builtin in bpftrace when its a **. very thanks!

**Comment by fbs** [comment]
Deref is just like in C, using the `*`. So `*$posix_memalign_ptr,`
