### ISSUE TITLE
libc.so.6 shouldn't be fixed.

### ISSUE THREAD

**Issue by FingerLiu** [iovisor/bpftrace#2075]
### What reproduces the bug?

`tools/gethostlatency.bt` does not work on my centOS machine.

After some research, found it was because libc.so.6 path was not the same with my machine.
```bash
# whereis libc.so.6
> libc.so: /usr/lib64/libc.so.6
```

Quick workaround is to change the path to /usr/lib64/libc.so.6 in my case.
Is there a method to dynamicly find the right location of libc.so on the running machine/

```bash
-uprobe:/lib/x86_64-linux-gnu/libc.so.6:getaddrinfo,
-uprobe:/lib/x86_64-linux-gnu/libc.so.6:gethostbyname,
-uprobe:/lib/x86_64-linux-gnu/libc.so.6:gethostbyname2
+uprobe:/usr/lib64/libc.so.6:getaddrinfo,
+uprobe:/usr/lib64/libc.so.6:gethostbyname,
+uprobe:/usr/lib64/libc.so.6:gethostbyname2
```

### bpftrace --info

System
  OS: Linux 5.15.4-1.el7.elrepo.x86_64 #1 SMP Sat Nov 20 08:10:25 EST 2021
  Arch: x86_64

Build
  version: v0.13.0
  LLVM: 12.0.0
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): no
  map batch (depends on Build:libbpf): yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
  iter:task: no
  iter:task_file: no

**Comment by viktormalik** [comment]
Yes, with the recent bpftrace, you can use:
```
uprobe:libc:getaddrinfo,
uprobe:libc:gethostbyname,
uprobe:libc:gethostbyname2
```

Unfortunately, `tools/gethostlatency.bt` cannot be fixed, yet, as this feature depends on a newer version of BCC, which may not be present in some systems (e.g. our CI). If we resolved #1933, then it'd be possible.
