### ISSUE TITLE
count the same ustack in the END func

### ISSUE THREAD

**Issue by b-ripper** [iovisor/bpftrace#2076]
<!--
ex. I want to trace the mem leak like this:
```
t:xxx:xxx_alloc
{
    @alloc_handle[(uint64 *)args->hdl] = ustack(perf);
}

t:xxx:xxx_destroy
{
    delete(@alloc_handle[(uint64 *)args->hdl]);
}

-->

### Is your feature request related to a problem? Please describe.
<!--
Place description here
-->

I want to trace the mem leak like this:
```
t:xxx:xxx_alloc
{
    @alloc_handle[(uint64 *)args->hdl] = ustack(perf);
}

t:xxx:xxx_release
{
    delete(@alloc_handle[(uint64 *)args->hdl]);
}
```
The map was printed after the Ctrl-C to end the program, like this:
```
@alloc_handle[0xXXXXXX]:
       7a00000000 0x7a00000000 ([function1])
       7a000000c0 0x7a000000c0 ([function2])

@alloc_handle[0xXXXXXX]:
       7a00000000 0x7a00000000 ([function1])
       7a000000c0 0x7a000000c0 ([function2])

@alloc_handle[0xXXXXXX]:
       7a00000000 0x7a00000000 ([function1])
       7a000000c0 0x7a000000c0 ([function2])
```

### Describe the solution you'd like
<!--
Place description here
-->
I want to count the same ustack together like this:
```
@alloc_ustack[
       7a00000000 0x7a00000000 ([function1])
       7a000000c0 0x7a000000c0 ([function2])
] : 3

```
Could it be implemented using count() in END func?

**Comment by danobi** [comment]
Maybe it's better to post-process the bpftrace output in this case. The helpers, when possible, are supposed to do the bulk of the work in-kernel so we don't have to copy as much data to userspace.

`count()` is used for a very specific purpose, so I don't think it makes sense to overload the functionality. I also don't think it's possible to aggregate in-kernel right now (w/ the way we currently handle stacks in bpftrace) b/c we BOR the pid the stack belongs to into the map key.

**Comment by mmisono** [comment]
How about this?

```
t:xxx:xxx_alloc
{
    @alloc_handle[ustack(perf)]++;
}

t:xxx:xxx_release / @alloc_handle[ustack(perf)] /
{
    @alloc_handle[ustack(perf)]--;
}
```

**Comment by b-ripper** [comment]
@mmisono thanks very much, it's a good way!
