### ISSUE TITLE
Bionic builds are broken

### ISSUE THREAD

**Issue by viktormalik** [iovisor/bpftrace#2084]
Our CI is not working and the bug seems to be in the Bionic docker build. The reported error is:
```
The repository 'https://repo.iovisor.org/apt/bionic bionic Release' does not have a Release file
```

IIUC, we're using the above repo to get `libbcc`, however, the repo is outdated for some time due to iovisor/bcc#2678.

We should resolve this somehow, an option would be to use up-to-date repos provided by:
https://launchpad.net/~hadret/+archive/ubuntu/bpfcc

Unfortunately, the BCC version shipped in Bionic is 0.5.0, which is even older than the one from the iovisor repo.

@fbs @danobi @thefallentree any thoughts?

**Comment by fbs** [comment]
Ah you beat me to it. Maybe its time to move away from bionic, its almost 4y old.

Or we could build bcc from scratch for now

**Comment by viktormalik** [comment]
> Ah you beat me to it. Maybe its time to move away from bionic, its almost 4y old.

Yeah, let's start with this. Its EOL is one year away, so we'd have to do that eventually.

If no one else has time, I can have a look into this as it should be fixed ASAP to re-enable the CI.

**Comment by danobi** [comment]
Working on moving CI to focal in https://github.com/iovisor/bpftrace/pull/2087 .

The embedded builds will need to finally be debugged b/c we need an embedded-llvm focal image to run embedded builds against. Will try to fix in a separate PR

**Comment by danobi** [comment]
CI is now fixed
