### ISSUE TITLE
after install bpftrace use YUM, `ip a` exec failed

### ISSUE THREAD

**Issue by Rtoax** [iovisor/bpftrace#2098]
after i install bpftrace with yum install bpftrace in CentOS8.5, failed when i execute `ip a`

```bash
$ ip a
ip: symbol lookup error: ip: undefined symbol: bpf_program__section_name, version LIBBPF_0.2.0
```

**Comment by fbs** [comment]
Don't think this is related to bpftrace, we don't provide the packages. 

Afaik `iproute2` has the ability to attach bpf programs to the network (socket) side. My guess is that  whatever bpftrace does causes issues with the libbpf dependencies. I suggest opening an issue on the centos bug tracker, or if the package is not 'official', contact the package creator directly :)

**Comment by Rtoax** [comment]
It's relate to `libbpf`

**Comment by dawin2015** [comment]
> It's relate to `libbpf`

do you solove the problem?

**Comment by dawin2015** [comment]
after `yum install -y libbpf`, problem is fixed

**Comment by Rtoax** [comment]
> after `yum install -y libbpf`, problem is fixed

Great
