### ISSUE TITLE
builtin for int to errno constant string translation

### ISSUE THREAD

**Issue by viktormalik** [iovisor/bpftrace#2114]
Per discussion in #2082, it would be nice to have a way to translate an errno integer into the corresponding constant string.

### Describe the solution you'd like

Could make a builtin function that does the translation. You'd probably want to store the `int -> string` mapping as a readonly bpf map that the prog can access. And only load the map if the script uses that builtin.

_Originally posted by @danobi in https://github.com/iovisor/bpftrace/discussions/2082#discussioncomment-1801628_

**Comment by aktau** [comment]
+1 this would be very nice. It's annoying to have to look that up all the time.
