### ISSUE TITLE
Tools get broken with newer kernels

### ISSUE THREAD

**Issue by viktormalik** [iovisor/bpftrace#2128]
Since many of our tools rely on kprobes and kernel struct types, it may (and it does) happen that they stop working with newer kernels. I'd like to use this bug to settle on approaches that we can take to avoid/resolve such problems.

Existing problems:
- #1896: `mdflush.bt` stops working due to `struct bio` change
- #1895: `tcpdrop.bt` stops working due to GCC change (kprobe is inlined)
- #2127: `bio*.bt` tools stop working due to renamed kprobes and a struct moved to a different header

We'll need a number of approaches to resolve the individual problems. So far, I can think of these:

1. If a kprobe is removed, it is usually possible to find a different one to attach to. We can solve this in a script by attaching to all potential kprobes which will display a warning but it'll work. We might want to add an option to ignore non-existing kprobe warnings and use that in scripts to improve user experience.
2. Move of a struct to a different header could be solved by relying on BTF rather than on header includes. This is proposed by #1823.
3. Change in a struct type is more difficult to resolve. We could add a way to somehow check if a field exists in a struct (using BTF).

Thoughts? Any more ideas of what can break and how to approach it?

**Comment by viktormalik** [comment]
I'd suggest taking the same approach as BCC does: if it's not simple to support multiple kernel versions in a single script, then we just keep the most recent one in `tools/` and provide scripts for old kernels in `tools/old/`.

@fbs @danobi @brendangregg any thoughts on this?

**Comment by danobi** [comment]
Multiple versions of the same script seems like the only sane way to me. If it's easy to support multiple kernels in the same script, that's great and we should do that. If there's enough skew, we can copy paste the script and add a comment in the old script saying something like "works on kernel A.BB - C.DD".

**Comment by mmisono** [comment]
Maybe we can use the `LINUX_VERSION_CODE` macro? Something like

```
#include <linux/version.h>

BEGIN {
#if (LINUX_VERSION_CODE < KERNEL_VERSION(5,0,0))
  printf("bar\n");
#else
  printf("baz\n");
#endif
}
```

... though it does not work now:

```
a.bt:4:1-49: ERROR: syntax error, unexpected preprocessor directive, expecting }
#if (LINUX_VERSION_CODE < KERNEL_VERSION(5,0,0))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by fbs** [comment]
Personally I'm not that happy with all the preprocessor tricks. I see the preprocessor more of an implementation detail. Its there to import header files so we can use those types. We just don't have a way to 'restrict' it so you can 'use' it for these purposes too.

With the move to BTF on the kernel side and us adding DWARF support for uprobes we can probably drop clang and the stuff that comes with it for a lighter build. Header parsing can be quite slow too, you never know what header is imported by the header you need, the network tools we have suffer from it.

Conditional compilation is also not without issues as you basically have multiple different bits of the same code which do (not) get compiled based on some conditions. So making sure every path is syntactically valid etc is hard.

But I do not have  a better solution than just multiple version either.

**Comment by danobi** [comment]
> Maybe we can use the LINUX_VERSION_CODE macro? Something like

Unfortunately that does not work for backported kernels. The version number can be a big lie when features/code is backported to an older version kernel.
