### ISSUE TITLE
Unconditional hex output

### ISSUE THREAD

**Issue by agrover** [iovisor/bpftrace#2130]
The current `buf()` implementation turns unprintable characters into escaped hex values, but leaves printable characters as-is. This can actually be hard to read when trying to print e.g. network headers. It would be easier to read if it were entirely hexadecimal.

See https://github.com/iovisor/bpftrace/issues/2009#issuecomment-990786547

**Comment by viktormalik** [comment]
Thanks for creating an issue for this!

We should probably agree on the approach to take here. Some options that come to mind:
1. Change behaviour of `%r` in `printf`.
2. Introduce new format specifier for `printf` (`%x` or `%rx`?)
3. Introduce a builtin function (`hex`).

@fbs wdyt?

**Comment by mmisono** [comment]
As I wrote in https://github.com/iovisor/bpftrace/issues/2009#issuecomment-923517641, the behavior of `%r` is the same as in Python. So I think it would be better to keep the current behavior. I think the `%rx` specifier is easy to use (though probably the `%rx` specifier is not common.)
