### ISSUE TITLE
Cannot find system headers on some systems

### ISSUE THREAD

**Issue by viktormalik** [iovisor/bpftrace#2150]
Debian-like systems (such as Ubuntu, which we use as a base for our Docker builds) moved system headers into arch-specific directories, e.g., `/usr/include/x86_64-linux-gnu`. On such systems, bpftrace is not able to find the headers and ClangParser fails to parse the script. 

This affects some of the shipped tools and makes CI fail.

### What reproduces the bug?

```
# bpftrace tools/tcp_accept.bt
```
 when BTF is available (as it tries to include `sys/socket.h`).

### Possible solutions

1. Use Clang to determine the list of system include paths. This can be done by running:
    ```
    $ clang -Wp,-v -x c -fsyntax-only /dev/null
    ```
    and parsing out the paths. While this is a good solution, it requires Clang to be installed, which is not a dependency of bpftrace and 
    is not available, e.g., when doing static builds.

2. It should be possible to obtain the list of include paths using Clang as a library, but we'd have to depend on `libclang-cpp` as the C API in `libclang` doesn't provide such functionality.

3. The simplest solution would be to hard-code `/usr/include/x86_64-linux-gnu` to the list of system include directories in ClangParser. This would only help on Ubuntu on x86, but at least it would make CI pass again. I implemented this one in #2149.

Do you think we should implement some more robust solution to this?

**Comment by danobi** [comment]
While I think it would be nice to make a best effort to keep up w/ distro include paths, I wouldn't spend too much time being clever here. I think we should still be trying to nudge users away from headers long term. And worst case user can specify `-I` flag on cli.

**Comment by viktormalik** [comment]
> While I think it would be nice to make a best effort to keep up w/ distro include paths, I wouldn't spend too much time being clever here. I think we should still be trying to nudge users away from headers long term. And worst case user can specify `-I` flag on cli.

I agree. Actually, option no. 1 above is quite easy to implement and if it doesn't help (e.g. Clang is not available), then it's no change from user perspective.
