### ISSUE TITLE
Trace process exits

### ISSUE THREAD

**Issue by serkan-ozal** [iovisor/bpftrace#2195]
Hi,

First of all, thanks for such a great tool for observability.

My question is that how it is possible to trace process exits with `bpftrace` as already supported by `bcc` https://github.com/iovisor/bcc/blob/master/tools/exitsnoop.py

In our case, we are trying to trace processes with their
- `name`,
- `start time`,
- `args`,
- `end time` (or `duration`),
- `exit code`

`execsnoop` already gives us enough informations for process `name`, `start time` and `args` but we also need to get process `exit time` (or `duration`) and `exit code`.

Thanks in advance.

**Comment by serkan-ozal** [comment]
Hi @fbs, Thanks for the hint 👍 

I have managed get it working but now I have another but simple problem :)

I am able to get configurations over positional parameters like `bpftrace -f json exitsnoop.bt -u <uid> ...`. But the problem is that I want to iterate over the positional parameters. I know it will be easier with `bcc`, but I don't want to switch to `bcc` from `btrace` just for such configuration challenge. 

So the question is that, how can I iterate over positional arguments to get and check given options?

Thanks.

**Comment by fbs** [comment]
You cannot. I hope to add a flag parser at some point in the future but right now the best option might be to dynamically generate the bpftrace script from a shell script that does the handling :(

**Comment by danobi** [comment]
Thanks @bolinfest ! We're still sorting out some licensing issues but once we've figured it out, please feel free to contribute the script to https://github.com/bpftrace/user-tools
