### ISSUE TITLE
Both operands to ICmp instruction are not of the same type!

### ISSUE THREAD

**Issue by Rtoax** [iovisor/bpftrace#2199]
env：

Happened in ` Ubuntu 20.04.4 LTS`:

* Ubuntu 20.04.4 LTS
* bpftrace v0.9.4
* LLVM version 10.0.0
* 5.11.0-40-generic

Not happen in `CentOS Stream9`：

* CentOS Stream9
* bpftrace v0.12.1
* LLVM version 13.0.1
* 5.14.0-70.el9.x86_64

bpftrace script:

```
kprobe:__d_instantiate_anon
{
    $disconnected = arg2;

    if (!$disconnected) {
        @dcount["HASH_ADD"] = count();
    }   
}
```

error:

```
bpftrace: /usr/include/llvm-9/llvm/IR/Instructions.h:1150: void llvm::ICmpInst::AssertOK(): Assertion `getOperand(0)->getType() == getOperand(1)->getType() && "Both operands to ICmp instruction are not of the same type!"' failed.
Aborted
```

**Comment by fbs** [comment]
Both are fairly old releases, we're on 0.14.1. Can you try with a newer build? We have a static build linked to the 0.14 release you can use. https://github.com/iovisor/bpftrace/releases/tag/v0.14.1

**Comment by Rtoax** [comment]
> Both are fairly old releases, we're on 0.14.1. Can you try with a newer build? We have a static build linked to the 0.14 release you can use. https://github.com/iovisor/bpftrace/releases/tag/v0.14.1

Thanks.
