### ISSUE TITLE
Get address like "&a"  in C

### ISSUE THREAD

**Issue by Rtoax** [iovisor/bpftrace#2214]
Does bpftrace need get vars address like C:

```c
int a;
int *pa = &a;
```

`&` to get address of var, or `addr($task->flags)`

```bpftrace
$task = curtask;
$pflag = &$task->flags;
```

**Comment by fbs** [comment]
Just curious, what is the usecase here?

**Comment by viktormalik** [comment]
ping @Rtoax, mind sharing a use-case?

**Comment by Rtoax** [comment]
Sorry, i forgot what i want in that time, maybe i want to get the offsetof of struct's field.

**Comment by viktormalik** [comment]
Duplicate of #553.
