### ISSUE TITLE
BTF does not appear to be detected

### ISSUE THREAD

**Issue by bkosciarz** [iovisor/bpftrace#2235]
Following along with [tutorial one liners](https://github.com/iovisor/bpftrace/blob/master/docs/tutorial_one_liners.md#lesson-12-kernel-struct-tracing) I see that `If the kernel has BTF (BPF Type Format) data, all kernel structs are always available.`

I believe this means that I can omit these includes from example `path.bt`:
```
#include <linux/path.h>
#include <linux/dcache.h>
```

This does not work as expected and gives an error that the struct definitions are missing even though my system appears to have BTF support.

I think I satisfy the following requirements from [btf_support](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#btf-support)
```
    Linux 4.18+ with CONFIG_DEBUG_INFO_BTF=y
        Building requires dwarves with pahole v1.13+
    bpftrace v0.9.3+ with BTF support (built with libbpf v0.0.4+)
```

`bpftrace` was installed from the apt repo

### What reproduces the bug?
```
sudo bpftrace path.bt
path.bt:6:28-49: ERROR: Unknown struct/union: 'struct path'
    printf("open path: %s\n", str(((struct path *)arg0)->dentry->d_name.name));
```

```
cat path.bt
//#include <linux/path.h>
//#include <linux/dcache.h>

kprobe:vfs_open
{
	printf("open path: %s\n", str(((struct path *)arg0)->dentry->d_name.name));
}
```

### bpftrace --info
```
sudo bpftrace --info
Kernel helpers
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes

Kernel features
  Loop support: yes
```

### other relevant info
```
uname -r
5.13.0-37-generic
```
```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
```
```
bpftrace -V
bpftrace v0.9.4
```
```
cat /boot/config-`uname  -r` | grep BTF
CONFIG_VIDEO_SONY_BTF_MPX=m
CONFIG_DEBUG_INFO_BTF=y
CONFIG_PAHOLE_HAS_SPLIT_BTF=y
CONFIG_DEBUG_INFO_BTF_MODULES=y
```
```
ls -l /sys/kernel/btf/vmlinux 
-r--r--r-- 1 root root 5044520 Apr 18 19:57 /sys/kernel/btf/vmlinux
```

**Comment by bkosciarz** [comment]
Ended up finding a fix, but it wasn't pretty. Documenting in case it is useful for someone in the future

I built `bpftrace` from source, but it was not able to detect libbpf as being installed or a package called `libdw-dev`.
`libdw-dev` was as easy as an apt install, but I needed to build `libbpf` from source (version 0.8).

cmake was able to find libbpf and libdw, but then I got several compilation errors with bpftrace.

file `src/btf.cpp` did not correctly set `HAVE_LIBBPF_BTF_DUMP_NEW_V0_6_0` even though I was on `v0.8`. Hacky solution was to hardcode the cpp file to use that case since it was falling to the old case.

I needed a couple slight modifications in `/usr/include/bpf/bpf.h` and `/usr/include/bpf/btf.h` which were adding a couple enum definitions in.
btf.h needed btf_func_linkage:
```
enum btf_func_linkage {
	BTF_FUNC_STATIC = 0,
	BTF_FUNC_GLOBAL = 1,
	BTF_FUNC_EXTERN = 2,
};
```
and bpf.h needed bpf_stats_type to be changed from
```
enum bpf_stats_type; /* defined in up-to-date linux/bpf.h */ 
```
changed to (https://github.com/libbpf/libbpf/issues/249)
```
enum bpf_stats_type
#ifdef __cplusplus
: int
#endif
; /* defined in up-to-date linux/bpf.h */
```

I also needed to add `/usr/lib64` to my loader path otherwise the `libbpf.so` would not be found at runtime.

I am now able to run `path.bt` example without the header files.

Leaving this issue open due to missing definition of `HAVE_LIBBPF_BTF_DUMP_NEW_V0_6_0` seeming like an error that should be fixed. Will close if devs think otherwise

**Comment by viktormalik** [comment]
Hi, sorry for a late answer. Just sharing some thoughts here for future reference.

First of all, bpftrace version 0.9.4 is fairly old and it's very likely that BTF support is not good there. So yes, your only option is to upgrade your system or to build bpftrace from source.

Now to the build problems:
- `HAVE_LIBBPF_BTF_DUMP_NEW_V0_6_0` is not correctly detected due to using old GCC. A solution would be to update your GCC or to use an older version of libbpf (0.5.0).
- When installing libbpf, it's possible to use e.g. `LIBDIR=/usr/local/lib make install` to install libraries into a path that Ubuntu searches by default. We do the same for our CI docker builds (see `docker/build.sh`).
- Not sure about the rest of the problems but I'd expect a similar issue (some libbpf feature not properly detected due to old GCC).

**Comment by viktormalik** [comment]
Anyway, I think that the issue can be closed.

**Comment by josebeo2016** [comment]
> Ended up finding a fix, but it wasn't pretty. Documenting in case it is useful for someone in the future
> 
> I built `bpftrace` from source, but it was not able to detect libbpf as being installed or a package called `libdw-dev`. `libdw-dev` was as easy as an apt install, but I needed to build `libbpf` from source (version 0.8).
> 
> cmake was able to find libbpf and libdw, but then I got several compilation errors with bpftrace.
> 
> file `src/btf.cpp` did not correctly set `HAVE_LIBBPF_BTF_DUMP_NEW_V0_6_0` even though I was on `v0.8`. Hacky solution was to hardcode the cpp file to use that case since it was falling to the old case.
> 
> I needed a couple slight modifications in `/usr/include/bpf/bpf.h` and `/usr/include/bpf/btf.h` which were adding a couple enum definitions in. btf.h needed btf_func_linkage:
> 
> ```
> enum btf_func_linkage {
> 	BTF_FUNC_STATIC = 0,
> 	BTF_FUNC_GLOBAL = 1,
> 	BTF_FUNC_EXTERN = 2,
> };
> ```
> 
> and bpf.h needed bpf_stats_type to be changed from
> 
> ```
> enum bpf_stats_type; /* defined in up-to-date linux/bpf.h */ 
> ```
> 
> changed to ([libbpf/libbpf#249](https://github.com/libbpf/libbpf/issues/249))
> 
> ```
> enum bpf_stats_type
> #ifdef __cplusplus
> : int
> #endif
> ; /* defined in up-to-date linux/bpf.h */
> ```
> 
> I also needed to add `/usr/lib64` to my loader path otherwise the `libbpf.so` would not be found at runtime.
> 
> I am now able to run `path.bt` example without the header files.
> 
> Leaving this issue open due to missing definition of `HAVE_LIBBPF_BTF_DUMP_NEW_V0_6_0` seeming like an error that should be fixed. Will close if devs think otherwise

I have same problem. I followed your quick fix and the bpftrace --info:
```
System
  OS: Linux 5.13.0-51-generic #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022
  Arch: x86_64

Build
  version: v0.15.0
  LLVM: 12.0.0
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf: yes
  libbpf btf dump: no
  libbpf btf dump type decl: no
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): no
  map batch (depends on Build:libbpf): yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes

```
