### ISSUE TITLE
Support IP comparison

### ISSUE THREAD

**Issue by xh4n3** [iovisor/bpftrace#2248]
### Is your feature request related to a problem? Please describe.
One example:
```
kfunc:dev_queue_xmit {
        $skb = args->skb;
        $iph = (struct iphdr *)($skb->head + $skb->network_header);
        $sip = ntop($iph->saddr);
        // I want to filter skbs by sip here.
        printf("%-8d %14s\n", pid, $sip);
}
```
This script may output a lot skbs, IP filtering should be added here. 

Workaround 1
```
        if (strncmp($sip, "127.0.0.1", 9)) {
                return;
        }
```
This prints error message: ERROR: strncmp() only supports string arguments (inet provided)

Workaround 2
```
        if (strncmp(str($sip), "127.0.0.1", 9)) {
                return;
        }
```
This prints error message: ERROR: str() expects an integer or a pointer type as first argument (inet provided)

Workaround 3
```
        if ($iph->saddr == 0x100007f ) {
                return;
        }

```
This actually worked, but if the script isn't very human-readable.

### Describe the solution you'd like
Solution 1: Add a new built-in func like pton, so we can compare numbers
```
        if ($iph->saddr == pton(AF_INET, "127.0.0.1)) {
                return;
        }
```
Then this script can be hand over to anyone unfamiliar with hex to dig into network issues, IMHO, this would work great with the command line arguments https://github.com/iovisor/bpftrace/issues/1945 

### Describe alternative solutions or features you've considered
Somehow fixing the case in workaround 1/2, but strncmp takes a length argument, which would be hard to determine.

**Comment by viktormalik** [comment]
This would be a nice feature, thanks for the suggestion!

I think that the solution using `pton` is the only one possible here as the `ntop` string is resolved asynchronously, making it impossible to be compared inside the BPF program (using e.g. `strncmp`).

**Comment by xh4n3** [comment]
> This would be a nice feature, thanks for the suggestion!

May I draft a PR regarding this? 😃

**Comment by viktormalik** [comment]
> May I draft a PR regarding this? smiley

Yes, please do, that would be great :-)

**Comment by xh4n3** [comment]
I'm able to convert string-format IPv6 address to char array now, but I think we may need the ability to compare char array in bpftrace language, otherwise we can only compare them char by char.

What I'm having now:
```
tracepoint:tcp:tcp_retransmit_skb {
  printf("real daddr %s\n", ntop(args->daddr_v6));

  // can convert back and forth
  printf("convert back and forth %s\n", ntop(pton("2001::1f0d:4435")));

  // can store the string as char addr[16]
  $addr = pton("2001::1f0d:4435");

  // can access the char in the char array
  printf("char 0 %x\n", $addr[0]);

  // can compare chars one by one between skb's addr and user's input
  if (args->daddr_v6[0] == $addr[0]) {
    printf("partial matched\n");
  }

  // * cannot compare char array
  if (args->daddr_v6 == $addr) {
    printf("all matched\n");
  }
  return;
}
```

I have some ideas, which one do you recommend? @viktormalik 
* implementing comparing on char arrays, (btw, how should we determine its length?)
* using buf(args->daddr_v6) == buf($addr) instead
* add a new built-in arrayncmp like strncmp

**Comment by xh4n3** [comment]
Done.
