### ISSUE TITLE
Error to retrieve the probe name

### ISSUE THREAD

**Issue by dth0** [iovisor/bpftrace#225]
Hello,

I'm trying to use the built-in variable "name" but for some reason, it is failing.

bpftrace -e 'tracepoint:syscalls:sys_exit_openat { printf("%-2d: %-10s \n", pid, comm); }'
Attaching 1 probe...

**440: vminfo
370: dbus-daemon
370: dbus-daemon
370: dbus-daemon
454: tuned**

bpftrace -e 'tracepoint:syscalls:sys_exit_openat { printf("%-2d: %-10s %s\n", pid, comm, name); }'

**1.81: syntax error, unexpected ), expecting (**

Linux devlab 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-10-07) x86_64 GNU/Linux

Thanks

**Comment by brendangregg** [comment]
We recently renamed it to "probe" (so we could reserve "name" for something else). Did we miss some docs that still call it name?

**Comment by dth0** [comment]
Yeah, it worked

Only these 2 places below still call it name.

[builtins](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#1-builtins)
[syncsnoop.bt](https://github.com/iovisor/bpftrace/blob/master/tools/syncsnoop.bt)

Thanks
