### ISSUE TITLE
exit() function bypasses END probe processing

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#228]
END probe processing is bypassed when the tracing session is terminated with a call to the exit() function:

```
# cat END-bypass.bt
tracepoint:syscalls:*
{
  @[probe] = count()
}

interval:s:5
{
  exit();
}

END
{
  clear(@);
}

# bpftrace.new END-bypass.bt
Attaching 612 probes...
<chop>
@[tracepoint:syscalls:sys_exit_sendto]: 17988
@[tracepoint:syscalls:sys_enter_sendto]: 17988
@[tracepoint:syscalls:sys_enter_recvfrom]: 19187
@[tracepoint:syscalls:sys_exit_recvfrom]: 19191
```

As expected, if I terminate the session with a `<Ctrl-C>` then the END probe is processed and nothing is printed.

The documentation isn't explicit on the behaviour of END processing in this case but I think it feels more natural for END probes to be processed on a controlled exit regardless of termination mechanism.

**Comment by williangaspar** [comment]
I and @mmarchini had a hack on it. We manage to make it work on kprobes, but intervals are nor working just yet

`bpftrace.cpp`

before
```c++
  // async actions
  if (printf_id == asyncactionint(AsyncAction::exit))
  {
    err = bpftrace->print_maps();
    exit(err);
  }`

now
```c++
  // async actions
  if (printf_id == asyncactionint(AsyncAction::exit))
  {
    END_trigger();
    bpftrace->poll_perf_events(true);
    err = bpftrace->print_maps();
    exit(err);
  }```

**Comment by tyroguru** [comment]
Thanks @caringi for fixing this! Really appreciate all the work.
