### ISSUE TITLE
Race condition in `usym` resolution

### ISSUE THREAD

**Issue by viktormalik** [iovisor/bpftrace#2284]
Originally discovered by @xutao323 in [this comment](https://github.com/iovisor/bpftrace/issues/2118#issuecomment-1017188844).

As `usym` is resolved asynchronously, a race condition may occur in case the traced binary exits before its symbols are resolved. This causes, e.g., the `func` builtin to return address instead of the actual function name.

### What reproduces the bug?

Usually can be reproduced using `func` inside an `uprobe/uretprobe` for a function close to the end of the traced binary:

```
# cat test.c
int fun() { }

int main() {
    fun();
}

# bpftrace -e 'uprobe:test:fun { printf("%s\n", func); }
Attaching 1 probe...
0x401106
```

Inserting a `sleep` fixes the problem:
```
# cat test.c
#include <unistd.h>
int fun() { sleep(1); }

int main() {
    fun();
}

# bpftrace -e 'uprobe:test:fun { printf("%s\n", func); }
Attaching 1 probe...
fun
```

Another way to reproduce is to run bpftrace in a debugger.

**Comment by jordalgo** [comment]
Is this still an issue?

**Comment by viktormalik** [comment]
I believe that we managed to solve the issue in most of the situations. There are still a few where we don't get the symbol name but I don't think that we can do much about them.

@lenticularis39 knows better, though, so if he can confirm my thoughts, I'd suggest closing this issue.

**Comment by lenticularis39** [comment]
There are still cases where usym resolution fails but IMO these should be tracked in separate, specific issues if they turn out to be problematic. 

I agree with closing this issue, if anyone hits a race condition regarding usym resolution, please open a new issue and describe the exact situation where it happened.
