### ISSUE TITLE
Implement BEGIN and END probes using USDTs

### ISSUE THREAD

**Issue by ajor** [iovisor/bpftrace#2292]
BEGIN and END are currently implemented as uprobes on the `BEGIN_trigger` and `END_trigger` functions in https://github.com/iovisor/bpftrace/blob/master/src/triggers.h

This means that BEGIN and END probes don't work when the bpftrace binary has been stripped of symbols:
```
# /tmp/bpftrace -e 'BEGIN { printf("hi\n") }'
Attaching 1 probe...
hi
^C

# strip /tmp/bpftrace 
# /tmp/bpftrace -e 'BEGIN { printf("hi\n") }'
Attaching 1 probe...
ERROR: Could not resolve symbol: /proc/self/exe:BEGIN_trigger
```

USDTs are not stripped so easily, so we won't have semi-broken bpftrace packages accidentally being released.
Currently it appears that the bpftrace package on Ubuntu 22.04 is stripped.

**Comment by lxyscls** [comment]
I think it is the problem of bpftrace debian package. I remove it and build it from scratch on my Ubuntu Server 22.04. It is ok now. 
https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#ubuntu

**Comment by danobi** [comment]
I actually have a PR up to address just this: https://github.com/iovisor/bpftrace/pull/2264 . Reviews welcome :)

USDTs are an interesting idea. I hadn't thought of that. But I think using BPF_PROG_RUN is more reliable still.

**Comment by ajor** [comment]
Ah I hadn't seen your PR! I agree that your way looks better, will give it a review today
