### ISSUE TITLE
BEGIN,END { ... } does not work

### ISSUE THREAD

**Issue by ajor** [iovisor/bpftrace#2294]
This appears to be a regression introduced in #2265

### What reproduces the bug?
With bpftrace built from fc940d31be140d54ceb4c7ae47371785f0b26b65 this script fails:
```
# ./src/bpftrace -e 'BEGIN,END { printf("hi\n") }' 
Attaching 2 probes...
ERROR: Error loading program: BEGIN,END (try -v)
```

Go back one commit to 746a53c35afafb5a782b49cd16692ca6fb0b6618 and it works as expected:
```
# ./src/bpftrace -e 'BEGIN,END { printf("hi\n") }' 
Attaching 2 probes...
hi
^Chi


```

**Comment by viktormalik** [comment]
Thanks for noticing this @ajor! Should be fixed by #2295.
