### ISSUE TITLE
add ppid builtin

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#23]
ppid for parent process ID.

This may require a kernel addition to do in a sane way: a ppid version of BPF_FUNC_get_current_pid_tgid(). Without it, we'd be digging the ppid from the curtask builtin (is there a sane way to know the right offset?).

**Comment by amagura** [comment]
Any update on this?

**Comment by danobi** [comment]
bpftrace has since added BTF support so there is a sane way to access fields in `curtask`.

For example, this should reliably work:

```
'BEGIN { print(curtask->parent->pid) }'
```

**Comment by mmarchini** [comment]
Is there any reason for us to implement `ppid` not that BTF makes accessing it straightforward?

**Comment by zhangguanzhang** [comment]
any update?

**Comment by brendangregg** [comment]
Ok, but can we please add `ppid` as a BTF wrapper? bpftrace will be coming to other OSes (Windows) and having us hard code "curtask->parent->pid" in all our programs/one-liners is yet another thing to port (assuming Windows won't have the exact same struct!).

**Comment by danobi** [comment]
I wouldn't be against adding such a helper if/when a ported bpf runtime materializes. But until there are more details, I think it's best we hold off on making a decision. Doing nothing on this issue for now does not close any doors.
