### ISSUE TITLE
Add support for bpf_trace_printk

### ISSUE THREAD

**Issue by xh4n3** [iovisor/bpftrace#2300]
### Is your feature request related to a problem? Please describe.
I need `bpf_trace_printk` while developing bpftrace features, and I don't have enough confidence about the `printf` output because I may have broken these codes.

### Describe the solution you'd like
Add a built-in function `debugf`, which calls `bpf_trace_printk`. Compared with current `printf`, it has following benefits:
* The `bpf_trace_printk` is helpful while debugging bpftrace itself, e.g. the `printf` function.
* Since `debugf` doesn't rely on the async mechanism, it would help if we're debugging with async events.
* For bpftrace script developers, `debugf` prints to /sys/kernel/debug/tracing/trace, the output content won't get mixed with stdout to confuse script users.

### Describe alternative solutions or features you've considered
No.

I'm willing to submit a PR about this. Please leave comments if any, thanks!

**Comment by viktormalik** [comment]
I'm not against adding a new builtin function, but we should be cautious about this one. Looking at the helper description from the [bpf-helpers manpage](https://man7.org/linux/man-pages/man7/bpf-helpers.7.html):

>  Also, note that bpf_trace_printk() is slow, and
should only be used for debugging purposes. For
this reason, a notice block (spanning several
lines) is printed to kernel logs and states that
the helper should not be used "for production use"

So, our reference guide should strongly advise not to use this inside shipped scripts, which may be used in production.

Still, this can be useful as a replacement for `printf` when its async nature is a problem. So, feel free to proceed with the PR, but maybe an actual example where this is better than `printf` would be nice.

Thanks!

**Comment by xh4n3** [comment]
Thanks, I will add the warning part in the docs, and think about what scenarios for this to be suitable.

**Comment by danobi** [comment]
Sounds useful for debugging. Maybe we can leave it undocumented and print a loud warning any time it's used?
