### ISSUE TITLE
cmake fails due to missing: LIBBPF_LIBRARIES   LIBBPF_INCLUDE_DIRS

### ISSUE THREAD

**Issue by tinykim83** [iovisor/bpftrace#2303]
### What reproduces the bug?

Try to build bpf trace on Ubuntu 20.04 after installing bpfcc and all the pakage required for ubuntu 20.04 listed on the INSTALL.md.

libbpf or libbpf-dev package is not found on the ubuntu repository.
apt install libbpf fails.
bpftrace source is from the git : https://github.com/iovisor/bpftrace

This is the same on the Ubuntu 18.04.
bpftrace source is version 0.14.1

### bpftrace --info

log from Ubuntu 20.04

$ cat /proc/version
Linux version 5.13.0-30-generic (buildd@lcy02-amd64-003) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022

$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibBcc: /usr/lib/x86_64-linux-gnu/libbcc.so
-- Performing Test LIBBCC_ATTACH_KPROBE_SIX_ARGS_SIGNATURE
-- Performing Test LIBBCC_ATTACH_KPROBE_SIX_ARGS_SIGNATURE - Success
-- Performing Test LIBBCC_ATTACH_UPROBE_SEVEN_ARGS_SIGNATURE
-- Performing Test LIBBCC_ATTACH_UPROBE_SEVEN_ARGS_SIGNATURE - Failed
-- Looking for bcc_usdt_foreach
-- Looking for bcc_usdt_foreach - found
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Please install the libbpf development package (missing: LIBBPF_LIBRARIES
  LIBBPF_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibBpf.cmake:31 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:103 (find_package)

-- Configuring incomplete, errors occurred!

log from ubuntu 18.04
 $ cat /proc/version
Linux version 4.15.0-112-generic (buildd@lcy01-amd64-027) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020

$ cmake -DCMAKE_BUILD_TYPE=Release ..
CMake Error at /home6/bwkim/gitHub/cmake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Please install the libbpf development package (missing: LIBBPF_LIBRARIES
  LIBBPF_INCLUDE_DIRS)
Call Stack (most recent call first):
  /home6/bwkim/gitHub/cmake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibBpf.cmake:31 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:103 (find_package)

-- Configuring incomplete, errors occurred!
[CMakeError.log](https://github.com/iovisor/bpftrace/files/9166908/CMakeError.log)
[CMakeError.log](https://github.com/iovisor/bpftrace/files/9166924/CMakeError.log)

**Comment by viktormalik** [comment]
Unfortunately, Ubuntu 20.04 doesn't package libbpf, which is now required for bpftrace. The solution is to build libbpf from source, as is done in our [Docker build script](https://github.com/iovisor/bpftrace/blob/master/docker/build.sh#L28-L35).

**Comment by viktormalik** [comment]
I believe that this is now resolved and can be closed.
