### ISSUE TITLE
hex dump 

### ISSUE THREAD

**Issue by jarkkojs** [iovisor/bpftrace#2305]
It would be useful, or at least convenient to have, a variation of `buf()` that would print out a hex string with two characters for each 8-bit number. E.g. in my case, I'd like print out the full contents of some maybe around 300-2000 byte buffers.

**Comment by lenticularis39** [comment]
There is an option to print like this, but with a `\x` prefix:
```
# bpftrace -e 'BEGIN { printf("%rx", buf("Hello world", 11)); }'
Attaching 1 probe...
^C\x48\x65\x6c\x6c\x6f\x20\x77\x6f\x72\x6c\x64
```
An option to print without the prefix should be easy to implement.
