### ISSUE TITLE
Add support for strstr() builtin

### ISSUE THREAD

**Issue by liutingjieni** [iovisor/bpftrace#2306]
I have a requirement, I hope to be able to check which process deleted the "cores" related files. 
First of all, because my need is to write a script that is deployed on thousands of servers, it is difficult for us to confirm its configuration and the directory it is mounted on because of the change of the deployment version, so we need fuzzy matching. 

The only existing str function that supports bpftrace is strncmp, which has no way to obfuscate. And there is no way to traverse strings in bpftrace, so there is no way to use strncmp to write a strstr by hand.

### Describe the solution you'd like

Solution 1: Add a new built-in func like strstr()
` bpftrace  -e 'tracepoint:syscalls:sys_enter_unlink / strstr( str(args->pathname), "cores") > 0 / {printf("comm: %s(%d) delete file: %s\n", comm, pid, str(args->pathname)); printf("%s\n", ustack());}'`

I think strstr this is a generic requirement. There may be many times when there is no way to confirm the absolute path of the file or the full name of the process or...

### Describe alternative solutions or features you've considered

Another way is to get all the information in kernel mode and then filter it in user mode. But this results in a lot of pointless copying from kernel mode to user mode. I have tested that attaching the bpftrace program to the specified function and frequently triggering it. Copying all the information to user mode will cause a CPU to reach 100% utilization. Copying after kernel-state filtering has almost no impact on performance.

I'm willing to submit a PR about this. Please leave comments if any, thanks!

**Comment by viktormalik** [comment]
It could be nice to have `strstr` and since the BPF verifier now allows bounded loops and we have strings of bounded size, it should be possible to implement it. The implementation may still be tricky, but feel free to give it a try.

**Comment by liutingjieni** [comment]
I have started to develop this function now, but I have not developed bpftrace before, and I am not familiar with the related libraries of llvm. I have some difficulties in development and debugging. Do you have relevant information here to help me get started quickly?

**Comment by liutingjieni** [comment]
I am currently developing based on  0.12.1_release version, is this branch ok? If not, is it a recommended branch?

**Comment by fbs** [comment]
All development happens against the master branch. 0.12 is quite an old release.

As for LLVM, its something you have to get your head around. I recommend taking a look at the basics of single static assignment (SSA) and then at the IR reference guide and checking how other parts are implemented. The implementation of strncmp might be a good starting point: https://github.com/iovisor/bpftrace/blob/14ec7eaf32e3fa3818497a8a6361a77bb5c49189/src/ast/irbuilderbpf.cpp#L735

**Comment by liutingjieni** [comment]
This branch( 0.12.1_release) is used because there was a problem compiling the master. https://github.com/iovisor/bpftrace/issues/1610

**Comment by fbs** [comment]
0.12 is 1.5y old by now. Any work you do you'd have to rebase against master and that will be a massive challenge. Please make sure you have an up to date bcc and libbpf. You might have to compile those your self as debian 10 is fairly old

**Comment by liutingjieni** [comment]
Ok, I will update my developer computer to debian11 and rebuild the development environment. Thanks for your reply

**Comment by viktormalik** [comment]
Completed via #2393.
