### ISSUE TITLE
make fails due to error: ‘GTEST_SKIP’ was not declared in this scope

### ISSUE THREAD

**Issue by akanksha216** [iovisor/bpftrace#2312]
### What reproduces the bug?
Followed the steps from install.md file for fedora to build bpftrace .
'make -j8' throws the following error:
`make[2]: *** [tests/CMakeFiles/bpftrace_test.dir/build.make:146: tests/CMakeFiles/bpftrace_test.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/root/ak/bpftrace/tests/clang_parser.cpp: In member function ‘virtual void bpftrace::test::clang_parser::clang_parser_btf_unresolved_typedef_Test::TestBody()’:
/root/ak/bpftrace/tests/clang_parser.cpp:648:5: error: ‘GTEST_SKIP’ was not declared in this scope
     GTEST_SKIP();
     ^~~~~~~~~~
/root/ak/bpftrace/tests/clang_parser.cpp:648:5: note: suggested alternative: ‘GTEST_FAIL’
     GTEST_SKIP();
     ^~~~~~~~~~
     GTEST_FAIL`

### bpftrace --info

System
  OS: Linux 4.18.0-409.el8.ppc64le #1 SMP Tue Jul 12 00:27:15 EDT 2022
  Arch: ppc64le

Build
  version: v0.15.0-69-g7a81
  LLVM: 14.0.6
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libbpf bpf_prog_load: no
  libbpf bpf_map_create: no
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: yes
  skboutput: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes
  kprobe_multi: no
  raw_tp_special: yes

**Comment by fbs** [comment]
Do you have the correct version of gtest installed? Can you try building with the `-DVENDOR_GTEST=ON` cmake flag?

**Comment by akanksha216** [comment]
With the above mentioned solution , the make was successful and not finding the error.

**Comment by fbs** [comment]
yay
