### ISSUE TITLE
BEGIN probe exit with -1

### ISSUE THREAD

**Issue by caizixian** [iovisor/bpftrace#2318]
### What reproduces the bug?
`bpftrace -e 'BEGIN { printf("Hello eBPF!\n"); }'` on Ubuntu 18.04 with 5.4 HWE kernel. bpftrace, bcc, and libbpf are all built from source with LLVM 12.

Can reproduce this issue with the static `bpftrace` built using the [build-static.sh](https://github.com/iovisor/bpftrace/blob/master/build-static.sh) script. 

The output
```
bpftrace -e 'BEGIN { printf("Hello eBPF!\n"); }'
Attaching 1 probe...

echo $?
255
```

bpftrace commit: `05cfa8e6cde2d16cdaabe4ad16eb7fd4d793b6ec`
bcc commit: `0e29f7032897f2ebdd4c617910aa8ade74bc4b23`
libbpf commit: `0e43565ad8b4f7bdfa974916e9d7f800157d06ec`

Same problem with the END probe. 

Other probes seem to work fine, such as `bpftrace --unsafe -e 'tracepoint:syscalls:sys_enter_nanosleep { printf("%s is sleeping.\n", comm); }'`

### bpftrace --info
```
System
  OS: Linux 5.4.0-105-generic #119~18.04.1-Ubuntu SMP Tue Mar 8 11:21:24 UTC 2022
  Arch: x86_64

Build
  version: v0.15.0-75-g05cf
  LLVM: 12.0.1
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libbpf bpf_prog_load: yes
  libbpf bpf_map_create: yes
  libdw (DWARF support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: no
  dpath: no
  skboutput: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  map batch: no
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
  iter:task: no
  iter:task_file: no
  kprobe_multi: no
  raw_tp_special: yes
```

**Comment by caizixian** [comment]
I ran `strace`, and apparently the 5.4 kernel doesn't support `bpf_prog_test_run_opts`.

However, this symbol is in `bpf.h` from libbpf, so bpftrace tries to use `bpf_prog_test_run_opts` like here. 

https://github.com/iovisor/bpftrace/blob/05cfa8e6cde2d16cdaabe4ad16eb7fd4d793b6ec/src/bpftrace.cpp#L1029 

The current workaround I had is to comment out 

https://github.com/iovisor/bpftrace/blob/05cfa8e6cde2d16cdaabe4ad16eb7fd4d793b6ec/cmake/FindLibBpf.cmake#L57

**Comment by viktormalik** [comment]
cc @danobi

The problem seems to be that libbpf has `bpf_prog_test_run_opts` but the kernel doesn't have the `BPF_PROG_TEST_RUN` command, so we should check for it, too.

**Comment by danobi** [comment]
@caizixian can you give the linked PR a try please?

**Comment by caizixian** [comment]
@danobi Thanks a lot for the fix. I will test and report back.

**Comment by danobi** [comment]
ping @caizixian

**Comment by caizixian** [comment]
@danobi thanks for reminding and for the fix. Yes, I can confirm the problem is now fixed.
