### ISSUE TITLE
bpftrace cannot attach kprobe to module symbol+offset

### ISSUE THREAD

**Issue by BurntBrunch** [iovisor/bpftrace#2327]
### What reproduces the bug?
Trying to attach to an offset in a module function always fails. (`icmp_match` is in `ip_tables.ko`)

```
sudo src/bpftrace -e 'kprobe:icmp_match {print("enter\n"); exit()}'
Attaching 1 probe...
^C
```

```
sudo src/bpftrace -e 'kprobe:icmp_match+0x1 {print("enter\n"); exit()}'
Attaching 1 probe...
ERROR: Could not resolve symbol icmp_match. Use BPFTRACE_VMLINUX env variable to specify vmlinux path. Compile bpftrace with ALLOW_UNSAFE_PROBE option to force skip the check.
```

### bpftrace --info
```
System
  OS: Linux 5.18.17-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug 11 14:36:06 UTC 2022
  Arch: x86_64

Build
  version: v0.15.0-85-g14ec
  LLVM: 14.0.0
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libbpf bpf_prog_load: yes
  libbpf bpf_map_create: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: yes
  skboutput: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes
  kprobe_multi: no
  raw_tp_special: yes
```

### Discussion

This fails because we try to verify the kprobe offset ourselves in order to disallow offsets in the middle of instructions or outside of functions. When we do that, we end up parsing symbol tables for the kernel (thus requiring kernel debug symbols to be present, which is not documented anywhere afaict) but not for any modules.

The discussion in #956 shows that this was chosen because it produces better sanity checks, even though it does not add any safety per se. The kprobe machinery in the kernel already verifies that the location is viable in more ways than just "is at instruction boundary."

Given that this logic breaks module attachment with offsets and there's no viable way to extend it (we can't reasonably parse all modules' debug info), I think we can
1) save us a bunch of file system lookups
2) save us a bunch of symbol scanning and disassembly and
3) remove the need for kernel debug symbols
by just letting perf_event_open fail with its message? Perhaps we can extend the user-visible error string with diagnostics on possible failure modes?

@mmisono, @danobi, I'd love to hear you input!

**Comment by mmisono** [comment]
Given that the kprobe checks offset and prevents invalid attachment which breaks kernel, I think it is OK to let the check if the offset is within the function or not optional. In other words, if bpftrace finds the symbol, then it will perform checks. Otherwise, it can print some warning messages if -v is given and continue.

**Comment by danobi** [comment]
Opportunistic check for function boundaries sgtm. Probably don't need the insn alignment check.

**Comment by anakryiko** [comment]
Why not rely on kallsyms for looking up symbols? That will work for both vmlinux and kernel modules. You can only approximate function size because kallsyms doesn't record it, but that's still better than nothing.

**Comment by danobi** [comment]
@anakryiko I believe bpftrace uses `/sys/kernel/debug/tracing/available_filter_functions` to check that the requested symbol exists. Then uses `perf_event_open`'s `config1` to pass in kprobe func as a string. So we don't really need to resolve the addr of the symbol. We use vmlinux symbol table to check that the kprobe offset (eg `kprobe:my_func+0x5`), if provided, is still inside the requested symbol. Which I think is probably fine to do opportunistically.

**Comment by anakryiko** [comment]
@danobi the first part makes sense, the second -- reliance on having vmlinux image access seems like a complication. kallsyms seems like a better mechanism for the second part as it contains both vmlinux symbols and all the loaded module's ones. But I have no horse in the race, whatever makes most sense to bpftrace maintainers.

**Comment by danobi** [comment]
@anakryiko which is the second part? Checking vmlinux symbol table to find function sizes? 

Just trying to understand better what the options are.

**Comment by BurntBrunch** [comment]
> Checking vmlinux symbol table to find function sizes?

I think @anakryiko is saying we can use the kallsyms addresses to do a binary search on the symbol+offset addr and see if it falls on the same symbol. This would work in most egregious cases but would miss things the current vmlinux approach catches.

Personally, I don't think the overhead of finding a vmlinux image with debug symbols and parsing it is worth this sanity check.

Besides, there might be legitimate cases (attachment to something you saw in dmesg) that are expressed by the kernel as symbol + greater-than-symbol-size-offset that the kernel would allow attaching to but bpftrace deny it (without `--unsafe`).

**Comment by danobi** [comment]
> I think @anakryiko is saying we can use the kallsyms addresses to do a binary search on the symbol+offset addr and see if it falls on the same symbol. This would work in most egregious cases but would miss things the current vmlinux approach catches.

I see, that's an interesting technique.

> Personally, I don't think the overhead of finding a vmlinux image with debug symbols and parsing it is worth this sanity check.

Is the overhead noticible? I trace w/ kprobe relatively often and I haven't noticed it. I kinda like the extra sanity checks in case I typo and I end up tracing some totally unrelated function. Users are usually not tracing when things are going well -- better to prevent any further issues.

**Comment by BurntBrunch** [comment]
> Is the overhead noticible?

Only one way to find out! :smiley: 

I profiled startup and it looks like the kprobe attachment with offset is dominated by the `available_filter_functions` parsing and the verification part is tiny in comparison. 
The vast majority of the cost is in the kernel but there's some minor (~5% of cycles) STL usage improvements we can do too.

**Comment by anakryiko** [comment]
the issue with expecting to find symbol in vmlinux is not so much performance rather that kernel module symbols are not found there and cause unnecessary failures. I thought we were trying to fix that?

**Comment by danobi** [comment]
> I thought we were trying to fix that?

The linked PR does fix it, doesn't it?.

**Comment by anakryiko** [comment]
> > I thought we were trying to fix that?
> 
> The linked PR does fix it, doesn't it?.

Didn't see the PR. It alleviates the problem, yes. It will still emit invalid claim about failure to resolve the symbol, but that's guarded by verbose option, so I guess it's fine.

The point, though, is that kernel modules are not supported at the same level as vmlinux in this case. But I'll let you guys decide what and whether you want to do anything about that.
