### ISSUE TITLE
./build 

### ISSUE THREAD

**Issue by TanCharles** [iovisor/bpftrace#2350]
### bpftrace --info
 Using cache
 ---> 1a3247018652
Step 12/12 : ENTRYPOINT ["bash", "/build.sh"]
 ---> Using cache
 ---> e5cdbdd29fab
Successfully built e5cdbdd29fab
Successfully tagged bpftrace-builder-focal:latest
/mnt/test/bpftrace
CMake Error at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Please install the libbpf development package (missing: LIBBPF_LIBRARIES
  LIBBPF_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibBpf.cmake:31 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:103 (find_package)

-- Configuring incomplete, errors occurred!
See also "/mnt/test/bpftrace/build-release-focal/CMakeFiles/CMakeOutput.log".
See also "/mnt/test/bpftrace/build-release-focal/CMakeFiles/CMakeError.log".
-->

Already installed libbpf package

**Comment by danobi** [comment]
Can you try with this patch applied?
```diff
diff --git a/build.sh b/build.sh
index 4da38426..643c90c2 100755
--- a/build.sh
+++ b/build.sh
@@ -3,5 +3,6 @@ set -e
 export BASE=focal
 export LLVM_VERSION=12
 export RUN_TESTS=1
+export BUILD_LIBBPF=ON
 ./build-docker-image.sh
 ./build-release.sh "$@"
```

**Comment by miwojcik** [comment]
I have the same problem. Unfortunately the patch doesn't solve it.

**Comment by TanCharles** [comment]
> 你可以试试这个补丁吗？
> 
> ```diff
> diff --git a/build.sh b/build.sh
> index 4da38426..643c90c2 100755
> --- a/build.sh
> +++ b/build.sh
> @@ -3,5 +3,6 @@ set -e
>  export BASE=focal
>  export LLVM_VERSION=12
>  export RUN_TESTS=1
> +export BUILD_LIBBPF=ON
>  ./build-docker-image.sh
>  ./build-release.sh "$@"
> ```

Thank you. Maybe it has something to do with my operating system. My operating system is Euler

**Comment by TanCharles** [comment]
> 我也有同样的问题。不幸的是，补丁并没有解决它。

 Maybe it has something to do with my operating system. My operating system is Euler

**Comment by viktormalik** [comment]
The problem is that you're missing the libbpf package. If Euler is not packaging it, you have to install from source (which is exactly what the above patch does).

@miwojcik could you try installing libbpf manually from https://github.com/libbpf/libbpf?

**Comment by chengshuyi** [comment]
```
diff --git a/build-release.sh b/build-release.sh
index 2029c588..cd5c93d2 100755
--- a/build-release.sh
+++ b/build-release.sh
@@ -1,3 +1,3 @@
 #!/bin/bash
 set -eu
-docker run --network host --rm -it -u $(id -u):$(id -g) -v $(pwd):$(pwd) -e STATIC_LINKING=OFF -e STATIC_LIBC=OFF -e ALLOW_UNSAFE_PROBE=OFF -e VENDOR_GTEST=ON -e RUN_TESTS=${RUN_TESTS} bpftrace-builder-${BASE} "$(pwd)/build-release-${BASE}" Release "$@"
+docker run --network host --rm -it -u $(id -u):$(id -g) -v $(pwd):$(pwd) -e STATIC_LINKING=OFF -e STATIC_LIBC=OFF -e ALLOW_UNSAFE_PROBE=OFF -e VENDOR_GTEST=ON -e RUN_TESTS=${RUN_TESTS} -e BUILD_LIBBPF=ON bpftrace-builder-${BASE} "$(pwd)/build-release-${BASE}" Release "$@"
```
Can you try with this patch applied?

**Comment by miwojcik** [comment]
It looks to be a move in good direction, because libbpf build is now started in `docker/build.sh` script, but it fails to create `/src` directory:
```
~/bpftrace/docker ~/bpftrace
Sending build context to Docker daemon  20.48kB
Step 1/12 : FROM ubuntu:focal
 ---> a0ce5a295b63
Step 2/12 : ARG LLVM_VERSION
 ---> Using cache
 ---> 0731057d2519
Step 3/12 : ENV LLVM_VERSION=$LLVM_VERSION
 ---> Using cache
 ---> 9ddca20efe06
Step 4/12 : RUN apt-get update && apt-get install -y curl gnupg &&    llvmRepository="\ndeb http://apt.llvm.org/focal/ llvm-toolchain-focal main\ndeb-src http://apt.llvm.org/focal/ llvm-toolchain-focal main\ndeb http://apt.llvm.org/focal/ llvm-toolchain-focal-${LLVM_VERSION} main\ndeb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-${LLVM_VERSION} main\n" &&    echo $llvmRepository >> /etc/apt/sources.list &&     curl -L https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - &&     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4052245BD4284CDD
 ---> Using cache
 ---> 4044a97eecf4
Step 5/12 : RUN curl -L --output /tmp/cmake.tar.gz   https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0-linux-x86_64.tar.gz   && tar -xf /tmp/cmake.tar.gz -C /usr/local/ --strip-components=1
 ---> Using cache
 ---> 4e8560612572
Step 6/12 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 6c7350c9dd72
Step 7/12 : RUN apt-get update && apt-get install -y       make       pkg-config       asciidoctor       bison       binutils-dev       flex       g++       git       libelf-dev       zlib1g-dev       libbpfcc-dev       libcereal-dev       libdw-dev       libpcap-dev       clang-${LLVM_VERSION}       libclang-${LLVM_VERSION}-dev       libclang-common-${LLVM_VERSION}-dev       libclang1-${LLVM_VERSION}       llvm-${LLVM_VERSION}       llvm-${LLVM_VERSION}-dev       llvm-${LLVM_VERSION}-runtime       libllvm${LLVM_VERSION}       systemtap-sdt-dev       python3       xxd       libssl-dev
 ---> Using cache
 ---> ed3eca524c1e
Step 8/12 : RUN if [ "$LLVM_VERSION" -ge 13 ] ; then apt-get install -y libmlir-${LLVM_VERSION}-dev ; fi
 ---> Using cache
 ---> 9ffe24847da0
Step 9/12 : RUN ln -s /usr/bin/python3 /usr/bin/python
 ---> Using cache
 ---> faa4f5b98812
Step 10/12 : COPY build.sh /build.sh
 ---> Using cache
 ---> ca238d6252db
Step 11/12 : RUN chmod 755 /build.sh
 ---> Using cache
 ---> 5c337eb7d60e
Step 12/12 : ENTRYPOINT ["bash", "/build.sh"]
 ---> Using cache
 ---> 90b5c333d265
Successfully built 90b5c333d265
Successfully tagged bpftrace-builder-focal:latest
~/bpftrace
mkdir: cannot create directory '/src': Permission denied
```

**Comment by viktormalik** [comment]
Hi, we have changed the way we're using BCC/libbpf. By default, both are vendored (built from source) in their last version. If you want to use system BCC and libbpf, you need to pass `USE_SYSTEM_BPF_BCC=1` to the `build.sh` script (or to the `docker run` command).

That said, `build-release.sh` should now work out of box. Could you give it a try?

**Comment by miwojcik** [comment]
Classic `build.sh` now works fine for me @viktormalik. Great job!

**Comment by viktormalik** [comment]
Thanks for confirmation @miwojcik!
