### ISSUE TITLE
ustack  error

### ISSUE THREAD

**Issue by liutingjieni** [iovisor/bpftrace#2353]
### What reproduces the bug?

Printing the stack of a thread, there will be an occasional error( I confirm that I have not called any kernel functions in the function of this thread). But if the function is called by the main thread to print its stack, there will be no error.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/46086382/189134514-5e7be9b8-a9f3-4cd7-89e0-bba0d039c36f.png">

I found the source of this error, but I rely on don't understand why?
![c71lUvmXSH](https://user-images.githubusercontent.com/46086382/189136182-a7650b8a-575b-486b-99cf-45e2dc2578c0.png)

**Comment by BurntBrunch** [comment]
Do you have a way to reproduce this? Have you tried running with `bpftrace -kk` to verify the kernel side program is not emitting errors?
