### ISSUE TITLE
Buffer mechanism required

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#236]
I think some thought needs to go into designing a buffering mechanism for trace output and I'm logging this issue as a placeholder for thoughts and ideas on this.

Currently it looks like we just throw output to stdout and are therefore at the mercy of terminal disciplines and output buffering. Take the following trivial example:

```
#  bpftrace -e 'BEGIN { printf("Hello, World!"); }'
Attaching 1 probe...
```

We never see the "Hello, World!" output until the bpftrace process exits as the output is buffered in the processes stdout. If I add a '\n' or set the size of the output descriptors buffer to 0 then the output is seen immediately:

```
[root@devvm1362.cln1 /root/BPF] stdbuf  -o0  bpftrace -e 'BEGIN { printf("Hello, World!"); }'
Attaching 1 probe...
Hello, World!
```

Apologies for having no real substance at the minute but I'll revisit with further thoughts when time allows.

**Comment by ajor** [comment]
Not sure if this would come under the same ticket, but some kind of rate limiting on output would be good too. If I run a script like `tracepoint:sched:sched_switch { printf("hi\n") }` then the printfs are happening so frequently that my `^C` isn't registered and I have to `kill` bpftrace manually.

**Comment by FooBarWidget** [comment]
Ask and you shall receive. See my pull request.
