### ISSUE TITLE
enforce_inifinite_rlimits() needs tidying up

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#240]
This is a small task and a simple fix.

`main.cpp:enforce_infinite_rlimit()` has a few issues that need tidying up:

* The `getrlimit()` call is not needed and can be removed (at least I can't see a reason for its existence in the current form of the code).
* If it was to stay then the error message needs changing - 's/set/get' in that error string.
* Do the `struct rlimit` initialisation when it is declared - it's just tidier.
* In the error messages dump both the errno and a textual representation of that (i.e., `strerror()`).

**Comment by ajor** [comment]
What was this code needed for anyway? I thought BCC handled the rlimit stuff for us

**Comment by sourabhtk37** [comment]
@tyroguru I'd like to take this issue up. Added PR #391
