### ISSUE TITLE
invalid func unknown#111

### ISSUE THREAD

**Issue by tanjianfeng** [iovisor/bpftrace#2403]
### What reproduces the bug?

$ docker run -ti -v /usr/src:/usr/src:ro -v /lib/modules/:/lib/modules:ro -v /sys/kernel/debug/:/sys/kernel/debug:rw --net=host --pid=host --privileged quay.io/iovisor/bpftrace:latest bpftrace -v --include linux/skbuff.h -e 'kprobe:napi_gro_receive { $skb = ((struct sk_buff *)arg1); $ret = skboutput("receive.pcap", $skb, $skb->len, 0); }'

INFO: node count: 16
Attaching 1 probe...

Error log: 
0: (79) r6 = *(u64 *)(r1 +104)
1: (b7) r1 = 30011
2: (7b) *(u64 *)(r10 -32) = r1
3: (b7) r1 = 0
4: (7b) *(u64 *)(r10 -24) = r1
5: (85) call bpf_ktime_get_ns#5
6: (7b) *(u64 *)(r10 -16) = r0
7: (bf) r3 = r6
8: (07) r3 += 128
9: (bf) r1 = r10
10: (07) r1 += -4
11: (b7) r2 = 4
12: (85) call bpf_probe_read#4
13: (61) r3 = *(u32 *)(r10 -4)
14: (67) r3 <<= 32
15: (18) r1 = 0xffffffff
17: (4f) r3 |= r1
18: (18) r2 = 0xffff889e97c23c00
20: (bf) r4 = r10
21: (07) r4 += -32
22: (bf) r1 = r6
23: (b7) r5 = 24
24: (85) call unknown#111
invalid func unknown#111

ERROR: Error loading program: kprobe:napi_gro_receive

### bpftrace --info

run -ti -v /usr/src:/usr/src:ro -v /lib/modules/:/lib/modules:ro -v /sys/kernel/debug/:/sys/kernel/debug:rw --net=host --pid=host --privileged quay.io/iovisor/bpftrace:latest bpftrace --info
System
  OS: Linux 4.19.91 #1 SMP Fri Jun 4 21:54:18 CST 2021
  Arch: x86_64

Build
  version: v0.16.0
  LLVM: 12.0.0
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libbpf bpf_prog_load: yes
  libbpf bpf_map_create: yes
  libdw (DWARF support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: yes
  send_signal: no
  override_return: no
  get_boot_ns: no
  dpath: no
  skboutput: no

Kernel features
  Instruction limit: 131072
  Loop support: no
  btf: no
  map batch: no
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
  iter:task: no
  iter:task_file: no
  kprobe_multi: no
  raw_tp_special: no

### cat /boot/config-`uname -r` | grep BTF
<none>

Does skboutput need BTF?

**Comment by xh4n3** [comment]
Hi @tanjianfeng , what kernel version are you on? The skboutput function relys on `bpf_skb_output`, which is only available after kernel 5.5
https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md#helpers

**Comment by tanjianfeng** [comment]
Thanks for the timely reply. Will close this issue.

**Comment by fbs** [comment]
Shouldnt the run time feature checking check whether this call is available?

**Comment by xh4n3** [comment]
@fbs Ah you're right, let me fix that #2404
