### ISSUE TITLE
Codegen tests have been failing for a while and no one noticed

### ISSUE THREAD

**Issue by BurntBrunch** [iovisor/bpftrace#2412]
If a ~~tree~~ test ~~falls~~ fails in a forest, does it ~~make a sound~~ matter? :smiley: 

codegen tests have been failing (i.e. scripts/update_codegen_tests.sh fails) since f9dbbc8f076947f11c774aeef8080eb35137a8b0 and no one noticed. 

I think something or other needs to be mocked but more to the overall point - do we actually think these tests matter? I'm firmly on the "no" side - there's nothing they'd catch that won't also break other, potentially more precise, runtime and unit tests.

The fact that this wasn't caught in CI is also surprising and kinda tells how much they're valued anyway.

cc @michalgr @fbs

P.S. The failures are [here](https://gist.github.com/BurntBrunch/a4ec1e1b3327b502a706c9ebd0c57e23).

**Comment by fbs** [comment]
`update_codegen_tests.sh` itself is not a test right? It's just a helper.

The value of the codegen tests has been up for debate before. I think they are shitty but they're the best we have at the moment. They do help to spot if changes cause unexpected codegen changes

**Comment by BurntBrunch** [comment]
> update_codegen_tests.sh itself is not a test right? It's just a helper.

Yeah but it fails on the tests themselves - the tests just don't get run in CI on 12 I guess? Idk how the failures got missed, they're straight-up parsing/semantic failures.

**Comment by michalgr** [comment]
I am sorry about that, I'll put up a fix

**Comment by BurntBrunch** [comment]
> I am sorry about that, I'll put up a fix

Actually, @michalgr, I'm not sure what's going on here. I see the tests running and passing [here](https://github.com/iovisor/bpftrace/actions/runs/3383589871/jobs/5619628660). I can no longer reproduce the failure above either.

I'll chalk it up to something weird in my local setup and close this issue.

**Comment by michalgr** [comment]
Depending on your distro tracefs might be located either under "/sys/kernel/debug/tracing" or ""/sys/kernel/tracing". My change added some static state keeping track of whether it's accessible via debugfs or not. I expect those tests fail when "/sys/kernel/debug/tracing" is not present.
