### ISSUE TITLE
get all arguments values of a function as a string in uprobe and kprobe. something like $$parms in systemtap do.

### ISSUE THREAD

**Issue by simpzan** [iovisor/bpftrace#2436]
### Is your feature request related to a problem? Please describe.
I want to print all argument values of many traced functions with uprobe and kprobe. 

### Describe the solution you'd like
provide api to get function's all argument values as a string. some like $$parms in systemtap. https://sourceware.org/systemtap/SystemTap_Beginners_Guide/targetvariables.html

### Describe alternative solutions or features you've considered
Or simpler just provide a variable for the number of argument of each traced function. Then I can just write a loop myself to construct the arguments in a string.

**Comment by fbs** [comment]
> Or simpler just provide a variable for the number of argument of each traced function. Then I can just write a loop myself to construct the arguments in a string.

Don't you need the type as well? If you just know the number of arguments you have to treat everything like an int and hope it prints ok.

BTF provides us with all the info we need, guess what you want is something like:

```
kfunc:xxx {
  print(args)
}
```

`args` would then be formatted like any other struct and we can use BTF to fill in field names and properly format each type

**Comment by simpzan** [comment]
> > Or simpler just provide a variable for the number of argument of each traced function. Then I can just write a loop myself to construct the arguments in a string.
> 
> Don't you need the type as well? If you just know the number of arguments you have to treat everything like an int and hope it prints ok.
Yes, you are right. It's a downgraded implementation.

> 
> BTF provides us with all the info we need, guess what you want is something like:
> 
> ```
> kfunc:xxx {
>   print(args)
> }
> ```
> 
> `args` would then be formatted like any other struct and we can use BTF to fill in field names and properly format each type
Yes, it will be great if bpftrace support this for both uprobe and kprobe.

**Comment by fbs** [comment]
> Yes, it will be great if bpftrace support this for both uprobe and kprobe.

The thing with kprobes is that we don't have the type info so the implementation is mediocre at best. I'm worried its going to be a useless footgun instead of being helpful. Even if you print it as integers the different bit widths can confuse the data, depending on the architecture. If its stack based its worse than register based.

For uprobes it should be doable, assuming we have dwarf or other debug info

**Comment by viktormalik** [comment]
Agreed with @fbs, but we could support it for kfuncs (via BTF) and uprobes (via DWARF). Would that be sufficient?

**Comment by simpzan** [comment]
> Agreed with @fbs, but we could support it for kfuncs (via BTF) and uprobes (via DWARF). Would that be sufficient?

Yes, it will be sufficient. Thank you!
