### ISSUE TITLE
TextMate grammar / VS Code extension?

### ISSUE THREAD

**Issue by bolinfest** [iovisor/bpftrace#244]
I started to create a VS Code extension for bpftrace files. Currently the only thing it includes of any significance is a TextMate grammar:

https://github.com/bolinfest/bpftrace-vscode/blob/master/syntaxes/bpftrace.tmLanguage.json

This is my first TextMate grammar, so I'm sure it's terrible, but at least `.bt` files look much nicer in VS Code now:

![image](https://user-images.githubusercontent.com/655869/48296703-14f5c300-e44f-11e8-82b4-fecefb03892b.png)

I can continue to develop the VS Code extension on my own, but maybe it would be better if it were part of the bpftrace repo or were its own repo under iovisor? If you don't want to take it, I'm happy to keep it under my name, but I thought I'd check first before publishing to the VS Code extension marketplace.

In the limit, ideally the extension would also surface a simple [LSP](https://microsoft.github.io/language-server-protocol/) for `.bt` files so it would provide more than just syntax highlighting. To do that well, it probably requires a recoverable parser, but maybe we can at least get some nice hover functionality when the file parses.

**Comment by ajor** [comment]
Thanks, this is really cool! I think it'd be best to keep it in a separate repository from bpftrace, but we could add a link to your repo in the bpftrace readme

**Comment by jgkamat** [comment]
I've created an [emacs major mode](https://gitlab.com/jgkamat/bpftrace-mode) for bpftrace as well. Since the syntax is very similar to c, it's actually very trivial (just adding highlighting for the bpftrace-specific keywords and syntax ontop of the c font-lock tables).

If `bpftrace -d` was a little better behaved, it would be easy to add a syntax checker as well (see #707).

**Comment by mmarchini** [comment]
I started to work on a [vim plugin](https://github.com/mmarchini/bpftrace.vim) for bpftrace files, if anyone is interested. Still missing a lot of things (struct, array access, etc.), but it's a start.

**Comment by jordalgo** [comment]
Closing this as the recommendation is to link to plugins from the readme.

**Comment by jgkamat** [comment]
@jordalgo, should we submit a pull request to add plugin links to the bpftrace readme? I'm not sure if there's a better place to have them end up, sorry.

**Comment by jordalgo** [comment]
@jgkamat Sure, let's try it there first with a new sub-heading.
