### ISSUE TITLE
bpftrace falsely reports lockdown=confidentiality on Ubuntu 18.04?

### ISSUE THREAD

**Issue by thomasdullien** [iovisor/bpftrace#2455]
I am operating on a Ubuntu 18.04 machine with lockdown set to `[none]`, but due to the line 
https://github.com/iovisor/bpftrace/blob/5082168e6138b636df373bb3b649391261d77441/src/lockdown.cpp#L78 bpftrace falsely reports that lockdown is set to confidentiality. This entire line looks like a bit of a hack -- why can't Ubuntu 19 not read `/sys/kernel/security/lockdown` ?

```
root@censored:/home/ubuntu# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
root@censored:/home/ubuntu# cat /sys/kernel/security/lockdown
[none] integrity confidentiality
```

**Comment by fbs** [comment]
The comment above it has some details:

```
  // Ubuntu (19.10 at least) ships a lockdown version that fully blocks the bpf
  // syscall
  ```
  
  If thats no longer true we should revisit it, its been 2 years

**Comment by florianl** [comment]
The same issue is tracked also in https://github.com/iovisor/bcc/issues/2565

In the meantime Ubuntu switched to `LOCKDOWN_INTEGRITY_MAX` mode from `LOCKDOWN_CONFIDENTIALITY_MAX` by default with commit https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/focal/commit/?id=ef7c6600bb3e347a1ddff83bcd40454c221a64c3

As @thomasdullien suggested, `/sys/kernel/security/lockdown` should be preferred to get the correct security mode.

**Comment by viktormalik** [comment]
I tried to run a Ubuntu 18.04 VM without secure boot but there's no `/sys/kernel/security/lockdown` node there. Am I doing something wrong?

Anyway, the node exists on all other supported Ubuntu versions, so I removed the hack in #2467 to read `/sys/kernel/security/lockdown` for all systems. Could you please check that it works with the fix?
