### ISSUE TITLE
0.17 changelog doesn't mention strcontains

### ISSUE THREAD

**Issue by yump** [iovisor/bpftrace#2497]
### What reproduces the bug?

1. See `strcontains` in the [refererence guide on Github](https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md).

2. Attempt to use it on version 0.16, resulting in `ERROR: Unknown function: strcontains`.

3. Look on the releases page to see if it's too new, finding nothing.

4. Dig up #2393 in the history of `lexer.l`.

### bpftrace --info

bpftrace v0.16.0

I don't know what you want to do here.  I was about to make a PR for it, but I realized altering the changelog of a version already released could be considered poor etiquette, if it is even possible.

**Comment by fbs** [comment]
yeah seems like we forgot it. We can just add it to the changelog in master and update the release in github. Doing a release might be a but much

**Comment by viktormalik** [comment]
Agreed with @fbs, doing a release is too much. Not sure if we want to override an existing release, though - could it break anything? If not, then I have no objections.

**Comment by fbs** [comment]
it just updates the release description in github afaik. It still linked to the same tag so on the git side nothing changes

**Comment by viktormalik** [comment]
Then let's do it :)

**Comment by viktormalik** [comment]
@fbs any progress on this? Should I have a look?

**Comment by fbs** [comment]
its now in https://github.com/iovisor/bpftrace/releases/tag/v0.17.0
