### ISSUE TITLE
Can't attach to usdt

### ISSUE THREAD

**Issue by purpleP** [iovisor/bpftrace#2504]
```
$ sudo ~/Downloads/bpftrace -p `pidof usdt` -e 'usdt:/home/m/code/aya-examples/usdt/target/release/usdt:hello_provider:hello { printf("%d", arg0); }'
ERROR: couldn't get argument 0 for /home/m/code/aya-examples/usdt/target/release/usdt:hello_provider:hello

$ readelf -n /home/m/code/aya-examples/usdt/target/release/usdt

Displaying notes found in: .note.gnu.property
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_PROPERTY_TYPE_0
      Properties: x86 ISA needed: x86-64-baseline

Displaying notes found in: .note.gnu.build-id
  Owner                Data size 	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: 69f2454147ab0999f77b0a90a2fcb62b74b47cc6

Displaying notes found in: .note.ABI-tag
  Owner                Data size 	Description
  GNU                  0x00000010	NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 3.2.0

Displaying notes found in: .note.stapsdt
  Owner                Data size 	Description
  stapsdt              0x00000035	NT_STAPSDT (SystemTap probe descriptors)
    Provider: hello_provider
    Name: hello
    Location: 0x000000000000887b, Base: 0x0000000000045006, Semaphore: 0x0000000000051032
    Arguments: -8@%rax

```

### bpftrace --info
```
sudo ~/Downloads/bpftrace --info
System
  OS: Linux 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023
  Arch: x86_64

Build
  version: v0.17.0
  LLVM: 12.0.0
  unsafe uprobe: no
  bfd: yes
  libdw (DWARF support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes
  kprobe_multi: yes
  raw_tp_special: yes
```

`trace.py` works just fine and prints the argument.

**Comment by purpleP** [comment]
I've seen a similar issue and tried to use the name of a binary as provider name. It somehow worked a few times and then stopped.

**Comment by viktormalik** [comment]
We're relying on BCC with USDT probes so it's hard to debug anything without the source (or at least the binary). Could you perhaps provide a minimal example to reproduce this?

**Comment by purpleP** [comment]
> We're relying on BCC with USDT probes so it's hard to debug anything without the source (or at least the binary). Could you perhaps provide a minimal example to reproduce this?
[out.tar.gz](https://github.com/iovisor/bpftrace/files/10730982/out.tar.gz)
https://github.com/purpleP/aya-examples

**Comment by viktormalik** [comment]
Interesting, I wasn't able to reproduce this issue (the program attaches fine) but the probe never fires. Tested with the latest master. I'll try to debug it more when I have time.

**Comment by lenticularis39** [comment]
It works for me with both static bpftrace and master bpftrace:
```
# /tmp/bpftrace-static --info
System
  OS: Linux 4.18.0-425.10.1.el8_7.x86_64 #1 SMP Wed Dec 14 16:00:01 EST 2022
  Arch: x86_64

Build
  version: v0.17.0
  LLVM: 12.0.0
  unsafe uprobe: no
  bfd: yes
  libdw (DWARF support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes
  kprobe_multi: no
  raw_tp_special: yes
```

```
# /tmp/bpftrace-static -p `pidof usdt` -e 'usdt:/tmp/usdt/target/release/usdt:hello_provider:hello { printf("%d\n", arg0); }'
Attaching 1 probe...
532855434
532855435
532855436
532855437
532855438
532855439
532855440
532855441
532855442
532855443
532855444
532855445
532855446
532855447
532855448
532855449
532855450
532855451
532855452
...
```

**Comment by purpleP** [comment]
> It works for me with both static bpftrace and master bpftrace:
> 
> ```
> # /tmp/bpftrace-static --info
> System
>   OS: Linux 4.18.0-425.10.1.el8_7.x86_64 #1 SMP Wed Dec 14 16:00:01 EST 2022
>   Arch: x86_64
> 
> Build
>   version: v0.17.0
>   LLVM: 12.0.0
>   unsafe uprobe: no
>   bfd: yes
>   libdw (DWARF support): no
> 
> Kernel helpers
>   probe_read: yes
>   probe_read_str: yes
>   probe_read_user: yes
>   probe_read_user_str: yes
>   probe_read_kernel: yes
>   probe_read_kernel_str: yes
>   get_current_cgroup_id: yes
>   send_signal: yes
>   override_return: yes
>   get_boot_ns: yes
>   dpath: yes
>   skboutput: no
> 
> Kernel features
>   Instruction limit: 1000000
>   Loop support: yes
>   btf: yes
>   map batch: yes
>   uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): no
> 
> Map types
>   hash: yes
>   percpu hash: yes
>   array: yes
>   percpu array: yes
>   stack_trace: yes
>   perf_event_array: yes
> 
> Probe types
>   kprobe: yes
>   tracepoint: yes
>   perf_event: yes
>   kfunc: yes
>   iter:task: yes
>   iter:task_file: yes
>   kprobe_multi: no
>   raw_tp_special: yes
> ```
> 
>  ```
> # /tmp/bpftrace-static -p `pidof usdt` -e 'usdt:/tmp/usdt/target/release/usdt:hello_provider:hello { printf("%d\n", arg0); }'
> Attaching 1 probe...
> 532855434
> 532855435
> 532855436
> 532855437
> 532855438
> 532855439
> 532855440
> 532855441
> 532855442
> 532855443
> 532855444
> 532855445
> 532855446
> 532855447
> 532855448
> 532855449
> 532855450
> 532855451
> 532855452
> ...
> ```

It also worked for me once in a while when provider was named the same way an executable was (you have an issue about it somewhere).

So is working stable? How much attempts you’ve made?

**Comment by lenticularis39** [comment]
> So is it working stably? How many attempts have you made?

I tried running both bpftrace and the executable over ten times and didn't get any errors, even with a different provider name from the executable name (`usdt` vs `hello-provider`).

**Comment by viktormalik** [comment]
This doesn't seem to be a bpftrace bug, can we close?
