### ISSUE TITLE
user switch from suid bit applications not detected

### ISSUE THREAD

**Issue by manfred-kaiser** [iovisor/bpftrace#2509]
I want to monitor systemcalls with bpftrace . For most systemcalls, this works as expected, but I have problems to monitor applications, where the suid bit is set.

My example application, a simple C application, which is owned by the root user and the suid bit is set:

```
$ sudo chown root testapp
$ sudo chmod +s testapp
$ ./testapp
```
`ps -aux` output:

`root       12408  0.0  0.0  14460  3352 pts/2    Sl+  14:46   0:00 ./testapp
`

Folowing syscalls are monitored (https://github.com/iovisor/bpftrace/blob/master/tools/setuids.bt):

-  setuid
-  setfsuid
-  setreuid
-  setresuid

I expect that their is a user switch to root which is monitored, because the application is owned by root and the suid bit is set.

When testing with "`su - testuser`", this also does not monitor the userswitch to root.

By listiing the running processes with "ps" the "su" command is run by "root":

```
$ ps -aux | grep su
root        7384  0.0  0.0  13000  4244 pts/0    S+   12:12   0:00 su - testuser
```

Why is this not detected by monitoring the mentioned syscalls?

I have tried "seteuid" (https://man7.org/linux/man-pages/man2/seteuid.2.html) because this should be used by suid bit applications, but seteuid is not known by bpftrace.

**Comment by fbs** [comment]
Setting the `setuid` flag doesn't change the application, so it shouldn't suddenly start performing syscalls it didn't do before. The logic must be in the kernel, and the kernel doesn't do systemcalls so it won't show up here as 'switch to root'.


> When testing with "su - testuser", this also does not monitor the userswitch to root.

But does it show up as 'switch to testuser'?

> I have tried "seteuid" (https://man7.org/linux/man-pages/man2/seteuid.2.html) 
This document states:

```
   C library/kernel differences
       On Linux, seteuid() and setegid() are implemented as library
       functions that call, respectively, setreuid(2) and setregid(2).
```

If its not a syscall you cannot trace it.

**Comment by manfred-kaiser** [comment]
@fbs Thanks for the information. I thought the kernel is using it's own system calls to switch the userids for the process.

> > When testing with "su - testuser", this also does not monitor the userswitch to root.
>
> But does it show up as 'switch to testuser'?

Only the systemcall "setuid" is captued. The start and userswitch due to the suid bit is not shown.

----

I have done some tests to learn more about bpftrace, systemcalls and processes.

For testing purposes, a copy of the `sleep` command is used.

    $ cp /bin/sleep ~
    $ sudo chown root ~/sleep
    $ sudo chmod +s ~/sleep
    $ ./sleep 1337

`ps` is used to verify, if the process is running with root-privileges:

    $ ps aux | grep sleep
    root  5552  0.0  0.0  16872  1012 pts/2  S+   10:18   0:00 ./sleep 1337
    

@fbs  As you mention, `execve` does not use the setuid(2) family syscalls to set the userids for the process. The function, where the suid bit is interpreted can be found in exec.c in the kernel sources: Here's an evidence that it's interpreted by `execve` https://github.com/torvalds/linux/blob/38f8ccde04a3fa317b51b05e63c3cb57e1641931/fs/exec.c#L1596

`bpftrace` only supports the `uid` in handlers, but not `euid`, `ruid`, and `fuid`. When executing applications, where the suid bit is set, the uid is the same as the user, who started the application. `euid`, `ruid` and `fuid` are changed to the owner of the file.

This can be verified by going to the process information in `/proc/{pid}/status` .

There is a line, which starts with `Uid:`

    Uid:	1000	0	0	0

The columns are defined as `uid`,  `euid`,  `ruid` and `fuid`. 

So I think with `bpftrace` it's not possible to monitor applications where the suid bit is set, but in combination with python (or another scripting language) the information can be combined with the information from the `/proc/ filesystem.

Example python script to monitor seuid bit applications:

Following `bpftrace`-script, which prints the command name and the pid is used. This is stored as `monitor.bt`.

    tracepoint:syscalls:sys_exit_exec*
    {
	    printf("%s;%d\n", comm, pid);
    }

Following python script executes `bpftrace` and reads the captured information from stdout:

```python
import os
import subprocess
import signal

def get_resuid(pid):
    '''Return username of UID of process pid'''
    pid_path = '/proc/{}/status'.format(pid)
    if os.path.isfile(pid_path):
        for ln in open(pid_path):
            if ln.startswith('Uid:'):
                return [int(x) for x in ln.split()[1:5]]
    return None

proc = subprocess.Popen(
    [
        '/home/manfred/bin/bpftrace',
        '-q',
        '/home/manfred/monitor.bt'
    ],
    stdout=subprocess.PIPE
)
while True:
  line = proc.stdout.readline()
  if not line:
    break
  comm, pid = line.decode().strip("\n").rsplit(";", maxsplit=1)
  pid = int(pid)
  uids = get_resuid(pid)
  if uids:
    print("{} -> {}".format(comm, uids))
```

The `bpfscript` monitors the execution of new application which are started with `execve` and prints the pid. This pid is used to get the uid, euid, ... from the proc filesystem and prints this information to stdout.

This will look like:

```
sleep -> [1000, 0, 0, 0]
```

The columns are specified as `uid`, `euid`, `ruid` and `fuid`.

----

**Is there a way to monitor suid bit applications only with bpftrace or is this not possible?**

**Comment by fbs** [comment]
`uid` is backed by the `bpf_get_current_uid_gid()` bpf helper which you can find here: https://elixir.bootlin.com/linux/latest/source/kernel/bpf/helpers.c#L230 following the code you can get the fields from `task_struct` which you get from the `curtask` builtin:  https://elixir.bootlin.com/linux/latest/source/include/linux/sched.h#L1064

It's an RCU field so it might need some tricky stuff, but my guess is that it's possible to get those other `*uid`s out

https://elixir.bootlin.com/linux/latest/source/include/linux/sched.h#L1064

**Comment by viktormalik** [comment]
This doesn't look like a bpftrace bug in the end. @manfred-kaiser can we close this?

**Comment by manfred-kaiser** [comment]
Thanks for the help and comments. As you wrote this is not a bug in bpftrace and this issue can be closed.
