### ISSUE TITLE
CommandLine Error: Option 'help-list' registered more than once!

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#251]
Just did git pull and build, and got:

```
$ ./src/bpftrace 
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

llvm-5.0 system.

**Comment by Leo-Yan** [comment]
I got another LLVM error as below:

root@debian:/mnt/linux-kernel/bpftrace# ./build/src/bpftrace 
: CommandLine Error: Option 'disable-inlined-alloca-merging' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

**Comment by mmarchini** [comment]
Introduced by 56fdbc0ac5ac4a92cea2f9aab5cc246b33498964. Trying to find a fix, otherwise, I suggest we revert it.

**Comment by mmarchini** [comment]
`find_library(found_LLVM LLVM)` is returning not found, thus we're taking the wrong path when building and we're not linking against LLVM correctly.

**Comment by chenhengqi** [comment]
:facepalm:  Still got this with llvm-12 installed:

```
bpftrace -h
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
[2]    10287 IOT instruction (core dumped)  bpftrace -h
```

**Comment by fbs** [comment]
Did you build bcc yourself, if you did make sure you dynamic link against llvm. See debc79ef9ad4784258705a92ae70f9c7689a9c24

**Comment by chenhengqi** [comment]
Yeah, that's the problem. Rebuild bcc and fixed. Thanks.

**Comment by chenk008** [comment]
bpftrace 0.12 is broken on centos with this error message

**Comment by fbs** [comment]
> bpftrace 0.12 is broken on centos with this error message

Can you provide some more details? Which build on which centos? The 8 build is not supplied by us. I maintain the centos 7 build and afaik that works :)

**Comment by bumblebeeK** [comment]
Nice!
