### ISSUE TITLE
casts should be ints if needed

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#252]
From #223 , we wanted a way to test whether args->ru was NULL. But casts can't currently can't be treated as ints.

Either these should work:

```
# bpftrace -e 'tracepoint:syscalls:sys_enter_wait4 /args->ru/ { printf("hi\n"); }'
Invalid type for predicate: cast

# bpftrace -e 'tracepoint:syscalls:sys_enter_wait4 { printf("hi %d\n", args->ru); }'
printf: %d specifier expects a value of type integer (cast supplied)
```

Or, these should work:

```
# bpftrace -e 'tracepoint:syscalls:sys_enter_wait4 /(int)args->ru/ { printf("hi\n"); }'
Unknown struct/union: 'int'

# bpftrace -e 'tracepoint:syscalls:sys_enter_wait4 { printf("hi %d\n", (int)args->ru); }'
Unknown struct/union: 'int'
```

**Comment by navytux** [comment]
yesterday I got confused by jumping to wrong semaphore declaration in `linux/rwsem-spinlock.h`. The generic rw_semaphore is in `linux/rwsem.h` and there count is `atomic_long_t` which is a structure. The following bpftrace program thus works:

```
#include <linux/path.h>
#include <linux/dcache.h>
#include <linux/sched.h>
#include <linux/mm_types.h>

kprobe:fuse_readpage,kprobe:fuse_readpages {
        printf("%s (%d) %s\n", probe, ((task_struct *)curtask)->mm->mmap_sem.count.counter, stack);
}
```

sorry for the noise.

**Comment by brendangregg** [comment]
I think there's three parts to this: map keys, printf, and predicates. I'll look at fixing some or all.
