### ISSUE TITLE
Equivalent parameters of BPFTRACE_STRLEN

### ISSUE THREAD

**Issue by unknowndevQwQ** [iovisor/bpftrace#2522]
### Is your feature request related to a problem? Please describe.
I want a `-s <STRLEN>` option like strace/truss to do something like setting BPFTRACE_STRLEN. Also, add strace/truss-like instructions for the cropped parts.

### Describe the solution you'd like
Add the `-s` option to bpftrace to control the length of the output.

### Describe alternative solutions or features you've considered
If bpftrace has an environment variable similar to dtrace's `-b` option, add a similar argument.

**Comment by viktormalik** [comment]
> I want a `-s <STRLEN>` option like strace/truss to do something like setting BPFTRACE_STRLEN. 

Why is `BPFTRACE_STRLEN` not sufficient?

> Also, add strace/truss-like instructions for the cropped parts.

Can you expand on this?

**Comment by unknowndevQwQ** [comment]
> > I want a `-s <STRLEN>` option like strace/truss to do something like setting BPFTRACE_STRLEN.
> 
> Why is `BPFTRACE_STRLEN` not sufficient?
> 

sudo Passing BPFTRACE_STRLEN to bpftrace requires the -E argument, which makes every `sudo bpftrace` lengthy.
> > Also, add strace/truss-like instructions for the cropped parts.
> 
> Can you expand on this?

Add a `...` for incomplete content when bpftrace knows the content is truncated.
Current: `769    plasmashell        29   0 /usr/share/kser`
Expectations: `769    plasmashell        29   0 /usr/share/kser...`

**Comment by danobi** [comment]
The "..." suffix sounds like a good idea to me.

However, I'd prefer to not have duplicate interfaces that do similar things. Perhaps if passing `BPFTRACE_STRLEN=...` is too verbose consider exporting the env var in your shell or wrap your invocation in a script.

**Comment by unknowndevQwQ** [comment]
> However, I'd prefer to not have duplicate interfaces that do similar things. Perhaps if passing `BPFTRACE_STRLEN=...` is too verbose consider exporting the env var in your shell or wrap your invocation in a script.

I need to edit sudoers to allow exporting of relevant environment variables to be read by the command after sudo. Trying to use shell wrapping? Seems to work fine until I want to add a bpftrace argument.

**Comment by viktormalik** [comment]
> I need to edit sudoers to allow exporting of relevant environment variables to be read by the command after sudo. Trying to use shell wrapping? Seems to work fine until I want to add a bpftrace argument.

Can't you do:
```bash
#! /bin/sh
export BPFTRACE_STRLEN=...
bpftrace "$@"
```

**Comment by unknowndevQwQ** [comment]
> > I need to edit sudoers to allow exporting of relevant environment variables to be read by the command after sudo. Trying to use shell wrapping? Seems to work fine until I want to add a bpftrace argument.
> 
> Can't you do:
> 
> ```shell
> #! /bin/sh
> export BPFTRACE_STRLEN=...
> bpftrace "$@"
> ```

This is not flexible enough - I don't need to see 200 characters every time I use it, sometimes I only need to know 100.

**Comment by viktormalik** [comment]
> This is not flexible enough - I don't need to see 200 characters every time I use it, sometimes I only need to know 100.

Then:
```bash
#! /bin/sh
export BPFTRACE_STRLEN="$1"
shift
bpftrace "$@"
```
Or you can have more advanced option parsing. I really think that pretty much any use case can be handled with a custom script. I agree with @danobi - let's avoid duplicate interfaces for same things.

**Comment by unknowndevQwQ** [comment]
> > This is not flexible enough - I don't need to see 200 characters every time I use it, sometimes I only need to know 100.
> 
> Then:
> 
> ```shell
> #! /bin/sh
> export BPFTRACE_STRLEN="$1"
> shift
> bpftrace "$@"
> ```
> 
> Or you can have more advanced option parsing. I really think that pretty much any use case can be handled with a custom script. I agree with @danobi - let's avoid duplicate interfaces for same things.

It is still limited in that it requires the length parameter to be in the first place, and I want to set the length parameter as freely as strace does.

**Comment by viktormalik** [comment]
> It is still limited in that it requires the length parameter to be in the first place, and I want to set the length parameter as freely as strace does.

Then write your own arg parser in the script. Seriously, you're asking us to do redundant work and implement a duplicate functionality for your specific use-case which can be handled by a trivial script. This is seriously a waste of other people's time (as has been this thread).

**Comment by unknowndevQwQ** [comment]
> > It is still limited in that it requires the length parameter to be in the first place, and I want to set the length parameter as freely as strace does.
> 
> Then write your own arg parser in the script. Seriously, you're asking us to do redundant work and implement a duplicate functionality for your specific use-case which can be handled by a trivial script. This is seriously a waste of other people's time (as has been this thread).

I found an OK solution on stackoverflow, with known restrictions viewed from [here](https://stackoverflow.com/questions/40088478/can-getopts-parse-a-subset-of-a-bash-scripts-arguments-and-leave-the-rest-intac/40089073#40089073).
[wbpftrace.sh.txt](https://github.com/iovisor/bpftrace/files/11166368/wbpftrace.sh.txt)

**Comment by ajor** [comment]
Truncated strings notice is being handled in a new issue: https://github.com/iovisor/bpftrace/issues/2553
