### ISSUE TITLE
'linux/types.h' file not found

### ISSUE THREAD

**Issue by sjLambda** [iovisor/bpftrace#2532]
I get this error:
/bpftrace/include/clang_workarounds.h:14:10: fatal error: 'linux/types.h' file not found

with:
bpftrace 0.16.0
uname:
Linux Guix 6.2.6 #1 SMP PREEMPT_DYNAMIC 1 x86_64 GNU/Linux

Is there a missing package or path not set properly? Any suggestions? Thx.

**Comment by danobi** [comment]
Hi, `linux/types.h` is `#include`d by bpftrace during script build time to work around some issues. I think it's usually provided by the kernel headers package. On my system (arch linux) it's `linux-api-headers`. You can check other systems here: https://pkgs.org/search/?q=%2Fusr%2Finclude%2Flinux%2Ftypes.h

I think installing the appropriate kernel headers package will fix the issue.
