### ISSUE TITLE
Support golang1.17+ arguments

### ISSUE THREAD

**Issue by liyan-ah** [iovisor/bpftrace#2547]
### Is your feature request related to a problem? Please describe.

Golang-1.17 was [released](https://github.com/golang/go/releases/tag/go1.17) in 2021/08/17. It's calling conventions changed, and current bpftrace argN does't support the new calling conventions well. Since golang is a popular language, support go1.17+ will be really helpful. Do we need   some new arguments?  
Here is the new calling convention in x86_64 platform, refered from [Go internal ABI specification](https://github.com/golang/go/blob/master/src/cmd/compile/abi-internal.md).
| param | argN | go1.17+ |
| -       | -     | -  	       |
| 1	      |  rdi  | rax |
| 2	      | rsi | rbx |
| 3       | rdx | rcx | 
| 4       | rcx | rdi |
| 5       | r8 | rsi |
| 6       | r9  | r8 |
| 7       | stack | r9 |
| 8       | stack | r10 |
| 9       | stack | r11 |
| 10      | stack | stack |

### Describe the solution you'd like

refered from: https://github.com/iovisor/bpftrace/issues/740, maybe some new aliases like:
* `goarg0`==`ctx->rax`
* `goarg1`==`ctx->rbx`
* etc
will helps.

### Describe alternative solutions or features you've considered

The other alternative solution is support `ctx->rax`, `ctx->rbx` like `arg-rax`, `arg-rbx`, and the new calling conventions can be supported.

Much thanks for your time.

**Comment by liyan-ah** [comment]
> 

Good idea. 
And do you think provide direct register access parameters in bpftrace, like `rax, rbx, r10, etc`, as I mentions above, is acceptable? 
Looking forward a proper solution.

**Comment by danobi** [comment]
I think adding language into the probe as a modifier would imply we have to detect the golang version, right? In practice I think this is possible (eg `go version $binary`) will report the version of go that `$binary` is compiled with. Mechanically you could refer to:
* https://github.com/golang/go/blob/b441eb3f978b8b7d4f09f8e583d419d8f4e40af6/src/cmd/go/internal/version/version.go#L143-L162
* https://github.com/golang/go/blob/master/src/debug/buildinfo/buildinfo.go#L177-L186

But do we think it's feasible to maintain a decoder / mapping forever? Perhaps another option like @liyan-ah suggested is to expose direct register access.

**Comment by liyan-ah** [comment]
> I don't think we have to. Golang used to be stackbased, now register based (https://go.dev/doc/go1.17#compiler). So users had to use `sarg` and now have to update programs to `arg` anyway. Detection would be a nice extra, can warn users that sarg isn't going to work anymore.
> 
> We can already access registers, `reg("r15")` should just work https://github.com/iovisor/bpftrace/blob/a2c23086a97cffc31fe2d78feeae211c9df6b155/man/adoc/bpftrace.adoc

Thanks for your reply. I would try to access register directly latter, and this do solve my problem.
Also, `sarg` is still very important, or if we have another methods to access memory directly, when it comes to stack passing argument, even in `go-1.17+` as I mentioned above. 
Do you think providing some guides for different languages' argument reading in some place (a readme file or a blog link) is a good idea ? That would help new learners.

**Comment by danobi** [comment]
> I don't think we have to. Golang used to be stackbased, now register based (https://go.dev/doc/go1.17#compiler). So users had to use `sarg` and now have to update programs to `arg` anyway. Detection would be a nice extra, can warn users that sarg isn't going to work anymore.

Ah, ok. I thought they had changed the register based calling convention after the initial switch from stack -> register.

> 
> We can already access registers, `reg("r15")` should just work https://github.com/iovisor/bpftrace/blob/a2c23086a97cffc31fe2d78feeae211c9df6b155/man/adoc/bpftrace.adoc

Whoops, right. I forgot about that helper :)

**Comment by danobi** [comment]
> Do you think providing some guides for different languages' argument reading in some place (a readme file or a blog link) is a good idea ? That would help new learners.

Yeah absolutely. A doc file in this repo would be nice. Possibly with tables like the one you provided in the issue.

**Comment by myaut** [comment]
```
goarg0==ctx->rax
goarg1==ctx->rbx
```
This is, unfortunately broken for arguments that occupy two registers such as strings. So ctx->rbx can point to the length of arg0, not the second function argument.

**Comment by danobi** [comment]
@myaut Right, it requires a bit of awareness from person doing the tracing. For example, you can pass aggregates in C as well: https://godbolt.org/z/67a4Yde5e
