### ISSUE TITLE
uprobes: trying to trace all functions of a userspace program using '*' returns an error "Offset outside the function bounds"

### ISSUE THREAD

**Issue by caringi** [iovisor/bpftrace#2552]
I have a small C program (less than 1000 lines of code) with around 20 functions and I would like to trace all of them (when each function is called) using something like: 

`$ bpftrace -c /home/caringi/devel/test/prog -e 'uprobe:/home/caringi/devel/test/prog:* { printf("#%d %s\n", pid, probe); }'`

Using the '*' in order to avoid specifying each function, one by one.

But the problem is: this approach doesn't work.

```
Attaching 12 probes...
ERROR: Offset outside the function bounds ('register_tm_clones' size is 0)
```

The cause is some functions (added by gcc?) with size == 0:

```
0000000000401080 t deregister_tm_clones
00000000004010b0 t register_tm_clones
0000000000401120 t frame_dummy
.
.
.
```

So I made a small change in the bpftrace code to be able to accomplish what I need:

```
diff --git a/src/attached_probe.cpp b/src/attached_probe.cpp
index c33d7308..d573573d 100644
--- a/src/attached_probe.cpp
+++ b/src/attached_probe.cpp
@@ -498,7 +498,9 @@ void AttachedProbe::resolve_offset_uprobe(bool safe_mode)
   if (func_offset >= sym.size) {
     std::stringstream ss;
     ss << sym.size;
-    throw std::runtime_error("Offset outside the function bounds ('" + symbol + "' size is " + ss.str() + ")");
+    std:: cout << "Offset outside the function bounds ('" << symbol
+        << "' size is " << ss.str() << ")" << std::endl;
+    return;
   }
```

This is just a workaround, but what would be the right solution for this case?

There is a related Issue (from 2019): https://github.com/iovisor/bpftrace/issues/940

**Comment by viktormalik** [comment]
I had a look and the problem is that setting the symbol size in `.symtab` is optional and compilers often don't do it for their generated symbols. There are basically two ways to approach this:

1. Allow attaching to symbols with size 0. This will mostly work as `bcc_elf_foreach_sym` only lists symbols from the `.text` section but if there is a symbol with an actual size 0 (i.e. no instructions), then the attachment to it may cause trouble. I'm not sure how likely that is.
2. Skip attachment to symbols with size 0 without failing. We could possibly print a warning but your use-case seems pretty useful (attaching to all functions in a binary) and since basically every binary contains such symbols, there would be a lot of noise.

I slightly prefer the second option (without warnings) as I don't see much use for tracing GCC-generated functions. So, I'm gonna implement it but in case someone has other opinion/idea, please let me know.

**Comment by viktormalik** [comment]
In the end, I went with option 2 *with warnings*. The reason is that users may expect that `uprobe:*` will attach to all functions in the binary (as listed by `nm`) so we better inform them that it's not happening.

@caringi mind giving it a try? #2562

**Comment by caringi** [comment]
@viktormalik sure, it's working...

Without --unsafe:

```
./src/bpftrace -c /home/caringi/devel/test/prog -e 'uprobe:/home/caringi/devel/test/prog:* { printf("#%d %s\n", pid, probe); }' 
Attaching 12 probes...
WARNING: Could not determine boundary for register_tm_clones (symbol has size 0). Skipping attachment (use --unsafe to force attachement).
WARNING: Could not determine boundary for frame_dummy (symbol has size 0). Skipping attachment (use --unsafe to force attachement).
WARNING: Could not determine boundary for deregister_tm_clones (symbol has size 0). Skipping attachment (use --unsafe to force attachement).
WARNING: Could not determine boundary for _init (symbol has size 0). Skipping attachment (use --unsafe to force attachement).
WARNING: Could not determine boundary for _fini (symbol has size 0). Skipping attachment (use --unsafe to force attachement).
WARNING: Could not determine boundary for __do_global_dtors_aux (symbol has size 0). Skipping attachment (use --unsafe to force attachement).
<my_expected_output>
```

With --unsafe:

```
./src/bpftrace --unsafe -c /home/caringi/devel/test/prog -e 'uprobe:/home/caringi/devel/test/prog:* { printf("#%d %s\n", pid, probe); }' 
Attaching 12 probes...
<my_expected_output>
#1384368 uprobe:/home/caringi/devel/test/prog:_start
#1384368 uprobe:/home/caringi/devel/test/prog:_init
#1384368 uprobe:/home/caringi/devel/test/prog:frame_dummy
#1384368 uprobe:/home/caringi/devel/test/prog:register_tm_clones
<my_expected_output>
#1384368 uprobe:/home/caringi/devel/test/prog:__do_global_dtors_aux
#1384368 uprobe:/home/caringi/devel/test/prog:deregister_tm_clones
#1384368 uprobe:/home/caringi/devel/test/prog:_fini
```

Thanks a lot!
