### ISSUE TITLE
Support adding a trailing identifier to truncated strings

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#2553]
### Is your feature request related to a problem? Please describe.

Currently if you do something like `str(args->name, 3)` you might get something back like "123". In these cases, it's hard to tell if the string was truncated or not.

### Describe the solution you'd like

It would be nice if bpftrace could detect the truncation and display something like "1..". 

### Describe alternative solutions or features you've considered

Not sure if there's any better ways.

**Comment by danobi** [comment]
So I took a look at this and I think we'll need kernel support to do the properly.

bpftrace currently calls into `bpf_probe_read_(kernel|user)_str()` helpers to read the string. The issue is that `bpf_probe_read_*_str()` will insert a NUL byte at the end. So from our end, we cannot simply look at the last byte and check if it's a NUL (the implication is that if it's !NUL, then we know it's truncation).

We cannot replace `bpf_probe_read_*_str()` with `bpf_probe_read_*()` either b/c we would have to guess how long the string is. The guessing is necessary b/c if we try to read too much data the helper could page fault which would error out the call. Another problem with guessing is we could possibly read past the end of the string and start reading from a second string. And if we end in the middle of the second string, then it'll be marked as truncation when in reality it's not.

So adding kernel support for this may be necessary. However, the kernel has a soft-freeze on helpers and instead wants kfuncs. bpftrace does not yet support kernel kfuncs (not to be confused with fentry/fexit progs).

**Comment by ajor** [comment]
As an easy method that doesn't require kernel support, we could just append "..." whenever we get a max-length string. It would have false positives when a string is exactly equal in length to max-strlen, but I think would be a lot more useful than not showing anything for truncated strings (as we do currently).

**Comment by danobi** [comment]
That sounds like an acceptable tradeoff to me. I'll make sure to leave an escape hatch just in case as well. Documenting the exact trailer should help with grepping if anyone starts scratching their head
