### ISSUE TITLE
Builtin variable comm's is ambiguous

### ISSUE THREAD

**Issue by maokelong** [iovisor/bpftrace#2580]
### What reproduces the bug?

**comm is the thread name instead of the process name.**

From src/ast/irbuilderbpf.cpp:947, we can find that bpftrace will issue `bpf_get_current_comm` when getting `comm`.
```cpp
void IRBuilderBPF::CreateGetCurrentComm(...)
{
  ...
  // long bpf_get_current_comm(char *buf, int size_of_buf)
  // Return: 0 on success or negative error
  FunctionType *getcomm_func_type = FunctionType::get(
      getInt64Ty(), { buf->getType(), getInt64Ty() }, false);
  CallInst *call = CreateHelperCall(libbpf::BPF_FUNC_get_current_comm,
                                    getcomm_func_type,
                                    { buf, getInt64(size) },
                                    "get_comm",
                                    &loc);
  CreateHelperErrorCond(ctx, call, libbpf::BPF_FUNC_get_current_comm, loc);
}
```

Step into `bpf_get_current_comm`'s impl(https://elixir.bootlin.com/linux/latest/source/kernel/bpf/helpers.c#L252), we can find that it's done by returning current's struct stask's comm field, which means thread name.
```c
[BPF_CALL_2](https://elixir.bootlin.com/linux/latest/C/ident/BPF_CALL_2)([bpf_get_current_comm](https://elixir.bootlin.com/linux/latest/C/ident/bpf_get_current_comm), char *, buf, [u32](https://elixir.bootlin.com/linux/latest/C/ident/u32), size)
{
	struct [task_struct](https://elixir.bootlin.com/linux/latest/C/ident/task_struct) *[task](https://elixir.bootlin.com/linux/latest/C/ident/task) = [current](https://elixir.bootlin.com/linux/latest/C/ident/current);

	if ([unlikely](https://elixir.bootlin.com/linux/latest/C/ident/unlikely)(![task](https://elixir.bootlin.com/linux/latest/C/ident/task)))
		goto err_clear;

	/* Verifier guarantees that size > 0 */
	[strscpy](https://elixir.bootlin.com/linux/latest/C/ident/strscpy)(buf, [task](https://elixir.bootlin.com/linux/latest/C/ident/task)->[comm](https://elixir.bootlin.com/linux/latest/C/ident/comm), size);
	return 0;
err_clear:
	[memset](https://elixir.bootlin.com/linux/latest/C/ident/memset)(buf, 0, size);
	return -[EINVAL](https://elixir.bootlin.com/linux/latest/C/ident/EINVAL);
}
```
It's different from bpftrace's user guidance.

![image](https://user-images.githubusercontent.com/12730912/234534841-eebc9c08-9d37-4e68-bc60-67e01e45bd3a.png)

**Comment by maokelong** [comment]
Guys, is there a convient way to get a correct process name?

**Comment by viktormalik** [comment]
Do you have an example when the thread (task) name is different from the process name?

**Comment by maokelong** [comment]
> Do you have an example when the thread (task) name is different from the process name?

Sure, here is a clang demo to change a thread's name.

```c
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

void *thread_function(void *arg)
{
    while (1) {
        sleep(1);
    }
}

int main(void)
{
    int i;
    pthread_t threads[5];

    for (i = 0; i < 5; i++) {
        pthread_create(&threads[i], NULL, thread_function, NULL);
    }

    for (i = 0; i < 5; i++) {
        char name[16];
        sprintf(name, "new-name-%d", i);
        pthread_setname_np(threads[i], name);
    }

    for (i = 0; i < 5; i++) {
        pthread_join(threads[i], NULL);
    }

    return 0;
}
```

When compiled this program and run as a.out, I got the following 6 threads:
![image](https://user-images.githubusercontent.com/12730912/234543300-e4ec3d5f-0134-43fd-8042-846487df3cc3.png)

By checking their's comm we can easily draw a conclusion that: A Process's Name Can Be Different from It's Threads.
![image](https://user-images.githubusercontent.com/12730912/234543873-1145a041-123b-4a76-9dad-11542302da0c.png)

**Comment by viktormalik** [comment]
You can get the process and thread ids using `pid` and `tid` and then lookup the information in `/proc/<pid>/task/<tid>/` (e.g. using the `system` call if you want to do that from a bpftrace script).

**Comment by maokelong** [comment]
> You can get the process and thread ids using `pid` and `tid` and then lookup the information in `/proc/<pid>/task/<tid>/` (e.g. using the `system` call if you want to do that from a bpftrace script).

Thank you for your information on `/proc/<pid>/task<tid>` , I got new knowledge : )

But getting process' name by `system` call has serval drawbacks, which makes such method hard to put into practical.

1. Can't use `system`'s output as map's key because of its async attribute;
2. Eventhough `system` is synchronous and there's a way to leverage it's output, it's too slow for micro-architectural analysis;

Here's a demo revealing it's performance:

```c
// execute the shell cmd "cat /proc/1/cmdline" and print the duration

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main()
{
    struct timespec start, end;
    clock_gettime(CLOCK_MONOTONIC_RAW, &start);
    system("cat /proc/1/cmdline");
    clock_gettime(CLOCK_MONOTONIC_RAW, &end);
    printf("duration = %lu nanoseconds\n", (end.tv_sec - start.tv_sec) * 1000000000 + (end.tv_nsec - start.tv_nsec));
    return 0;
}
```

The result demostrate that forking a new thread and executing a simple cat cmd can take 1ms. It's too long.
```
mkl@DESKTOP-HHR9IJG:~/workspace/cppdemo$ gcc stat_proc.c ; ./a.out
/initduration = 1091800 nanoseconds
mkl@DESKTOP-HHR9IJG:~/workspace/cppdemo$ gcc stat_proc.c ; ./a.out
/initduration = 1032400 nanoseconds
```

**Comment by maokelong** [comment]
> You can get the process and thread ids using `pid` and `tid` and then lookup the information in `/proc/<pid>/task/<tid>/` (e.g. using the `system` call if you want to do that from a bpftrace script).

If BTF is enabled, a good practice (as far as my knowledge) to get process name in bpftrace is `curtask->group_leader->comm`.

But it's impossible for those don't have BTF     :- (

**Comment by viktormalik** [comment]
Well, then it should be possible to do:
```
#include <linux/sched.h>
...
((struct task_struct *)curtask)->group_leader->comm
...
```

**Comment by viktormalik** [comment]
It looks like what you need is achievable with the current bpftrace so can we close this?

**Comment by maokelong** [comment]
> It looks like what you need is achievable with the current bpftrace so can we close this?

Sure. Thanks for your quick response and help!

**Comment by fbs** [comment]
Should we improve documentation on this?
