### ISSUE TITLE
create release assets with CI

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#2609]
currently I have to do the release, then wait for the ci to run so I can extract the binary from the image and then run a script to generate assets.
Its not a whole lot of work but I usually get side tracked and forget.

It would be nice if the CI can do this, so we can just tag the release and all assets are attached automagically with a tag ci run

**Comment by danobi** [comment]
Yes, +1. Should be fairly straightforward as well. I did this for `vmtest` in an hour: https://github.com/danobi/vmtest/blob/master/.github/workflows/release.yml

**Comment by danobi** [comment]
Although our case is slightly more complicated b/c it has to wait on the image push. For that I think we can use https://github.com/marketplace/actions/wait-on-check. 

See in particular the example (which is our use case): https://github.com/marketplace/actions/wait-on-check#a-real-world-scenario
