### ISSUE TITLE
min() doesn't handle negative values

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#261]
The min() builtin function doesn't handle negative values:

```
BEGIN
{
  @counter = 5;
}

interval:s:1
{
  @["min-cnt"] = min(@counter);
  @counter = @counter - 1
}

#  /root/BPF] bpftrace ./min-broken.bt
Attaching 2 probes...
^C

@[min-cnt]: 18446744073709551609


@counter: -8
```

**Comment by williangaspar** [comment]
@tyroguru, can you confirm if the bug still happening? I've tested on my machine and it is working.

**Comment by tyroguru** [comment]
@williangaspar - my pull request #265 fixed this issue. I'll close this.
