### ISSUE TITLE
Test compilation fails with missing libdw-devel

### ISSUE THREAD

**Issue by wcunning** [iovisor/bpftrace#2635]
Just cloned fresh on a new Fedora 38 install, and other than finding a couple of additional libraries needed installing (will submit INSTALL.md PR later today), I now get the following error: 

```
[ 34%] Generating btf_data.h, dwarf_data.h
CMake Error at /home/wcunning/projects/bpf/bpftrace/tests/data/configure_headers.cmake:7 (file):
  file READ must be called with at least two additional arguments


make[2]: *** [tests/data/CMakeFiles/debuginfo_data.dir/build.make:76: tests/data/btf_data.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:2611: tests/data/CMakeFiles/debuginfo_data.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

Google does not indicate immediately what might be going wrong on this compilation, and I didn't see any recently opened or closed issues that might help with the error message. Anybody got any ideas?

**Comment by fbs** [comment]
Do you have libdw (drawf) installed?

**Comment by wcunning** [comment]
That does not seem to be a package I can install. There's a libdwarf, but nothing seems to exist for drawf. Am I missing something in how I should be searching?

**Comment by wcunning** [comment]
@fbs You were correct -- I had the relevant library, but not the development version. I have successfully compiled now, and have created a pull request to update INSTALL.md to reflect the additional dependencies on Fedora 38. 

https://github.com/iovisor/bpftrace/pull/2637

**Comment by fbs** [comment]
Thanks. If you want to attempt to fix the build issue. https://github.com/iovisor/bpftrace/blob/master/tests/data/CMakeLists.txt#L46-L60 this defines the var that is used https://github.com/iovisor/bpftrace/blob/master/tests/data/configure_headers.cmake .  Looks like the depends https://github.com/iovisor/bpftrace/blob/master/tests/data/CMakeLists.txt#L79 doesn't work as expected

**Comment by xpahos** [comment]
Looks like the same problem with Ubuntu.
