### ISSUE TITLE
Builtin for getting jiffies

### ISSUE THREAD

**Issue by viktormalik** [iovisor/bpftrace#2644]
### Is your feature request related to a problem? Please describe.

There are applications in which it would be useful to access the `jiffies` kernel variable, see e.g. #2633. 

### Describe the solution you'd like

Introduce a new builtin `jiffies` which returns the jiffies value obtained via the `bpf_jiffies64` helper (if the helper is available on the given kernel).

**Comment by heterog** [comment]
I created a pr https://github.com/iovisor/bpftrace/pull/2769 , wish it can bring some helps :)

**Comment by jordalgo** [comment]
PR was merged.
