### ISSUE TITLE
Specifying mnt namespace setting uprobe is not supported

### ISSUE THREAD

**Issue by duanjiong** [iovisor/bpftrace#2647]
### What reproduces the bug?

According to the documentation the bpftrace option -p can only be used to enable USDT probes, but not uprobe. perf's option `-target-ns` can enable uprobe.

### bpftrace --info

System
  OS: Linux 5.15.1300-0.el9.x86_64 #1 SMP Fri Jul 15 14:09:00 UTC 2022
  Arch: x86_64

Build
  version: v0.17.0
  LLVM: 15.0.7
  unsafe uprobe: no
  bfd: yes
  libdw (DWARF support): no

Kernel helpers
  probe_read: no
  probe_read_str: no
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: no
  send_signal: no
  override_return: no
  get_boot_ns: no
  dpath: no
  skboutput: no

Kernel features
  Instruction limit: -1
  Loop support: no
  btf: no
  map batch: no
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: no
  percpu hash: no
  array: no
  percpu array: no
  stack_trace: no
  perf_event_array: no

Probe types
  kprobe: no
  tracepoint: no
  perf_event: no
  kfunc: no
  iter:task: no
  iter:task_file: no
  kprobe_multi: no
  raw_tp_special: no

**Comment by viktormalik** [comment]
I'm not sure I understand the problem. The `-p` option can be used in combination with uprobes, could you please elaborate more? Maybe even add an example? Thanks!

**Comment by mmarchini** [comment]
Our documentation might be outdated (a lot of it is I think). IIRC -p has worked for uprobes for years. So maybe we just need to update our docs?

**Comment by duanjiong** [comment]
> I'm not sure I understand the problem. The `-p` option can be used in combination with uprobes, could you please elaborate more? Maybe even add an example? Thanks!

Sorry, this is my mistake, I will close this issue
