### ISSUE TITLE
check for 32-bit in src/arch/CMakeLists.txt seems wrong

### ISSUE THREAD

**Issue by mwhudson** [iovisor/bpftrace#2654]
Trying to build on Ubuntu armhf with an Ubuntu arm64 kernel fails, with this error:

  Unsupported architecture: armv7l

It looks like the only value of CMAKE_SYSTEM_PROCESSOR (which is the same as `uname -m` ttbomk) that is accepted for 32-bit ARM is armv7-a. But unless I am missing something (certainly possible), the possible values of `uname -m` on 32-bit arm are "arm", "armv7l" and "armv8l" (well and armv7b and armv8b for the linux32 personality running on big endian aarch64 but well). So I think the check should probably be changed.

It's possible I'm confused about all this though.

**Comment by viktormalik** [comment]
cc @tnovak who was adding support for 32bit ARM

**Comment by panlinux** [comment]
Here is a link to such a failed build (search for `armv7l`):
https://launchpadlibrarian.net/664084756/buildlog_ubuntu-mantic-armhf.bpftrace_0.17.0-2_BUILDING.txt.gz

Note the kernel:
```
Kernel version: Linux bos01-arm64-018 5.4.0-147-generic #164-Ubuntu SMP Tue Mar 21 14:25:54 UTC 2023 aarch64
```
But the userspace environment is all armhf:
```
RUN: /usr/share/launchpad-buildd/bin/in-target mount-chroot --backend=chroot --series=mantic --arch=armhf PACKAGEBUILD-26015351
```
cmake output:
```
cd obj-arm-linux-gnueabihf && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/arm-linux-gnueabihf -DBUILD_TESTING:BOOL=OFF -DUSE_SYSTEM_BPF_BCC=1 ..
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibBcc: /usr/lib/arm-linux-gnueabihf/libbcc.so  
-- Looking for bcc_usdt_foreach
-- Looking for bcc_usdt_foreach - found
-- Found LibBpf: /usr/lib/arm-linux-gnueabihf/libbpf.so  
-- Found LibElf: /usr/lib/arm-linux-gnueabihf/libelf.so  
-- Found LibCereal: /usr/include  
-- Found BISON: /usr/bin/bison (found version "3.8.2") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Looking for name_to_handle_at
-- Looking for name_to_handle_at - found
-- Please install the libbfd development package (missing: LIBBFD_LIBRARIES LIBBFD_INCLUDE_DIRS) 
-- Please install the libopcodes development package (missing: LIBOPCODES_LIBRARIES LIBOPCODES_INCLUDE_DIRS) 
-- Found LibDw: /usr/lib/arm-linux-gnueabihf/libdw.so  
-- Please install the libcap development package (missing: LIBPCAP_LIBRARIES LIBPCAP_INCLUDE_DIRS) 
-- Looking for sys/sdt.h
-- Looking for sys/sdt.h - found
-- Performing Test HAVE_FFI_CALL
-- Performing Test HAVE_FFI_CALL - Success
-- Found FFI: /usr/lib/arm-linux-gnueabihf/libffi.so  
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /usr/lib/arm-linux-gnueabihf/libtinfo.so  
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.13") 
-- Found LibXml2: /usr/lib/arm-linux-gnueabihf/libxml2.so (found version "2.9.14") 
-- Found LLVM 14.0.6: /usr/lib/llvm-14/lib/cmake/llvm
CMake Error at src/arch/CMakeLists.txt:20 (message):
  Unsupported architecture: armv7l
```

**Comment by tnovak** [comment]
> on Ubuntu armhf with an Ubuntu arm64 kernel

I think we'd need to build with `src/arch/aarch64.cpp` in this case, to match the kernel.

We already have some places in code where we need to handle different bitness between kernel and userspace (e.g. [`get_kernel_ptr_width`](https://github.com/iovisor/bpftrace/blob/9e4a5b16bd16a105d8bd4cda91db6ed4267182be/src/utils.cpp#L1285)). Might be possible to merge `arm.cpp` and `aarch64.cpp` and choose between the two options at runtime rather than compile time; let me look into this a bit more.

**Comment by mwhudson** [comment]
> I think we'd need to build with `src/arch/aarch64.cpp` in this case, to match the kernel.

No, although armhf builds on Ubuntu are done on a machine that is running an arm64 kernel we still want the binaries to work with an armhf kernel. Can the arm64 kernel in linux32 mode really not execute the same bpf programs as an armhf kernel?

**Comment by tnovak** [comment]
> Can the arm64 kernel in linux32 mode really not execute the same bpf programs as an armhf kernel?

@mwhudson: there are some differences between 32-bit and 64-bit kernels that bpftrace has to take into account -- for example, members of `struct pt_regs` (passed as the "context" argument to a BPF program attached to e.g. a kprobe), which we use to extract function arguments (`arg`, `reg` builtins), will have a different size.

This is normally encoded in `src/arch/`, but with [f7883b7e](https://github.com/iovisor/bpftrace/commit/f7883b7e6b53a600728253d340286122a8221a91) and other related changes  I think it shouldn't be difficult to merge `{arm,aarch64}.cpp` so that the same bpftrace `armhf` binary can be used with both an `arm` and an `arm64` kernel.

**Comment by daniloegea** [comment]
Just for reference, there is a second issue related to this. Even if the build passes the cmake checks it will fail on armhf for a different reason.

There's some discussion here https://github.com/iovisor/bpftrace/pull/2360
