### ISSUE TITLE
 no member named ‘kprobe_multi’ error received while trying to build bpftrace-v.0.18.0

### ISSUE THREAD

**Issue by hundredmiles** [iovisor/bpftrace#2672]
```
[  3%] Building CXX object src/CMakeFiles/runtime.dir/attached_probe.cpp.o
/root/bpftrace-0.18.0/src/attached_probe.cpp: In member function ‘void bpftrace::AttachedProbe::attach_multi_kprobe()’:
/root/bpftrace-0.18.0/src/attached_probe.cpp:895:8: error: ‘struct bpf_link_create_opts’ has no member named ‘kprobe_multi’
  895 |   opts.kprobe_multi.syms = syms.data();
      |        ^~~~~~~~~~~~
/root/bpftrace-0.18.0/src/attached_probe.cpp:896:8: error: ‘struct bpf_link_create_opts’ has no member named ‘kprobe_multi’
  896 |   opts.kprobe_multi.cnt = syms.size();
      |        ^~~~~~~~~~~~
/root/bpftrace-0.18.0/src/attached_probe.cpp:897:8: error: ‘struct bpf_link_create_opts’ has no member named ‘kprobe_multi’
  897 |   opts.kprobe_multi.flags = probe_.type == ProbeType::kretprobe
      |        ^~~~~~~~~~~~
/root/bpftrace-0.18.0/src/attached_probe.cpp:908:28: error: ‘struct bpf_link_create_opts’ has no member named ‘kprobe_multi’
  908 |       for (i = 0; i < opts.kprobe_multi.cnt; i++)
```

Reason to build from source: ``` Segmentation fault ``` with currently installed bpftrace using ```apt-get install bpftrace```

System info:
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
kernel version: 5.15.0-77-generic
```

**Comment by tnovak** [comment]
Are you building with `-DUSE_SYSTEM_BPF_BCC=1`?

Bpftrace depends on a fairly recent version of libbpf, newer than what many distributions provide. If you clone the git repo (rather than downloading the release tarball), you could use vendored libraries (see [INSTALL.md](https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#vendored-libraries)).

**Comment by hundredmiles** [comment]
I tried building with ```-DUSE_SYSTEM_BPF_BCC=1```
I get the following error now. It is not able to find LIBBPF_LIBRARIES
```
/bpftrace/build# cmake -DUSE_SYSTEM_BPF_BCC=1 ..
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Please install the libbpf development package (missing: LIBBPF_LIBRARIES
  LIBBPF_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibBpf.cmake:54 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:119 (find_package)
```

Note that I also have bcc in my system. Unfortunately, when I install the latest version of bcc on my machine Ubuntu 22.04, it requires llvm and clang v14 and bpftrace seems not be compatible with v14 of llvm. When I do ```apt get bpftrace``` it downloads v11 of llvm. However, it does not run and throws the error: 
```
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

As a workaround, I first install bcc with llvm-11 and then install bpftrace. However, then my bcc code does not execute unless I install llvm-14 which then breaks bpftrace!

**Comment by viktormalik** [comment]
> I tried building with `-DUSE_SYSTEM_BPF_BCC=1` I get the following error now. It is not able to find LIBBPF_LIBRARIES
> 
> ```
> /bpftrace/build# cmake -DUSE_SYSTEM_BPF_BCC=1 ..
> CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Please install the libbpf development package (missing: LIBBPF_LIBRARIES
>   LIBBPF_INCLUDE_DIRS)
> Call Stack (most recent call first):
>   /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
>   cmake/FindLibBpf.cmake:54 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:119 (find_package)
> ```

That means that you're missing the libbpf development package, should be called `libbpf-dev` on Ubuntu 22.04.

> Note that I also have bcc in my system. Unfortunately, when I install the latest version of bcc on my machine Ubuntu 22.04, it requires llvm and clang v14 and bpftrace seems not be compatible with v14 of llvm. When I do `apt get bpftrace` it downloads v11 of llvm. 

bpftrace supports all versions of LLVM from 9 up to 16. It seems that the version packaged in your system is for LLVM 11 but that doesn't mean that a newer version won't work with LLVM 14.

> However, it does not run and throws the error:
> 
> ```
> : CommandLine Error: Option 'help-list' registered more than once!
> LLVM ERROR: inconsistency in registered CommandLine options
> ```
> 
> As a workaround, I first install bcc with llvm-11 and then install bpftrace. However, then my bcc code does not execute unless I install llvm-14 which then breaks bpftrace!

Did you try to follow the build procedure from [INSTALL.md](https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#building-bpftrace-1)?
```
git clone https://github.com/iovisor/bpftrace --recurse-submodules
mkdir bpftrace/build; cd bpftrace/build;
../build-libs.sh
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j8
sudo make install
```
Especially the `../build-libs.sh` part is important as it will build BCC and libbpf from their latest source, making sure that they contain all the latest features (including `kprobe_multi`).

**Comment by vigarov** [comment]
Hey @viktormalik ! I successfully built, installed and got bpftrace running on my local Ubuntu 22.04.2 (kernel v5.19.0-43), following the steps from [INSTALL.md](https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#building-bpftrace-1). However, after trying the same on my remote server running Ubuntu 22.04.3 (kernel v5.15.0-88) I got first got an error from the `cmake -DCMAKE_BUILD_TYPE=Release ..` line stating that find_package couldn't find LIBBPF. I manually installed (using `apt install libbpf-dev`), however I now get the same error as @hundredmiles above. 
Since there isn't a `build-libs.sh` script anymore, would you simply suggest building libbpf from scratch (using [this](https://github.com/libbpf/libbpf) ), or would there be another way to fix this error?

Thanks in advance!

**Comment by danobi** [comment]
You might find the appimage we distribute helpful: https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#appimage-install

Or do a nix build: https://github.com/iovisor/bpftrace/blob/master/docs/nix.md#build-bpftrace

**Comment by vigarov** [comment]
The appimage worked first try, I have to admit I completely missed it. Thanks to both of you for your quick and helpful answers!!
