### ISSUE TITLE
Attaching to LSM probes without having the BPF LSM loaded fails silently

### ISSUE THREAD

**Issue by snctfd** [iovisor/bpftrace#2716]
### What reproduces the bug?

My kernel was compiled without the BPF LSM enabled (more specifically, `CONFIG_LSM="landlock,lockdown,yama,integrity,apparmor"`). Despite this, LSM probes show up in `bpftrace -l`, and we can attempt to attach to LSM probes as follows:

```
sudo bpftrace -v -k -e 'kfunc:vmlinux:bpf_lsm_path_chmod { printf("%s\n", comm); }'
INFO: node count: 7
Attaching 1 probe...

Program ID: 33

The verifier log:
processed 105 insns (limit 1000000) max_states_per_insn 1 total_states 6 peak_states 6 mark_read 2

Attaching kfunc:vmlinux:bpf_lsm_path_chmod
^C
```

While this appears to succeed, the program is never invoked. The same behavior is observed if attaching to `kprobe:bpf_lsm_path_chmod`. On another machine with a kernel compiled with the BPF LSM, events trigger the program as expected.  It would be nice if this failure was detected and passed on to the user. 

### bpftrace --info

```
System
  OS: Linux 5.15.0-1040-aws #45~20.04.1-Ubuntu SMP Tue Jul 11 19:08:13 UTC 2023
  Arch: x86_64

Build
  version: v0.18.0-102-g9d4e
  LLVM: 10.0.0
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: no
  get_func_ip: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: no
  raw_tp_special: yes
  iter: yes
```

**Comment by danobi** [comment]
Interesting. I suspect this is a quirk with the infra in the kernel. I'm not sure we can generically handle this from `kfunc` probes -- it would be weird for it to have LSM awareness. But from an LSM probe we can handle it (see https://github.com/iovisor/bpftrace/issues/2783).

I'm going to close this as a wont-fix, but this should be taken into account if/when we add LSM probes.
