### ISSUE TITLE
Re-examine the embedded builds

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#2721]
The embedded builds were added by @dalehamel quite a while ago. It looks like our CI supports a few different embedded configurations. I am no longer sure which configurations people are actually using downstream. To the best of my knowledge, the one big desirable downstream is the fully static bpftrace binary. So maybe this will be the only embedded configuration we support in the future?
    
This task is to re-examine the embedded builds and see which can be removed or reworked. I am cautiously optimistic that we can use https://github.com/rsms/llvmbox to build a fully static bpftrace binary.

It looks like the embedded build only supports LLVM 10 and LLVM 12. I am sure we are all seriously dreading the day when we need to upgrade it.

**Comment by danobi** [comment]
So `nix bundle` functions but has two downsides:

1. It takes ~30s for first run (due to self-extraction). Subsequent runs take ~2-3s.
2. It's a ~300 MB binary (~10x size of static binary today)

I looked around more and found that you can use a bundlers: https://github.com/ralismark/nix-appimage

With the appimage, the size is still roughly the same but the first run is down to ~1s. Subsequent runs are identical to the first, so still ~1s.

I think 10x binary footprint is a worthy tradeoff for how much code we can delete. The static builds are immensely complicated and I don't think we can maintain it long term.

NB: all the above options produce a fully hermetic "static" binary that can run on any linux system.

**Comment by viktormalik** [comment]
> I think 10x binary footprint is a worthy tradeoff for how much code we can delete. The static builds are immensely complicated and I don't think we can maintain it long term.

I completely agree. Static builds are notoriously painful so if it's "only" the 10x binary footprint growth that we need to pay to get rid of them, I'm in favor of doing it.

**Comment by fbs** [comment]
Would that mean shipping a 300MB binary with every release?

**Comment by danobi** [comment]
Yes, as well as for every commit on master (our quay images). The exact mechanism for master builds distribution is TBD.

But note that 300MB is the _starting_ size. If you inspect the appimage, there is a lot of useless stuff held inside:

```
$ ./result --appimage-mount
/tmp/.mount_resultMJnObk
```

In another terminal:

```
$ cd /tmp/.mount_resultMJnObk

$ du -hs .
1.8G    .

$ ls -lh
total 46K
-r-xr-xr-x 1 root root 46K Dec 31  1979 AppRun
lrwxrwxrwx 1 root root  65 Dec 31  1979 entrypoint -> /nix/store/f5kdqmdkw0qg7sdlfagr16grkqkp8230-bpftrace/bin/bpftrace
drwxrwxrwx 2 root root   0 Dec 31  1979 mountroot
drwxr-xr-x 3 root root   0 Dec 31  1979 nix

$ cd nix/store
$ tree | tail -n50
    │       │       │   ├── xmlreader.cpython-310.opt-2.pyc
    │       │       │   └── xmlreader.cpython-310.pyc
    │       │       ├── saxutils.py
    │       │       └── xmlreader.py
    │       ├── xmlrpc
    │       │   ├── client.py
    │       │   ├── __init__.py
    │       │   ├── __pycache__
    │       │   │   ├── client.cpython-310.opt-1.pyc
    │       │   │   ├── client.cpython-310.opt-2.pyc
    │       │   │   ├── client.cpython-310.pyc
    │       │   │   ├── __init__.cpython-310.opt-1.pyc
    │       │   │   ├── __init__.cpython-310.opt-2.pyc
    │       │   │   ├── __init__.cpython-310.pyc
    │       │   │   ├── server.cpython-310.opt-1.pyc
    │       │   │   ├── server.cpython-310.opt-2.pyc
    │       │   │   └── server.cpython-310.pyc
    │       │   └── server.py
    │       ├── zipapp.py
    │       ├── zipfile.py
    │       ├── zipimport.py
    │       └── zoneinfo
    │           ├── _common.py
    │           ├── __init__.py
    │           ├── __pycache__
    │           │   ├── _common.cpython-310.opt-1.pyc
    │           │   ├── _common.cpython-310.opt-2.pyc
    │           │   ├── _common.cpython-310.pyc
    │           │   ├── __init__.cpython-310.opt-1.pyc
    │           │   ├── __init__.cpython-310.opt-2.pyc
    │           │   ├── __init__.cpython-310.pyc
    │           │   ├── _tzpath.cpython-310.opt-1.pyc
    │           │   ├── _tzpath.cpython-310.opt-2.pyc
    │           │   ├── _tzpath.cpython-310.pyc
    │           │   ├── _zoneinfo.cpython-310.opt-1.pyc
    │           │   ├── _zoneinfo.cpython-310.opt-2.pyc
    │           │   └── _zoneinfo.cpython-310.pyc
    │           ├── _tzpath.py
    │           └── _zoneinfo.py
    ├── nix-support
    │   └── setup-hook
    └── share
        ├── gdb
        │   └── libpython.py
        └── man
            └── man1
                ├── python3.10.1.gz
                └── python3.1.gz -> /nix/store/zn2g96d0hhk5h8x7982m2gbbawgwsrvz-python3-3.10.11/share/man/man1/python3.10.1.gz

658 directories, 10885 files
```

The neat thing about nix is we have full control over the _entire_ dependency tree. So over time, I expect we can overlay changes to strip unnecessary stuff out of the store that we embed into the appimage.

I imagine everything except for the shared libraries and glibc support files (like locales and whatnot) can be stripped.

**Comment by danobi** [comment]
(Just taking notes here for my future reference)

`pkgs.writeReferencesToFile` is the magic function that lists all paths to dependencies in the nix store:
https://github.com/danobi/nix-appimage/blob/5d5093111a1ec4f116c1c57b7a807d41404bfa5e/flake.nix#L87

The dependency paths are passed to `mksquashfs` below:
https://github.com/danobi/nix-appimage/blob/5d5093111a1ec4f116c1c57b7a807d41404bfa5e/flake.nix#L99

The task at hand would be to create some kind of filter over what should be passed to `mksquashfs`. Off the top of my head, there's a bunch of ways to do it. Would be an exercise of finding the cleanest way. Pretty interesting task if you ask me :)
