### ISSUE TITLE
Allow attaching uprobes to address

### ISSUE THREAD

**Issue by jasonkeene** [iovisor/bpftrace#273]
It would be nice to be able to attach uprobes to specific instructions. My use case is being able to disassemble a go binary and attach to the ret instructions to measure function exit. Something like this:

```
uprobe:/path/to/bin:0x6b0f60 {
    @start[tid] = nsecs;
}
```

**Comment by tyroguru** [comment]
I actually think this an important requirement for userland dynamic tracing. Being able to explicitly specify call sites in a function is something that is extremely useful e.g., I have multiple calls to foo() and I want to differentiate between the calls - I know where they occur so I just probe these addresses. I can drag function arguments out of registers as i wish so have access to arguments - that's a nice setup to have.

**Comment by mmarchini** [comment]
Closing since this was implemented in #803
