### ISSUE TITLE
Kprobe LINUX_VERSION_CODE issue

### ISSUE THREAD

**Issue by dw** [iovisor/bpftrace#274]
I can see what's broken, but I'm not sure how it's supposed to work.

- Start with Ubuntu 18.04 default kernel, install dbgsyms and headers
- Install bpftrace deps per INSTALL.md
- Build bpftrace, observe general success
- Attempt to use 'cgroup' variable, notice it was introduced after 4.15, programs on earlier kernels fail to load.
- Go ferreting for newer Ubuntu kernel, find https://launchpad.net/~canonical-kernel-team/+archive/ubuntu/ppa , install 4.18.0-12-generic from there
- *Discover bpftrace no longer functions*
- Go digging, notice LINUX_VERSION_CODE check in `kernel/bpf/syscall.c`
- Notice bpftrace is already basically bruteforcing this field before failing
- Notice none of the LINUX_VERSION_CODE tried match the running kernel per the `#define` in the associated -headers package.
- Hack the value from the -headers package into bpftrace, observe success.

In `attached_kprobe.cpp`, we see it first tries:

- LINUX_VERSION_CODE as defined in the translation unit, which I think comes from `/usr/include/linux/version.h`.
- Regexing the equivalent constant out of `/usr/include/linux/version.h`
- Falling back to attempting to generate the constant via `uname`, which somehow fails here.

After hard-wiring the constant:

````
sudo strace -febpf bpftrace -e 'BEGIN { printf("hi\n"); exit(); }'
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_PERF_EVENT_ARRAY, key_size=4, value_size=4, max_entries=8, map_flags=0, inner_map_fd=0, ...}, 96) = 3
Attaching 1 probe...
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_KPROBE, insn_cnt=27, insns=0x7fbc8f58c000, license="GPL", log_level=0, log_size=0, log_buf=0, kern_version=266769, prog_flags=0, ...}, 96) = 5
````

Prior to hard-wiring:

````
build] sudo strace -febpf ./src/bpftrace -e 'BEGIN { printf("hi\n"); exit(); }'
bpf(BPF_MAP_CREATE, {map_type=BPF_MAP_TYPE_PERF_EVENT_ARRAY, key_size=4, value_size=4, max_entries=8, map_flags=0, inner_map_fd=0, ...}, 96) = 3
Attaching 1 probe...
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_KPROBE, insn_cnt=27, insns=0x7f49f9a55000, license="GPL", log_level=0, log_size=0, log_buf=0, kern_version=266002, prog_flags=0, ...}, 96) = -1 EINVAL (Invalid argument)
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_KPROBE, insn_cnt=27, insns=0x7f49f9a55000, license="GPL", log_level=0, log_size=0, log_buf=0, kern_version=266002, prog_flags=0}, 96) = -1 EINVAL (Invalid argument)
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_KPROBE, insn_cnt=27, insns=0x7f49f9a55000, license="GPL", log_level=1, log_size=102400, log_buf=0x7fffa552be40, kern_version=266002, prog_flags=0}, 96) = -1 EINVAL (Invalid argument)
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_KPROBE, insn_cnt=27, insns=0x7f49f9a55000, license="GPL", log_level=0, log_size=0, log_buf=0, kern_version=266752, prog_flags=0, ...}, 96) = -1 EINVAL (Invalid argument)
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_KPROBE, insn_cnt=27, insns=0x7f49f9a55000, license="GPL", log_level=0, log_size=0, log_buf=0, kern_version=266752, prog_flags=0}, 96) = -1 EINVAL (Invalid argument)
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_KPROBE, insn_cnt=27, insns=0x7f49f9a55000, license="GPL", log_level=1, log_size=102400, log_buf=0x7fffa552be40, kern_version=266752, prog_flags=0}, 96) = -1 EINVAL (Invalid argument)
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_KPROBE, insn_cnt=27, insns=0x7f49f9a55000, license="GPL", log_level=0, log_size=0, log_buf=0, kern_version=266002, prog_flags=0, ...}, 96) = -1 EINVAL (Invalid argument)
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_KPROBE, insn_cnt=27, insns=0x7f49f9a55000, license="GPL", log_level=0, log_size=0, log_buf=0, kern_version=266002, prog_flags=0}, 96) = -1 EINVAL (Invalid argument)
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_KPROBE, insn_cnt=27, insns=0x7f49f9a55000, license="GPL", log_level=1, log_size=102400, log_buf=0x7fffa552be40, kern_version=266002, prog_flags=0}, 96) = -1 EINVAL (Invalid argument)
````

uname -r output:

````
4.18.0-12-generic
````

Is this possible a Fedora vs. Debian directory layout thing?

**Comment by dw** [comment]
Options seem to be:

- Prefer self-built kernels, problem avoided
- Blame Ubuntu, weird mismatching uname vs. EXTRAVERSION
- Blame bpftrace, shouldn't be trying to synthesize that constant(?). Find a better approach

This might be helped by teaching cmake to add /lib/modules/`uname -r`/build/include to the front of the include search path, assuming that won't cause something else to explode. At least in that case, bpftrace is 'fixed' simply by recompiling.

**Comment by dalehamel** [comment]
Looks very similar to https://github.com/iovisor/bpftrace/issues/206

**Comment by dw** [comment]
LINUX_VERSION_CODE for the running kernel should be available via /sys/kernel/notes (export of .notes section of running image), however my Ubuntu kernel lacks any such field, possibly some result of reproducible builds?

The .notes section of the vdso however *does* have it:

````>>> struct.pack('L', 266769)     # running LINUX_VERSION_CODE
'\x11\x12\x04\x00\x00\x00\x00\x00'
````

Then extract it:

````
$ ./extract-vdso >derp
[  INFO  ] vDSO region at 0x7ffda0b96000
[  INFO  ] Done, good-bye
[04:32:42 u1804!27 fo] readelf -n derp

Displaying notes found in: .note
  Owner                 Data size       Description
  Linux                0x00000004       Unknown note type: (0x00000000)
   description data: 11 12 04 00
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: f161331bec5149be0c7d9bdf817b2fd0bf93b36d
````

Is pulling this value out of the in-process VDSO too elaborate? Seems it just needs a little ELF parsing and the result should always be accurate, so the other methods could be removed.
