### ISSUE TITLE
printf("%s\n",ustack) out put many [unknown]

### ISSUE THREAD

**Issue by ingangi** [iovisor/bpftrace#2764]
$ bpftrace -V
bpftrace v0.18.0-152-gd724  (latest)

### What reproduces the bug?
faild to print ustak in uprobe like:
uprobe:/path/to/mybinary:myfunc{ printf("%s\n", ustack(perf));}
![Screenshot2023_09_14_163756](https://github.com/iovisor/bpftrace/assets/9778842/7b043fbd-8c7b-4233-bb46-718edc12df06)
many '[unknown]' frames.
- my binary build with -g
- systemtap can resolve symbols of this binary perfectly! (use print_ubacktrace(), run with 'stap -d mybinary')

### bpftrace --info
$ sudo bpftrace --info
System
  OS: Linux 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023
  Arch: x86_64

Build
  version: v0.18.0-152-gd724
  LLVM: 14.0.0
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: no
  get_func_ip: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: no
  raw_tp_special: yes
  iter: yes

**Comment by danobi** [comment]
Looks like you're using perf output format for stack traces. My guess is the process exited before bpftrace could symbolize. Systemtap might be doing some kind of fancier offline symbolization. Which would be a nice thing to support in bpftrace too if we don't already.

But just a guess. Having a reproducer would help

**Comment by ingangi** [comment]
@danobi thank you for your reply, but I can swear the process didn't exit. Even if I remove perf-format the result is the same. I can reproduce this problem anytime (in fact it never works). Below is how the cpp was compiled(gcc 11.4):
```
g++ -c -I. -DLINUX -D_REENTRANT -fPIE -O2 -g  -o test.o test.cpp
```

**Comment by ingangi** [comment]
@danobi I wrote a very simple c++ program, and the stack traceback by bpftrace seems also wrong. my cpp code is:
```c++
#include <iostream>
#include <unistd.h>

int func_1(int i)
{
    int add = 1;
    return i+add;
}
int func_2(int i)
{
    int add = 2;
    return func_1(add+i);
}
int func_3(int i)
{
    int add = 3;
    return func_2(i+add);
}

int main() 
{
    int i = 0;
    while (1) 
    {        
        std::cout << func_3(i++) << std::endl;
        usleep(500000);
    }
    return 0;
}
```
compile it with: ` g++ -o stacktest -g -O0 -fno-omit-frame-pointer stacktest.cpp`

when use gdb to catch `func_1`,  the result was correct:
![Screenshot2023_09_20_110027](https://github.com/iovisor/bpftrace/assets/9778842/2cb0e6bf-84a5-48d3-bf67-cc71b0469f69)

But when I use bpftrace: `bpftrace -e 'uprobe:/home/test/stacktest:func_1 {printf("%s\n", ustack)}'` , `func_2` was missed in the bt:
![Screenshot2023_09_20_110131](https://github.com/iovisor/bpftrace/assets/9778842/b75abcb4-5247-4794-937e-c3d40a177192)

then I try to catch 'func_2' with `bpftrace -e 'uprobe:/home/test/stacktest:func_2 {printf("%s\n", ustack)}'`, I got this wrong stack:
![Screenshot2023_09_20_110232](https://github.com/iovisor/bpftrace/assets/9778842/d19b6480-c505-422d-b0ff-c4a38489b1ef)

**Comment by viktormalik** [comment]
> @danobi I wrote a very simple c++ program, and the stack traceback by bpftrace seems also wrong. my cpp code is:

This looks like something we have seen already, see discussion in #2703. I'm not sure what causes the issue, might be worth debugging, but we're obtaining stacks from `bpf_get_stackid` so the actual problem may be in kernel.

FWIW, I think that this is not related to the original problem (showing `[unknown]`), though. We could use a reproducer for that.
