### ISSUE TITLE
`args.foo` broken in v0.19.0 ?

### ISSUE THREAD

**Issue by martinetd** [iovisor/bpftrace#2771]
### What reproduces the bug?

Trying to run execsnoop.bt after updating yields this error:
```
./execsnoop.bt:26:2-12: ERROR: Can not access field 'argv' on type '(ctx) struct _tracepoint_syscalls_sys_enter_execve *'. Try dereferencing it first, or using '->'
    join(args.argv);
    ~~~~~~~~~~
```
Replacing `args.argv` by `args->argv` makes it work again

I tried other scripts using `args.foo` and had a similar experience -- it's not difficult to fix so I'd be happy to open a PR just replacing each of these after testing, but since it's breaking existing scripts I'm wondering if it was on purpose?

### bpftrace --info

```
System
  OS: Linux 6.1.44 #1-NixOS SMP PREEMPT_DYNAMIC Tue Aug  8 18:03:51 UTC 2023
  Arch: x86_64  

Build
  version: v0.19.0
  LLVM: 16.0.6
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: yes
  get_func_ip: yes

Kernel features 
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: no
  raw_tp_special: yes
  iter: yes
```

**Comment by martinetd** [comment]
Oh, sorry it's a problem with my build -- I was using an old version of bpftrace through #!/usr/bin/env but I was expecting the scripts to point to the newly built bpftrace.

It works as expected when using the correct binary, with both versions (`args.foo` and `args->foo`) -- sorry for the noise!

**Comment by WhiverFichos** [comment]
Found this problem using package from apt. 
The binary from Releases works.

**Comment by viktormalik** [comment]
@WhiverFichos your apt package version is probably <0.19.0 in which we changed the `args` builtin to be a structure instead of a pointer.
