### ISSUE TITLE
Broken kretprobe kstack dump

### ISSUE THREAD

**Issue by echkenluo** [iovisor/bpftrace#2774]
1. enable kretprobe kstack trace:
echo r skb_segment > kprobe_events
echo stacktrace > events/kprobes/r_skb_segment_0/trigger
echo 1 >  events/kprobes/r_skb_segment_0/enable 

2. sudo bpftrace -e 'kretprobe:skb_segment { printf("kstack: %s\t, return value: %d\n", kstack, retval); }'
3. send packet
4. console output as below:
kstack: 
        kretprobe_trampoline+0
        , return value: -777579008

without kstack output.

**Comment by echkenluo** [comment]
how can i dump kstack  in kretprobe script ?

**Comment by myaut** [comment]
Seems like an old issue - https://github.com/iovisor/bpftrace/issues/68

**Comment by ajor** [comment]
Closing as duplicate of #101
