### ISSUE TITLE
Limit uprobes in shared libraries to a single process when `-p` is given

### ISSUE THREAD

**Issue by viktormalik** [iovisor/bpftrace#2817]
### Is your feature request related to a problem? Please describe.

When attaching to uprobes in shared libraries, the `-p` option is ignored, i.e. library functions called from all processes are hit. Limiting to the calls from the given process would make more sense, e.g. the `gethostlatency.bt` tool (which attaches to several libc functions) could be used per-process:
```
# bpftrace gethostlatency.bt -p $(pgrep firefox)
```
At the moment, the above command will show host name lookup times for all processes, not just the firefox process. See #2813 for details (the reproducer from there can be used on non-NixOs systems, too).

### Describe the solution you'd like

The `bpf_attach_uprobe` function from BCC that we use has a `pid` parameter. At the moment, we're only using the parameter for the `BEGIN` and `END` probes, this could be expanded to also pass the value from `-p`. We're already doing something similar for USDT probes.

**Comment by jordalgo** [comment]
Working on this one here: https://github.com/jordalgo/bpftrace/tree/uprobe-pid-targeting
