### ISSUE TITLE
Support kprobe:module:function

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#2826]
Originally in #2660:

> As mentioned in the issue https://github.com/iovisor/bpftrace/pull/1413 ，the kprobe type currently does not support selecting kernel modules.
>
> This draft MR supports it by allowing the 'kprobe:module:function' syntax with little code changes. Note that wildcard is not supported yet in this MR. I hope anyone who is interested in this feature can make use of this draft patch, or even improve it and make it mergeable in the future.

TLDR: `kfunc` supports selecting symbols by kernel module. `kprobe` does not. It would be good to support kprobe module selection.

PR looks fairly close to completion. Just need some tests and documentation updates.

**Comment by danobi** [comment]
https://github.com/iovisor/bpftrace/pull/2897

**Comment by matthew-olson-intel** [comment]
This is fixed by #2897
