### ISSUE TITLE
Add `EXPECT_JSON` runtime test directive

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#2841]
Runtime tests have quite a few available directives (see https://github.com/iovisor/bpftrace/blob/master/tests/README.md#runtime-test-directives).

A bunch of json output tests (see https://github.com/iovisor/bpftrace/blob/master/tests/runtime/json-output) pipe output from bpftrace to python like this:

```
NAME complex
RUN {{BPFTRACE}} -q -f json -e 'BEGIN { @complex[comm,2] = 5; exit(); }' | python3 -c 'import sys,json; print(json.load(sys.stdin) == json.load(open("runtime/outputs/complex.json")))'
EXPECT ^True$
TIMEOUT 5
```

Would be good to add a `EXPECT_JSON` directive to simplify all those tests. So something like:

```
NAME complex
RUN {{BPFTRACE}} -q -f json -e 'BEGIN { @complex[comm,2] = 5; exit(); }'
EXPECT_JSON runtime/outputs/complex.json
TIMEOUT 5
```

It needs to be done in python (and not an exact string match) to ignore dict reorderings. Cuz in json those kinds of reorderings are not semantically relevant.

**Comment by luigirizzo** [comment]
see https://github.com/iovisor/bpftrace/pull/2845 for a possible implementation of this directive.
