### ISSUE TITLE
bpftrace list probes errors out with fentry/fexit not available for your kernel version

### ISSUE THREAD

**Issue by gkamathe** [iovisor/bpftrace#2855]
### What reproduces the bug? Provide code if possible.

Installing bpftrace from source and simply running -l command reproduces the issue on Fedora 37

```
$ /usr/local/bin/bpftrace -l
stdin:1:1-1: ERROR: fentry/fexit not available for your kernel version.
*:*

$ 
$ ls -l /sys/kernel/btf/vmlinux 
-r--r--r--. 1 root root 5769698 Nov 28 19:07 /sys/kernel/btf/vmlinux
$ 
$ file /sys/kernel/btf/vmlinux
/sys/kernel/btf/vmlinux: data
$

$ /usr/local/bin/bpftrace --version
bpftrace v0.19.0-76-g5ac0
$ 
$ cat /etc/fedora-release 
Fedora release 37 (Thirty Seven)
$ 
$ uname -r
6.5.12-100.fc37.x86_64
$ 
```

### `bpftrace --info` output

```
$ bpftrace --info
System
  OS: Linux 6.5.12-100.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:28:44 UTC 2023
  Arch: x86_64

Build
  version: v0.19.0-76-g5ac0
  LLVM: 15.0.7
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

libbpf: failed to find valid kernel BTF
Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: no
  skboutput: no
  get_tai_ns: yes
  get_func_ip: yes
  jiffies64: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: no
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
  kprobe_multi: yes
  uprobe_multi: no
  raw_tp_special: yes
  iter: no

$ 
```

**Comment by gkamathe** [comment]
@viktormalik 

https://github.com/iovisor/bpftrace/commit/4151babaf9b616e8006762cfa853c01fde3408ae

**Comment by viktormalik** [comment]
cc @jordalgo can you have a look? It seems that the recent addition of `fentry`/`fexit` aliases causes problems when kfunc is not available.

**Comment by gkamathe** [comment]
Some additional debug logs, seems errors are coming from libbpf ?

```
$ /usr/local/bin/bpftrace -l -d
[DEBUG] libbpf: Unsupported BTF_KIND:19
[DEBUG] libbpf: loading kernel BTF '/sys/kernel/btf/vmlinux': -22
[WARN] libbpf: failed to find valid kernel BTF
ERROR: BTF: failed to find BTF data for vmlinux, errno 3
ERROR: BTF: failed to find BTF data
[DEBUG] libbpf: Unsupported BTF_KIND:19
[DEBUG] libbpf: loading kernel BTF '/sys/kernel/btf/vmlinux': -22
[WARN] libbpf: failed to find valid kernel BTF
ERROR: BTF: failed to find BTF data for vmlinux, errno 3
ERROR: BTF: failed to find BTF data
stdin:1:1-1: ERROR: fentry/fexit not available for your kernel version.
*:*

$ 
```

The file its looking for is present

```
$ ls -l /sys/kernel/btf/vmlinux
-r--r--r--. 1 root root 5769698 Nov 28 19:07 /sys/kernel/btf/vmlinux
$ 
$ file /sys/kernel/btf/vmlinux
/sys/kernel/btf/vmlinux: data
$ 
```

**Comment by gkamathe** [comment]
Found some references to similar errors "Unsupported BTF_KIND:19" at other places (bpftune), check below links

https://github.com/oracle/bpftune/issues/35#issuecomment-1635542029

https://lore.kernel.org/bpf/20230720201443.224040-1-alan.maguire@oracle.com/

As for the libbpf version this is what I have on the system where issue was reproduced

```
$ rpm -qa | grep -i libbpf
libbpf-0.8.0-2.fc37.x86_64
libbpf-devel-0.8.0-2.fc37.x86_64
$ 
```

**Comment by jordalgo** [comment]
> cc @jordalgo can you have a look? It seems that the recent addition of fentry/fexit aliases causes problems when kfunc is not available.

No problem. Will have a look.

**Comment by jordalgo** [comment]
I believe this is just a biproduct of fentry/fexit being alphabetically first in the attach point provider list. kfuncs/kretfuncs should trigger a similar error "kfunc/kretfunc not available for your kernel version" as they both use the same check:
```
 if (!bpftrace_.feature_->has_kfunc())
```

That being said, I'm not sure if we want bpftrace to completely error out when listing things if only one feature is not supported.

**Comment by viktormalik** [comment]
> I believe this is just a biproduct of fentry/fexit being alphabetically first in the attach point provider list. kfuncs/kretfuncs should trigger a similar error "kfunc/kretfunc not available for your kernel version"

Is that really the case? I remember fixing this in the past so that listing everything lists available probes only. Also, after reverting 4151babaf9b616e8006762cfa853c01fde3408ae, `bpftrace -l` works as expected (with no `kfunc:` probes shown on a system without BTF).

It looks to me as if the `fentry`/`fexit` alias somehow disrupted this.
