### ISSUE TITLE
type_id=3 vlen != 0 on 5.4 LTS kernel

### ISSUE THREAD

**Issue by xiaoqing-wei** [iovisor/bpftrace#2913]
Hi team,

when using the bleeding edge bpftrace static build on a centos7 with elrepo kernel (5.4/6.6)
I found that bt scripts with BEGIN {} is not working on bleeding bpftrace 0.19.0 binary combined 5.4 kernel.

I also tried from https://repos.baslab.org/rhel/7/bpftrace-daily/
bpftrace-0.14.1-1.202204049382ad1.el7.x86_64 , and it's working

1) 0.19.0 + 5.4 lts kernel
2) 0.19.0 + 6.6 lts kernel
3) 0.14.1 + 5.4 lts kernel

/2) and 3) are good.
/1) is not working.

./bpftrace -v -e 'BEGIN {printf("Hello eBPF"); exit();}'
INFO: node count: 8
Attaching 1 probe...

Error log: 
magic: 0xeb9f
version: 1
flags: 0x0
hdr_len: 24
type_off: 0
type_len: 76
str_off: 76
str_len: 50
btf_total_size: 150
[1] PTR (anon) type_id=2
[2] INT int8 size=1 bits_offset=0 nr_bits=8 encoding=SIGNED
[3] FUNC_PROTO (anon) return=4 args=(1 var1)
[4] INT int64 size=8 bits_offset=0 nr_bits=64 encoding=SIGNED
[5] FUNC BEGIN type_id=3 vlen != 0

ERROR: Error loading program: BEGIN
[root@VM-224-24-centos bpftrace-bleeding-edge]# uname -r
5.4.266-1.el7.elrepo.x86_64

=====

./bpftrace -v -e 'BEGIN {printf("Hello eBPF"); exit();}'
INFO: node count: 8
Attaching 1 probe...

Program ID: 4

The verifier log: 
processed 60 insns (limit 1000000) max_states_per_insn 0 total_states 4 peak_states 4 mark_read 2

Attaching BEGIN
Hello eBPF

[root@VM-224-24-centos bpftrace-bleeding-edge]# uname -r
6.6.10-1.el7.elrepo.x86_64

===== bpftrace --info on 5.4 lts kernel =====
System
  OS: Linux 5.4.266-1.el7.elrepo.x86_64 #1 SMP Mon Jan 8 23:23:50 EST 2024
  Arch: x86_64

Build
  version: v0.19.0
  LLVM: 17.0.6
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

libbpf: failed to find valid kernel BTF
Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: no
  dpath: no
  skboutput: no
  get_tai_ns: no
  get_func_ip: no
  jiffies64: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: no
  module btf: no
  map batch: no
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: no

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
  kprobe_multi: no
  uprobe_multi: no
  raw_tp_special: no
  iter: no

====

I also tried watchpoint, and it failed with same reason.

./bpftrace -v -e "watchpoint:0x$(awk '$3 == "jiffies" {print $1}' /proc/kallsyms):8:w {@[kstack] = count();}"
INFO: node count: 7
Attaching 1 probe...

Error log: 
magic: 0xeb9f
version: 1
flags: 0x0
hdr_len: 24
type_off: 0
type_len: 76
str_off: 76
str_len: 102
btf_total_size: 202
[1] PTR (anon) type_id=2
[2] INT int8 size=1 bits_offset=0 nr_bits=8 encoding=SIGNED
[3] FUNC_PROTO (anon) return=4 args=(1 var1)
[4] INT int64 size=8 bits_offset=0 nr_bits=64 encoding=SIGNED
[5] FUNC watchpoint_18446744071601934336 type_id=3 vlen != 0

WARNING: Error loading program: watchpoint:18446744071601934336:8:w, skipping.
ERROR: Error attaching probe: watchpoint:18446744071601934336:8:w: Bad file descriptor

**Comment by danobi** [comment]
cc @viktormalik @jordalgo 

I'm going to put this under high priority fix. This looks like a regression with BTF loading. 5.4 kernel is an LTS with EOL Dec, 2025. So we should make sure it works.

This fix would be a good candidate for vmtest (https://github.com/danobi/vmtest) in CI.

**Comment by viktormalik** [comment]
I'll investigate tomorrow.

**Comment by jordalgo** [comment]
@viktormalik Let me know if you want me to take a look too.

**Comment by danobi** [comment]
Is this something we should try bringing up to bpf@vger? IIUC libbpf does kinda promise to gracefully handle backwards compat. Not sure if this case is applicable though.

**Comment by viktormalik** [comment]
I didn't have time to look more carefully but it seems that BTF/func_info support was added in 5.0. So it may be that our generated BTF cannot be handled by older kernels. I'll investigate more next week.

**Comment by viktormalik** [comment]
So, I was able to find the problem - older kernels do not have https://github.com/torvalds/linux/commit/51c39bb1d5d105a02e29aa7960f0a395086e6342 and therefore do not support BTF_KIND_FUNC entries with global linkage. Libbpf sanitizes this for older kernels since https://github.com/torvalds/linux/commit/2d3eb67f64ec317bbfe340cfcc8325d40a6ff317 (same series) but it only does that when the program is loaded via `bpf_object` (which we don't at this point).

I can see several options going forward:
1. Mimic libbpf behaviour and do the same sanitization in bpftrace (including an added runtime check that kernel doesn't support global BTF func entries). This would eventually go away (we plan to load via `bpf_object`) so it's a bit of redundant work. If we still go that way, I'd prefer doing it only after the `BpfBytecode` class is introduced (#2912) b/c that's where such code logically belongs.
2. Do nothing now and wait until we make better use of libbpf for program loading (tracked in #2334) and we will get the sanitization (and others) for free.
3. Add a new option `--no-btf` to skip generation of BTF which will allow to use current bpftrace on older kernels with (e.g.) this feature missing.

**Comment by danobi** [comment]
@viktormalik nice find. Do you have a sense of how much work is left? If you can finish libbpf migration in this release cycle then I think it'd be ok to wait.

**Comment by viktormalik** [comment]
TBH I don't think that we can make it this cycle. The work itself will take some time but reviews may take even longer since it's a big change. On top of that, I'd like to do a release soon as we did the last one ~3 months ago.

**Comment by ajor** [comment]
Sorry for my ignorance, but if BTF_FUNC_GLOBAL isn't supported on older kernels, how are these BTF entries appearing in there?

Option 1 (Mimic libbpf behaviour and do the same sanitization in bpftrace) sounds the best to me, and judging from that libbpf commit it doesn't look like too much work?

**Comment by viktormalik** [comment]
> Sorry for my ignorance, but if BTF_FUNC_GLOBAL isn't supported on older kernels, how are these BTF entries appearing in there?

We're emitting them by marking the functions in our BPF programs with `ExternalLinkage` (to prevent LLVM inlining them). This is then translated (by LLVM) into a BTF entry with `BTF_FUNC_GLOBAL`.
 
> Option 1 (Mimic libbpf behaviour and do the same sanitization in bpftrace) sounds the best to me, and judging from that libbpf commit it doesn't look like too much work?

It's not that easy b/c we have to copy some portion of libbpf code for iterating BTF entries in a non-const way. These functions are internal to libbpf and they only export functions which give you const-pointers. But I'm already doing something similar when emitting BTF for maps (which also needs some fixing on our side) so I can try to reuse that code here.

**Comment by jordalgo** [comment]
Nice work!
