### ISSUE TITLE
cpid builtin for child PID

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#298]
As a follow on from the -c option #297, this should work:

```
bpftrace -e 'k:vfs_read /pid == cpid/ { printf("%s == ls\n", comm); }' -c ls
...
ls == ls
ls == ls
ls == ls
```

This will involve adding cpid as a builtin. It should return the child PID of the process launched in -c.

**Comment by kazuho** [comment]
> I took a look at this, but there's a problem with ordering: when we build the BPF program and process cpid, the child process hasn't launched yet from main.cpp->run().
> 
> If the code could be modified to do the fork() earlier, and the execve() later (somehow! we're now in a different process, so it might involve some IPC call), then the child PID would be available for when we need it.

Novice user of bpftrace here. I have a tentative patch that does that in https://github.com/kazuho/bpftrace/commit/2ca62f9d7376d568b83c6396a6a49bec3e35d07d, using  pipe (2), though it is my understanding that it becomes impossible to set USDT probes if we delay calling `execve`.

So to me it seems that the right solution is to use `ptrace` to trap the execution of the child process _after_ `execve` is being called.

Does that sound correct to you? If it does, maybe I can find some time to work on a PR. I am interested in using USDT from the moment the process is being launched.
