### ISSUE TITLE
Poor handling of incorrect spelling of 'syscalls' provider in probe spec

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#306]
This problem may be wider than the as described here. When tracing the exit(2) probe I misspelt the 'syscalls' provider component with 'sysalls' and the outcome is a real mess:

```
# cat exit.bt
tracepoint:sysalls:sys_enter_exit
{
        @[comm] = count();
}
# ./bpftrace ./exit.bt
No such file or directory: /sys/kernel/debug/tracing/events/sysalls/sys_enter_exit/format
Attaching 1 probe...
open(/sys/kernel/debug/tracing/events/sysalls/sys_enter_exit/id): No such file or directory
Error attaching probe: tracepoint:sysalls:sys_enter_exit
```

I would have expected a simple error message about a malformed probe specification or an invalid provider and not a bunch of implementation specific error messages.

**Comment by brendangregg** [comment]
You're right, providers need better handling. Each needs a clause or a function to do an "is valid name" check. Like tracepoint_is_valid(), kprobe_is_valid(), etc.
