### ISSUE TITLE
Build warnings are turned off

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#316]
While doing some packaging, I discovered the cmake build has all the build warnings turned off: https://github.com/iovisor/bpftrace/blob/master/CMakeLists.txt#L8-L21 . Any reason for this? Can I turn them back on?

It catches a couple of harmless issues right now. However, we might get lucky in the future and have it catch some trickier bugs.

**Comment by mmarchini** [comment]
Sounds good to me.

**Comment by sourabhtk37** [comment]
@danobi Can I take this up? Added PR.

**Comment by fbs** [comment]
Looks fixed with #403
