### ISSUE TITLE
Appetite for C++17

### ISSUE THREAD

**Issue by Birch-san** [iovisor/bpftrace#318]
Any thoughts on whether to update to [C++17](https://stackoverflow.com/questions/38060436/what-are-the-new-features-in-c17)?

We use the visitor pattern in a few places, so it'd be nice to have access to std::variant and std::visit. We had multiple implementations of IPrintable which I suspect could've been expressed as a std::variant (i.e. a type-safe union).

std::optional would be nice (this provides a more semantic alternative over having to check whether our pointers are null).

std::string_view would be a nice way to avoid string copies (upon which [a pull request](https://github.com/iovisor/bpftrace/pull/217) was blocked for 2 months).

std::byte would add useful semantic; we currently receive perf events as a `uint8_t*`.

std::apply may be able to tidy up [this switch statement](https://github.com/iovisor/bpftrace/blob/01491c635447b07276a49e13bd8e7c91a6074e97/src/bpftrace.cpp#L273-L301). Maybe it provides a way to pass variadic arguments (perhaps as std::any), which would help with https://github.com/iovisor/bpftrace/issues/317.

Structured bindings is a nice way to have multiple return types. For example: when we attempt Map creation, we may fail to acquire a BPF map handle. It'd be good to return an optional Map **and** error information. So that we can print and handle the error in the context of our algorithm.

C++ is [supported down to Clang 5](https://clang.llvm.org/cxx_status.html), which is already our minimum requirement.

**Comment by brendangregg** [comment]
merged #384, closing
