### ISSUE TITLE
Add `--version`

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#322]
`bpftrace --version` should output the current version of bpftrace. Right now we're on version [0.8](https://github.com/iovisor/bpftrace/releases/tag/v0.8).

**Comment by williangaspar** [comment]
I guess it should print Copyright and License information along with the version. Do We have the version saved somewhere already? Like an environment variable or something.

**Comment by xbe** [comment]
I like [this approach](https://stackoverflow.com/a/12368262).

It relies on running:
```
git describe --abbrev=4 --dirty --always --tags
```

Presently, that gives me:
```
v0.8-9-gc008
```

That means that the last git-tagged version was 0.8, which was 9 commits ago. The current git commit hash starts with "c008".
