### ISSUE TITLE
ksym() alias/replacement to sym()

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#324]
`kaddr()` and `uaddr()` are nice and symmetric. `sym()` and `usym()` are inconsistent. I keep wanting to use `ksym()` but mistake.

I'd add `ksym()` as an alias to `sym()`, then replace `sym()` with `ksym()` in all our docs and scripts. We could potentially remove `sym()` in the future.

**Comment by dalehamel** [comment]
Weighing in with my 2 cents - I agree.

It's more consistent with usym and is also more intuitive. bpftrace is also new enough (at least "in the wild") that changing this now won't be too bad in terms of compatibility. Aliasing would handle that concern, and the docs update should prevent `sym` from propagating too much.

This should also be a fairly trivial change codewise.
