### ISSUE TITLE
Missing libclang.a for static build

### ISSUE THREAD

**Issue by DavidVentura** [iovisor/bpftrace#336]
Hello
I am trying to do a static build of bpftrace, but failing to find `libclang.a`

```
$ cmake -DCMAKE_BUILD_TYPE=Release -DSTATIC_LINKING:BOOL=ON ../
$ make
/usr/bin/ld: cannot find -lclang
collect2: error: ld returned 1 exit status
src/CMakeFiles/bpftrace.dir/build.make:566: recipe for target 'src/bpftrace' failed
make[2]: *** [src/bpftrace] Error 1
CMakeFiles/Makefile2:236: recipe for target 'src/CMakeFiles/bpftrace.dir/all' failed
make[1]: *** [src/CMakeFiles/bpftrace.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

```
$ sudo /usr/share/bcc/tools/opensnoop -x -n ld
PID    COMM               FD ERR PATH
8756   ld                 -1   2 /usr/lib/gcc/x86_64-linux-gnu/7/libclang.a
8756   ld                 -1   2 /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libclang.a
8756   ld                 -1   2 /usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libclang.a
8756   ld                 -1   2 /lib/x86_64-linux-gnu/libclang.a
8756   ld                 -1   2 /lib/../lib/libclang.a
8756   ld                 -1   2 /usr/lib/x86_64-linux-gnu/libclang.a
8756   ld                 -1   2 /usr/lib/../lib/libclang.a
8756   ld                 -1   2 /usr/lib/gcc/x86_64-linux-gnu/7/../../../libclang.a
8756   ld                 -1   2 //usr/local/lib/x86_64-linux-gnu/libclang.a
8756   ld                 -1   2 //lib/x86_64-linux-gnu/libclang.a
8756   ld                 -1   2 //usr/lib/x86_64-linux-gnu/libclang.a
8756   ld                 -1   2 //usr/lib/x86_64-linux-gnu64/libclang.a
8756   ld                 -1   2 //usr/local/lib64/libclang.a
8756   ld                 -1   2 //lib64/libclang.a
8756   ld                 -1   2 //usr/lib64/libclang.a
8756   ld                 -1   2 //usr/local/lib/libclang.a
8756   ld                 -1   2 //lib/libclang.a
8756   ld                 -1   2 //usr/lib/libclang.a
8756   ld                 -1   2 //usr/x86_64-linux-gnu/lib64/libclang.a
8756   ld                 -1   2 //usr/x86_64-linux-gnu/lib/libclang.a
```

I checked on ubuntu's repositories and `libclang.a` is not provided, I even downloaded the 7.0.1 release of clang and the file is also not in the tar.. where am I supposed to get it?

Just as sanity check - I am running the exact same commands that the ubuntu docker image is running..

**Comment by mmarchini** [comment]
`libclang.a` is not provided in LLVM official releases or Fedora/CentOS/Debian/Ubuntu repositories. We should contact packagers and LLVM releasers and ask to add libclang.a to the released files as well (I just don't know who to contact in that case).

**Comment by caringi** [comment]
At least in Fedora, shipping static libraries is strongly discouraged...

"Packages including libraries SHOULD exclude static libs as far as possible (eg by configuring with --disable-static). Applications linking against libraries SHOULD link against shared libraries not static versions."

https://docs.fedoraproject.org/en-US/packaging-guidelines/#packaging-static-libraries

**Comment by gslavin** [comment]
I tried building my own libclang.a in order to build a static version of bpftrace, but I ran into further problems:

    [  5%] Built target parser
    [  6%] Built target arch
    [ 13%] Built target ast 
    [ 15%] Built target resources
    [ 16%] Linking CXX executable bpftrace
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.a(eh_globals.o): undefined reference to symbol '__tls_get_addr@@GLIBC_2.3'
    //lib/x86_64-linux-gnu/ld-linux-x86-64.so.2: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    src/CMakeFiles/bpftrace.dir/build.make:581: recipe for target 'src/bpftrace' failed
    make[2]: *** [src/bpftrace] Error 1
    CMakeFiles/Makefile2:1196: recipe for target 'src/CMakeFiles/bpftrace.dir/all' failed
    make[1]: *** [src/CMakeFiles/bpftrace.dir/all] Error 2
    Makefile:138: recipe for target 'all' failed
    make: *** [all] Error 2

Has anyone successfully built a static version of bpftrace? I'm currently using the following cmake options:

`cmake -DCMAKE_BUILD_TYPE=Release -DSTATIC_LINKING:BOOL=ON ..`

**Comment by dalehamel** [comment]
I was trying to get a static build working with glibc, in the hopes that I could get a working static build that wouldn't crash, as a fix for #266 

Unfortunately, I ran into the same issue as @gslavin exactly.

It appears that the symbol `__tls_get_addr` isn't defined within glibc:

```
objdump -tT /lib64/libc-2.29.so | grep __tls_get_addr
0000000000000000      DF *UND*  0000000000000000  GLIBC_2.3   __tls_get_addr
```

It looks like from ldd, glibc depends on this symbol existing in:

```
objdump -tT /lib64/ld-linux-x86-64.so.2 | grep tls_get_addr
0000000000017400 g    DF .text  000000000000003d  GLIBC_2.3   __tls_get_addr
```

However... that means that there is no way that I can think of to actually do a static build with glibc, as this symbol is provided by the runtime linker DSO.

The reason why this seems to work with alpine is that musl includes this directly within its libc implementation. However, the very issue I'm trying to work around is the bugs that musl introduces per my debugging of #266 

This might mean that a fully statically linked bpftrace is only possible with musl, though I might take a crack at trying this with uclibc just to see how that goes, as it appears to include this symbol like musl does...

**Comment by dalehamel** [comment]
Nope, it looks like uclibc would have the same issue:

```
$objdump -tT /lib/libc.so.0 | grep __tls
0000000000000000      DF *UND*  0000000000000000 __tls_get_addr
```
```
$ ldd /lib/libc.so.0
d64-uClibc.so.0 => /lib/ld64-uClibc.so.0 (0x7f1c8c796000)
```

```
objdump -tT /lib/ld64-uClibc.so.0 | grep tls
000000000000a110 g    DO .bss   0000000000000008 _dl_tls_static_used
000000000000a158 g    DO .bss   0000000000000008 _dl_tls_static_nelem
0000000000003133 g    DF .text  0000000000000056 _dl_tls_setup
0000000000002331 g    DF .text  00000000000000fc _dl_allocate_tls_init
0000000000003abc g    DF .text  0000000000000120 __tls_get_addr
```

But when you do this to musl, you can see:

```
$ objdump -tT /lib/libc.musl-x86_64.so.1  | grep __tls
000000000004fb7f g    DF .text  0000000000000019 __tls_get_addr
```

So musl doesn't seem to need this separate static library, but perhaps that might also be the reason why the crashes in #266 occur, as it looks like it is these dynamic library symbols that cause the crash there.

Perhaps then it might actually be impossible to have a 100% statically built bpftrace? (that is also correct, as #266 shows the musl build seems to crash)

**Comment by dalehamel** [comment]
To work around the missing libclang.a though, I was thinking a viable solution might be to configure llvm/clang as part of bpftrace cmake build, this can pass the necessary cmake flag to make the static libclang.a, and other static libraries.

Even if a fully static build cannot be done, this eliminates the need to distribute llvm/clang.

**Comment by dalehamel** [comment]
https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/dl-tls.c;h=65d35202200e3436588a94b21a2204b49a305125;hb=HEAD#l821 has a comment a warning about this function with statically linked programs:

```
821 /* The generic dynamic and local dynamic model cannot be used in
822    statically linked applications.  */
```
