### ISSUE TITLE
kstack alias/replacement to stack

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#344]
Similar to #324, for consistency and intuition it would be nice if the stack builtins were called kstack and ustack.

We can put in an alias for stack->kstack that prints a warning that it will be deprecated later.

**Comment by williangaspar** [comment]
should the deprecated message appear at the start or the end of execution? Sometimes probes will print a lot of data right away

**Comment by brendangregg** [comment]
Start. That would make logical sense: when it's doing compiling and checking of code, before running.
