### ISSUE TITLE
runtime test suite

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#35]
The /tests currently test parsing and BPF code generation, but does not test tracing functionality at runtime (actually running bpftrace and tracing an event). This is necessary to ensure everything actually works. It's a little tricky, as any given event (kprobe, tracepoint, etc) may or may not fire on its own, and may need to be triggered by the test suite.

I could imagine using the tracepoint:syscalls:sys_exit_nanosleep event as much as possible, as it's a stable API and can be easily triggered (from the shell: `sleep 1`).

Here's a very basic hacky example:

```
test=pid; sleep 1 & sleep 15 & ./src/bpftrace -e 'tracepoint:syscalls:sys_exit_nanosleep { printf("SUCCESS '$test' %d\n", pid); exit(); }' | grep '^SUCCESS '$test' [0-9][0-9]*$' || echo "FAILURE $test"
test=uid; sleep 1 & sleep 15 & ./src/bpftrace -e 'tracepoint:syscalls:sys_exit_nanosleep { printf("SUCCESS '$test' %d\n", uid); exit(); }' | grep '^SUCCESS '$test' [0-9][0-9]*$' || echo "FAILURE $test"
test=reg; sleep 1 & sleep 15 & ./src/bpftrace -e 'tracepoint:syscalls:sys_exit_nanosleep { printf("SUCCESS '$test' %d\n", reg("ip")); exit(); }' | grep '^SUCCESS '$test' [0-9][0-9]*$' || echo "FAILURE $test"
```

The idea of spawning a "sleep 1" and a "sleep 15" is to allow the test to complete quickly (sleep 1), but if bpftrace was slow to initialize, then there is a 15 second timeout (or shorter, since prior tests that complete in 1 second leave 15 second sleepers still running).

Running these produces the output

```
SUCCESS pid 1446
SUCCESS uid 0
SUCCESS reg 0
```

So the output says "SUCCESS" or "FAILURE", the name of the test, and some argument to aid debugging.

I think it would be better to write this in C++, or C, or Perl, or Python, and have better control over the sleeps.

The functionality that should be tested should be everything from the reference guide.

**Comment by williangaspar** [comment]
Should it run with the other tests or separated? The test suite takes about 20s to run.
Right now I'm running them with:

```cd tests/python```
```sudo python -m unittest discover --pattern=*.py```

**Comment by ajor** [comment]
I think it should have it's own separate way of running the tests as these new ones will require root and probably won't work in the CI

**Comment by williangaspar** [comment]
There is a couple of functions and variables printing random characters. 

ex: `bpftrace -e 'uprobe:/bin/bash:readline { printf("%s\n", usym(reg("ip"))); }'`

Can someone check whether  it is a problem with pbftrace or just my environment?
maybe https://github.com/iovisor/bpftrace/issues/194 has something to do with it
