### ISSUE TITLE
No output after executing the command "bpftrace -lv tracepoint:syscalls:sys_enter_open" followed by the tutorial.

### ISSUE THREAD

**Issue by CavemanWork** [iovisor/bpftrace#378]
Environment: 
- ubuntu 18.04
- kernel Linux version 4.15.0-29-generic

Follow the guide in [The -v option when listing tracepoints will show their arguments for use from the args builtin](https://github.com/iovisor/bpftrace/blob/HEAD/docs/reference_guide.md#4--l-listing-probes ), no result of the terminal. 

`root@Yingyun-VB:~/workspace/bpftrace# bpftrace -lv tracepoint:syscalls:sys_enter_open                                                             
tracepoint:syscalls:sys_enter_open
`

**Comment by brendangregg** [comment]
I wonder if you have debugfs mounted on /sys/kernel/debug. Can you try this cat(1) command?

```
# cat /sys/kernel/debug/tracing/events/syscalls/sys_enter_open/format
name: sys_enter_open
ID: 602
format:
	field:unsigned short common_type;	offset:0;	size:2;	signed:0;
	field:unsigned char common_flags;	offset:2;	size:1;	signed:0;
	field:unsigned char common_preempt_count;	offset:3;	size:1;	signed:0;
	field:int common_pid;	offset:4;	size:4;	signed:1;

	field:int __syscall_nr;	offset:8;	size:4;	signed:1;
	field:const char * filename;	offset:16;	size:8;	signed:0;
	field:int flags;	offset:24;	size:8;	signed:0;
	field:umode_t mode;	offset:32;	size:8;	signed:0;

print fmt: "filename: 0x%08lx, flags: 0x%08lx, mode: 0x%08lx", ((unsigned long)(REC->filename)), ((unsigned long)(REC->flags)), ((unsigned long)(REC->mode))
```

**Comment by CavemanWork** [comment]
The debugfs was mounted, and result of cat() like below:

cat /sys/kernel/debug/tracing/events/syscalls/sys_enter_open/format
name: sys_enter_open
ID: 604
format:
        field:unsigned short common_type;       offset:0;       size:2; signed:0;
        field:unsigned char common_flags;       offset:2;       size:1; signed:0;
        field:unsigned char common_preempt_count;       offset:3;       size:1; signed:0;
        field:int common_pid;   offset:4;       size:4; signed:1;
        field:int __syscall_nr; offset:8;       size:4; signed:1;
        field:const char * filename;    offset:16;      size:8; signed:0;
        field:int flags;        offset:24;      size:8; signed:0;
        field:umode_t mode;     offset:32;      size:8; signed:0;

print fmt: "filename: 0x%08lx, flags: 0x%08lx, mode: 0x%08lx", ((unsigned long)(REC->filename)),((unsigned long)(REC->flags)), ((unsigned long)(REC->mode))

**Comment by brendangregg** [comment]
Should work then. I only recently merged that feature, so make sure you have that commit in your list.cpp, and you've run a fresh build and install:
```
~/Build/bpftrace/src> git log -p list.cpp 
commit 4a048fccbd1bf28743e36c349e156ea2734d2855
Author: Augusto Caringi <acaringi@redhat.com>
Date:   Tue Jan 22 17:25:55 2019 +0100

    Add support to list tracepoint arguments (#323)

[...]
```

**Comment by CavemanWork** [comment]
@brendangregg  
Ah~ it works after pulled the latest code, Thanks!
