### ISSUE TITLE
local variable name reuse: A call to built-in function 'abort' is not supported.

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#380]
```
# ./testfunc.bt 
error: <unknown>:0:0: in function tracepoint:sched:sched_process_exec i64 (i8*): A call to built-in function 'abort' is not supported.
```

program:

```
#!/usr/local/bin/bpftrace

tracepoint:sched:sched_process_fork
{
	$name = "fork";
	@[$name] = count();
}

tracepoint:sched:sched_process_exec
{
	$name = "exec";
	@[$name] = count();
}
```

If instead of $name in the second probe, I rename that to $name2, it works. The problem is reusing $name across different probes. Each probe should be able to have its own version of $name without clashing. I think the problem is that it's compiled as a global variable when it should be local.

**Comment by tyroguru** [comment]
I've hit this one several times so a fix would be super helpful.
