### ISSUE TITLE
fn_name needs to be unique for attaching to same probe

### ISSUE THREAD

**Issue by sourabhtk37** [iovisor/bpftrace#395]
Note: Creating issue for discussion (from #22 )

https://github.com/iovisor/bpftrace/blob/master/src/attached_probe.cpp#L429

**Comment by sourabhtk37** [comment]
Should we go ahead with random alphanumeric suffix?

**Comment by mmarchini** [comment]
An incremental numeric suffix should work I think

**Comment by sourabhtk37** [comment]
@mmarchini Forgive me, but how can we know if a probe of same type is already attached?

**Comment by mmarchini** [comment]
True, if it has been attached by another process we might not see it. What about suffixing it with `_<bpftrace pid>_<incremental number>`?

**Comment by sourabhtk37** [comment]
yeah, that should work. If we have 1 one bpftrace process, we could increment it by one and if 2 process, increment it by 2. What do you say?

**Comment by brendangregg** [comment]
What was this solving? Was it a name clash in /sys/kernel/debug/tracing/*events? (that's going away in the future with perf_event_open() and FD access, but we'd need a fix in the meantime).

**Comment by mmarchini** [comment]
> Was it a name clash in /sys/kernel/debug/tracing/*events?

That's what I thought when I read the TODO, but apparently, it's not clashing:

```
# ./src/bpftrace -e 'usdt:/home/mmarchini/lsls/main:fprobe { printf("1\n"); } usdt:/home/mmarchini/lsls/main:fprobe { printf("2\n"); }'

# cat /sys/kernel/debug/tracing/uprobe_events
p:uprobes/p__home_mmarchini_lsls_main_692_2_bcc_9649 /home/mmarchini/lsls/main:0x0000000000000692
p:uprobes/p__home_mmarchini_lsls_main_692_1_bcc_9649 /home/mmarchini/lsls/main:0x0000000000000692
```

Maybe something changed in `bcc` and we don't need unique fn_names anymore?
