### ISSUE TITLE
const leads to struct not recognized

### ISSUE THREAD

**Issue by navytux** [iovisor/bpftrace#406]
Consider the following program

```c
#include <linux/fuse.h>
#include <linux/uio.h>

kretprobe::fuse_dev_read {
        $to = (iov_iter *)arg1;
        $buf = $to->iov->iov_base;
}
```

On it bpftrace gives:

```
root@deco:# bpftrace x.bt 
Unknown struct/union: 'const struct iovec'
```

However if I manually remove const from `iov_iter`  struct:

```c
#include <linux/fuse.h>
#include <linux/uio.h>

struct xiov_iter {
        unsigned int type;
        size_t iov_offset;
        size_t count;
        union {
                /*const*/ struct iovec *iov;                     // <-- NOTE
                /*const*/ struct kvec *kvec;
                /*const*/ struct bio_vec *bvec;
                struct pipe_inode_info *pipe;
        };
        union {
                unsigned long nr_segs;
                struct {
                        int idx;
                        int start_idx;
                };
        };
};

kretprobe::fuse_dev_read {
        $to = (xiov_iter *)arg1;
        $buf = $to->iov->iov_base;
}
```

it compiles ok.

**Comment by dalehamel** [comment]
I wonder if in LLVM a const struct has a different type code than a normal struct?

If so, it could probably be a simple fix to add the necessary type to treat const structs as structs are treated.

**Comment by dalehamel** [comment]
I checked https://clang.llvm.org/doxygen/group__CINDEX.html#gaaccc432245b4cd9f2d470913f9ef0013 and I don't see anything that should obviously handle the const struct case, I'm a bit surprised if CXCursor_StructDecl  doesn't :thinking: 

It would be good to attach a debugger and see what happens in `clang_parser.cpp` and have a minimal example of a `const struct` not working where a `struct` does.

**Comment by dalehamel** [comment]
I wonder if it thinks that it is a `CXCursor_ConstAttr`? If so, I'd expect it to do that for any type of `const`.

**Comment by navytux** [comment]
Thanks
