### ISSUE TITLE
C++17 build

### ISSUE THREAD

**Issue by Birch-san** [iovisor/bpftrace#434]
C++17 was enabled by https://github.com/iovisor/bpftrace/pull/384, justification: https://github.com/iovisor/bpftrace/issues/318

The first attempt to use a C++17 feature was in https://github.com/iovisor/bpftrace/pull/399.

This resulted in build breaks. As a stopgap to un-break the build: the feature was rewritten in C++14 via https://github.com/iovisor/bpftrace/pull/423 and https://github.com/iovisor/bpftrace/pull/433.

It's worth discussing next steps. I propose to get C++17 build working again.

### Characterisation of the build break

We have a [matrix of build targets](https://github.com/iovisor/bpftrace/blob/master/.travis.yml), which behaved differently.

Travis results [here](https://travis-ci.org/iovisor/bpftrace/jobs/493441034) for https://github.com/iovisor/bpftrace/pull/421, which was a commit downstream of https://github.com/iovisor/bpftrace/pull/399 and https://github.com/iovisor/bpftrace/pull/384 (i.e. used C++17 features, and had C++17 support enabled).

- LLVM5 target [failed to build](https://travis-ci.org/iovisor/bpftrace/jobs/493441040)
- LLVM6 target [built successfully](https://travis-ci.org/iovisor/bpftrace/jobs/493441034)
- LLVM7 target [built successfully](https://travis-ci.org/iovisor/bpftrace/jobs/493441036)

But the LLVM target refers to _which libLLVM version we link against_, and is _not a commentary on which compiler was used_.

The _real_ difference here is that the LLVM5 target is built using a substantially different Docker image (our [alpine image](https://github.com/iovisor/bpftrace/blob/master/docker/Dockerfile.alpine), as opposed to one of our [fedora images](https://github.com/iovisor/bpftrace/tree/master/docker)).

Broken Alpine build [installs gcc 6](https://travis-ci.org/iovisor/bpftrace/jobs/493441040#L478-L482):

```
(14/62) Installing libstdc++ (6.4.0-r9)
(15/62) Installing gcc (6.4.0-r9)
(16/62) Installing musl-dev (1.1.19-r10)
(17/62) Installing libc-dev (0.7.1-r0)
(18/62) Installing g++ (6.4.0-r9)
```

Successful Fedora build [installs gcc 8](https://travis-ci.org/iovisor/bpftrace/jobs/493441034#L504):

```
 Package                  Arch     Version                      Repository Size
================================================================================
 gcc                      x86_64   8.2.1-6.fc28                 updates    23 M
```

gcc introduced the majority of its C++17 features [as of gcc 7](https://gcc.gnu.org/projects/cxx-status.html#cxx17) (of particular note are structured bindings, which were used in https://github.com/iovisor/bpftrace/pull/399).

### Solution

We should update our Alpine image to grab a newer gcc, g++ and libstdc++. Specifically gcc 7 or newer.

**Comment by Birch-san** [comment]
We get our gcc 6 when [we install build-base](https://github.com/iovisor/bpftrace/blob/master/docker/Dockerfile.alpine#L4) — it's [a transitive dependency](https://pkgs.alpinelinux.org/package/v3.8/main/x86_64/build-base).

**Comment by Birch-san** [comment]
Alpine 3.9 main repository includes gcc 8:

https://pkgs.alpinelinux.org/packages?name=gcc&branch=v3.9&repo=main&arch=x86_64

Maybe all we need to do is update [our base image](https://github.com/iovisor/bpftrace/blob/master/docker/Dockerfile.alpine#L1) to `alpine:3.9`.

**Comment by mmarchini** [comment]
I think we should avoid C++17 features for now, recent changes broke a lot of people who are actively working on bpftrace. We can revisit it in the future though.

(I like the idea of using a newer version of the language, just don't think it's the right time to adopt it in the project)
