### ISSUE TITLE
--silent (or --quiet)

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#446]
This option would disable any output to stdout which doesn't come from the bpftrace program being executed. I think the only message that would be suppressed right now is `Attaching X probes...`, since we output other warnings to stderr. The goal is to make it easier for external applications to parse bpftrace's output.

**Comment by brendangregg** [comment]
I'd add it as -q. See #19.

We can still do #19, if we want, there'll just be a few that are reserved (--version, --help).

Also note that with the tools using #!/usr/bin/env bpftrace, they can't accept options. #!/usr/local/bin/bpftace can. There are other issues with env we discovered with bcc, and bcc has now switched back to direct paths, and I've been thinking that we will want to as well.

**Comment by mmarchini** [comment]
-q sounds good to me.
