### ISSUE TITLE
Parser.unterminated_string syntax error

### ISSUE THREAD

**Issue by zlim** [iovisor/bpftrace#456]
Is this expected?

https://travis-ci.org/iovisor/bpftrace/jobs/498975534#L1678
```
[ RUN      ] Parser.unterminated_string
10.668-674: unterminated string
10.668-674: syntax error, unexpected end of file
```

**Comment by mmarchini** [comment]
Probably expected, since this is testing how bpftrace behaves for unterminated strings. But we probably could suppress that warning (and maybe have the test actually check if the warning was thrown).

**Comment by fbs** [comment]
We already have a few that test the warning messages (like https://github.com/iovisor/bpftrace/blob/v0.9.3/tests/parser.cpp#L1175). I think we should just hide the output from these tests.
