### ISSUE TITLE
semantic_analyser.builtin_functions uses deprecated sym

### ISSUE THREAD

**Issue by zlim** [iovisor/bpftrace#457]
https://travis-ci.org/iovisor/bpftrace/jobs/498975534#L1692
```
[ RUN      ] semantic_analyser.builtin_functions
warning: sym is deprecated and will be removed in the future. Use ksym instead.
```

**Comment by synth0** [comment]
So what's the problem here?

Should the warning message not appear in the test logs?

If that's the case, how about we just change the unit tests to give the SemanticAnalyser a dummy std::ostream (`out_`) object that doesn't write to stderr?
