### ISSUE TITLE
Substring/partial string comparison

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#459]
> Yes, this is super annoying so a fix would be good to see soon. We do need more than this though for pattern matching in a predicate. I  often need to do the equivalent of 't:syscall:whatever/comm == "hhvm*" as I am interested in a range of processes whose name begins with "hhvm". In DTrace you could do something like /strstr(execname, "hhvm") != NULL/ if my memory serves me right.

_Originally posted by @tyroguru in https://github.com/iovisor/bpftrace/issues/198#issuecomment-461229979_

**Comment by brendangregg** [comment]
maybe this is now easier, building on the new work in #487.

I would at least like an `strncmp(char *s1, char *s1, int len)`.

**Comment by brendangregg** [comment]
Taking a look, adding strncmp() shouldn't be too hard.

We'd rename CreateStrcmp() to CreateStrncmp() that took an extra length argument, and then add a CreateStrcmp() wrapper that passed bpftrace_.strlen_ as that argument.

**Comment by jgkamat** [comment]
I'm working on this at the moment. I'm running into a couple issues, but once I figure those out I should have something that's worth reviewing.
