### ISSUE TITLE
Inconsistencies with tracepoint arguments

### ISSUE THREAD

**Issue by secumod** [iovisor/bpftrace#463]
This does not work
```
# bpftrace -e 'tracepoint:block:block_bio_complete { printf("%x\n", args->sector); }'
libclang: crash detected during parsing: {
  'source_filename' : 'definitions.h'
  'command_line_args' : ['clang', '-I', '/bpftrace/include', '-nostdinc', '-isystem', '/virtual/lib/clang/include', '-I/lib/modules/4.19.24-cloudflare-2019.2.11/build/arch/x86/include', '-I/lib/modules/4.19.24-cloudflare-2019.2.11/build/arch/x86/include/generated', '-I/lib/modules/4.19.24-cloudflare-2019.2.11/build/include', '-I/lib/modules/4.19.24-cloudflare-2019.2.11/build/include', '-I/lib/modules/4.19.24-cloudflare-2019.2.11/build/arch/x86/include/uapi', '-I/lib/modules/4.19.24-cloudflare-2019.2.11/build/arch/x86/include/generated/uapi', '-I/lib/modules/4.19.24-cloudflare-2019.2.11/build/include/uapi', '-I/lib/modules/4.19.24-cloudflare-2019.2.11/build/include/generated/uapi', '-include', '/lib/modules/4.19.24-cloudflare-2019.2.11/build/include/linux/kconfig.h', '-D__KERNEL__', '-D__BPF_TRACING__', '-D__HAVE_BUILTIN_BSWAP16__', '-D__HAVE_BUILTIN_BSWAP32__', '-D__HAVE_BUILTIN_BSWAP64__'],
  'unsaved_files' : [('definitions.h', '...', 273), ('/bpftrace/include/__stddef_max_align_t.h', '...', 1771), ('/bpftrace/include/float.h', '...', 5192), ('/bpftrace/include/limits.h', '...', 3735), ('/bpftrace/include/stdarg.h', '...', 2025), ('/bpftrace/include/stddef.h', '...', 4499), ('/bpftrace/include/stdint.h', '...', 23388)],
  'options' : 0,
}
Clang error while parsing C definitions: 2
Input (273): #include <linux/types.h>
struct _tracepoint_block_block_bio_complete
{
  unsigned short common_type;
  unsigned char common_flags;
  unsigned char common_preempt_count;
  int common_pid;
  dev_t dev;
  sector_t sector;
  unsigned nr_sector;
  int error;
  char rwbs[8];
};

Struct/union of type '_tracepoint_block_block_bio_complete' does not contain a field named 'sector'
```

however works with attaching a filter
```
# bpftrace -e 'tracepoint:block:block_bio_complete /comm == "dd"/ { printf("%x\n", args->sector); }'
Attaching 1 probe...
0
1
2
```

but does not work, when using in programs (even with filters), for example an approximation of biolatency, but with tracepoints
```
BEGIN
{
	printf("Tracing block device I/O... Hit Ctrl-C to end.\n");
}

tracepoint:block:block_bio_queue
/comm == "dd"/

{
	@start[args->sector] = nsecs;
}

tracepoint:block:block_bio_complete
/@start[args->sector]/

{
	@usecs = hist((nsecs - @start[args->sector]) / 1000);
	delete(@start[args->sector]);
}
```

**Comment by redbaron** [comment]
I see similar problems, do you run it in docker? I suspect it might be related:

```
# bpftrace -e 'tracepoint:syscalls:sys_enter_sendto /comm == "ip"/ { printf("sendto: %zu\n", args->len) }'
definitions.h:9:3: error: unknown type name 's64'
definitions.h:11:3: error: unknown type name 'size_t'
definitions.h:12:3: error: unknown type name 'u64'
definitions.h:14:3: error: unknown type name 's64'
Attaching 1 probe...

```

then in another console:

```
$ strace -etrace=sendto -s 1500 -y ip r >/dev/null 
sendto(3<socket:[662435463]>, "(\0\0\0\32\0\1\3\267\211\201\\\0\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\10\0\35\0\1\0\0\0", 40, 0, NULL, 0) = 40
+++ exited with 0 +++
```

I would expect output to be 40, but instead I have:

```
Attaching 1 probe...
sendto: 1306034008
```

**Comment by secumod** [comment]
No, not docker - just bare metal Linux. And in my case the version of the Linux headers precisely match the running kernel.

**Comment by ajor** [comment]
But you used Docker to compile bpftrace right, @secumod? The `libclang: crash detected during parsing` is an error we're seeing a lot with builds on Alpine Linux (#266). Unfortunately we don't have a fix for it yet other than to avoid the docker build.

@redbaron I think you're seeing a different issue here. Looks like the problem is the libclang isn't correctly parsing your tracepoint structs and will won't be using the correct offset for the `len` field in `args`. I'm not sure why your bpftrace doesn't know about `s64`, `u64` and `size_t` - if this is still a problem please feel free to raise an issue about it.

**Comment by secumod** [comment]
Yes, correct. So you think it is just because of musl?

**Comment by ajor** [comment]
Yeah, that's the belief about the Alpine failures. The Clang crashes are inconsistent in my experience, like you're seeing here too.

**Comment by aojea** [comment]
> @redbaron I think you're seeing a different issue here. Looks like the problem is the libclang isn't correctly parsing your tracepoint structs and will won't be using the correct offset for the len field in args. I'm not sure why your bpftrace doesn't know about s64, u64 and size_t - if this is still a problem please feel free to raise an issue about it.

@ajor I have the same issues compiling from source (not using docker), 
should I open a new issue? Is there something I can check first?

**Comment by ForestWang123** [comment]
> udo build-release/src/bpftrace -e 'tracepoint:block:block_bio_complete { printf("%x\n", args->sector); }'
> definitions.h:8:3: error: unknown type name 'dev_t'
> definitions.h:9:3: error: unknown type name 'sector_t'
> ```
I alse have absolutely the same issue  compiling from source (not using docker),
I am using bpftrace v0.11.4 with 4.18.0 linux kernel.

@aojea , @ajor 
any progress about this issue?

**Comment by fbs** [comment]
hi o/

Please open a discussion to continue this in, this issue has been closed ages ago
