### ISSUE TITLE
need to warn when exceeding map key limits

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#464]
This may well be an existing issue as I remember reading something from @brendangregg  on this recently in an issue. Please close this if it is a duplicate.

Currently, associative arrays are statically sized to a hard coded value ('max_entries' in map.cpp which is currently 128). When a script exceeds this number of active entries a  write to the hash appears to work and a read from that hash entry returns 0. An example with map.cpp:max_entries set to 8:

```
# cat broken-maps.bt
BEGIN
{
        @["1"] = nsecs;
        @["2"] = nsecs;
        @["3"] = nsecs;
        @["4"] = nsecs;
        @["5"] = nsecs;
        @["6"] = nsecs;
        @["7"] = nsecs;
        @["8"] = nsecs;
        @["9"] = nsecs;
        @["10"] = nsecs;

        printf("nsecs = %llu\n", @["10"]);
}

# ./bpftrace ./broken-maps.bt
Attaching 1 probe...
nsecs = 0
^C

@[1]: 1380839892949659
@[2]: 1380839892958637
@[3]: 1380839892959973
@[4]: 1380839892961084
@[5]: 1380839892962178
@[6]: 1380839892963548
@[7]: 1380839892964913
@[8]: 1380839892966208

```

Increasing the size of 'max_entries' would be good but it is just a band-aid. The silent write and a read returning 0 causes logic errors in scripts that can be extremely difficult to debug.

If the number of entries is to remain static then we must inform the user that the size has been exceeded and allow them to tune the map size accordingly. Obviously, the most preferable solution would be to have a dynamic map size.

**Comment by brendangregg** [comment]
There was another case where we increased the defaults for stack maps. I think in this case we should make that 1024 (at least) to start with, and follow up to see how to print warnings when exceeded.

**Comment by tyroguru** [comment]
Re; the "enhancement" label. Of course, any bug can be seen as an enhancement of current behaviour :-) . However, this is actually a bug and quite a nasty one at that as it leads to highly misleading script behaviour owing to the way we just silently drop the write and return 0 for a read. Really needs fixing ASAP.

**Comment by brendangregg** [comment]
changed title. At the very least, on program termination we could iterate over all maps and if any has a key count that equals max_entries then print:

```WARNING: map %s has reached the BPFTRACE_MAP_KEYS_MAX limit, possible lost entries.```

This check needs to happen before the END action is performed. Eg, imagine you have a `@start` hash for timing, which you `clear(@start)` in the END: we need to check its limit before END is processed. So I'd put this check at the start of END.

I'm hoping the kernel can give us this status so it is known for certain.

**Comment by ajor** [comment]
Good point about the END thing - I think that problem could also happen in the middle of a script, say we have a function `foo` which takes a very long time to return, and lots of threads calling it:
```
uprobe:foo
{
   @[tid] = nsecs;
}
uretprobe:foo /@[tid]/
{
  delete(@[tid])
}
```

We could hit the map limit but then be well below it again by the end of the bpftrace tracing session.

**Comment by brendangregg** [comment]
Right, we'll only catch that with kernel support. I'll talk to Alexei about it. Ideally we can interrogate a map and know how many keys it's dropped, and if that's non-zero, print it at the end of a bpftrace program. In the meantime we can add the END logic for a warning.

**Comment by tyroguru** [comment]
I think it's essential that we pick this condition as soon as the data is reaped from the kernel. Hitting this condition will invalidate your results so a user must know ASAP and not at the end. The fix is fine for now but we should try and do some dynamic growth in the future as static sizing is not a viable long term solution as you don't know apriori how big your keyed data is. Obviously, this may well need some kernel changes.

**Comment by brendangregg** [comment]
Adding map statistics was discussed at LSFMM: it needs to be added to the kernel, but that will let us check (at the end) and know for sure if there have been overflows, and how many.

Dynamic sizing I imagine will be tricky since we probably can't allocate in BPF context. That may require an async thread to poll the populated size of the maps (using the map statistics) and grow them if they are running out of headroom.

Right now we can add the END logic to warn when we detect maps are full (or within 1% of being full, since we may have just deleted a few keys from the full point).

Maybe we could also detect programs that will have many keys beforehand, and automatically increase the map size. For example, profile:hz: with [ku]stack as map keys. I'd add this if it was simple: I wouldn't go overboard since we ultimately want kernel solutions.

**Comment by mmisono** [comment]
With #1276, now we can detect exceeding map key limits using `-k` option. For example:

```
% sudo BPFTRACE_MAP_KEYS_MAX=2 ./src/bpftrace -e \
  'BEGIN { @[0] = 0; @[1] = 1; @[2] = 2;} -k'
Attaching 1 probe...
stdin:1:35-36: WARNING: Failed to map_update_elem: Argument list too long (-7)
BEGIN { @[0] = 0; @[1] = 1; @[2] = 2;}
                                 ~

^C

@[0]: 0
@[1]: 1
```

**Comment by danobi** [comment]
The dynamic sizing issue is tricky b/c IIUC maps need to be pinned in memory. So it may be a tough sell for kernel folks to allow dynamic sizing. I think the best we can do for now is what @mmisono  introduced.
