### ISSUE TITLE
USDT wildcard match support

### ISSUE THREAD

**Issue by dalehamel** [iovisor/bpftrace#493]
Currently I get an error if trying to do any type of wildcard match on a USDT probe

```
bpftrace -e 'usdt::ruby:method__entry { @[probe]++}' -p 1271
Wildcard matches aren't available on probe type 'usdt'
No probes to attach
```

In this case i'm actually just omitting the library path, but calling `probe` causes it to bail because it hits the wildcard lookup code.

It would be great to support wildcards for usdt probes and since we already have the code to list USDT tracepoints in `list.cpp` it should be a simple matter of connecting the dots by adding support to `find_wildcard_matches`).

I'd also expect to be able to use a wildcard for the provider or usdt function name, so that a user easily attach to a all probes on a provider, or even all USDT probes on a process / library if the user is feeling really courageous.

**Comment by tyroguru** [comment]
@dalehamel - I may be wrong here but I think the error we see in this instance is related to the 'probe' builtin. If I use a simple example that I have here:

```
# cat dyno.bt
usdt:/usr/local/bin/dynolog:request_context_switch_before
{
  printf("%s\n", comm);
}

# /tmp/bpftrace -p 3113 ./dyno.bt
Attaching 1 probe...
FutureTimekeepr
FutureTimekeepr
```

If I change the 'comm' to use 'probe':

```
# cat dyno.bt
usdt:/usr/local/bin/dynolog:request_context_switch_before
{
  printf("%s\n", probe);
}

# /tmp/bpftrace -p 3113 ./dyno.bt
Wildcard matches aren't available on probe type 'usdt'
No probes to attach
```

**Comment by dalehamel** [comment]
@tyroguru yes I believe that's true. Checking the code quickly, `need_expansion` is set to `true` for the probe builtin in the semantic analyzer code.

Then, when it's processed here https://github.com/iovisor/bpftrace/blob/80efbcfc264f7b99c39d5919f4e7bf0d99a0705c/src/bpftrace.cpp#L90, it runs through the wildcard code, which I believe is what results in this message.

my example wasn't great, but illustrates one case that needs fixing. I'd also like to be able to generically use wildcards for USDT probes, which would fail under the current implementation

**Comment by dalehamel** [comment]
By the way, I do intend on submitting a PR to fix this (hopefully this weekend, while I have some time to kill on a train) :)

**Comment by tyroguru** [comment]
> By the way, I do intend on submitting a PR to fix this (hopefully this weekend, while I have some time to kill on a train) :)

Excellent - nice one! Wish I could work on the trains I catch every day but it's mostly standing room only :-(

**Comment by dalehamel** [comment]
I have a draft PR up that has the broad strokes done to enable this functionality^

It needs tidying up, hopefully I can have it ready for a real review this weekend.

**Comment by dalehamel** [comment]
I have taken the PR out of draft and it is ready for review https://github.com/iovisor/bpftrace/pull/508

**Comment by tyroguru** [comment]
@dalehamel - with the changes you are doing here, would you expect me to be able to list probes using a wildcard syntax? So, if I have a simple C++ application (name - 'user_passwd' in the example below) then I get a bunch of probes defined in glibc, libm, libpthread, etc. If I use the '-l' option with a '-p' option then we get all probes listed as spoken about previously:

```
#  /tmp/bpftrace -p `pgrep passwd` -l |more
software:alignment-faults:
software:bpf-output:
software:context-switches:
software:cpu-clock:
software:cpu-migrations:
software:dummy:
software:emulation-faults:
<chop>
```

However, if I try and pattern match a couple of probes provided by the dynamic linker then it filters all usdt probes but I would have expected it to just give me the two 'unmap*' that the 'rtld' provider exports:

```
#  /tmp/bpftrace -p `pgrep passwd` -l 'usdt:/lib64/ld-linux-x86-64.so.2:unmap*'
usdt:/usr/lib64/libc-2.17.so:libc:setjmp
usdt:/usr/lib64/libc-2.17.so:libc:longjmp
usdt:/usr/lib64/libc-2.17.so:libc:longjmp_target
usdt:/usr/lib64/libc-2.17.so:libc:memory_heap_new
<chop>
```

It only provides usdt probes but all of them though. Is this what you expected?

**Comment by dalehamel** [comment]
@tyroguru the functionality you're referring to is #504 

Right now it is actually just returning all tracepoints on the binary. You correctly point out that it should be using the search string, as other types of probes do.

This is the code that would need to change: https://github.com/iovisor/bpftrace/blob/77d49296cd43be739a0389d7b2db3f1d838aad68/src/list.cpp#L149-L155

I'll take a look at this a little later - thanks for the feedback!

**Comment by dalehamel** [comment]
@tyroguru i've fixed it with my latest push, 3476bf1d1203fa5ef6a6dab19dc18cef11fbd520

I can now filter like so:

```
bpftrace -l 'usdt:*pars*' -p ${RUBY_PID}
usdt:/usr/bin/ruby:ruby:parse__begin
usdt:/usr/bin/ruby:ruby:parse__end
```

This ties into the existing probe filtering function, so the behavior should be consistent with other probes now.

Nice catch!

**Comment by tyroguru** [comment]
@dalehamel - great work. A few observations about current behaviour:

1. With a `-l` flag and no pattern specification we don't see any usdt probes:

```
#  /tmp/bpftrace -l -p 3412699 | wc -l
40104
#  /tmp/bpftrace -l -p 3412699 | grep -c usdt
0
```

If I provide a pattern then we do see them:

```
#  /tmp/bpftrace -l 'usdt:*' -p 3412699 | grep -c usdt
79
```

2. It appears that we don't pattern match using the ':' delimiter fields in a probe specification. For example, take these two probes:

```
#  /tmp/bpftrace -l 'usdt:*' -p 3412699 | grep reloc
usdt:/usr/lib64/ld-2.17.so:rtld:reloc_complete
usdt:/usr/lib64/ld-2.17.so:rtld:reloc_start
```

Then I'd expect the following to work but it doesn't:

```
# /tmp/bpftrace -l 'usdt:::*reloc*' -p 3412699 | grep -c usdt
0
```

I assume an empty field means we don't match anything because if I wildcard all fields then it works:

```
#  /tmp/bpftrace -l 'usdt:*:*:reloc*' -p 3412699
usdt:/usr/lib64/ld-2.17.so:rtld:reloc_complete
usdt:/usr/lib64/ld-2.17.so:rtld:reloc_start
```

However, we obviously aren't using the probe spec delimiters in such a way as I don't actually need to include any of them:

```
# /tmp/bpftrace -l 'usdt*reloc*' -p 3412699
usdt:/usr/lib64/ld-2.17.so:rtld:reloc_complete
usdt:/usr/lib64/ld-2.17.so:rtld:reloc_start
```

Maybe it's my misunderstanding in general about how bpftrace uses its delimiters in a probe specification but we don't seem to use them here anyway.

3. No doubt related to the above comment on probe spec delimiters but the following doesn;t work when I would expect it to:

```
# /tmp/bpftrace -l 'usdt:::reloc*' -p 3412699 | grep -c usdt
0
```

I have to wildcard before and after `reloc` for this to work.

Hope this makes sense!


(As a general side note: to be honest I have no idea what i going off with the way in which USDT "translates" the provider name and labels all probes as from the 'usdt' provider. That makes absolutely zero sense to me).

**Comment by dalehamel** [comment]
@tyroguru thanks for the testing once again!

Regarding not listing probes when no wildcards are specified - yes that’s definitely a bug and an oversight on my part, I’ll have a quick fix up for that soon.

For using colons as wildcards, that’s a bit trickier.

On the one hand, this is more consistent with the attach syntax. On the other hand, it doesn’t look like any of the other probe types do this for listing, as I’m using the same filtering function they use. I could add it, but treating two colons as a * is treated, but if I do so, would I do this just for usdt or for all of them?

Using wildcards explicitly should allow matching the colon cases either way.

**Comment by tyroguru** [comment]
@dalehamel - yeah, let's not get bogged down in changing general behaviour here. As you say, all probes behave like this so your changes are consistent anyway. If you can just fix the first issue then that would be great.

**Comment by dalehamel** [comment]
@tyroguru I've fixed the first by just checking if a search string is empty or not, which seems reasonable to me. 

I have actually used dtrace a few times now (embarrassingly, I hadn't before this), and I see what you mean on expecting colons to be wildcards. Indeed, this is inconsistent with how probes are actually attached.

that's a separate issue though, as you say, this is currently consistent.

Listing all usdt probes by just doing `bpftrace -l -p $(pgrep -f tracetest) `works for me now. Please give it another look over.

I did however find some existing cases that seem broken by my code, I will fix those up.
