### ISSUE TITLE
'-p' option doesn't complain if pid begins with non-integer value

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#501]
If an invalid (non-existent) but correctly formed pid is supplied to the `-p` option then an error message is provided:

```
#  bpftrace -l -p 44444
<elided software probe list>
failed to initialize usdt context for pid: 44444
```

However, if a pid is supplied which begins with any non-integer value then we don't generate any form of error message:

```
#  bpftrace -l -p aa44444
<lots of probes elided>
```

(obviously the same effect is generated with an argument with no integers, i.e. `-p hello`).

Looks like we just match the any leading integers so this leads to this interesting behaviour:

```
#  bpftrace -l -p 33aaa
<elided software probe list>
failed to initialize usdt context for pid: 33
```

**Comment by brendangregg** [comment]
fixed by #505
