### ISSUE TITLE
Should be able to list available USDT probes in executable or library 

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#504]
Currently we can list the available USDT probes in a running process using the '-l -p' combination:

```
# /tmp/bpftrace -l -p 4133832| grep passwd
usdt:/data/users/jonhaslam/BPFTrace-hol/CODE/usdt/usdt-samp1:"passwdfound"
```
However, if we want to see the available probes prior to execution we must either use `tplist.py` or `readelf -n`. I think it makes sense to make the `-l -c` option do the equivalent of `tplist -l` so we would get something like:

```
# bpftrace -l -c ./usdt-samp1
usdt:usdt-samp1:"passwdfound"
```

**Comment by dalehamel** [comment]
@tyroguru i noticed this problem while i was working on https://github.com/iovisor/bpftrace/issues/493, I can either add this to that PR (as it's pretty trivial I think), or follow up with another one.

**Comment by dalehamel** [comment]
I wonder if the interface should, to be more consistent, be like:

```
bpftrace -l 'usdt:/path/to/file:*"
```

I'll take a look at what we do for uprobes to pass a filename, as it's another case where I think it'd be useful, and it's better to be consistent.

**Comment by mmarchini** [comment]
> I wonder if the interface should, to be more consistent, be like:
> 
> ```
> bpftrace -l 'usdt:/path/to/file:*"
> ```

I like this interface more than -c.

**Comment by tyroguru** [comment]
@dalehamel - great stuff. Go with what you think works best - the `-l` on its own will work fine I think.

**Comment by dalehamel** [comment]
Per https://github.com/iovisor/bpftrace/issues/493#issuecomment-479007614

I need to modify the existing list code in https://github.com/iovisor/bpftrace/pull/508 to properly grab the wildcards, I'm thinking by just splitting on ":" to be able to still grab the path.
