### ISSUE TITLE
no error log printed on systems without /usr directory

### ISSUE THREAD

**Issue by michalgr** [iovisor/bpftrace#506]
Android is a quite hostile environment and it has no /usr directory which makes [kernel_version](https://github.com/iovisor/bpftrace/blob/master/src/attached_probe.cpp#L295) fail during 3rd attempt to load a bpf program, in which case we end up with no info what went wrong. Here is a detailed description of the problem I run into:
1. I run bpftrace script which depends on a helper function not provided by my kernel
2. [first two attempts](https://github.com/iovisor/bpftrace/blob/master/src/attached_probe.cpp#L336) to load bpf program fail with useful hints logged to log_buf
3. during 3rd attempt [kernel_version](https://github.com/iovisor/bpftrace/blob/master/src/attached_probe.cpp#L295) returns 0 due to missing "/usr/include/linux/version.h" header
4. bpf_prog_load is called with wrong kernel version (0)
5. bpf_prog_load zeroes first byte of the provided log_buf
6. bpf syscall is called
7. kernel does not append anything to the log buffer before returning EINVAL
8. we end up with an empty log_buf even though first two attempts resulted in useful information being logged

I tried to work around this by running with `-d` or `-dd` ([this is what seeded the idea](https://github.com/iovisor/bpftrace/blob/master/src/attached_probe.cpp#L317)) but turns out the execuction terminates [before bpf_prog_load is called](https://github.com/iovisor/bpftrace/blob/master/src/main.cpp#L301).

I ended up adding check for `kernel_version` returning 0 and simply skipping iterations where that happens, although dumping the buffer after each failed iteration also sounds tempting. Please let me know if this is the right approach and it's worth opening a pull request.

**Comment by ajor** [comment]
`-v` might be of help to you here

Skipping the prog_load if kernel_version returns 0 sounds like a good idea
