### ISSUE TITLE
Error building bpftrace on Ubuntu 16.04 (4.15.0-46-generic)

### ISSUE THREAD

**Issue by gslavin** [iovisor/bpftrace#507]
I've added my full build output below.  Additional information:

1. I installed bcc using the Ubuntu - Upstream Stable and Signed Packages section on this page: https://github.com/iovisor/bcc/blob/master/INSTALL.md
2. The bcc tools seem to work fine.  Tools like /usr/share/bcc/tools/stackcount give the expected results.
3. I installed bpftrace using the Ubuntu instructions on this page: https://github.com/iovisor/bpftrace/blob/master/INSTALL.md
4.  Oddly, I could build bpftrace a month ago, but I recently did an apt update which updated the bcc package, which broke bpftrace.  I tried rebuilding bpftrace and hit these build issues. 

My build errors are very similar to the build errors in the following issue:

https://github.com/linuxkit/linuxkit/issues/3296#issuecomment-469020564

### Full build output

user@dev:~/bpftrace/build$ make bpftrace -j8
[  3%] [FLEX][flex_lexer] Building scanner with flex 2.6.0
[  6%] [BISON][bison_parser] Building parser with bison 3.0.4
Scanning dependencies of target resources
Scanning dependencies of target arch
src/lexer.l:52: warning, rule cannot be matched
[ 13%] Building CXX object resources/CMakeFiles/resources.dir/headers.cpp.o
[ 13%] Building CXX object src/arch/CMakeFiles/arch.dir/x86_64.cpp.o
[ 16%] Linking CXX static library libresources.a
[ 16%] Built target resources
Scanning dependencies of target parser
[ 20%] Building CXX object CMakeFiles/parser.dir/lex.yy.cc.o
[ 23%] Building CXX object CMakeFiles/parser.dir/parser.tab.cc.o
[ 26%] Linking CXX static library libarch.a
[ 26%] Built target arch
[ 30%] Linking CXX static library libparser.a
[ 30%] Built target parser
Scanning dependencies of target ast
[ 33%] Building CXX object src/ast/CMakeFiles/ast.dir/ast.cpp.o
[ 36%] Building CXX object src/ast/CMakeFiles/ast.dir/irbuilderbpf.cpp.o
[ 40%] Building CXX object src/ast/CMakeFiles/ast.dir/printer.cpp.o
[ 43%] Building CXX object src/ast/CMakeFiles/ast.dir/codegen_llvm.cpp.o
[ 46%] Building CXX object src/ast/CMakeFiles/ast.dir/semantic_analyser.cpp.o
/home/ubuntu0/bpftrace/src/ast/irbuilderbpf.cpp: In member function ‘llvm::CallInst* bpftrace::ast::IRBuilderBPF::CreateProbeReadStr(llvm::AllocaInst*, llvm::Value*, llvm::Value*)’:
/home/ubuntu0/bpftrace/src/ast/irbuilderbpf.cpp:284:16: error: ‘BPF_FUNC_probe_read_str’ was not declared in this scope
       getInt64(BPF_FUNC_probe_read_str),
                ^
/home/ubuntu0/bpftrace/src/ast/irbuilderbpf.cpp: In member function ‘llvm::CallInst* bpftrace::ast::IRBuilderBPF::CreateProbeReadStr(llvm::Value*, size_t, llvm::Value*)’:
/home/ubuntu0/bpftrace/src/ast/irbuilderbpf.cpp:299:16: error: ‘BPF_FUNC_probe_read_str’ was not declared in this scope
       getInt64(BPF_FUNC_probe_read_str),
                ^
/home/ubuntu0/bpftrace/src/ast/irbuilderbpf.cpp: In member function ‘llvm::CallInst* bpftrace::ast::IRBuilderBPF::CreateGetCurrentTask()’:
/home/ubuntu0/bpftrace/src/ast/irbuilderbpf.cpp:560:16: error: ‘BPF_FUNC_get_current_task’ was not declared in this scope
       getInt64(BPF_FUNC_get_current_task),
                ^
/home/ubuntu0/bpftrace/src/ast/irbuilderbpf.cpp: In member function ‘llvm::CallInst* bpftrace::ast::IRBuilderBPF::CreateGetStackId(llvm::Value*, bool, bpftrace::StackType)’:
/home/ubuntu0/bpftrace/src/ast/irbuilderbpf.cpp:597:16: error: ‘BPF_FUNC_get_stackid’ was not declared in this scope
       getInt64(BPF_FUNC_get_stackid),
                ^
src/ast/CMakeFiles/ast.dir/build.make:110: recipe for target 'src/ast/CMakeFiles/ast.dir/irbuilderbpf.cpp.o' failed
make[3]: *** [src/ast/CMakeFiles/ast.dir/irbuilderbpf.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/home/ubuntu0/bpftrace/src/ast/semantic_analyser.cpp: In member function ‘int bpftrace::ast::SemanticAnalyser::analyse()’:
/home/ubuntu0/bpftrace/src/ast/semantic_analyser.cpp:984:5: warning: assuming signed overflow does not occur when reducing constant in comparison [-Wstrict-overflow]
 int SemanticAnalyser::analyse()
     ^
CMakeFiles/Makefile2:1138: recipe for target 'src/ast/CMakeFiles/ast.dir/all' failed
make[2]: *** [src/ast/CMakeFiles/ast.dir/all] Error 2
CMakeFiles/Makefile2:1208: recipe for target 'src/CMakeFiles/bpftrace.dir/rule' failed
make[1]: *** [src/CMakeFiles/bpftrace.dir/rule] Error 2
Makefile:602: recipe for target 'bpftrace' failed
make: *** [bpftrace] Error 2

**Comment by gslavin** [comment]
I investigated further, and I found a hacky work around.

If I replace /usr/include/linux/bpf.h with /usr/include/bcc/compat/linux/bpf.h, the build completely successfully.

On my system, the linux-libc-dev:amd64: package owns /usr/include/linux/bpf.h.

Is bpftrace supposed to referencing /usr/include/linux/bpf.h or should it be referencing /usr/include/bcc/compat/linux/bpf.h?

**Comment by gslavin** [comment]
Another workaround I've tried is replacing

`#include "linux/bpf.h"`

with

`#include "bcc/compat/linux/bpf.h"`

in bcc/BPF.h, bcc/bcc_syms.h, and bcc/libbpf.h in my bbc installation (/usr/include/bcc).  This fixes the build for me.

This supports my previous comment where I think bcc should probably be referencing it's internal copy of bpf.h (at least on Ubuntu 16.04).

I'm very new to bpftrace, so let me know if there is a better way to fix these build problems.

**Comment by paulofelipefeitosa** [comment]
Thanks, @gslavin it worked for me! :smile:

**Comment by mmarchini** [comment]
Is this still an issue with the latest version of bcc and bpftrace?

**Comment by gslavin** [comment]
Yes, this is still an issue with the latest version of bcc and bpftrace.  I've mentioned two workarounds above that try to avoid using /usr/include/linux/bpf.h, which appears to be the root of the issue.  On my system this file is owned by the linux-libc-dev package.

**Comment by galkinvv** [comment]
Found a workaround using only cmake call argumrnts without modifying any files. Add the following definition while calling cmake. Its enforcing including correct bpf.h in every compilation and bypasses content of wrong bpf.h by predefining its header guard macro. Very ugly, but working for me
```
-DCMAKE_CXX_FLAGS="-include /usr/include/bcc/compat/linux/bpf.h -D__LINUX_BPF_H__"
```

**Comment by fbs** [comment]
part of the CI now so should work

**Comment by Davidrjx** [comment]
in debian9 dist, seems not working

> Found a workaround using only cmake call argumrnts without modifying any files. Add the following definition while calling cmake. Its enforcing including correct bpf.h in every compilation and bypasses content of wrong bpf.h by predefining its header guard macro. Very ugly, but working for me
> 
> ```
> -DCMAKE_CXX_FLAGS="-include /usr/include/bcc/compat/linux/bpf.h -D__LINUX_BPF_H__"
> ```
