### ISSUE TITLE
[Help] Get current Unix timestamp

### ISSUE THREAD

**Issue by paulofelipefeitosa** [iovisor/bpftrace#512]
Is there any way to get the current Unix timestamp like `date +%s%N`? I tried to use `nsecs`, but the returned values are different from the Unix timestamp values. I do not want to use `system` because of its overhead.

Code:
```
BEGIN
{
	system("date +%s\n", "%s%N");
	printf("%d\n", nsecs);
	printf("%ld\n", nsecs);
	printf("%lld\n", nsecs);
	printf("%llu\n", nsecs);
}
```
```
# bpftrace -c 'bash run-test.sh' read.bt
Attaching 5 probes...
1553818092079803233
...
-857500477
19313610430715
19313610431634
19313610432555
```

**Comment by brendangregg** [comment]
There's the time() builtin, which prints an strftime() code, but it's resolution is seconds.

What's the use case? It might be possible to dig things out of the kernel to map nsecs back to %s%N, but maybe there's an easier way to solve the problem.

**Comment by paulofelipefeitosa** [comment]
@brendangregg thanks for the reply, I am measuring the impact of the `clone` and `execve` syscalls, but also I need the `execve` exit timestamp to serve as the baseline timestamp to calculate the impact of others traces involving JVM profiling with a JVMTI Agent. 

This is an output using the `system(date +%s%N)`.
```
Attaching 5 probes...
1553818672706532132
[1553818672708558753] JVMTI started
[1553818672708590207] VMTrace started
[1553818672709231107] Dynamic code generated: flush_icache_stub
[1553818672709247816] Dynamic code generated: get_cpu_info_stub
...
```
Code:
```
tracepoint:syscalls:sys_enter_execve 
{
  printf("execve: %s: ", str(args->filename));
  @start[tid] = nsecs;
}

tracepoint:syscalls:sys_exit_execve / @start[tid] /
{
  printf("%d -- %lld\n", nsecs - @start[tid], nsecs);
  delete(@start[tid]);
}

tracepoint:syscalls:sys_enter_clone 
{
  @start_clone[tid] = nsecs;
}

tracepoint:syscalls:sys_exit_clone / @start_clone[tid] /
{
  printf("clone: %d\n", nsecs - @start_clone[tid]);
  delete(@start_clone[tid]);
}

```

**Comment by paulofelipefeitosa** [comment]
Hey @brendangregg I looked at the bpftrace code and saw that the `nsecs` uses `bpf_ktime_get_ns` that is the kernel timestamp using the `CLOCK_MONOTONIC` and the "Unix timestamp" that I mentioned is got using `CLOCK_REALTIME`, the easy way to solve my problem is adopting `CLOCK_MONOTONIC` in my JVMTI Agent. 

Thanks!!!
