### ISSUE TITLE
enum support

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#520]
We really need enum support, as they are used in various kernel places. As a simple test case:

```
#!/usr/local/bin/bpftrace

enum {
        STATE_A = 1,
        STATE_B,
        STATE_C
        STATE_MAX
};

kprobe:vfs_read
{
	@[STATE_B]++;
}
```

This currently does:

```
# ./enum.bt 
4.17: syntax error, unexpected =, expecting (
```

**Comment by gslavin** [comment]
I see two main approaches:

1) Add support for enums to the lexer.l/parser.yy files
2) Parse enums during the ClangParser::parse step

As a quick test of feasibility of (2), a single line change to lexer.l allowed me to parse the enum information in ClangParser::parse using a new call to clang_visitChildren. But I don't have a good understanding about how this information should be handled by the bpftrace program. 

One idea is to expose the enum values as global variables, which is something that would work equally well for simple defines (see issue #153).  This route seems fairly simple to me and avoids adding complexity to the lexer/parser.

**Comment by brendangregg** [comment]
Maybe I'm wrong, but I would have guessed we'd try to see if there was a clang pre-processor we could use, particularly for #defines, that worked like the C pre-processor. Something similar should work for enums too (we could have a pre-pre-processor pass that turned enums into #defines, right?). Then we aren't creating a lot of global variables we aren't using (ok, the llvm optimizer should throw out unused things, but I'm having other troubles with the llvm optimizer right now). Maybe:

https://clang.llvm.org/doxygen/classclang_1_1Preprocessor.html

I'm currently creating some new instrumentation and I'm hitting #153 and #520 every day. It's a PITA. I'd welcome a solution. If global vars aren't so bad...

**Comment by mmarchini** [comment]
This was implemented. I see two other features we might want wrt enumerators:

Do we want semantic analysis of enum types? For example:

```c
enum Foo {
  a = 1,
  b
}

k:f {
  $var = (enum Foo)a; // Should be fine
  $var = (enum Foo)2; // Should also be fine
  $var = 3; // Should fail
}
```

Or "symbolificating" enums:

```c
// From v8.h
enum GCType {
  kGCTypeScavenge = 1 << 0,
  kGCTypeMarkSweepCompact = 1 << 1,
  kGCTypeIncrementalMarking = 1 << 2,
  kGCTypeProcessWeakCallbacks = 1 << 3,
  kGCTypeAll = kGCTypeScavenge | kGCTypeMarkSweepCompact |
               kGCTypeIncrementalMarking | kGCTypeProcessWeakCallbacks
};

usdt:node:gc__start {
  $gcType = $1;
  // Should print "kGCTypeScavenge" for $gcType == (1 << 0), etc.
  printf("%s\n", (enum GCType)$gcType);
}
```

**Comment by mmarchini** [comment]
Basic support was added in #538. I'll open extra issues for the other use cases I mentioned.
