### ISSUE TITLE
regex is slowing startup

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#526]
I have a more complex example that takes a few seconds for bpftrace to start, which turns out to be in regex for tracepoint arguments. Here is a simple (and faster) example:

```
# time bpftrace -e 'BEGIN { exit(); } t:syscalls:sys_enter_execve { @[0, 0, 0]++ }'
Attaching 2 probes...

real	0m0.191s
user	0m0.056s
sys	0m0.038s

# time bpftrace -e 'BEGIN { exit(); } t:syscalls:sys_enter_execve { @[args->filename, args->argv, args->envp]++ }'
Attaching 2 probes...

real	0m0.401s
user	0m0.231s
sys	0m0.052s
```

Here is a CPU flamegraph where I've searched for regex:

![cpuflamegraph-bpftrace-startup](https://user-images.githubusercontent.com/1101211/55823550-c9574c00-5ab6-11e9-87bc-97ec15775daf.png)

87.4% of CPU time is in regex. You can see the codepaths: it's in sementic_analyser.cpp here:

```C++
void SemanticAnalyser::visit(FieldAccess &acc)
[...]
  if (type.is_tparg) {
    for (AttachPoint *attach_point : *probe_->attach_points) {
      assert(probetype(attach_point->provider) == ProbeType::tracepoint);

      std::set<std::string> matches = bpftrace_.find_wildcard_matches(
          attach_point->target, attach_point->func,
          "/sys/kernel/debug/tracing/available_events");
      for (auto &match : matches) {
        std::string tracepoint_struct =
            TracepointFormatParser::get_struct_name(attach_point->target,
                                                    match);
        structs[tracepoint_struct] = bpftrace_.structs_[tracepoint_struct].fields;
      }
    }
```

In this case, I'm not even using a wildcard -- I'm matching syscalls:sys_enter_execve.

Could someone please fix this, eg:

* Do a direct match if no wildcard operators are used.
* Cache results (this is called several times due to multiple passes through semantic analyser).
* Something else :)

**Comment by mmarchini** [comment]
Fixed by #559 and #557.
