### ISSUE TITLE
List and attach syntax are inconsistent

### ISSUE THREAD

**Issue by dalehamel** [iovisor/bpftrace#565]
We implement the parsing for matching probes in a list here:
https://github.com/iovisor/bpftrace/blob/master/src/list.cpp#L116-L139 

And this logic is basically duplicated for filtering probes to attach:
https://github.com/iovisor/bpftrace/blob/master/src/bpftrace.cpp#L152

These should use the same syntax and provide the same filtering functionality.

#557 and #508 both touch this

**Comment by dalehamel** [comment]
Things to consider:

* Behavior for wildcards on paths, for uprobe/usdt
* Consistently in syntax for filtering lists of probes, and wildcarding probes
* Using the same, standardized filter function anywhere we try to filter probes (attach / list anyways)
* Consistency with dtrace syntax / functionality (or at least compatibility)

**Comment by mmarchini** [comment]
Just hit one case where the filtering works for one but not for the other:

```
# bpftrace -e 'usdt:*usdt_test* { printf("here\n" ); exit(); }' -p $(pidof usdt_test)
No probes to attach

# bpftrace -l 'usdt:*usdt_test*' -p $(pidof usdt_test)
usdt:/home/mmarchini/workspace/iovisor/bpftrace/build/tests/testprogs/usdt_test:tracetest:testprobe
usdt:/home/mmarchini/workspace/iovisor/bpftrace/build/tests/testprogs/usdt_test:tracetest:testprobe2
usdt:/home/mmarchini/workspace/iovisor/bpftrace/build/tests/testprogs/usdt_test:tracetest2:testprobe2

```

**Comment by dalehamel** [comment]
I need to catch up on the find_wildcard_matches refactor, it might also be related to another bug filed about usdt context being closed too soon that I need to check into.

I expect to have time for both tomorrow if no one gets to it before then
