### ISSUE TITLE
Crash finding tracepoint args

### ISSUE THREAD

**Issue by ajor** [iovisor/bpftrace#572]
I just hit an assertion failure when running this program: `blah:blah { printf("%d\n", args->path) }`
https://github.com/iovisor/bpftrace/blob/79f9bc2efa1e523a37783bb7f1b5d54cc729d904/src/ast/semantic_analyser.cpp#L757

We should also add tests for code in this area. `find_wildcard_matches()` can be mocked out like in https://github.com/iovisor/bpftrace/blob/79f9bc2efa1e523a37783bb7f1b5d54cc729d904/tests/bpftrace.cpp#L197

As an optimisation, could we get away with only running `find_wildcard_matches()` on the first pass of the semantic analyser? I can imagine this call is quite expensive.

**Comment by mmarchini** [comment]
Closed via https://github.com/iovisor/bpftrace/pull/726
