### ISSUE TITLE
increase map limit

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#594]
Amazed I didn't hit this earlier:

```
# grep 128 src/map.cpp 
  int max_entries = 128;
```

```
# bpftrace -e 'profile:hz:999 { @[cpu, nsecs] = count(); } interval:s:1 { exit() }' | wc -l
    131
```

That should be way more.

**Comment by tyroguru** [comment]
This is a dup of #464 which was categorised as an enhancement - obviously it's a very serious usability issue.

**Comment by brendangregg** [comment]
ok thanks, I want to change one of these bug titles to capture the follow-up work: we need to warn when the map key limit is reached.

**Comment by tyroguru** [comment]
I think just do it under which ever one you want and close the other one. The important thing is that you're fixing it which is great!
