### ISSUE TITLE
tracepoint argument is dumped wrong

### ISSUE THREAD

**Issue by ming1** [iovisor/bpftrace#604]
Obviously, `args->nr_events` is wrong, given it is same with the lower word
of `args->ctxp`.

```
# bpftrace -e 'tracepoint:syscalls:sys_enter_io_setup {printf("%u %x %p\n", pid, args->nr_events, args->ctxp)}'
definitions.h:10:3: error: unknown type name 'aio_context_t'
Attaching 1 probe...
23837 38687f58 0xffff888038687f58
23837 38687f58 0xffff888038687f58
```

**Comment by ming1** [comment]
# cat /sys/kernel/debug/tracing/events/syscalls/sys_enter_io_setup/format name: sys_enter_io_setup
ID: 875
format:
	field:unsigned short common_type;	offset:0;	size:2;	signed:0;
	field:unsigned char common_flags;	offset:2;	size:1;	signed:0;
	field:unsigned char common_preempt_count;	offset:3;	size:1;	signed:0;
	field:int common_pid;	offset:4;	size:4;	signed:1;

	field:int __syscall_nr;	offset:8;	size:4;	signed:1;
	field:unsigned nr_events;	offset:16;	size:8;	signed:0;
	field:aio_context_t * ctxp;	offset:24;	size:8;	signed:0;

print fmt: "nr_events: 0x%08lx, ctxp: 0x%08lx", ((unsigned long)(REC->nr_events)), ((unsigned long)(REC->ctxp))

**Comment by mmarchini** [comment]
The type of `ctxp` is not known to bpftrace, thus the error:

> `definitions.h:10:3: error: unknown type name 'aio_context_t'`

With recent versions of bpftrace, the program above won't execute:

```
# bpftrace -e 'tracepoint:syscalls:sys_enter_io_setup {printf("%u %x %p\n", pid, args->nr_events, args->ctxp)}'
definitions.h:10:3: error: unknown type name 'aio_context_t'

#
```

You'll need to include a header that defines aio_context_t. Grepping Kernel headers, this seems to be defined in `uapi/linux/aio_abi.h`:

```
# grep -R aio_context_t
linux/syscalls.h:asmlinkage long sys_io_setup(unsigned nr_reqs, aio_context_t __user *ctx);
linux/syscalls.h:asmlinkage long sys_io_destroy(aio_context_t ctx);
linux/syscalls.h:asmlinkage long sys_io_getevents(aio_context_t ctx_id,
linux/syscalls.h:asmlinkage long sys_io_submit(aio_context_t, long,
linux/syscalls.h:asmlinkage long sys_io_cancel(aio_context_t ctx_id, struct iocb __user *iocb,
linux/compat.h:#include <linux/aio_abi.h>       /* for aio_context_t */
linux/compat.h:typedef  compat_ulong_t          compat_aio_context_t;
linux/compat.h:asmlinkage long compat_sys_io_getevents(compat_aio_context_t ctx_id,
linux/compat.h:asmlinkage long compat_sys_io_submit(compat_aio_context_t ctx_id, int nr,
uapi/linux/aio_abi.h:typedef __kernel_ulong_t aio_context_t;
```

Running the program again, this time with the correct include:

```
# bpftrace --include uapi/linux/aio_abi.h -e 'tracepoint:syscalls:sys_enter_io_setup {printf("%u %x %p\n", pid, args->nr_events, args->ctxp)}'
Attaching 1 probe...
12187 80 0x7ffed08cfbc8
13366 80 0x7ffc0c805aa8
```


Output seems better now. The example I'm using is `io_setup(128, &ctx);`, which means nr_events is correct (0x80 == 128). And if I print &ctx in my example program, I get the same address there and on  bpftrace. Hope that helps.

**Comment by mmarchini** [comment]
Closing as this has been answered, but I think we can somehow provide better information for users when there are missing includes in tracepoint usage.

(better error message is different from #537, and I believe both are important)
