### ISSUE TITLE
Trace output to file

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#605]
When running a command with the `-c` option the output of both the bpftrace program and the "traced program" will get mixed as they both print to stdout. Writing a wrapper script is possible but that might break a feature like `cpid` (#298) as it likely forks too.  I think that having control over where the trace output goes would be the best way to solve it (`-o filename`). 

If adding it is considered useful I'd like to give it a try.

**Comment by danobi** [comment]
Sounds like a reasonable feature. I'd be +1 but I think more consensus would be required.

**Comment by ajor** [comment]
Yeah sounds good. Would `-o` redirect the bpftrace output or the other command's output?

**Comment by danobi** [comment]
I think redirecting the bpftrace output makes the most sense. strace has the same semantics:
```
$ strace -o /var/tmp/output ls
cgroup1.bt  cgroup2-ext.bt  file_sb_dev.bt  positional_attachpoint.bt  process_lifetime.bt  top_writers.bt
```

**Comment by brendangregg** [comment]
-o makes sense. Like strace(1).

**Comment by danobi** [comment]
I took a look at this when I was bored on a plane. So it looks like bpftrace just uses `std::cout` and `std::cerr` whenever it wants to print stuff out. This makes this feature a little tricky. I think there's a couple ways it could be implemented:
* Use a sink object everywhere to wrap `std::cerr` and `std::cout` so we can change the actual sink as we please
* Use `dup(2)` to save `STDOUT_FILENO` and `STDERR_FILENO`; `dup2(2)` to change stdout/stderr fds to some file fd; then in child process `dup2(2)` the saved stdout/stderr back to 1 and 2

Option 2 probably has less code churn but can potentially be confusing. I'd probably vote for option 1 and take the churn once.

**Comment by ajor** [comment]
Yeah, option 1 sounds the right way to go about it

**Comment by fbs** [comment]
I was toying with option 1 as it gives as I only wanted to capture the trace program output, which always prints to stdout. So earlier errors and messages like `Attaching 5 probes...` would not end up in the file. The patch can be found here: https://github.com/fbs/bpftrace/commit/52139aca239199265c5994c5717e4a37f0196982

This works for everything except printf:

```
vagrant@ubuntu-bionic:~/build/src$ sudo ./bpftrace -o /tmp/lalal -e 'i:ms:1 { @=hist(nsecs); }' -c ls
Attaching 1 probe...
CMakeFiles  Makefile  arch  ast  bpftrace  cmake_install.cmake


vagrant@ubuntu-bionic:~/build/src$ cat /tmp/lalal
@:
[2G, 4G)              27 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
```

However, I'm not sure what to do with the `printf`s in `perf_event_printer` yet.  I initially took a look at boost.format but that:
- introduces a new dependency
- might impact format string behaviour
- doesn't work with the current code as `PrintableString::value` returns an uint64. Probably needing more changes.

Another option might be to rewrite printf to snprintf. But I'm not sure what buffer size to use for that? Is the string length currently limited in anyway way?

There is probably a way better option that I'm missing, thoughts?

**Comment by ajor** [comment]
Ah I hadn't thought of printf - that's annoying.

I'd rather not bring in boost if we can avoid it. I'm leaning towards snprintf, but you're right that we'd have to introduce a limit to strings we're printing out. There isn't one at the moment, since despite having a maximum size for string literals (for now), we can't tell how big something like `printf("%s\n", usym(ptr))` would expand to. At least with snprintf we'd be able to get rid of all the duplicated code for `system()`!

**Comment by danobi** [comment]
I think if you pass in a nullptr to snprintf it’ll return how many bytes it needs to write the format string. Then you can allocate a buffer on the heap to avoid blowing the stack.
