### ISSUE TITLE
Positional parameters don't work in probes

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#606]
```
$ sudo ./build/src/bpftrace ~/scratch/bpftrace/positional_attachpoint.bt 1
1.12: syntax error, unexpected $, expecting {

$ cat ~/scratch/bpftrace/positional_attachpoint.bt 
interval:s:$1
{
    printf("hello world\n");
}
```

Does this make sense as a feature request?

**Comment by mmarchini** [comment]
Yes, I think it makes sense.

**Comment by fbs** [comment]
For this we will probably have to stop parsing the attach points in the parser (bison) and move it to the semantic analyser. 

Removing it from a milestone as it is not a priority thing and atm nobody is working on it.
