### ISSUE TITLE
tcpaccept failed with "terminate called after throwing an instance of 'std::out_of_range'"

### ISSUE THREAD

**Issue by joestringer** [iovisor/bpftrace#611]
I'm testing with a recent (albeit custom) kernel derived from the `bpf-next` tree for 5.2 kernel, using bpftrace installed from snap on Ubuntu 18.04.1 (bionic). I wouldn't expect my custom changes to impact bpftrace in the following manner:

Hit this with the `tcpaccept.bt` cloned from this repo today:

```
$ ~/tcpaccept.bt 
/bpftrace/include/stdarg.h:52:1: warning: null character ignored [-Wnull-character]
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/bitops.h:209:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/bitops.h:255:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/bitops.h:308:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/jump_label.h:23:2: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/jump_label.h:39:2: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/atomic.h:85:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/atomic.h:125:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/atomic.h:139:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/atomic.h:154:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/atomic64_64.h:76:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/atomic64_64.h:118:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/atomic64_64.h:132:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/atomic64_64.h:147:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/processor.h:550:17: warning: taking address of packed member 'sp0' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/processor.h:567:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/processor.h:567:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/processor.h:567:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/processor.h:567:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/cpufeature.h:165:2: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/preempt.h:94:9: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/qspinlock.h:23:8: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/include/asm-generic/qspinlock.h:74:55: warning: passing 'u32 *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/include/asm-generic/atomic-instrumented.h:691:38: note: passing argument to parameter 'old' here
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/include/asm-generic/qspinlock.h:87:52: warning: passing 'u32 *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/include/asm-generic/atomic-instrumented.h:691:38: note: passing argument to parameter 'old' here
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/include/asm-generic/qrwlock.h:74:56: warning: passing 'u32 *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/include/asm-generic/atomic-instrumented.h:691:38: note: passing argument to parameter 'old' here
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/include/asm-generic/qrwlock.h:101:53: warning: passing 'u32 *' (aka 'unsigned int *') to parameter of type 'int *' converts between pointers to integer types with different sign [-Wpointer-sign]
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/include/asm-generic/atomic-instrumented.h:691:38: note: passing argument to parameter 'old' here
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/refcount.h:70:13: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/refcount.h:84:13: error: 'asm goto' constructs are not supported yet
/lib/modules/5.1.0-rc7-bpf-tproxy-pre2/build/arch/x86/include/asm/uaccess_64.h:132:3: error: 'asm goto' constructs are not supported yet
fatal error: too many errors emitted, stopping now [-ferror-limit=]
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
Aborted
```

```
$ bpftrace --version
bpftrace v0.9-75-g94b8
```

This seems perhaps similar to #58, happy to run commands and provide ouput if it helps any.

**Comment by joestringer** [comment]
For what it's worth, I'm able to get other bpftrace programs working, they also have the same warning/error complaints at the top about the lack of `asm goto` support.

**Comment by joestringer** [comment]
Seems somehow related to these lines, if I set them to 0 instead then I hit other errors:

https://github.com/iovisor/bpftrace/blob/71d1cd55fc12f6fef5f4f09fba5d7f9945655135/tools/tcpaccept.bt#L36-L40

Other error, weirdly:
```
Unknown struct/union: 'sock'
```

**Comment by joestringer** [comment]
OK, part of it may just be mismatching older bpftrace with newer tools, as `tcpaccept.bt` was updated only a couple of weeks ago in commit https://github.com/iovisor/bpftrace/commit/c9dd10f93ba21c81f2e622dacf8ec816d1f0c5c8.

**Comment by joestringer** [comment]
Aha, it's the include of `#include <linux/socket.h>` which must occur after `#include <net/sock.h>`. Don't know why, but rearranging those fixed the `unknown struct/union` issue for me.

**Comment by brendangregg** [comment]
Ok... If you want, send a PR to flip the include order. :)

**Comment by joestringer** [comment]
Can do, that's an easy fix.

That said, it highlights a limitation in the runtime, which is that you can't use a structure for casting if it's not imported from the first `#include`. I tried importing both `net/sock.h` and `linux/skbuff.h`, then use casts for both `struct sock` and `struct sk_buff`, then whichever header I import second, the corresponding struct can't be found. Is this just an oversight or is there some deeper underlying issue with multiple imports?

**Comment by ajor** [comment]
Is your Clang maybe hitting an error trying to parse `<net/sock.h>`? What version are you using?

I've just tested and definitions from multiple headers do work for me.

`foo.h`:
```
struct Foo { int x; };
```

`bar.h`:
```
struct Bar { int y; };
```

```
#include "foo.h"
#include "bar.h"

BEGIN
{
  ((Foo *)0)->x; // fine
  ((Bar *)0)->y; // fine
  ((Bar *)0)->z; // fails
}
```

**Comment by joestringer** [comment]
> It looks like your Clang is hitting an error trying to parse <net/sock.h>, so isn't getting onto the second header in your case.

How do you tell this? When I rearrange the headers per #615, everything seems to just work. So do you mean that clang gets confused towards the end of the `net/sock.h`, but then it's not fatal enough that it prevents the main bpftrace functions from being compiled?

> What version of Clang are you using?

```
$ clang --version
clang version 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-7/bin
```

> Are the correct defines not in place so your compiler is getting some code passed to it which is only intended to be seen by GCC?

I don't understand "correct defines in place" for the compiler or how GCC plays into this. As a `bpftrace` user, I installed from snap (specific version is described above in the issue description), then tried to use the examples from the repository here using standard `bpftrace` invocations documented here in the repository, eg `/path/to/bpftrace/tools/tcpaccept.bt` and they don't work for me. Admittedly I am running newer Clang/LLVM from the apt repositories provided by the LLVM community, which could complicate things a little (though they're still official LLVM/Clang releases AFAIK).

That said, do you expect that I need to twiddle with some other configuration options somewhere to get these things to work correctly? Is there something in particular I can try?

Also for reference, since you mentioned GCC:
```
$ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ajor** [comment]
You say that you still see the errors when you rearrange the headers, so I don't think everything is working, it just happens that the clang failure is after the particular structs needed by this script are defined.

The error message you're seeing (`'asm goto' constructs are not supported yet`) is because `asm goto` is something which is supported by GCC but not Clang, so I assumed we shouldn't be reading that part of the header files. By defines I meant something like `#ifdef __GNUC__`, but I might have been wrong about the cause.

It looks like BCC have seen the same issue with Linux 5.0 headers: https://github.com/iovisor/bcc/issues/2119, with a fix in https://github.com/iovisor/bcc/pull/2133. We probably need to do something similar.
