### ISSUE TITLE
lhist negative ranges

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#618]
lhist accepts negative numbers but drops the sign internally, which leads to unexpected behaviour:

```
root@ubuntu-bionic:~/build# sudo ../bpftrace -e 'i:ms:1 { @=lhist(-10, -10, 100, 1); }'
lhist() too many buckets, must be <= 1000 (would need 464824020)
lhist() min must be less than max (provided min 93943354841488 and max 100)
lhist() step is too large for the given range (provided step 1 for range -93943354841388)
```
```
root@ubuntu-bionic:~/build# sudo ../bpftrace -e 'i:ms:1 { @=lhist(-10, -10, -1, 1); }'
Attaching 1 probe...
^C

@:
[103233936, 103233937)      91 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|
```

```
sudo ../bpftrace -e 'i:ms:1 { @=lhist(-10, 0, 10, -1); }'
lhist() step is too large for the given range (provided step 94564705045168 for range 10)
```

What I'd expect would be something like:

```
sudo ../bpftrace -e 'i:ms:1 { @=lhist(-10, -10, 10, 1); }'
lhist(): range must be postive (min >0; max > min)`
```

**Comment by brendangregg** [comment]
right, with the current lhist() it should throw such a warning.

**Comment by danobi** [comment]
I'm digging into this right now. Yikes, upcasts using `static_cast`. I tested with `dynamic_cast` and the casts fail.

> drops the sign internally

Actually this is not the case. I think the parser is broken. We're just reading random memory. If you run your test multiple times, you'll get different error numbers each time.

**Comment by ajor** [comment]
Looks like we should be checking that the arguments to lhist are literals, as well as being integers too.

e.g. https://github.com/iovisor/bpftrace/blob/0e2ce5ffad1f6a80e91f2d5d525da667025dfbd5/src/ast
/semantic_analyser.cpp#L212

`check_arg(call, Type::integer, 1);` -> `check_arg(call, Type::integer, 1, true);`

We've got at least one other bug where we don't check for literals too - might be a common issue in there.
