### ISSUE TITLE
using join() in an map leads to a segv

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#633]
Yes, I know that in its current design you shouldn't be doing this but as a bit of destructive testing I thought I'd key a map with a join() and see what it does:

```
# cat examp.bt
t:syscalls:sys_enter_execv*
{
  @[join(args->argv)] = count();
}

# bpftrace ./examp.bt
Segmentation fault (core dumped)
```

**Comment by mmarchini** [comment]
segfault is not what I would expect :)

This will probably be superseded by #26, but we can keep this open for now. Maybe there are other cases where this happens as well?
