### ISSUE TITLE
bpftrace as a library

### ISSUE THREAD

**Issue by andreasgerstmayr** [iovisor/bpftrace#643]
I plan to integrate bpftrace as a library into a new Performance Co-Pilot PMDA. The big picture will be: a user opens a Grafana dashboard, enters a bpftrace command and sees an appropriate visualization (e.g. a latency heatmap, depending on the bpftrace command) in near real-time.

For this I'd like to update the bpftrace build process to split the build output into a shared object and dynamically link the frontend (the current CLI) with the library. Is there interest in merging this upstream when I prepare it?

Cheers,
Andreas

**Comment by javierhonduco** [comment]
cc @danobi

**Comment by ajor** [comment]
I'm not sure... my concern with releasing a libbpftrace is that people would expect a stable API, which I definitely don't want. bpftrace.h is pretty awful at the moment so there is a lot I want to change in there.

If we do produce a shared library, what's the benefit of dynamically linking the frontend to it? Couldn't we just have the frontend statically linked to the bpftrace compents (like we do now) and a separate shared library?

**Comment by andreasgerstmayr** [comment]
Thanks for your comments, and sorry for my late reply.

> I'm not sure... my concern with releasing a libbpftrace is that people would expect a stable API, which I definitely don't want. bpftrace.h is pretty awful at the moment so there is a lot I want to change in there.

The interface would be quite minimal, I'd only need a function which accepts a bpftrace script and runs it, and a function which returns the values of the bpf maps, e.g. for heat maps I'm interested in the `values` argument of the `BPFtrace::print_hist()` function. Would you be fine with a minimal interface like this, or do you plan to change these code paths soon?

> If we do produce a shared library, what's the benefit of dynamically linking the frontend to it? Couldn't we just have the frontend statically linked to the bpftrace compents (like we do now) and a separate shared library?

The benefit I see from dynamically linking the frontend to the library is deduplication.

Another way to integrate bpftrace in an external application would be to `exec()` it and read the eBPF maps directly - but then the way how bpftrace stores histograms in BPF maps would be the interface (and I'd have to figure out which kind of data structure is inside the BPF maps).

Or do you have any other idea on how to integrate bpftrace into an external application? Maybe I'm overlooking something. For my use case I need to execute scripts and get the data (heatmaps, tables, ...) in some structured way.

**Comment by andreasgerstmayr** [comment]
Just got another idea - adding two new arguments:
* `--interval`: print eBPF maps every X seconds to stdout, same as the interval argument for system performance tools like `iostat`, `pidstat` etc.
* `--format=json`: print maps in JSON format - not 100% required, but would ease the integration

Would this work for you @ajor?

**Comment by andreasgerstmayr** [comment]
Hm, probably it's better to let the user decide which maps are important and let them print it continuously with `interval:s:1 { print(@bytes); }` in the bpftrace script instead of a general `print_maps()` every X seconds.

I'll close this for now, sorry for the noise.

**Comment by ajor** [comment]
Agree on using `interval:s:1 { ... }`, but JSON output sounds like a good idea

**Comment by mmarchini** [comment]
@andreasgerstmayr you might be interested in #445.

**Comment by andreasgerstmayr** [comment]
Thanks @mmarchini! I did look for tickets regarding the library aspect, but forgot to search for open issues about JSON output. I already started with a JSON output implementation in the last few days, I'll will publish it for review asap.
