### ISSUE TITLE
END probe not called with exit()

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#658]
I'm sure this was fixed previously but an explicit call to exit() means that END() probe processing is bypassed:

```
BEGIN
{
  printf("Begin\n");
}

interval:s:5
{
  exit();
}

END
{
  printf("End\n");
}

# bpftrace ./end.bt
Attaching 3 probes...
Begin
# 

The documentation doesn't specify the exact semantics of an exit() but we should call END regardless of how we exit.

**Comment by shish** [comment]
Duplicate of #228?

**Comment by tyroguru** [comment]
Thanks @shish! That is so funny as I logged @228 :-) . I thought it existed but couldn't see it so logged it again. SIgh.
