### ISSUE TITLE
bpftrace segmentation fault

### ISSUE THREAD

**Issue by horseinthesky** [iovisor/bpftrace#664]
Hello.
I've just started reading about bpftrace and try to do tutorial one liners https://github.com/iovisor/bpftrace/blob/master/docs/tutorial_one_liners.md
but every example fails with `segmentation fault`

```
sudo bpftrace -l 'BEGIN { printf("hello world\n"); }'
terminate called after throwing an instance of 'std::regex_error'
  what():  Unexpected escape character.
[1]    8006 abort      sudo bpftrace -l 'BEGIN { printf("hello world\n"); }'

sudo bpftrace -e 'tracepoint:syscalls:sys_enter_openat { printf("%s %s\n", comm, str(args->filename)); }'
Error creating perf event map (-1)
Attaching 1 probe...
[1]    8065 segmentation fault  sudo bpftrace -e 

sudo bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'
Error creating map: '@'
Error creating perf event map (-1)
Attaching 1 probe...
[1]    8125 segmentation fault  sudo bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'
```

I'm on Ubuntu 18.04 and installed `bpftrace` via `sudo snap install bpftrace`. Could someone pls tell me what I am doing wrong?

**Comment by caringi** [comment]
Hi,

> Hello.
> I've just started reading about bpftrace and try to do tutorial one liners https://github.com/iovisor/bpftrace/blob/master/docs/tutorial_one_liners.md
> but every example fails with `segmentation fault`
> 
> ```
> sudo bpftrace -l 'BEGIN { printf("hello world\n"); }'
> terminate called after throwing an instance of 'std::regex_error'
>   what():  Unexpected escape character.
> [1]    8006 abort      sudo bpftrace -l 'BEGIN { printf("hello world\n"); }'

The correct command line is:

`sudo bpftrace -e 'BEGIN { printf("hello world\n"); }'`

But bpftrace shouldn't crash in this situation (this is a bug and I'll take a look into it).

> sudo bpftrace -e 'tracepoint:syscalls:sys_enter_openat { printf("%s %s\n", comm, str(args->filename)); }'
> Error creating perf event map (-1)
> Attaching 1 probe...
> [1]    8065 segmentation fault  sudo bpftrace -e 
> 
> sudo bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'
> Error creating map: '@'
> Error creating perf event map (-1)
> Attaching 1 probe...
> [1]    8125 segmentation fault  sudo bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'
> ```
> 
> I'm on Ubuntu 18.04 and installed `bpftrace` via `sudo snap install bpftrace`. Could someone pls tell me what I am doing wrong?

Some people already reported problems related to bpftrace & snap:

https://github.com/iovisor/bpftrace/issues/642

The recommendation is to install it this way:

`sudo snap install --devmode bpftrace`

**Comment by horseinthesky** [comment]
@caringi Sad but doesn't help =(
```
sudo snap install --devmode bpftrace
bpftrace 0-20191704-94b8667ddb from Colin King (cking-kernel-tools) installed

bpftrace --version
bpftrace v0.8-66-g3a9c
```

The same issue:
```
 sudo bpftrace -e 'BEGIN { printf("hello world\n"); }'
Error creating perf event map (-1)
Attaching 1 probe...
[1]    10896 segmentation fault  sudo bpftrace -e 'BEGIN { printf("hello world\n"); }'

sudo bpftrace -e 'kretprobe:vfs_read { @bytes = lhist(retval, 0, 2000, 200); }'                              
Error creating map: '@bytes'
Error creating perf event map (-1)
Attaching 1 probe...
[1]    10955 segmentation fault  sudo bpftrace -e 
```

**Comment by caringi** [comment]
@horseinthesky have you followed the instructions here: 

https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#ubuntu-snap-package

?

```
sudo snap install --devmode bpftrace
sudo snap connect bpftrace:system-trace
```

**Comment by horseinthesky** [comment]
> @horseinthesky have you followed the instructions here:
> 
> https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#ubuntu-snap-package
> 
> ?
> 
> ```
> sudo snap install --devmode bpftrace
> sudo snap connect bpftrace:system-trace
> ```

Yes, I did.

**Comment by mmarchini** [comment]
@horseinthesky were you able to make this work?

> Error creating map: '@bytes'
> Error creating perf event map (-1)

That looks like something is blocking creation of BPF maps in your system. Are you running this inside a container? Or inside a shell installed via snap (for example tmux or zsh installed via snap)? What's the output of `dmesg` after you get these errors?

**Comment by mmarchini** [comment]
On a side note, I think bpftrace should stop and exit if it can't create maps. I'll open another issue for that.

**Comment by dailyherold** [comment]
I'm getting same seg faults on all bpftrace one lines, even the hello world one. Running fresh 19.10 and built from source based on instructions. `dmesg` output for 
```
❯ sudo bpftrace -e 'BEGIN { printf("hello world\n"); }'
[1]    16857 segmentation fault  sudo bpftrace -e 'BEGIN { printf("hello world\n"); }'
```
is the following:
```
[12102.514807] bpftrace[16858]: segfault at 5 ip 00007fe60e4f4ba5 sp 00007fff9d4dc808 error 4 in libc-2.30.so[7fe60e38e000+178000]
[12102.514822] Code: 00 00 0f 1f 00 31 c0 c5 f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 89 f9 48 89 fa c5 f9 ef c0 83 e1 3f 83 f9 20 77 2b <c5> fd 74 0f c5 fd d7 c1 85 c0 0f 85 eb 00 00 00 48 83 c7 20 83 e1
```
@joestringer I saw you on #1133 also using 19.10 and seems like you were all fine after figuring out build issues. Have you had any problems running bpftrace since? I didn't have build problems like you (built it tonight copy pasta from docs) but curious if you've fared better once build on 19.10.

**Comment by joestringer** [comment]
@dailyherold I ended up compiling completely statically via the instructions [here](https://github.com/iovisor/bpftrace/issues/1134#issuecomment-583221442), and did not hit any segfault type issues.

**Comment by dailyherold** [comment]
Interesting, ldd didn't show any issues with my dynamically linked binary. Still went for the static method and had same problem. Turns out it was lockdown mode enabled on my kernel, and #853 instructions fixed my problem.
