### ISSUE TITLE
Should require struct/union prefix when casting

### ISSUE THREAD

**Issue by ajor** [iovisor/bpftrace#682]
We're allowed to skip the struct/union prefix when casting as a shorthand at the moment, but it can cause problems:

test.h:
```
struct Foo
{
  int x;
};

typedef union
{
  int a;
  int b;
} Foo;
```

This script allows some invalid field accesses:
```
#include "test.h"

BEGIN
{
  ((Foo*)0)->a;
  ((Foo*)0)->b;
  ((Foo*)0)->x;
}
```

This is what should be required:
```
#include "test.h"

BEGIN
{
  ((Foo*)0)->a;
  ((Foo*)0)->b;
  ((struct Foo*)0)->x;
}
```

**Comment by mmarchini** [comment]
@brendangregg thoughts?
