### ISSUE TITLE
Wildcard on probe path not handled correctly

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#688]
I would expect the program below to attach to all USDT probes of usdt_test for the given PID. Got an syntax error instead:

```
# bpftrace -e 'usdt:*usdt_test*::* { printf("here\n" ); exit(); }' -p $(pidof usdt_test)
1.17-18: syntax error, unexpected path, expecting {
```

**Comment by dalehamel** [comment]
I'll take a look

**Comment by acj** [comment]
@mmarchini What behavior would you expect if the wildcard path matches more than one binary? Perhaps use the first match as the probe target and print a friendly warning?
