### ISSUE TITLE
support for bpftrace_send_signal

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#693]
Will be in Linux 5.3; bcc already has support: https://github.com/iovisor/bcc/pull/2387/commits/d3d3808b185457c7bb69e35f0fee5cd397c46991

I propose we have a builtin called `signal()`, which accepts the signal number as the argument. Any objections?

**Comment by tyroguru** [comment]
Yeah, this would be a great addition. Should be marked as an unsafe action though owing to it's wide ranging powers.

**Comment by danobi** [comment]
+1 that it should be unsafe.
