### ISSUE TITLE
keying a map with printf generates SEGV

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#697]
Yes, yes, obviously it doesn't make sense to key a map with a `printf()` but if you do it leads to a segv:

```
#  bpftrace -e 'BEGIN{@[printf("segv generator")] = count();}'
Segmentation fault (core dumped)
```

Obviously not a priority but just needs sorting out some time.

**Comment by mmarchini** [comment]
All of these `call X used as key in map cause segv" will probably be solved by the same PR
