### ISSUE TITLE
Tracking Issue: Compatibility with libstapsdt

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#71]
Opening this issue to remind us to check if bpftrace plays nicely with [sthima/libstapsdt](https://github.com/sthima/libstapsdt) and to remind us to take dynamic USDT probes into consideration when introducing USDT arguments (#33) and struct support for user-space tracepoints (#31).

**Comment by dalehamel** [comment]
I have used it with the python sample repeatedly and it seems to play nice.

I'm working on implementing a ruby wrapper to libstapsdt as well, so I'll file an issue if anything is wonky.

**Comment by mmarchini** [comment]
Yes, with #280 and #413 I think the usability of libstapsdt probes improved a lot. I played with Node.js a bit and was able to write some neat programs :)

I'm going to close for now, but if anyone is having issues with libstapsdt and bpftrace please let us know!
