### ISSUE TITLE
epoll_wait() usage needs to handle EINTR correctly

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#712]
Applying `strace(1)` to a bpftrace process causes bpftrace to exit prematurely. To replicate simply start any bpftrace invocation and ion another terminal apply strace to thee process and it will terminate.

This is because `epoll_wait(2)` returns -1 with `errno` set to `EINTR` and we don't handle this correctly in `BPFtrace::poll_perf_events()`.  I think to fix this we will need to do set some global state in the SIGINT handler to differentiate between the ptrace based condition that strace induces and the genuine condition of a user supplied `<ctrl-c>`.

**Comment by jgkamat** [comment]
I've got a [basic patch to fix this](http://github.com/jgkamat/bpftrace/tree/jay/epoll_wait_eintr), although I'm holding off on submitting it for a little bit while I test.
