### ISSUE TITLE
add support for bpf_override_return()

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#720]
e.g., for syscall error injection (testing, security, etc):

```
bpftrace -e 't:syscalls:sys_exit_openat /comm == "java"/ {
    if ((rand % 100) == 0) { override(ENOMEM); } }'
```

(Thanks Daniel Borkmann for the idea.)

**Comment by danobi** [comment]
Are we going to restrict this to syscalls? I believe functions need to be added to an error-injection whitelist for this to work on kprobes.

I believe all syscalls are whitelisted by default.

**Comment by ajor** [comment]
Don't want to go with `return()` as the name?

**Comment by brendangregg** [comment]
`return()` maybe. I worry about people using it by accident instead of `exit()`: a `return(0)` doesn't return out of the bpftrace action block (as might be assumed) -- it'd override the current syscall return value with a zero (which might be a surprise). Instead of it being a purely observability program, this capability makes bpftrace control the execution flow directly. You're now directly coding what the target should do next. Unlike, say, system() (which is async) or signal() (needs other handling).

I guess it'll also warn about needing --unsafe, which should be a clue.

**Comment by ajor** [comment]
Yeah good point. I feel that `override()` isn't descriptive enough about what it's overriding though. Maybe go with the full `override_return()`? But then it is quite long...
