### ISSUE TITLE
A mechanism for tunable parameters within scripts

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#728]
I just wanted to raise an issue to discuss the future of tunable parameters and how they are exposed and carried around with scripts.

Currently we have gone down the route of providing environment variables to allow the user some control over aspects of bpftrace behaviour that can be controlled by them. As of a day or so ago, the current set are:

```
ENVIRONMENT:
    BPFTRACE_STRLEN           [default: 64] bytes on BPF stack per str()
    BPFTRACE_NO_CPP_DEMANGLE  [default: 0] disable C++ symbol demangling
    BPFTRACE_MAP_KEYS_MAX     [default: 4096] max keys in a map
    BPFTRACE_CAT_BYTES_MAX    [default: 10k] maximum bytes read by cat builtin
    BPFTRACE_MAX_PROBES       [default: 512] max number of probes
```

The major challenge with this approach in the long term is the fundamental problem that the settings a script needs are not shipped around with the script. It's not really feasible to expect users to ship scripts around with extra text specifying what different parameters should be set to. Everything the script needs to run correctly should be provided within the script itself.

I think this means that the we need an extension to the language to allow specification of these variables within a script. Other implementations of tracing languages have used pre-processor type mechanism to achieve this such as a #pragma, i.e.,:

```
#pragma parameter BPFTRACE_MAX_PROBES 200
```

Other language features such as `unsafe` should be allowed to be specified here as well, i.e.,:

```
#pragma option unsafe
```

I haven't thought too much about syntax but hopefully you see what I mean. We could still allow both mechanisms if we wanted so that one liners could work with these tunables as they do now (they could be parsed and #pragma settings would override them maybe?).

**Comment by danobi** [comment]
Nice idea; I like it.

**Comment by brendangregg** [comment]
#pragma is rarely used. I think a lot of newbies will wonder what it is.

Since we already provide a command line interface (-p PID, -I DIR, etc), then as a starting point then how about putting the same interface in the script?

```
#!/usr/local/sbin/bpftrace

options = "-I /mnt/include -v"

BEGIN
{
...
```

Then we pass that string to the existing getops() logic.

**Comment by ajor** [comment]
If we want `unsafe` to protect people from dodgy scripts they download off the internet, we shouldn't allow it to be specified in scripts

**Comment by brendangregg** [comment]
True.

Plus I forgot about the environment variables in that example, since they don't have CLI options. Could be:

```
options = "-I /mnt/include -v"
environment[BPFTRACE_MAX_PROBES] = 200;
environment[BPFTRACE_STRLEN] = 64;
```

**Comment by jordalgo** [comment]
Closing in favor of discussing here: https://github.com/iovisor/bpftrace/pull/2815
