### ISSUE TITLE
Add $# parameter

### ISSUE THREAD

**Issue by ajor** [iovisor/bpftrace#741]
To return the number of command line arguments passed to the script at runtime.

**Comment by markdrayton** [comment]
What would example use cases for this be? Since there is no direct loop support and `unroll` doesn't yet (AFAICT) expose any way to do something with each positional parameter I can't see an immediate use for it. I'm sure I am missing something.

Nevertheless, I'm interested in trying to add this feature as an intro to bpftrace development. Is making `PositionalParameter` more generic (e.g. able to handle both positional params and the number of parameters via some additional state in the class) okay, or does this feature warrant an additional expression?

**Comment by ajor** [comment]
Making `PositionalParameter` able to handle this sounds like a good way to go.

Positional parameters are optional in bpftrace, and when they are not provided on the command line they get initialised to default values (0 for integers, "" for strings).

Two cases that `$#` would be useful for:
- Making positional parameters required, not optional
```
BEGIN
{
  if ($# < 2)
  {
    printf("Two arguments required\n");
    exit();
  }
}
```

- Setting different default values
```
kprobe:foo
{
  if ($# < 3)
  {
    // $3 will have the default value of 0 here
    $3 = -1; // instead initialise it to -1
  }
  ... use $3 ...
}
```

Scripts at the moment might be checking if a parameter is set by comparing to 0, but this would break if a user passes a value of 0 along through the command line.

**Comment by markdrayton** [comment]
It looks like bpftrace refuses to run scripts that refer to missing positional parameters:

```
$ sudo ./src/bpftrace -e 'BEGIN { printf("%d\n", $1) }'
missing positional parameter $1
```

I have a PR more or less ready for `$#`. If it's acceptable we could decide if the missing positional behaviour needs to change.

**Comment by brendangregg** [comment]
Missing positional parameters needs to be allowed. Lots of tools will use
it. Optional interval, optional latency threshold, optional pid.

**Comment by ajor** [comment]
Yep sorry, I've just merged #742 which re-enabled optional positional parameters.

**Comment by markdrayton** [comment]
At risk of derailing this PR, it looks like assigning to positionals doesn't work at the moment so setting default values won't work yet:

```
# bpftrace -e 'BEGIN { $1 = 1 }'
1.12: syntax error, unexpected =, expecting }
```

Maybe `$pid = $# < 1 ? 12345 : $1` is an acceptable method of handing optional parameters with default values? Obviously positionals could be assignable, just wondering if this simple alternative is okay.

**Comment by ajor** [comment]
Ah yeah, I just didn't think through that example well enough. `$pid = $# < 1 ? 12345 : $1` is a good way of doing it.
