### ISSUE TITLE
Should bpftrace exit after firing BEGIN if that's the only probe defined?

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#747]
Take the following script for example:

```
./src/bpftrace -e 'BEGIN { printf("hello\n") }'
Attaching 1 probe...
hello

```

bpftrace will stay open until it receives a SIGINT, but we're not listening to any probes after we executed BEGIN. Would it make sense to close bpftrace if no probes are attached after BEGIN? I know it's not the most useful feature for real scripts, but it's useful for our runtime test suite and for quick tests when developing.

**Comment by danobi** [comment]
I see the non-exit as being uniform with the other features. Adding a special case for this is probably fine, but it's another special case that has to be carried forward and remembered. Just a thought, I don't have a strong opinion on this.

**Comment by brendangregg** [comment]
FWIW, with awk(1), a BEGIN only program will exit, and END won't (END waits for EOF: Ctrl-D).

But yeah, I'm also wanting to avoid special casing too much.

Speaking of default actions, I think #234 will get more use by end-users. See my example one-liner at the end.

**Comment by mmarchini** [comment]
Uniformity across probe types make sense. Closing, if anyone has anything to add to the discussion feel free to comment or create a new issue.
