### ISSUE TITLE
Comm name and args not displayed correctly with one line examples

### ISSUE THREAD

**Issue by bbn-zbertils** [iovisor/bpftrace#767]
I'm using a Pi3b+ with Raspbian Stretch and custom kernel 4.19 with all BPF, kprobe/uprobe and trace points enabled.

```
Linux raspberrypi 4.19.42-v7+ #1 SMP Thu May 16 07:41:42 CDT 2019 armv7l GNU/Linux
```

I've compiled llvm/clang with the following from the llvm-project source (https://github.com/llvm/llvm-project), build steps were;

```bash
git clone https://github.com/llvm/llvm-project
cd llvm-project && mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGET_ARCH=ARM -DLLVM_TARGETS_TO_BUILD='ARM;BPF' -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_PROJECTS=clang -G "Unix Makefiles" ../llvm
```

```bash
git clone https://github.com/iovisor/bpftrace.git
cd bpftrace
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make
```

This builds and installs correctly, though when I run the one line example for `do_sys_open` I get odd outputs with `comm` and using the args. I can substitute `arg1` for any number, e.g. `arg5` and I get the same outputs where the comm name is not correctly displayed, and where the arg should be displayed is actually the comm name.

```bash
sudo bpftrace -e 'kprobe:do_sys_open { printf("%s: %s\n", comm, str(arg1)) }'
Attaching 1 probe...
: mv
: mv
: mv
: objdump
: objdump
: grep
```

To make it more weird, using the `sys_enter` tracepoint the comm name is displayed correctly.

```bash
sudo bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'
Attaching 1 probe...
^C

@[sudo]: 0
@[lxterminal]: 0
@[gmain]: 0
@[ld]: 0
@[rngd]: 3
@[lxpanel]: 23
@[Xorg]: 29
@[rm]: 67
@[gcc]: 4294967296
@[tee]: 12884901891
@[make]: 12884902745
@[systemd-journal]: 47244640256
@[bpftrace]: 94489280512
@[sshd]: 103079215128
@[recordmcount]: 257698037760
@[sh]: 377957122136
@[genksyms]: 747324309678
@[cc1]: 13743895347200
```

Advice on how to correct this would be appreciated.

**Comment by bbn-zbertils** [comment]
This appears to be the way bpftrace is handling strings. The usage of `@[comm]` does not break, but using a straight `comm` with formatter `%s` causes the invalid string characters.

**Comment by ajor** [comment]
What's the problem with the string handling? `comm` is meant to just return a string

This example works for me (on x64) at least

**Comment by bbn-zbertils** [comment]
I agree it should just be a string, and the debug output looks to be a string of 8-bit integers.

```bash
define i64 @"tracepoint:ext4:ext4_allocate_inode"(i8*) local_unnamed_addr section "s_tracepoint:ext4:ext4_allocate_inode_1" {
entry:
  %comm = alloca [16 x i8], align 1
.
.
.
```

I'm on arm32, so maybe it is an not directly related to the character string itself, but it's odd that any of the `argX` variables will output the `comm` name, and `comm` itself will always output garbage unless part of an `@[comm]` array.

I'm not sure if the src/arch/aarch64.cpp can be directly used on arm32, but the default is to use the x86_64.cpp architecture if `aarch64` is not detected by cmake. This is obviously incorrect for arm32 and forces only two possible 64-bit-only types of builds. I added the following to the src/arch/CMakeLists.txt to select the aarch64.cpp. If I can find the correct registers for pi3b+ (armv7l) I'll add a new source file for it, but for now am copying aarch64.

```cmake
if(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
    add_library(arch aarch64.cpp)
+ elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "armv7l")
+     add_library(arch aarch64.cpp)
else()
    add_library(arch x86_64.cpp)
endif()
```

**Comment by ajor** [comment]
The architecture file shouldn't actually matter for the `comm` builtin since it doesn't need to access any registers.
I wonder if the problem is the 32-bit architecture though. The bytecode bpftrace generates expects 64-bit, but I don't know how the Linux BPF VM handles these differences.

**Comment by bbn-zbertils** [comment]
Besides changing the use of uint64_t over to uint32_t, what else would be required to port to a 32-bit system? Or is this not possible without extensive work to llvm/clang/kernel ?

**Comment by ajor** [comment]
I've not looked over everything, but here are a few things I can remember that expect 64-bits:

- `b_.getInt64(x)` is used a lot in codegen_llvm.cpp
- basically everywhere the number `8` is used will need to be changed to `4`. This is across a few files, including semantic_analyser.cpp, codegen_llvm.cpp, bpftrace.cpp

**Comment by bbn-zbertils** [comment]
I did a wholesale change of 64 bit usages to 32 bit, `getInt64` -> `getInt32`, `8` -> `4` for the offsets, and `uint64_t` -> `uint32_t` except for a couple function prototypes that require uint64_t arguments on bcc functions (that actually weren't used). It looks like things are now working, at least better than they were.

```bash
sudo bpftrace -e 'kprobe:do_sys_open { printf("%s: %s\n", comm, str(arg1)) }'
Attaching 1 probe...
udisksd: /proc/self/mountinfo
udisksd: /proc/swaps
systemd: /proc/self/mountinfo
systemd: /sys/dev/block/179:2
systemd: /proc/self/mountinfo
systemd: /sys/dev/block/179:2
```

I haven't tested the entire suite of functionality, but for now this is serving my purposes. Thank you for your help!

**Comment by bbn-zbertils** [comment]
Created a branch `arm32-support` on forked copy of bpftrace repo here https://github.com/bbn-zbertils/bpftrace.git

Not yet doing a pull request as this change effectively removes 64-bit support and makes it 32-bit only. The correct way to implement it would be with a compile time #define or cmake switch to define an `uintx_t` type that replaces all uint64_t and effectively becomes uint32_t or uint64_t depending on the user's build preference. The BPF getInt64() values are not necessary to work on a pi3b+, something like...

Create the build files, need to change cmake files to properly handle new flag
```bash
cmake .. -DCMAKE_BUILD_TYPE=Release -DCOMPILE_32_BIT
```

And place in utils.h or some common header file.
```cpp
#define uintx_t               uint64_t
#define uint_byte_width       8

#ifdef COMPILE_32_BIT

#undef uintx_t
#undef uint_byte_width

#define uintx_t               uint32_t
#define uint_byte_width       4

#endif
```
