### ISSUE TITLE
Begin triggered by 2nd bpftrace script

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#777]
When starting two bpftrace scripts simultaneously the 2nd script triggers the begin of the first. E.g. for this simple script you only expect one print, but everytime bpftrace is started it triggers.

```
sudo bpftrace_master -e 'BEGIN { printf("begin %lu\n", nsecs); }'
Attaching 1 probe...
begin 227538708722011
begin 227541222308743
begin 227543284186801
begin 227559613951439
begin 227561841784258
begin 227570971414956
begin 227573587070662
```

Didn't see this documented yet, or found an issue for it.

I'll look into it.

**Comment by mmarchini** [comment]
Nice catch. BEGIN is implemented as a uprobe due to kernel limitations (see #360 for more context). I guess we could fix this by detaching from BEGIN after the probe is executed.

**Comment by ajor** [comment]
Guess it would be the same for END too. Could make them automatically filter by PID
