### ISSUE TITLE
calling another kernel function using BPFtrace

### ISSUE THREAD

**Issue by maindoor** [iovisor/bpftrace#792]
Hi,
With bcc/bpfd we should able to do this. Since BPFtrace is replacing bcc/bpfd, I'm wondering if it is possible to call another "kernel_function2" upon entry into a "kernel_function1" using BPFtrace ? 
I wanted to generate BPF byte code to use with bpfd and was asked to look at BPFtrace. This looks
very high level and doesn't give raw power. My target is resource limited and I'm trying to use BPFtrace on it. Is it a good idea to look at BPFtrace in this case ?

Thanks.

**Comment by danobi** [comment]
To be clear, do you want `kernel_function2` to be executed in kernel context when `kernel_function1` is executed?

> Since BPFtrace is replacing bcc/bpfd

I certainly wouldn't say bpftrace is trying to replace bcc. bpftrace depends on bcc's underlying machinery. I'd say the two are complementary.

**Comment by brendangregg** [comment]
BPF can't call kernel functions (BCC, bpftrace, or anything). BPF can only call BPF kernel helpers.

I'd investigate a static build of bpftrace for resource limited environments. Also keep an eye on deployment mechanisms, like kubectl-trace, bpfd, and CO-RE. Closing ticket.
