### ISSUE TITLE
Redirected/piped output buffers and does not display real time, regardless of buffer mode

### ISSUE THREAD

**Issue by bbn-zbertils** [iovisor/bpftrace#832]
Using the `-o` option and redirecting with `>` causes the output from the tracer to get buffered regardless of what the `-B` specified. The below commands all buffer large amounts of data and dump it when it reaches a certain limit.

```
bpftrace -e 'kprobe:do_sys_open { printf("do_sys_open: %s: %s\n", comm, str(arg1)) }' -o ~/do_sys_open.log -B none

bpftrace -e 'kprobe:do_sys_open { printf("do_sys_open: %s: %s\n", comm, str(arg1)) }' > ~/do_sys_open.log

bpftrace -e 'kprobe:do_sys_open { printf("do_sys_open: %s: %s\n", comm, str(arg1)) }' | myOtherToolThatPrints
```

Then `tail -f ~/do_sys_open.log` in another terminal, followed by `ls` in a third terminal, I can execute `ls` multiple times before the log file is dumped with many `ls` call outputs.

This error exists regardless of the output or redirection, __unless__ no output or redirection is specified.

```
bpftrace -e 'kprobe:do_sys_open { printf("do_sys_open: %s: %s\n", comm, str(arg1)) }'
```

The above command does not have this buffering issue and will output traces as they happen, which is the desired effect for outputting to a file, or piping to another tool.

**Comment by bbn-zbertils** [comment]
Fixed, needed to use `unbuffer` to keep output in tty mode.

```
sudo unbuffer bpftrace -e 'kprobe:do_sys_open { printf("do_sys_open: %s: %s\n", comm, str(arg1)) }'
```

**Comment by fbs** [comment]
Sounds like something we should fix. Having to run `unbuffer` to get output is a confusing.

**Comment by bbn-zbertils** [comment]
I originally thought this was a bpftrace issue, but I'm not sure how this could be fixed via bpftrace. It was a system imposed buffer, where all process outputs that get redirected will be buffered, not just bpftrace. Using `unbuffer` simply removes the buffer and allows the process to output as if it is direct to an interactive terminal.
