### ISSUE TITLE
Inefficient code generation leads to very misleading results

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#848]
Apologies for the horribly generic synopsis. Please adjust as the root cause becomes clear.

Whilst timing some getpid() calls I noticed some odd behaviour. Take the following script:

```
#  cat getpid-slow.bt
tracepoint:syscalls:sys_enter_getpid
{
        @[tid] = nsecs;
}

t:syscalls:sys_exit_getpid
/@[tid]/
{
        @average["getpid"] = avg(nsecs - @[tid]);
        @[tid] = 0;
}

interval:s:10
{
        print(@average);
        clear(@average);
}
```

On my system this produces:

```
@average[getpid]: 2695

@average[getpid]: 2716

@average[getpid]: 2763

@average[getpid]: 2334

@average[getpid]: 2656
```

However, if I manually hoist the time calculation out of the avg() into a local variable with:

```
# diff getpid-slow.bt getpid-fast.bt
--- getpid-slow.bt      2019-08-01 08:59:35.412161939 -0700
+++ getpid-fast.bt      2019-08-01 08:59:47.041174182 -0700
@@ -6,7 +6,8 @@
 t:syscalls:sys_exit_getpid
 /@[tid]/
 {
-        @average["getpid"] = avg(nsecs - @[tid]);
+        $time = nsecs - @[tid];
+        @average["getpid"] = avg($time);
         @[tid] = 0;
 }
```

then the runs look like this:

```
#  /tmp/bpftrace ./getpid-fast.bt
Attaching 3 probes...
@average[getpid]: 1858

@average[getpid]: 1825

@average[getpid]: 1580

@average[getpid]: 1487

@average[getpid]: 1559
```

It looks like this change means we execute in the BPF interpreter for a lot less time! If you dump out the byte code with `-vv` then we seem to generate a very odd and wasteful looking sequence of byte code that is executed before the call to bpf_ktime_get_ns() in the slow version and after it in the hoisted version. In the slow version bpf_ktime_get_ns() is at instruction 187 in its block but at instruction 14 in the hoisted version.

**Comment by tyroguru** [comment]
The code sequence I'm referring to above looks like this:

```
15: (73) *(u8 *)(r10 -9) = r7
16: (73) *(u8 *)(r10 -10) = r7
17: (73) *(u8 *)(r10 -11) = r7
18: (73) *(u8 *)(r10 -12) = r7
19: (73) *(u8 *)(r10 -13) = r7
20: (73) *(u8 *)(r10 -14) = r7
21: (73) *(u8 *)(r10 -15) = r7
22: (73) *(u8 *)(r10 -16) = r7
23: (73) *(u8 *)(r10 -17) = r7
24: (73) *(u8 *)(r10 -18) = r7
25: (73) *(u8 *)(r10 -19) = r7
26: (73) *(u8 *)(r10 -20) = r7
27: (73) *(u8 *)(r10 -21) = r7
28: (73) *(u8 *)(r10 -22) = r7
29: (73) *(u8 *)(r10 -23) = r7
30: (73) *(u8 *)(r10 -24) = r7
31: (73) *(u8 *)(r10 -25) = r7
32: (73) *(u8 *)(r10 -26) = r7
33: (73) *(u8 *)(r10 -27) = r7
34: (73) *(u8 *)(r10 -28) = r7
35: (73) *(u8 *)(r10 -29) = r7
36: (73) *(u8 *)(r10 -30) = r7
37: (73) *(u8 *)(r10 -31) = r7
38: (73) *(u8 *)(r10 -32) = r7
39: (73) *(u8 *)(r10 -33) = r7
40: (73) *(u8 *)(r10 -34) = r7
41: (73) *(u8 *)(r10 -35) = r7
42: (73) *(u8 *)(r10 -36) = r7
43: (73) *(u8 *)(r10 -37) = r7
44: (73) *(u8 *)(r10 -38) = r7
45: (73) *(u8 *)(r10 -39) = r7
```

That's a sample - there's about 80 or so instructions in that sequence.

**Comment by fbs** [comment]
This is due to:

```
diff --git a/src/ast/semantic_analyser.cpp b/src/ast/semantic_analyser.cpp
index bbb9816..f38bf66 100644
--- a/src/ast/semantic_analyser.cpp
+++ b/src/ast/semantic_analyser.cpp
@@ -62,7 +62,7 @@ void SemanticAnalyser::visit(String &string)
     err_ << "String is too long (over " << STRING_SIZE << " bytes): "
          << string.str << std::endl;
   }
  string.type = SizedType(Type::string, STRING_SIZE);
 }
```

```
$ sudo bpftrace -e 'BEGIN { @["abc"]=1 }'
551: hash  flags 0x0
	key 64B  value 8B
```

This is done to ensure all map keys have the same size so that `@["abc"] and `@["xxxxxxxxx"]` works, but as a side effect it will have to memset 64 bytes. 

I think it should be doable to keep track of the required string size (the size of the longest string) and use that instead of a fixed 64 bytes. This should reduce the amount of instructions for the average program by quite a bit, e.g. comm which is used often is 16 bytes max.

Changing  the memset to work with 8 bytes instead of 1  might be possible to but might be a lot of work as all array types are `[x * i8]` atm.

**Comment by viktormalik** [comment]
This problem should be now mitigated by #2044.

Running on my machine, the above two variants produce roughly the same numbers.
