### ISSUE TITLE
Provide CMAKE_INSTALL_MANDIR

### ISSUE THREAD

**Issue by Earnestly** [iovisor/bpftrace#851]
Currently the `man/man8/cmake_install.cmake` assumes the destination should be prefixed with `CMAKE_INSTALL_PREFIX` which is usually incorrect on systems (Fedora, Debian, Arch, etc.) which use `/usr/share/man` as their `MANDIR`.

I did consider adding a PR which adopts [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) but discovered this project requires a minimum of cmake version 2.8.12 which is far too old for this feature.

The ideal interface would look something like:

```
% cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_MANDIR=/usr/share/man .
```

With changes such as (`man/man8/CMakeLists.txt`):

```cmake
install(FILES ${GZFILES} DESTINATION ${CMAKE_INSTALL_MANDIR}/man8)
```

As it stands every mainstream linux distribution has to do a little dance involving loops and/or `mv` to relocate the manuals and directories which could be avoided with this.

**Comment by ahkok** [comment]
Seconded. This cost me extra time packaging for `clearlinux`. This ought to be standard and not need custom adjustment to match all the other packages.

**Comment by mmarchini** [comment]
> I did consider adding a PR which adopts GNUInstallDirs but discovered this project requires a minimum of cmake version 2.8.12 which is far too old for this feature.

We can probably consider bumping the minimal cmake version (I'm not sure why it is 2.8.12 right now).

**Comment by ahkok** [comment]
that was released october 2013. Slightly old by now. 3.0.0 is from june 
2014. Even that is ancient in many ways.
