### ISSUE TITLE
hist() doesn't support 64 bit values

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#856]
The `hist()` map function truncates values that are > 32 bit.

```
#  cat hist-4G.bt

BEGIN
{
  $num = 10*1024*1024*1024;

  printf("Number being added: %lld\n", $num);
  @[probe] = hist($num);
}

interval:s:1
{
  exit();
}

# /tmp/bpftrace ./hist-4G.bt 10737418240
Attaching 2 probes...
Number being added: 10737418240


@[BEGIN]:
[2G, 4G)               1 |@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@|

```

**Comment by luigirizzo** [comment]
I just noted the same problem.

The fix is rather timple, start the loop from 5 instead of 4 in the following line

https://github.com/iovisor/bpftrace/blob/096235a10ebe8c955375a4755d1a42619135f767/src/ast/passes/codegen_llvm.cpp#L3117C12-L3117C18

**Comment by danobi** [comment]
@luigirizzo thanks for the report. Indeed the fix is simple. I'll put up a PR soon
