### ISSUE TITLE
Dealing with typedef redefinition errors 

### ISSUE THREAD

**Issue by carlpett** [iovisor/bpftrace#876]
I'm just getting started with bpftrace, so this is most likely a problem behind the keyboard, but I'm guessing it might be a good thing to document for the next confused person.
I wanted to test with `tracepoint:syscalls:sys_enter_sendmsg`. Checking `/sys/kernel/debug/tracing/events/syscalls/sys_enter_sendmsg/format`, `field:struct user_msghdr * msg` looks interesting. However, with this program, I get `Unknown struct/union: 'user_msghdr'`:
```c
tracepoint:syscalls:sys_enter_sendmsg {
  printf("entersend %s %s\n", comm, str(args->msg->msgiov));
}
```

Looking at `man sendmsg`, it references `sys/types.h`, and this is where I get into trouble. Adding `#include <sys/types.h>`, I instead get a bunch of errors like these:
```
/usr/include/sys/types.h:192:20: error: typedef redefinition with different types ('__blkcnt_t' (aka 'long') vs 'u64' (aka 'unsigned long long'))
/lib/modules/5.2.9-200.fc30.x86_64/source/include/linux/types.h:131:13: note: previous definition is here
```

Seems my standard headers aren't the same as the kernel-headers package? What am I supposed to do in this situation? Can I exclude the standard headers from the search path, or am I doomed until a new glibc-headers package comes along?

**Comment by carlpett** [comment]
_(Digging into the actual struct definitions, it looks like `args->msg->msgiov` won't work when I get the includes working, but that is a separate issue I can hopefully resolve then :slightly_smiling_face: )_

**Comment by fbs** [comment]
did you try including `linux/socket.h`?  `user_msghdr` is [defined there](https://elixir.bootlin.com/linux/v5.2.9/source/include/linux/socket.h#L58).  

As you're dealing with kernel code here you should include `linux/` headers. If you start including the headers for userspace you run into issues like these as definitions conflict. `linux/types.h` is included by default btw.

**Comment by carlpett** [comment]
Ah, no, I did not try that. That worked much better, thanks!
Given that the manpage references the `sys/*` headers rather than `linux/*`, is this just "something you need to know", or could I have figured that out somewhere in the docs?

**Comment by fbs** [comment]
>  Given that the manpage references the sys/* headers rather than linux/*, is this just "something you need to know", or could I have figured that out somewhere in the docs?

The man pages are for user space applications and how they should use it. So you can use them to figure out what the syscall does and how the inputs work but for the (kernel) internal types and details you have to look into the kernel source. 

Having some kind of "my first tracing program" doc might be useful. Going from "I know the syscall" to a usable program.

**Comment by carlpett** [comment]
Ok, thanks! I'll see if I get my little experiment working and then I might be able to document my journey there :) 

I'll close this though, thanks for explaining!
