### ISSUE TITLE
`min` and negative numbers

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#893]
Follow up from #834

Min currently does some offsetting which limits it's range to 32 bit. As a result the follow program doesn't print a thing:

```
sudo bpftrace -e 'i:ms:1 { @=min(4294967298); @=min(4294967297); exit() }'
Attaching 1 probe...


```

This behaviours doesn't appear to be documented either.

Would be good if we can fix this.

**Comment by jordalgo** [comment]
This works now as expected.
