### ISSUE TITLE
Support BPF_PROG_TYPE_PERF_EVENT context access

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#895]
`BPF_PROG_TYPE_PERF_EVENT` bpf programs are passed a special context holding interesting data related to the attached perf event.

This is the struct: https://github.com/torvalds/linux/blob/master/include/uapi/linux/bpf_perf_event.h#L13

It'd be useful if `software` and `hardware` probes had a builtin, `perfdata`, for accessing the context (like `arg*` for kprobe).

**Comment by danobi** [comment]
Closing in favor of #945

**Comment by mmisono** [comment]
With #1104, now we can access context data using `ctx` builtin. For example:

```sh
% sudo ./src/bpftrace -e 'i:s:1 { printf("%d\n", ctx->sample_period); }'
Attaching 1 probe...
1000000000
1000000000
^C
```

(In this case, the type of `ctx` is `struct bpf_perf_event_data`)

**Comment by danobi** [comment]
Awesome, thanks!
