### ISSUE TITLE
add unroll() loops

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#9]
Sometimes we'd like to run the same block of code a small number of times. This ticket is to add an `unroll()` loop operator for this purpose.

Eg, this:

```
 ./src/bpftrace -e 'kprobe:do_nanosleep { $i = 0; unroll(5) { printf("i: %d\n", $i); $i = $i + 1; } }'
```

Should run the block of code 5 times, and print:

```
i: 1
i: 2
i: 3
i: 4
i: 5
```

(It may print out-of-order if do_nanosleep() executes on different CPUs simultaneously.)

I imagine this will involve editing lexer.l and parser.yy, and the codegen may call "accept" on the same "stmt" node in a loop. I'd do if-else #8 first, since it will show how to wrap `stmt`s in codegen, and builds upon the existing ternary code that wraps `expr`s.

There should be a limit to the unroll number, eg, 20, enforced in semantic_analyser.cpp, since otherwise it'll be too easy for people to bust the BPF instruction limit.

Note that BPF recently (Linux 4.18-ish?) added better support for unrolled loops, so this may become a BPF call if that capability is detected, and support a much higher unroll number.

Note I'm also assuming that we'll only want to support constant ints as the unroll() argument, at least to begin with, and not an expression like `unroll($max)`.

**Comment by williangaspar** [comment]
Should it accept variables (`unroll($i)`) as input or just integers (`unroll(5)`)?

**Comment by brendangregg** [comment]
try both, and if there's a problem, just start with integers and have semantic analyzer say that variables are not yet supported.

**Comment by williangaspar** [comment]
The only issue I'm having with variables is a way of blocking values above 20. I'm trying to cast a `Value` to an `Integer` but I idk if it's possible.

**Comment by ajor** [comment]
I'm not sure if it is possible to unroll based on a variable value. Wouldn't it just be a regular loop at that point rather than an unrolled loop?

I couldn't find info on the new BPF support for unrolled loops though - @brendangregg have you got any links?

**Comment by mmarchini** [comment]
I think we should start with static values first.
