### ISSUE TITLE
cgroup built-in variable is the same for all containers

### ISSUE THREAD

**Issue by mythi** [iovisor/bpftrace#900]
The [commit](https://github.com/torvalds/linux/commit/bf6fa2c893c5237b48569a13fa3c673041430b6c) suggests that it'd be possible to check to which cgroup a pid belongs to.

I'm using `bpftrace` to print `cgroup`s for each `pid` I'm getting via a tracepoint but `cgroup` stays the same even if the `pid`s are from different containers.

I wrote a tool to search for that cgroup ID I'm getting and the result is:
```
cgroupid - path
4294967297 - /sys/fs/cgroup/blkio
4294967297 - /sys/fs/cgroup/cpu,cpuacct
4294967297 - /sys/fs/cgroup/cpuset
4294967297 - /sys/fs/cgroup/devices
4294967297 - /sys/fs/cgroup/freezer
4294967297 - /sys/fs/cgroup/hugetlb
4294967297 - /sys/fs/cgroup/memory
4294967297 - /sys/fs/cgroup/net_cls,net_prio
4294967297 - /sys/fs/cgroup/perf_event
4294967297 - /sys/fs/cgroup/pids
4294967297 - /sys/fs/cgroup/systemd
```

Have I understood `cgroup` ID wrong?

**Comment by fbs** [comment]
Can you share the source of this program? Which bpftrace and kernel version do you use?

**Comment by mmarchini** [comment]
What are you using for containers? Docker or something else?

I noticed the same thing yesterday. I *think* this is the expected behavior (e.g., the cgroupid is actually the same for different containers in some container environments), but I'm not sure. Someone more familiar with cgroups should be able to answer better.

If I do `systemctl status 28747 | grep CGroup` for two processes in two different containers, I get the same result as well.

**Comment by mythi** [comment]
I'm running a kubernetes cluster with cgroup driver set to 'systemd'. `bpftrace v0.9.2` and Linux 5.2.15.

My code that shows the issue:

```
bpftrace -e 'tracepoint:x86_fpu:x86_fpu_regs_deactivated {@c[pid] = cgroup} interval:s:15 {exit()}'
Attaching 2 probes...


@c[41065]: 4294967297
@c[41161]: 4294967297
@c[41047]: 4294967297
@c[40975]: 4294967297
@c[40903]: 4294967297
@c[40950]: 4294967297
@c[41059]: 4294967297
@c[40981]: 4294967297
@c[41219]: 4294967297
@c[421]: 4294967297
@c[2573]: 4294967297
@c[16571]: 4294967297
@c[40936]: 4294967297
@c[40962]: 4294967297
@c[40999]: 4294967297
@c[41195]: 4294967297
@c[40897]: 4294967297
@c[41220]: 4294967297
@c[40900]: 4294967297
@c[41201]: 4294967297
@c[2319]: 4294967297
@c[722]: 4294967297
@c[40930]: 4294967297
@c[41192]: 4294967297
@c[1373]: 4294967297
@c[40916]: 4294967297
@c[41197]: 4294967297
@c[412]: 4294967297
@c[41167]: 4294967297
@c[41199]: 4294967297
@c[41125]: 4294967297
@c[1337]: 4294967297
@c[41203]: 4294967297
@c[40915]: 4294967297
...
```

> If I do systemctl status 28747 | grep CGroup for two processes in two different containers, I get the same result as well.

This is not the case for me. I get two different paths. In which case I'd need two different `cgroup` IDs to match against `cgroupid(<path>)` .

**Comment by mythi** [comment]
For `cgroup` to work, the unified cgroup hierarcy (cgroup-v2) must be mounted. It's not obvious in the docs but a comment in the builder code gave me a hint and I tested it works. When I enabled the "hybrid" cgroup mode in my systemd config, things started working as expected.
