### ISSUE TITLE
Remove constructors without location information from `ast.h`

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#902]
Should we remove constructors without location information from `ast.h` in the future?

_Originally posted by @mmarchini in https://github.com/iovisor/bpftrace/pull/845#issuecomment-531887628_

**Comment by danobi** [comment]
Yeah sounds reasonable.

**Comment by danobi** [comment]
Similar to #912, possibly do both together.

**Comment by vladdy** [comment]
Can I grab this one?

**Comment by vladdy** [comment]
@danobi Do you want me to wait with this before you merge #912?

**Comment by viktormalik** [comment]
Done by #1625.
