### ISSUE TITLE
Move `ast.h` class definitions into `ast.cpp`

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#912]
We do inline definitions in a couple places but that number is starting to grow. We should really define these methods in the .cpp so it doesn't take forever to recompile bpftrace if you modify the ast code.

See `src/ast/ast.h` and `src/ast/ast.cpp`.

**Comment by vladdy** [comment]
Can I grab this one?

**Comment by danobi** [comment]
Sorry, taking this one. Working on #1047 and it made sense to do this first.

**Comment by vladdy** [comment]
Not a problem. Thank you!
