### ISSUE TITLE
Availability of probes such as vminfo:::pgin in bpftrace?

### ISSUE THREAD

**Issue by gbansal2** [iovisor/bpftrace#924]
This is not a bug or an issue report, but more of a usage/feature request question. Apologize if this is not the right place for this, if so please suggest if there are any forums to post questions like this.

Question 1 -
I find the vminfo provider in dtrace very useful for getting stats like pgin, etc. 
Is there a similar probe available in bpftrace?
I have used some of the probes available in software:: category such as software:faults, but the vminfo provider provides many more than just faults. 

Question 2 -
Is there any probe to trace the virtual memory address that triggered a page-fault?

Thanks

**Comment by brendangregg** [comment]
See the event sources diagram on http://www.brendangregg.com/perf.html

Most of these event types are tracepoints, but some are software events. page faults are available as software events, which bpftrace can instrument.

**Comment by gbansal2** [comment]
Thanks Brendan. I was able to use the kmem:mm_page_alloc tracepoint.
btw - I am a big fan of your books/blogs :). Both the Dtrace and Sys Perf books are awesome!
