### ISSUE TITLE
Inconsistent dereferenced pointer value

### ISSUE THREAD

**Issue by javierhonduco** [iovisor/bpftrace#930]
@tyroguru and I found out an interesting case. If we store a pointer in a global variable and then print the value twice, the results are not consistent:

```C
#include <linux/mm.h>

kprobe:do_wp_page
{
    @a = (struct vm_fault*)arg0;
    printf("%llx %llx\n", @a->address, @a->address);
    printf("------\n");
}
```
```
ffffc90006836000 1db70
------
ffffc90006836000 1db70
------
ffffc90006836000 1db70
------
ffffc90006836000 1db70
^C
```

But if we store the pointer in a scratch variable, the output seem to make sense:

```C
#include <linux/mm.h>

kprobe:do_wp_page
{
    $a = (struct vm_fault*)arg0;
    printf("%llx %llx\n", $a->address, $a->address);
    printf("------\n");
}
```

```
7ffe2db9e000 7ffe2db9e000
------
55f7cf566000 55f7cf566000
------
55f7cf594000 55f7cf594000
^C
```

On top of that, if we try comparing the two values before printing, we get an even more interesting behaviour (maybe this should be a separate issue!):

```C
#include <linux/mm.h>

kprobe:do_wp_page
{
    @a = (struct vm_fault*)arg0;
    if(@a->address == @a->address) {
        printf("%llx %llx\n", @a->address, @a->address);
        printf("------\n");
    }
}
```
```
ffffc90006875000 1db70
------
ffffc90006875000 1db70
------
ffffc90006875000 1db70
------
ffffc90006875000 1db70
```

I'm running `bpftrace v0.9.2` and `Linux 4.16.18`. @tyroguru is running on the latest commit.

Cheers!

**Comment by olsajiri** [comment]
looks like we don't hande pointer loading to a map properly,
I put some fix together in my map/field branch if you want to try:
  https://github.com/olsajiri/bpftrace/tree/map/field

I'll do some more testing and create pull request

**Comment by olsajiri** [comment]
damn, that breaks predicate, I'll push new version

**Comment by javierhonduco** [comment]
@olsajiri Thanks a lot for working on this!! 😄
