### ISSUE TITLE
Infer type of uaddr pointer

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#939]
Take the code below for example:

```d
uprobe:node:_ZN2v88internal17Builtin_JsonParseEiPPNS0_6ObjectEPNS0_7IsolateE
{
  $stringLengthOffset = *uaddr("v8dbg_class_String__length__SMI");
  printf("v8dbg_class_String__length__SMI: %lx\n", $stringLengthOffset);
}
```

`v8dbg_class_String__length__SMI` is an `int` global variable which will always be set to 16 (0x10). But if we run a Node.js program traced by the program above, we'll get the following output:

```console
$ bpftrace test.bt
v8dbg_class_String__length__SMI: 1800000010
```

This happens because the return of `uaddr("v8dbg_class_String__length__SMI")` is an `int64_t *`, but the type should be `int32_t *`. To workaround this I had to cast it to `int32` after dereferencing the pointer, which is not all that intuitive.

There are two things we can do to improve this (and we probably should do both):

1. Infer the pointer type of uaddr if the data size matches a known integer type
2. Allow users to define the pointer type when calling uaddr (`uaddr(name[, type])`). As a bonus, we can use semantic analysis to force users to define a pointer type when the data size doesn't match a known integer type

**Comment by mmisono** [comment]
With #942, at least it is possible to write
```
 $stringLengthOffset = *(int32*)uaddr("v8dbg_class_String__length__SMI");
```

`bcc_elf_foreach_sym` is used for [symbol resolution](https://github.com/iovisor/bpftrace/blob/d092cb13f6e538029e8ae3d5421fc893712b5bd7/src/bpftrace.cpp#L1599) but [`struct bcc_symbol`](https://github.com/iovisor/bcc/blob/5cf529eeb448fa5422f305727ee4be7d01ebf391/src/cc/bcc_syms.h#L27) does not contain the symbol size. So I think we need to fix bcc first.

**Comment by fbs** [comment]
The size is already passed to the callback. If we use our own struct instead of bcc_symbol, like we do for uprobe offset it should be fine. I'll make a PR :)
