### ISSUE TITLE
Direct context access

### ISSUE THREAD

**Issue by mmisono** [iovisor/bpftrace#945]
Currently, access to `args` and `ctx` is performed by `bpf_probe_read()`.
Generally, this is not a problem, but the verifier may rewrite the access to the context.
For example, we cannot access the `sample_period` filed of [`bpf_perf_event_data`](https://github.com/torvalds/linux/blob/26bc672134241a080a83b2ab9aa8abede8d30e1c/include/uapi/linux/bpf_perf_event.h#L13) in the following way because of [the conversion](https://github.com/torvalds/linux/blob/26bc672134241a080a83b2ab9aa8abede8d30e1c/kernel/trace/bpf_trace.c#L1147).

```
#include <uapi/linux/bpf_perf_event.h>
software:cpu:1000000000 {
  $data = (struct bpf_perf_event_data*)ctx;
  $sample_period = $data->sample_period;
  printf("sample_period=%d\n", $sample_period);
}
```

Output is:

```
% sudo ./src/bpftrace probe.bt
Attaching 1 probe...
sample_period=0
...
```

As mentioned in #895, in this case, I think creating a special variable `perfdata` or a special function `perfdata()` (like `reg()`) is sufficient, but it would be nice to have direct access functionality.

----

Related: #739

**Comment by brendangregg** [comment]
I'd be cautious about putting "perfdata" into the bpftrace API as it's a Linux implementation detail -- what happens when we port this to other operating systems (which are adopting BPF)?

**Comment by mmisono** [comment]
I agree with that point. In addition to this, If we support "perfdata", we need to keep up with `bpf_perf_event_data` structure change.
