### ISSUE TITLE
Static build with uprobe offset fails

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#953]
My static build on centos 7 fails to link when uprobe offset is enabled. It seems like lib iberty is a requirement for the static builds. The following patch fixes it:

```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 65f3a34..f32f35a 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -62,6 +62,9 @@ if (STATIC_LINKING)
   target_link_libraries(bpftrace ${LIBBCC_LIBRARIES})
   target_link_libraries(bpftrace ${LIBBPF_LIBRARY_STATIC})
   target_link_libraries(bpftrace ${LIBBCC_LOADER_LIBRARY_STATIC})
+  if(HAVE_BFD_DISASM)
+    target_link_libraries(bpftrace -liberty)
+  endif(HAVE_BFD_DISASM)
 else()
   target_link_libraries(bpftrace ${LIBBCC_LIBRARIES})
 endif()
```

Looking at https://lore.kernel.org/lkml/4dfc634cfcfb236883971b5107cf3c28ec8a31be.1542328222.git.sdf@google.com/ it seems like this is only required for some OS. But I'm not  sure that is worth the effort or that we should just link agains iberty on all OS. 

@olsajiri what do you think?

**Comment by mmarchini** [comment]
> But I'm not sure that is worth the effort or that we should just link agains iberty on all OS.

I think it's fine if the binary size doesn't grow considerably.

---

Unrelated: you're able to build bpftrace statically on CentOS 7? Should we use CentOS 7 instead of alpine in our CI?

**Comment by fbs** [comment]
> Unrelated: you're able to build bpftrace statically on CentOS 7? Should we use CentOS 7 instead of alpine in our CI?

I created a static build for machines @ work but it's not pretty. It first builds LLVM and makes use of devtoolset GCC so not your typical build. Details can be found [here](https://github.com/fbs/el7-bpf-specs). I wouldn't call it an improvement over the current static build setup.

**Comment by danobi** [comment]
> I think it's fine if the binary size doesn't grow considerably.

Yeah should be fine b/c linker will discard unused symbols from static library (by default).
