### ISSUE TITLE
uprobes do not respect mount namespaces (0.9.2) 

### ISSUE THREAD

**Issue by dalehamel** [iovisor/bpftrace#968]
Using bpftrace included with ubuntu eoan (0.9.2), there are several issues with uprobes not respecting mount namespaces:

listing probes, I would expect that if I do:

```
bpftrace -l 'uprobe:*' -p MY_PID
```

That this should be taken relative to the path of the command within the mount namespace of the pid. However, this fails, as bpftrace checks that the path against the mount namespace which bpftrace itself is running in. I believe this can be rather easily fixed for uprobes, by preppending `/proc/MY_PID/root` to the namespace, or perhaps there is a helper in bcc that can be used.

Likewise, I would expect that if the mount namespace of the process I am trying to probe is not equal to the mount namespace that bpftrace is running from, that it should determine this and probe the correct mount namespace. For instance, when I try to run:

```
bpftrace -e 'uprobe:/usr/local/bin/memcached:process_command { printf("arg1: %s\n", arg1)}' -p MY_PID
```

I receive the following error:

```
failed to stat uprobe target file /usr/local/bin/memcached: No such file or directory
```

However, I can force it to work by hacking in the path accordingly:

```
bpftrace -e 'uprobe:/proc/MY_PID/root/usr/local/bin/memcached:process_command { printf("arg1: %s\n", str(arg1))}'
```

I would expect that if a PID is specified, that this should not be necessary, as it should be able to infer the correct path from this. I would also expect that, as with USDT probes, the path can be omitted entirely if the PID is specified, as it can be inferred from the pid's own executable path.

I would be more than happy to submit these changes and associated tests, perhaps I'm missing the boat for the 0.9.3 release?

Also, I beg your pardon in case any of this has been fixed between 0.9.2 and the 0.9.3 release.

**Comment by fbs** [comment]
> I would be more than happy to submit these changes and associated tests, 

+1, bpftrace + namespaces still needs a bit (lots?) of love.

> perhaps I'm missing the boat for the 0.9.3 release?

It won't make 0.9.3, but if you have the time to work on this I'll happily tag it for 0.9.4.

**Comment by dalehamel** [comment]
> It won't make 0.9.3, but if you have the time to work on this I'll happily tag it for 0.9.4.

Yeah i figured it was too late to board that train. I'll happily have this done before 0.9.4 release.

**Comment by dalehamel** [comment]
It looks like listing USDT probes is also broken, I'll take a look at that while i'm working on this.

**Comment by dalehamel** [comment]
Sorry for the long delay here, I've got a failing regression test for this now, so i'll go ahead and make it passe

**Comment by dalehamel** [comment]
Ok, i've got #1021 up which includes regression tests and appears to fix the issue
