### ISSUE TITLE
bitfield access support

### ISSUE THREAD

**Issue by lostjeffle** [iovisor/bpftrace#969]
Hello, guys,

I wonder if bpftrace would add support for bitfield access. 

For the following structure and bpftrace script, when we access version and ihl separately, the whole u8 is actually returned. We have to do mask operations on the returned u8, which is somehow inconvenient.

```
struct iphdr {
#if defined(__LITTLE_ENDIAN_BITFIELD)
    __u8    ihl:4,
        version:4;
#elif defined (__BIG_ENDIAN_BITFIELD)
    __u8    version:4,
        ihl:4;
  ...
};
```

```
kprobe:ip_send_check{
  printf("version is %x, ihl is %x\n", ((struct iphdr*)arg0)->version, ((struct iphdr*)arg0)->ihl);
}
```

**Comment by danobi** [comment]
Seems doable. Internally we store byte offsets into parsed structs. Clang gives us the bit offset and bit field width. I think bpf is byte addressed so we'll have to compute a mask and save that data in `class Field` and apply that mask during codegen.

Some implementation details so I don't forget:
* clang_getFieldDeclBitWidth
  * https://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#ga80bbb872dde5b2f26964081338108f91
* clang_Cursor_getOffsetOfField
  * https://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#gaa7e0f0ec320c645e971168ac39aa0cab

**Comment by danobi** [comment]
```diff
diff --git a/src/clang_parser.cpp b/src/clang_parser.cpp
index f39afeb..86fd71c 100644
--- a/src/clang_parser.cpp
+++ b/src/clang_parser.cpp
@@ -338,6 +338,14 @@ bool ClangParser::visit_children(CXCursor &cursor, BPFtrace &bpftrace)
           auto offset = clang_Type_getOffsetOf(ptype, ident.c_str()) / 8;
           auto type = clang_getCanonicalType(clang_getCursorType(c));

+          std::cout << "ident=" << ident
+            << " offset=" << clang_Type_getOffsetOf(ptype, ident.c_str())
+            << " is_bitfield=" << clang_Cursor_isBitField(c)
+            << " field_offset=" << clang_Cursor_getOffsetOfField(c)
+            << " size=" << clang_Type_getSizeOf(type)
+            << " field_decl_width=" << clang_getFieldDeclBitWidth(c)
+            << std::endl;
+
           auto struct_name = get_clang_string(clang_getCursorSpelling(named_parent));
           if (struct_name == "")
             struct_name = ptypestr;
```

**Comment by lostjeffle** [comment]
Nice work. It would be useful if bitfield could be accessed directly, especially for network related tracing. Thanks for replying.

**Comment by danobi** [comment]
I wrote the code and it looks like it works. I'll add tests soon
