### ISSUE TITLE
usdts and child process

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#990]
The way we currently spawn a child process is:

- fork child, let it block on a pipe read
- go through the whole codegen phase
- attach the probes
- let the child run, i.e. execve

The issue with this is that we cannot use USDTs on the child process as it hasn't `execve`d yet when we try to attach them.

Using `ptrace` to pause the child after `execve` seems like a viable option. Not all programs like to be ptraced but I don't think they can detect it if you detach right after they `execve`d. 

To be on the safe side we can keep the original behaviour and hide the ptrace one behind a flag  (`--ptrace-child`?), which is disabled by default and enabled for USDTs.

**Comment by javierhonduco** [comment]
Good idea! Was thinking on how to solve this as well 😄 

> Using ptrace to pause the child after execve seems like a viable option. Not all programs like to be ptraced but I don't think they can detect it if you detach right after they execved.

I think think it's a reasonable assumption due to strace's popularity!

As a follow-up, should we look into how to make this work with [dynamic USDTs](https://github.com/sthima/libstapsdt/)? Not sure how could we approach this but might be interesting as well cc @mmarchini @dalehamel

**Comment by dalehamel** [comment]
The issue I see with dynamic USDT @javierhonduco is that you can’t know for certain when they would be enabled, it may not happen immediately on boot. This creates a race that can be difficult to reason about, and the only option I can think makes sense is for bpftrace to poll waiting for the USDT target symbol to be present.

I suspect some programs will also only want to enable dynamic USDT on receiving a signal, perhaps that would need to be supported as well, where bpftrace would need it emit a signal to the child process after spawning it. Again though, a race as we cannot know of the signal handler has been set up, and not all signals are safe to send without a handler.

I like the concept overall, I’m interested to help out however I can.

**Comment by fbs** [comment]
I'm working on a solution for this. A separate "child process manager" class which will allow us to remove some code from `class BPFtrace` (#1080) and also add pidfd support (#880).

**Comment by viktormalik** [comment]
Fixed by #1238.
