### ISSUE TITLE
long positional param crashes parser

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#994]
Not the most likely case to hit but bpftrace shouldn't crash:

```
 bpftrace -e 'i:s:100 { @=$111111111111111111111111111 }'
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoll
Aborted
```

Parser.yy
```
param : PARAM      { $$ = new ast::PositionalParameter(PositionalParameterType::positional, std::stoll($1.substr(1, $1.size()-1)), @$); }
```

**Comment by vladdy** [comment]
Grabbing this one

**Comment by mmisono** [comment]
@vladdy 
Hi, are you working on this now? Recently I'm trying to fuzz bpftrace and a fuzzer relatively quickly found this issue. It is nice to fix this to make fuzzers happy :)

**Comment by vladdy** [comment]
I'll work on this tomorrow! Thank you for the reminder!
