### ISSUE TITLE
Replace LLVM

### ISSUE THREAD

**Issue by ajor** [iovisor/bpftrace#997]
The LLVM dependency has been a problem for some users due to its size.

We should be able to create our own BPF-specific compiler backend with a much smaller footprint. It should perform basic optimisations but does not need to come close to LLVM's performance.

**Comment by jordalgo** [comment]
@ajor Do you have more details on this one?

**Comment by ajor** [comment]
Added a little explanation to the top comment, but closing because there are no plans to continue with this in the near future.
